export default {
  '0': {
    levelCap: 20,
    talentCap: 1,
    
    moraCostCharacter: 20000,
    gemCostCharacter: 1,
    gemRarityCharacter: 2,
    bossCostCharacter: 0,
    floraCostCharacter: 3,
    enemyCostCharacter: 3,
    enemyRarityCharacter: 1,
    moraCostWeapon: {
      '5': 10000,
      '4': 5000,
      '3': 5000,
      '2': 5000,
      '1': 0,
    },
    forgeryRarityWeapon: 2,
    forgeryCostWeapon: {
      '5': 5,
      '4': 3,
      '3': 2,
      '2': 1,
      '1': 1,
    },
    strongRarityWeapon: 2,
    strongCostWeapon: {
      '5': 5,
      '4': 3,
      '3': 2,
      '2': 1,
      '1': 1,
    },
    weakRarityWeapon: 1,
    weakCostWeapon: {
      '5': 3,
      '4': 2,
      '3': 1,
      '2': 1,
      '1': 1,
    },
    
    baseStatMultiplier: 0,
    ascendStatMultiplier: 0,
  },
  '1': {
    levelCap: 40,
    talentCap: 1,
    
    moraCostCharacter: 40000,
    gemCostCharacter: 3,
    gemRarityCharacter: 3,
    bossCostCharacter: 2,
    floraCostCharacter: 10,
    enemyCostCharacter: 15,
    enemyRarityCharacter: 1,
    moraCostWeapon: {
      '5': 20000,
      '4': 15000,
      '3': 10000,
      '2': 5000,
      '1': 5000,
    },
    forgeryRarityWeapon: 3,
    forgeryCostWeapon: {
      '5': 5,
      '4': 3,
      '3': 2,
      '2': 1,
      '1': 1,
    },
    strongRarityWeapon: 2,
    strongCostWeapon: {
      '5': 18,
      '4': 12,
      '3': 8,
      '2': 5,
      '1': 4,
    },
    weakRarityWeapon: 1,
    weakCostWeapon: {
      '5': 12,
      '4': 8,
      '3': 5,
      '2': 4,
      '1': 2,
    },
    
    baseStatMultiplier: 38/182,
    ascendStatMultiplier: 0,
  },
  '2': {
    levelCap: 50,
    talentCap: 2,
    
    moraCostCharacter: 60000,
    gemCostCharacter: 6,
    gemRarityCharacter: 3,
    bossCostCharacter: 4,
    floraCostCharacter: 20,
    enemyCostCharacter: 12,
    enemyRarityCharacter: 2,
    moraCostWeapon: {
      '5': 30000,
      '4': 20000,
      '3': 15000,
      '2': 10000,
      '1': 5000,
    },
    forgeryRarityWeapon: 3,
    forgeryCostWeapon: {
      '5': 9,
      '4': 6,
      '3': 4,
      '2': 3,
      '1': 2,
    },
    strongRarityWeapon: 3,
    strongCostWeapon: {
      '5': 9,
      '4': 6,
      '3': 4,
      '2': 3,
      '1': 2,
    },
    weakRarityWeapon: 2,
    weakCostWeapon: {
      '5': 9,
      '4': 6,
      '3': 4,
      '2': 3,
      '1': 2,
    },
    
    baseStatMultiplier: 65/182,
    ascendStatMultiplier: 1,
  },
  '3': {
    levelCap: 60,
    talentCap: 4,
    
    moraCostCharacter: 80000,
    gemCostCharacter: 3,
    gemRarityCharacter: 4,
    bossCostCharacter: 8,
    floraCostCharacter: 30,
    enemyCostCharacter: 18,
    enemyRarityCharacter: 2,
    moraCostWeapon: {
      '5': 45000,
      '4': 30000,
      '3': 20000,
      '2': 15000,
      '1': 10000,
    },
    forgeryRarityWeapon: 4,
    forgeryCostWeapon: {
      '5': 5,
      '4': 3,
      '3': 2,
      '2': 1,
      '1': 1,
    },
    strongRarityWeapon: 3,
    strongCostWeapon: {
      '5': 18,
      '4': 12,
      '3': 8,
      '2': 5,
      '1': 4,
    },
    weakRarityWeapon: 2,
    weakCostWeapon: {
      '5': 14,
      '4': 9,
      '3': 6,
      '2': 4,
      '1': 3,
    },
    
    baseStatMultiplier: 101/182,
    ascendStatMultiplier: 2,
  },
  '4': {
    levelCap: 70,
    talentCap: 6,
    
    moraCostCharacter: 100000,
    gemCostCharacter: 6,
    gemRarityCharacter: 4,
    bossCostCharacter: 12,
    floraCostCharacter: 45,
    enemyCostCharacter: 12,
    enemyRarityCharacter: 3,
    moraCostWeapon: {
      '5': 55000,
      '4': 35000,
      '3': 25000,
      '2': 0,
      '1': 0,
    },
    forgeryRarityWeapon: 4,
    forgeryCostWeapon: {
      '5': 9,
      '4': 6,
      '3': 4,
      '2': 0,
      '1': 0,
    },
    strongRarityWeapon: 4,
    strongCostWeapon: {
      '5': 14,
      '4': 9,
      '3': 6,
      '2': 0,
      '1': 0,
    },
    weakRarityWeapon: 3,
    weakCostWeapon: {
      '5': 9,
      '4': 6,
      '3': 4,
      '2': 0,
      '1': 0,
    },
    
    baseStatMultiplier: 128/182,
    ascendStatMultiplier: 2,
  },
  '5': {
    levelCap: 80,
    talentCap: 8,
    
    moraCostCharacter: 120000,
    gemCostCharacter: 6,
    gemRarityCharacter: 5,
    bossCostCharacter: 20,
    floraCostCharacter: 60,
    enemyCostCharacter: 24,
    enemyRarityCharacter: 3,
    moraCostWeapon: {
      '5': 65000,
      '4': 45000,
      '3': 30000,
      '2': 0,
      '1': 0,
    },
    forgeryRarityWeapon: 5,
    forgeryCostWeapon: {
      '5': 6,
      '4': 4,
      '3': 3,
      '2': 0,
      '1': 0,
    },
    strongRarityWeapon: 4,
    strongCostWeapon: {
      '5': 27,
      '4': 18,
      '3': 12,
      '2': 0,
      '1': 0,
    },
    weakRarityWeapon: 3,
    weakCostWeapon: {
      '5': 18,
      '4': 12,
      '3': 8,
      '2': 0,
      '1': 0,
    },
    
    baseStatMultiplier: 155/182,
    ascendStatMultiplier: 3,
  },
  '6': {
    levelCap: 90,
    talentCap: 10,
    
    moraCostCharacter: 0,
    gemCostCharacter: 0,
    gemRarityCharacter: 5,
    bossCostCharacter: 0,
    floraCostCharacter: 0,
    enemyCostCharacter: 0,
    enemyRarityCharacter: 3,
    moraCostWeapon: {
      '5': 0,
      '4': 0,
      '3': 0,
      '2': 0,
      '1': 0,
    },
    forgeryRarityWeapon: 5,
    forgeryCostWeapon: {
      '5': 0,
      '4': 0,
      '3': 0,
      '2': 0,
      '1': 0,
    },
    strongRarityWeapon: 4,
    strongCostWeapon: {
      '5': 0,
      '4': 0,
      '3': 0,
      '2': 0,
      '1': 0,
    },
    weakRarityWeapon: 3,
    weakCostWeapon: {
      '5': 0,
      '4': 0,
      '3': 0,
      '2': 0,
      '1': 0,
    },
    
    baseStatMultiplier: 1,
    ascendStatMultiplier: 4,
  },
};
