export default {
  '1': {
    matMoraCount: 12500,
    matEnemyCount: 6,
    matEnemyQuality: 1,
    matMasteryCount: 3,
    matMasteryQuality: 2,
    matTrounceCount: 0,
    matCrownCount: 0,
  },
  '2': {
    matMoraCount: 17500,
    matEnemyCount: 3,
    matEnemyQuality: 2,
    matMasteryCount: 2,
    matMasteryQuality: 3,
    matTrounceCount: 0,
    matCrownCount: 0,
  },
  '3': {
    matMoraCount: 25000,
    matEnemyCount: 4,
    matEnemyQuality: 2,
    matMasteryCount: 4,
    matMasteryQuality: 3,
    matTrounceCount: 0,
    matCrownCount: 0,
  },
  '4': {
    matMoraCount: 30000,
    matEnemyCount: 6,
    matEnemyQuality: 2,
    matMasteryCount: 6,
    matMasteryQuality: 3,
    matTrounceCount: 0,
    matCrownCount: 0,
  },
  '5': {
    matMoraCount: 37500,
    matEnemyCount: 9,
    matEnemyQuality: 2,
    matMasteryCount: 9,
    matMasteryQuality: 3,
    matTrounceCount: 0,
    matCrownCount: 0,
  },
  '6': {
    matMoraCount: 120000,
    matEnemyCount: 4,
    matEnemyQuality: 3,
    matMasteryCount: 4,
    matMasteryQuality: 4,
    matTrounceCount: 1,
    matCrownCount: 0,
  },
  '7': {
    matMoraCount: 260000,
    matEnemyCount: 6,
    matEnemyQuality: 3,
    matMasteryCount: 6,
    matMasteryQuality: 4,
    matTrounceCount: 1,
    matCrownCount: 0,
  },
  '8': {
    matMoraCount: 450000,
    matEnemyCount: 9,
    matEnemyQuality: 3,
    matMasteryCount: 12,
    matMasteryQuality: 4,
    matTrounceCount: 2,
    matCrownCount: 0,
  },
  '9': {
    matMoraCount: 700000,
    matEnemyCount: 12,
    matEnemyQuality: 3,
    matMasteryCount: 16,
    matMasteryQuality: 4,
    matTrounceCount: 2,
    matCrownCount: 1,
  },
  '10': {
    matMoraCount: 0,
    matEnemyCount: 0,
    matEnemyQuality: 3,
    matMasteryCount: 0,
    matMasteryQuality: 4,
    matTrounceCount: 0,
    matCrownCount: 0,
  },
};
