export default {
  '1': {
    moraCost: 12500,
    enemyCost: 6,
    enemyRarity: 1,
    masteryCost: 3,
    masteryRarity: 2,
    trounceCost: 0,
    crownCost: 0,
  },
  '2': {
    moraCost: 17500,
    enemyCost: 3,
    enemyRarity: 2,
    masteryCost: 2,
    masteryRarity: 3,
    trounceCost: 0,
    crownCost: 0,
  },
  '3': {
    moraCost: 25000,
    enemyCost: 4,
    enemyRarity: 2,
    masteryCost: 4,
    masteryRarity: 3,
    trounceCost: 0,
    crownCost: 0,
  },
  '4': {
    moraCost: 30000,
    enemyCost: 6,
    enemyRarity: 2,
    masteryCost: 6,
    masteryRarity: 3,
    trounceCost: 0,
    crownCost: 0,
  },
  '5': {
    moraCost: 37500,
    enemyCost: 9,
    enemyRarity: 2,
    masteryCost: 9,
    masteryRarity: 3,
    trounceCost: 0,
    crownCost: 0,
  },
  '6': {
    moraCost: 120000,
    enemyCost: 4,
    enemyRarity: 3,
    masteryCost: 4,
    masteryRarity: 4,
    trounceCost: 1,
    crownCost: 0,
  },
  '7': {
    moraCost: 260000,
    enemyCost: 6,
    enemyRarity: 3,
    masteryCost: 6,
    masteryRarity: 4,
    trounceCost: 1,
    crownCost: 0,
  },
  '8': {
    moraCost: 450000,
    enemyCost: 9,
    enemyRarity: 3,
    masteryCost: 12,
    masteryRarity: 4,
    trounceCost: 2,
    crownCost: 0,
  },
  '9': {
    moraCost: 700000,
    enemyCost: 12,
    enemyRarity: 3,
    masteryCost: 16,
    masteryRarity: 4,
    trounceCost: 2,
    crownCost: 1,
  },
  '10': {
    moraCost: 0,
    enemyCost: 0,
    enemyRarity: 3,
    masteryCost: 0,
    masteryRarity: 4,
    trounceCost: 0,
    crownCost: 0,
  },
};
