export default {
    "forte": {
        "Basic Attack": {
            "motionValues": [
                {
                    "scaling": [
                        "16%",
                        "17.32%",
                        "18.63%",
                        "20.47%",
                        "21.78%",
                        "23.29%",
                        "25.39%",
                        "27.48%",
                        "29.58%",
                        "31.81%",
                        "34.44%",
                        "37.06%",
                        "39.69%",
                        "42.31%",
                        "44.93%",
                        "47.56%",
                        "50.18%",
                        "52.81%",
                        "55.43%",
                        "58.05%"
                    ],
                    "name": "Part 1 Damage"
                },
                {
                    "scaling": [
                        "26.67%",
                        "28.86%",
                        "31.04%",
                        "34.11%",
                        "36.29%",
                        "38.81%",
                        "42.31%",
                        "45.8%",
                        "49.3%",
                        "53.02%",
                        "57.39%",
                        "61.77%",
                        "66.14%",
                        "70.51%",
                        "74.89%",
                        "79.26%",
                        "83.63%",
                        "88.01%",
                        "92.38%",
                        "96.75%"
                    ],
                    "name": "Part 2 Damage"
                },
                {
                    "scaling": [
                        "24%*2",
                        "25.97%*2",
                        "27.94%*2",
                        "30.7%*2",
                        "32.66%*2",
                        "34.93%*2",
                        "38.08%*2",
                        "41.22%*2",
                        "44.37%*2",
                        "47.72%*2",
                        "51.66%*2",
                        "55.59%*2",
                        "59.53%*2",
                        "63.46%*2",
                        "67.4%*2",
                        "71.34%*2",
                        "75.27%*2",
                        "79.21%*2",
                        "83.14%*2",
                        "87.08%*2"
                    ],
                    "name": "Part 3 Damage"
                },
                {
                    "scaling": [
                        "25.34%*2",
                        "27.42%*2",
                        "29.49%*2",
                        "32.4%*2",
                        "34.48%*2",
                        "36.87%*2",
                        "40.19%*2",
                        "43.51%*2",
                        "46.84%*2",
                        "50.37%*2",
                        "54.52%*2",
                        "58.68%*2",
                        "62.83%*2",
                        "66.99%*2",
                        "71.14%*2",
                        "75.3%*2",
                        "79.45%*2",
                        "83.61%*2",
                        "87.76%*2",
                        "91.92%*2"
                    ],
                    "name": "Part 4 Damage"
                },
                {
                    "scaling": [
                        "90.4%",
                        "97.82%",
                        "105.23%",
                        "115.61%",
                        "123.02%",
                        "131.55%",
                        "143.41%",
                        "155.27%",
                        "167.13%",
                        "179.73%",
                        "194.55%",
                        "209.38%",
                        "224.21%",
                        "239.03%",
                        "253.86%",
                        "268.68%",
                        "283.51%",
                        "298.33%",
                        "313.16%",
                        "327.99%"
                    ],
                    "name": "Part 5 Damage"
                },
                {
                    "scaling": [
                        "30%",
                        "32.46%",
                        "34.92%",
                        "38.37%",
                        "40.83%",
                        "43.66%",
                        "47.59%",
                        "51.53%",
                        "55.47%",
                        "59.65%",
                        "64.57%",
                        "69.49%",
                        "74.41%",
                        "79.33%",
                        "84.25%",
                        "89.17%",
                        "94.09%",
                        "99.01%",
                        "103.93%",
                        "108.85%"
                    ],
                    "name": "Mid-Air Attack"
                },
                {
                    "scaling": [
                        "18.00%",
                        "19.48%",
                        "20.96%",
                        "23.02%",
                        "24.50%",
                        "26.20%",
                        "28.56%",
                        "30.92%",
                        "33.28%",
                        "35.79%",
                        "38.74%",
                        "41.69%",
                        "44.65%",
                        "47.60%",
                        "50.55%",
                        "53.50%",
                        "56.45%",
                        "59.41%",
                        "62.30%",
                        "65.31%"
                    ],
                    "name": "Aimed Shot Damage"
                },
                {
                    "scaling": [
                        "40.50%",
                        "43.83%",
                        "47.15%",
                        "51.80%",
                        "55.12%",
                        "58.94%",
                        "64.25%",
                        "69.56%",
                        "74.88%",
                        "80.52%",
                        "87.17%",
                        "93.81%",
                        "100.45%",
                        "107.09%",
                        "113.73%",
                        "120.38%",
                        "127.02%",
                        "133.66%",
                        "140.30%",
                        "146.94%"
                    ],
                    "name": "Fully Charged Aimed Shot Damage"
                },
                {
                    "scaling": [
                        "107.7%",
                        "116.54%",
                        "125.37%",
                        "137.73%",
                        "146.56%",
                        "156.72%",
                        "170.85%",
                        "184.98%",
                        "199.11%",
                        "214.12%",
                        "231.79%",
                        "249.45%",
                        "267.11%",
                        "284.77%",
                        "302.44%",
                        "320.1%",
                        "337.76%",
                        "355.43%",
                        "373.09%",
                        "390.75%"
                    ],
                    "name": "Dodge Counter Damage"
                },
                {
                    "scaling": [
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5"
                    ],
                    "name": "Mid-Air Attack Stamina Consumption"
                }
            ],
            "name": "Half Truths",
            "desc": "<size=40><color=Title>Basic Attack<\/color><\/size>nAalto fires up to 5 consecutive shots, dealing <color=Wind>Aero DMG<\/color>. Basic Attack 4 will spread the \"Mist\" forward, which lasts for 1.5s.n<size=10> <\/size>n<size=40><color=Title>Heavy Attack<\/color><\/size>nAalto enters the aiming state for a more powerful shot.nThe aimed shot fired after charging finishes deals <color=Wind>Aero DMG<\/color>.n<size=10> <\/size>n<size=40><color=Title>Mid-air Attack<\/color><\/size>nAalto consumes Stamina to perform consecutive shots at the target in mid-air, dealing <color=Wind>Aero DMG<\/color>.n<size=10> <\/size>n<size=40><color=Title>Dodge Counter<\/color><\/size>nUse <color=Highlight>Basic Attack<\/color> after a successful <color=Highlight>Dodge<\/color> to attack the target, dealing <color=Wind>Aero DMG<\/color>."
        },
        "Resonance Skill": {
            "motionValues": [
                {
                    "scaling": [
                        "30%",
                        "32.46%",
                        "34.92%",
                        "38.37%",
                        "40.83%",
                        "43.66%",
                        "47.59%",
                        "51.53%",
                        "55.47%",
                        "59.65%",
                        "64.57%",
                        "69.49%",
                        "74.41%",
                        "79.33%",
                        "84.25%",
                        "89.17%",
                        "94.09%",
                        "99.01%",
                        "103.93%",
                        "108.85%"
                    ],
                    "name": "Mist Missile Damage"
                },
                {
                    "scaling": [
                        "100%",
                        "100%",
                        "100%",
                        "100%",
                        "100%",
                        "100%",
                        "100%",
                        "100%",
                        "100%",
                        "100%",
                        "100%",
                        "100%",
                        "100%",
                        "100%",
                        "100%",
                        "100%",
                        "100%",
                        "100%",
                        "100%",
                        "100%"
                    ],
                    "name": "Mist Avatar HP"
                },
                {
                    "scaling": [
                        "8",
                        "8",
                        "8",
                        "8",
                        "8",
                        "8",
                        "8",
                        "8",
                        "8",
                        "8",
                        "8",
                        "8",
                        "8",
                        "8",
                        "8",
                        "8",
                        "8",
                        "8",
                        "8",
                        "8"
                    ],
                    "name": "Mist Avatar Duration"
                },
                {
                    "scaling": [
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10"
                    ],
                    "name": "Cooldown"
                },
                {
                    "scaling": [
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15"
                    ],
                    "name": "Con. Energy Regen"
                }
            ],
            "name": "Shift Trick",
            "desc": "<size=40><color=Title>Mist Avatar<\/color><\/size>rnCasts \"Mist\" and 1 \"Mist Avatar(s)\" to taunt the surrounding targets. The avatars inherit a portion of Aalto's HP and generate 6 <color=Highlight>Mist Bullets<\/color> around them, dealing <color=Wind>Aero DMG<\/color>.rn<size=10> <\/size>rn<size=40><color=Title>Mist Missiles<\/color><\/size>rnDeals <color=Wind>Aero DMG<\/color>, considered as Resonance Skill damage."
        },
        "Resonance Liberation": {
            "motionValues": [
                {
                    "scaling": [
                        "200%",
                        "216.4%",
                        "232.8%",
                        "255.76%",
                        "272.16%",
                        "291.02%",
                        "317.26%",
                        "343.5%",
                        "369.74%",
                        "397.62%",
                        "430.42%",
                        "463.22%",
                        "496.02%",
                        "528.82%",
                        "561.62%",
                        "594.42%",
                        "627.22%",
                        "660.02%",
                        "692.82%",
                        "725.62%"
                    ],
                    "name": "Skill Damage"
                },
                {
                    "scaling": [
                        "10%",
                        "10%",
                        "10%",
                        "10%",
                        "10%",
                        "10%",
                        "10%",
                        "10%",
                        "10%",
                        "10%",
                        "10%",
                        "10%",
                        "10%",
                        "10%",
                        "10%",
                        "10%",
                        "10%",
                        "10%",
                        "10%",
                        "10%"
                    ],
                    "name": "Gate Of Quandary ATK Increase"
                },
                {
                    "scaling": [
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20"
                    ],
                    "name": "Cooldown"
                },
                {
                    "scaling": [
                        "150",
                        "150",
                        "150",
                        "150",
                        "150",
                        "150",
                        "150",
                        "150",
                        "150",
                        "150",
                        "150",
                        "150",
                        "150",
                        "150",
                        "150",
                        "150",
                        "150",
                        "150",
                        "150",
                        "150"
                    ],
                    "name": "Res. Energy Cost"
                },
                {
                    "scaling": [
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20"
                    ],
                    "name": "Con. Energy Regen"
                }
            ],
            "name": "Flower in the Mist",
            "desc": "Generate a \"Gate of Quandary\" in front, dealing <color=Wind>Aero DMG<\/color>. When bullets pass through the \"Gate of Quandary\", ATK is increased. \"Gate of Quandary\" lasts for 10s."
        },
        "Inherent Skill": {
            "name": "Skillful Cooking",
            "desc": "Has a chance to produce special dishes when cooking"
        },
        "Intro Skill": {
            "motionValues": [
                {
                    "scaling": [
                        "33.34%*3",
                        "36.07%*3",
                        "38.8%*3",
                        "42.63%*3",
                        "45.36%*3",
                        "48.51%*3",
                        "52.88%*3",
                        "57.25%*3",
                        "61.63%*3",
                        "66.27%*3",
                        "71.74%*3",
                        "77.21%*3",
                        "82.67%*3",
                        "88.14%*3",
                        "93.61%*3",
                        "99.07%*3",
                        "104.54%*3",
                        "110.01%*3",
                        "115.47%*3",
                        "120.94%*3"
                    ],
                    "name": "Skill Damage"
                },
                {
                    "scaling": [
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10"
                    ],
                    "name": "Con. Energy Regen"
                }
            ],
            "name": "Feint Shot",
            "desc": "Aalto shows up out of thin air to performs rapid continuous shooting, dealing <color=Wind>Aero damage<\/color>."
        },
        "Forte Circuit": {
            "motionValues": [
                {
                    "scaling": [
                        "30%",
                        "32.46%",
                        "34.92%",
                        "38.37%",
                        "40.83%",
                        "43.66%",
                        "47.59%",
                        "51.53%",
                        "55.47%",
                        "59.65%",
                        "64.57%",
                        "69.49%",
                        "74.41%",
                        "79.33%",
                        "84.25%",
                        "89.17%",
                        "94.09%",
                        "99.01%",
                        "103.93%",
                        "108.85%"
                    ],
                    "name": "Mist Missile DMG"
                },
                {
                    "scaling": [
                        "40%",
                        "40%",
                        "40%",
                        "40%",
                        "40%",
                        "40%",
                        "40%",
                        "40%",
                        "40%",
                        "40%",
                        "40%",
                        "40%",
                        "40%",
                        "40%",
                        "40%",
                        "40%",
                        "40%",
                        "40%",
                        "40%",
                        "40%"
                    ],
                    "name": "Movement Speed Increase"
                }
            ],
            "name": "Misty Cover",
            "desc": "When Aalto passes through \"Mist\" or \"Gate of Quandary\", he enters \"Mistcloak Dash\".rn<size=10> <\/size>rn<size=40><color=Title>Mistcloak Dash<\/color><\/size>rnMovement speed increased;rnDuring this period, \"Mist Drops\" are continuously consumed, and for each 1 \"Mist Drop\" consumed, 1 Resonance Skill <color=Highlight>Mist Missile<\/color> is generated.rn<size=10> <\/size>rn<size=40><color=Title>Mist Drops<\/color><\/size>rnAalto can hold up to 6 Mist Drops.rnWhen <color=Highlight>Basic Attack<\/color> or <color=Highlight>Mid-air Attack<\/color> passes through \"Mist\" and hits the target, 1 \"Mist Drop\" is recovered."
        },
        "Outro Skill": {
            "name": "Dissolving Mist",
            "desc": "The next character (or other characters on a nearby team that activates an Outro Skill) gains 23% Aero DMG Deepen for 14s or until they are switched off field."
        }
    }
};