export default {
    "forte": {
        "Basic Attack": {
            "motionValues": [
                {
                    "scaling": [
                        "28.00%",
                        "30.29%",
                        "32.59%",
                        "35.80%",
                        "38.10%",
                        "40.74%",
                        "44.41%",
                        "48.09%",
                        "51.76%",
                        "55.66%",
                        "60.25%",
                        "64.85%",
                        "69.44%",
                        "74.03%",
                        "78.62%",
                        "83.21%",
                        "87.81%",
                        "92.40%",
                        "96.99%"
                    ],
                    "name": "Part 1 Damage"
                },
                {
                    "scaling": [
                        "33.30%",
                        "36.03%",
                        "38.76%",
                        "42.58%",
                        "45.31%",
                        "48.45%",
                        "52.82%",
                        "57.19%",
                        "61.56%",
                        "66.20%",
                        "71.66%",
                        "77.12%",
                        "82.58%",
                        "88.04%",
                        "93.50%",
                        "98.97%",
                        "104.43%",
                        "109.89%",
                        "115.35%"
                    ],
                    "name": "Part 2 Damage"
                },
                {
                    "scaling": [
                        "33.35%*2",
                        "36.08%*2",
                        "38.81%*2",
                        "42.64%*2",
                        "45.38%*2",
                        "48.52%*2",
                        "52.90%*2",
                        "57.27%*2",
                        "61.65%*2",
                        "66.30%*2",
                        "71.77%*2",
                        "77.24%*2",
                        "82.71%*2",
                        "88.18%*2",
                        "93.65%*2",
                        "99.11%*2",
                        "104.58%*2",
                        "110.05%*2",
                        "115.52%*2"
                    ],
                    "name": "Part 3 Damage"
                },
                {
                    "scaling": [
                        "19.25%*4",
                        "20.82%*4",
                        "22.40%*4",
                        "24.61%*4",
                        "26.19%*4",
                        "28.01%*4",
                        "30.53%*4",
                        "33.06%*4",
                        "35.58%*4",
                        "38.27%*4",
                        "41.42%*4",
                        "44.58%*4",
                        "47.74%*4",
                        "50.89%*4",
                        "54.05%*4",
                        "57.21%*4",
                        "60.36%*4",
                        "63.52%*4",
                        "66.68%*4"
                    ],
                    "name": "Part 4 Damage"
                },
                {
                    "scaling": [
                        "120.00%",
                        "129.84%",
                        "139.67%",
                        "153.45%",
                        "163.29%",
                        "174.61%",
                        "190.35%",
                        "206.10%",
                        "221.84%",
                        "238.57%",
                        "258.25%",
                        "277.93%",
                        "297.61%",
                        "317.29%",
                        "336.97%",
                        "356.65%",
                        "376.33%",
                        "396.01%",
                        "415.69%"
                    ],
                    "name": "Woolies Damage"
                },
                {
                    "scaling": [
                        "94.10%",
                        "101.81%",
                        "109.53%",
                        "120.33%",
                        "128.05%",
                        "136.92%",
                        "149.27%",
                        "161.61%",
                        "173.96%",
                        "187.08%",
                        "202.51%",
                        "217.94%",
                        "233.37%",
                        "248.80%",
                        "264.24%",
                        "279.67%",
                        "295.10%",
                        "310.53%",
                        "325.97%"
                    ],
                    "name": "Heavy Attack Damage"
                },
                {
                    "scaling": [
                        "62.00%",
                        "67.08%",
                        "72.16%",
                        "79.28%",
                        "84.36%",
                        "90.21%",
                        "98.35%",
                        "106.48%",
                        "114.61%",
                        "123.26%",
                        "133.43%",
                        "143.59%",
                        "153.76%",
                        "163.93%",
                        "174.10%",
                        "184.27%",
                        "194.43%",
                        "204.60%",
                        "214.77%"
                    ],
                    "name": "Mid-Air Attack"
                },
                {
                    "scaling": [
                        "63.34%*2",
                        "68.54%*2",
                        "73.73%*2",
                        "81.01%*2",
                        "86.20%*2",
                        "92.18%*2",
                        "100.49%*2",
                        "108.80%*2",
                        "117.11%*2",
                        "125.94%*2",
                        "136.33%*2",
                        "146.72%*2",
                        "157.11%*2",
                        "167.50%*2",
                        "177.89%*2",
                        "188.28%*2",
                        "198.67%*2",
                        "209.06%*2",
                        "219.45%*2"
                    ],
                    "name": "Dodge Counter Damage"
                },
                {
                    "scaling": [
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25"
                    ],
                    "name": "Heavy Attack Stamina Consumption"
                },
                {
                    "scaling": [
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30"
                    ],
                    "name": "Mid-Air Attack Stamina Consumption"
                }
            ],
            "name": "Wooly Attack",
            "desc": "<size=40><color=Title>Basic Attack<\/color><\/size>rnEncore performs up to 4 consecutive attacks, dealing <color=Fire>Fusion DMG<\/color>.rn<size=10> <\/size>rn<size=40><color=Title>Basic Attack: Wooly Strike<\/color><\/size>rnAfter <color=Highlight>Basic Attack 4<\/color>, press the Basic Attack button to attack the target, dealing <color=Fire>Fusion DMG<\/color>.rn<size=10> <\/size>rn<size=40><color=Title>Heavy Attack<\/color><\/size>rnEncore consumes Stamina to attack the target, dealing <color=Fire>Fusion DMG<\/color>.rn<size=10> <\/size>rn<size=40><color=Title>Mid-air Attack<\/color><\/size>rnEncore consumes Stamina to perform a Mid-Air Plunging Attack, dealing <color=Fire>Fusion DMG<\/color>.rn<size=10> <\/size>rn<size=40><color=Title>Dodge Counter<\/color><\/size>rnUse <color=Highlight>Basic Attack<\/color> after a successful <color=Highlight>Dodge<\/color> to attack the target, dealing <color=Fire>Fusion DMG<\/color>."
        },
        "Resonance Skill": {
            "motionValues": [
                {
                    "scaling": [
                        "38.53%*8",
                        "41.69%*8",
                        "44.85%*8",
                        "49.28%*8",
                        "52.44%*8",
                        "56.07%*8",
                        "61.13%*8",
                        "66.18%*8",
                        "71.24%*8",
                        "76.61%*8",
                        "82.93%*8",
                        "89.25%*8",
                        "95.57%*8",
                        "101.89%*8",
                        "108.21%*8",
                        "114.53%*8",
                        "120.85%*8",
                        "127.17%*8",
                        "133.49%*8"
                    ],
                    "name": "Flaming Woolies Damage"
                },
                {
                    "scaling": [
                        "170.60%",
                        "184.58%",
                        "198.57%",
                        "218.16%",
                        "232.15%",
                        "248.24%",
                        "270.62%",
                        "293.00%",
                        "315.38%",
                        "339.16%",
                        "367.14%",
                        "395.12%",
                        "423.10%",
                        "451.08%",
                        "479.06%",
                        "507.04%",
                        "535.01%",
                        "562.99%",
                        "590.97%"
                    ],
                    "name": "Energetic Welcome Damage"
                },
                {
                    "scaling": [
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10"
                    ],
                    "name": "Cooldown"
                },
                {
                    "scaling": [
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15"
                    ],
                    "name": "Flaming Woolies Con. Energy Regen"
                },
                {
                    "scaling": [
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5"
                    ],
                    "name": "Energetic Welcome Con. Energy Regen"
                }
            ],
            "name": "Flaming Woolies",
            "desc": "<size=40><color=Title>Flaming Woolies<\/color><\/size>rnEncore summons Cloudy and Cosmos to attack with burning rays, dealing <color=Fire>Fusion DMG<\/color>.rn<size=10> <\/size>rn<size=40><color=Title>Energetic Welcome<\/color><\/size>rnAfter casting <color=Highlight>Flaming Woolies<\/color>, use <color=Highlight>Resonance Skill<\/color> to perform <color=Highlight>Energetic Welcome<\/color>, dealing <color=Fire>Fusion DMG<\/color>."
        },
        "Resonance Liberation": {
            "motionValues": [
                {
                    "scaling": [
                        "45.36%*2",
                        "49.08%*2",
                        "52.80%*2",
                        "58.01%*2",
                        "61.73%*2",
                        "66.01%*2",
                        "71.96%*2",
                        "77.91%*2",
                        "83.86%*2",
                        "90.18%*2",
                        "97.62%*2",
                        "105.06%*2",
                        "112.50%*2",
                        "119.94%*2",
                        "127.38%*2",
                        "134.81%*2",
                        "142.25%*2",
                        "149.69%*2",
                        "157.13%*2"
                    ],
                    "name": "Cosmos: Frolicking Part 1 Damage"
                },
                {
                    "scaling": [
                        "28.37%*3",
                        "30.70%*3",
                        "33.02%*3",
                        "36.28%*3",
                        "38.61%*3",
                        "41.28%*3",
                        "45.00%*3",
                        "48.72%*3",
                        "52.45%*3",
                        "56.40%*3",
                        "61.05%*3",
                        "65.71%*3",
                        "70.36%*3",
                        "75.01%*3",
                        "79.66%*3",
                        "84.31%*3",
                        "88.97%*3",
                        "93.62%*3",
                        "98.27%*3"
                    ],
                    "name": "Cosmos: Frolicking Part 2 Damage"
                },
                {
                    "scaling": [
                        "33.19%*4",
                        "35.92%*4",
                        "38.64%*4",
                        "42.45%*4",
                        "45.17%*4",
                        "48.30%*4",
                        "52.65%*4",
                        "57.01%*4",
                        "61.36%*4",
                        "65.99%*4",
                        "71.43%*4",
                        "76.87%*4",
                        "82.32%*4",
                        "87.76%*4",
                        "93.20%*4",
                        "98.65%*4",
                        "104.09%*4",
                        "109.53%*4",
                        "114.98%*4"
                    ],
                    "name": "Cosmos: Frolicking Part 3 Damage"
                },
                {
                    "scaling": [
                        "97.59%*3",
                        "105.59%*3",
                        "113.59%*3",
                        "124.79%*3",
                        "132.79%*3",
                        "142.00%*3",
                        "154.80%*3",
                        "167.60%*3",
                        "180.40%*3",
                        "194.01%*3",
                        "210.01%*3",
                        "226.01%*3",
                        "242.02%*3",
                        "258.02%*3",
                        "274.02%*3",
                        "290.03%*3",
                        "306.03%*3",
                        "322.03%*3",
                        "338.04%*3"
                    ],
                    "name": "Cosmos: Frolicking Part 4 Damage"
                },
                {
                    "scaling": [
                        "109.44%",
                        "118.42%",
                        "127.39%",
                        "139.96%",
                        "148.93%",
                        "159.25%",
                        "173.61%",
                        "187.97%",
                        "202.32%",
                        "217.58%",
                        "235.53%",
                        "253.48%",
                        "271.42%",
                        "289.37%",
                        "307.32%",
                        "325.27%",
                        "343.22%",
                        "361.16%",
                        "379.11%"
                    ],
                    "name": "Cosmos: Heavy Attack Damage"
                },
                {
                    "scaling": [
                        "31.85%*4",
                        "34.46%*4",
                        "37.07%*4",
                        "40.72%*4",
                        "43.34%*4",
                        "46.34%*4",
                        "50.52%*4",
                        "54.70%*4",
                        "58.88%*4",
                        "63.32%*4",
                        "68.54%*4",
                        "73.76%*4",
                        "78.99%*4",
                        "84.21%*4",
                        "89.43%*4",
                        "94.66%*4",
                        "99.88%*4",
                        "105.10%*4",
                        "110.33%*4"
                    ],
                    "name": "Cosmos Rampage Damage"
                },
                {
                    "scaling": [
                        "33.19%*4",
                        "35.92%*4",
                        "38.64%*4",
                        "42.45%*4",
                        "45.17%*4",
                        "48.30%*4",
                        "52.65%*4",
                        "57.01%*4",
                        "61.36%*4",
                        "65.99%*4",
                        "71.43%*4",
                        "76.87%*4",
                        "82.32%*4",
                        "87.76%*4",
                        "93.20%*4",
                        "98.65%*4",
                        "104.09%*4",
                        "109.53%*4",
                        "114.98%*4"
                    ],
                    "name": "Cosmos: Dodge Counter Damage"
                },
                {
                    "scaling": [
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10"
                    ],
                    "name": "Cosmos Rave Duration"
                },
                {
                    "scaling": [
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16"
                    ],
                    "name": "Cooldown"
                },
                {
                    "scaling": [
                        "4",
                        "4",
                        "4",
                        "4",
                        "4",
                        "4",
                        "4",
                        "4",
                        "4",
                        "4",
                        "4",
                        "4",
                        "4",
                        "4",
                        "4",
                        "4",
                        "4",
                        "4",
                        "4",
                        "4"
                    ],
                    "name": "Cosmos Rampage Cooldown"
                },
                {
                    "scaling": [
                        "125",
                        "125",
                        "125",
                        "125",
                        "125",
                        "125",
                        "125",
                        "125",
                        "125",
                        "125",
                        "125",
                        "125",
                        "125",
                        "125",
                        "125",
                        "125",
                        "125",
                        "125",
                        "125",
                        "125"
                    ],
                    "name": "Res. Energy Cost"
                },
                {
                    "scaling": [
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20"
                    ],
                    "name": "Con. Energy Regen"
                }
            ],
            "name": "Cosmos Rave",
            "desc": "As Encore loses control, Cosmos breaks free and wreaks havoc on its surroundings.rn<size=10> <\/size>rn<size=40><color=Title>Basic Attack: Cosmos: Frolicking<\/color><\/size>rnDuring Cosmos Rave, the <color=Highlight>Basic Attack<\/color> is replaced with <color=Highlight>Cosmos: Frolicking<\/color>, which performs up to 4 consecutive attacks, dealing <color=Fire>Fusion DMG<\/color>, considered as Basic Attack damage.rn<size=10> <\/size>rn<size=40><color=Title>Cosmos: Heavy Attack<\/color><\/size>rnDuring Cosmos Rave, the <color=Highlight>Heavy Attack<\/color> is replaced with <color=Highlight>Cosmos: Heavy Attack<\/color>, consuming Stamina to attack the target, dealing <color=Fire>Fusion DMG<\/color>, considered as Heavy Attack damage.rn<size=10> <\/size>rn<size=40><color=Title>Resonance Skill: Cosmos: Rampage<\/color><\/size>rnDuring Cosmos Rave, <color=Highlight>Flaming Woolies<\/color> is replaced with <color=Highlight>Cosmos: Rampage<\/color>, dealing <color=Fire>Fusion DMG<\/color>, considered as Resonance Skill damage.rn<size=10> <\/size>rn<size=40><color=Title>Cosmos: Dodge Counter<\/color><\/size>rnDuring Cosmos Rave, use <color=Highlight>Basic Attack<\/color> after a successful <color=Highlight>Dodge<\/color> to attack the target, dealing <color=Fire>Fusion DMG<\/color>, considered as Basic Attack damage."
        },
        "Inherent Skill": {
            "name": "Skillful Cooking",
            "desc": "Has a chance to produce special dishes when cooking"
        },
        "Intro Skill": {
            "motionValues": [
                {
                    "scaling": [
                        "100.00%",
                        "108.20%",
                        "116.40%",
                        "127.88%",
                        "136.08%",
                        "145.51%",
                        "158.63%",
                        "171.75%",
                        "184.87%",
                        "198.81%",
                        "215.21%",
                        "231.61%",
                        "248.01%",
                        "264.41%",
                        "280.81%",
                        "297.21%",
                        "313.61%",
                        "330.01%",
                        "346.41%"
                    ],
                    "name": "Skill Damage"
                },
                {
                    "scaling": [
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10"
                    ],
                    "name": "Con. Energy Regen"
                }
            ],
            "name": "Woolies Can Help!",
            "desc": "Encore pounces at the enemies with Cosmos, dealing <color=Fire>Fusion DMG<\/color>."
        },
        "Forte Circuit": {
            "motionValues": [
                {
                    "scaling": [
                        "168.00%",
                        "181.77%",
                        "195.55%",
                        "214.83%",
                        "228.61%",
                        "244.45%",
                        "266.49%",
                        "288.53%",
                        "310.58%",
                        "334.00%",
                        "361.55%",
                        "389.10%",
                        "416.65%",
                        "444.20%",
                        "471.76%",
                        "499.31%",
                        "526.86%",
                        "554.41%",
                        "581.96%"
                    ],
                    "name": "Cloudy: Frenzy Damage"
                },
                {
                    "scaling": [
                        "23.35%*6+249.08%",
                        "25.26%*6+269.51%",
                        "27.18%*6+289.93%",
                        "29.86%*6+318.53%",
                        "31.77%*6+338.95%",
                        "33.97%*6+362.44%",
                        "37.04%*6+395.12%",
                        "40.10%*6+427.80%",
                        "43.17%*6+460.48%",
                        "46.42%*6+495.21%",
                        "50.25%*6+536.06%",
                        "54.08%*6+576.91%",
                        "57.91%*6+617.76%",
                        "61.74%*6+658.61%",
                        "65.57%*6+699.46%",
                        "69.40%*6+740.31%",
                        "73.23%*6+781.16%",
                        "77.06%*6+822.01%",
                        "80.89%*6+862.86%"
                    ],
                    "name": "Cosmos: Rupture Damage"
                },
                {
                    "scaling": [
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10"
                    ],
                    "name": "Cloudy: Frenzy Con. Energy Regen"
                },
                {
                    "scaling": [
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10"
                    ],
                    "name": "Cosmos: Rupture Con. Energy Regen"
                }
            ],
            "name": "Black & White Woolies",
            "desc": "<size=40><color=Title>Heavy Attack: Cloudy Frenzy<\/color><\/size>nWhen Encore's \"Dissonance\" is full, after casting a <color=Highlight>Heavy Attack<\/color>, Encore will consume all \"Dissonance\" to enter the Dissonance state, reducing damage taken by 70%. Switching Characters does not interrupt \"Dissonance\".nAfter the Dissonance state ends, Encore will cast <color=Highlight>Cloudy Frenzy<\/color>, dealing <color=Fire>Fusion DMG<\/color>, considered as Resonance Liberation damage.n<size=10> <\/size>n<size=40><color=Title>Heavy Attack: Cosmos Rupture<\/color><\/size>nDuring Cosmos Rampage, when casting <color=Highlight>Heavy Attack<\/color>, if \"Dissonance\" is full, Encore will consume all \"Dissonance\" to enter Cosmos' Dissonance state, reducing damage taken by 70%. Switching Characters does not interrupt \"Dissonance\".nAfter Cosmos' Dissonance state ends, Encore will cast <color=Highlight>Cosmos Rupture<\/color>, dealing <color=Fire>Fusion DMG<\/color>, considered as Resonance Liberation damage.n<size=10> <\/size>n<size=40><color=Title>Dissonance<\/color><\/size>nEncore can hold up to 100 \"Dissonance\".nWhen Normal Attack <color=Highlight>Wooly Attack<\/color> hits the target, Encore restores \"Dissonance\".nWhen Resonance Skill <color=Highlight>Flaming Woolies<\/color> hits the target, Encore restores \"Dissonance\".nWhen Resonance Skill <color=Highlight>Energetic Welcome<\/color> hits the target, Encore restores \"Dissonance\".nWhen Intro Skill <color=Highlight>Woolies Helpers<\/color> hits the target, Encore restores \"Dissonance\".nDuring the duration of Resonance Liberation <color=Highlight>Cosmos Rave<\/color>, hitting targets will restore \"Dissonance\" to Encore."
        },
        "Outro Skill": {
            "name": "Thermal Field",
            "desc": "Encore generates a Thermal Field centered around skill target, with a radius of 3m. Targets inside the Thermal Field are continuously burned, suffering <color=Fire>Fusion DMG<\/color> equal to 176.76% of Encore's ATK every 1.5s for 6s."
        }
    }
};