export default {
    "forte": {
        "Basic Attack": {
            "motionValues": [
                {
                    "scaling": [
                        "24.50%",
                        "26.51%",
                        "28.52%",
                        "31.34%",
                        "33.34%",
                        "35.65%",
                        "38.87%",
                        "42.08%",
                        "45.30%",
                        "48.71%",
                        "52.73%",
                        "56.75%",
                        "60.77%",
                        "64.79%",
                        "68.80%",
                        "72.82%",
                        "76.84%",
                        "80.86%",
                        "84.88%",
                        "88.89%"
                    ],
                    "name": "Part 1 Damage"
                },
                {
                    "scaling": [
                        "37.10%",
                        "40.15%",
                        "43.19%",
                        "47.45%",
                        "50.49%",
                        "53.99%",
                        "58.86%",
                        "63.72%",
                        "68.59%",
                        "73.76%",
                        "79.85%",
                        "85.93%",
                        "92.02%",
                        "98.10%",
                        "104.19%",
                        "110.27%",
                        "116.35%",
                        "122.44%",
                        "128.52%",
                        "134.61%"
                    ],
                    "name": "Part 2 Damage"
                },
                {
                    "scaling": [
                        "10.85%*4",
                        "11.74%*4",
                        "12.63%*4",
                        "13.88%*4",
                        "14.77%*4",
                        "15.79%*4",
                        "17.22%*4",
                        "18.64%*4",
                        "20.06%*4",
                        "21.58%*4",
                        "23.36%*4",
                        "25.13%*4",
                        "26.91%*4",
                        "28.69%*4",
                        "30.47%*4",
                        "32.25%*4",
                        "34.03%*4",
                        "35.81%*4",
                        "37.59%*4",
                        "39.37%*4"
                    ],
                    "name": "Part 3 Damage"
                },
                {
                    "scaling": [
                        "19.95%*2",
                        "21.59%*2",
                        "23.23%*2",
                        "25.52%*2",
                        "27.15%*2",
                        "29.03%*2",
                        "31.65%*2",
                        "34.27%*2",
                        "36.89%*2",
                        "39.67%*2",
                        "42.94%*2",
                        "46.21%*2",
                        "49.48%*2",
                        "52.75%*2",
                        "56.03%*2",
                        "59.30%*2",
                        "62.57%*2",
                        "65.84%*2",
                        "69.11%*2",
                        "72.39%*2"
                    ],
                    "name": "Part 4 Damage"
                },
                {
                    "scaling": [
                        "117.60%",
                        "127.25%",
                        "136.89%",
                        "150.39%",
                        "160.04%",
                        "171.12%",
                        "186.55%",
                        "201.98%",
                        "217.41%",
                        "233.81%",
                        "253.09%",
                        "272.38%",
                        "291.66%",
                        "310.95%",
                        "330.24%",
                        "349.52%",
                        "368.81%",
                        "388.10%",
                        "407.38%",
                        "426.67%"
                    ],
                    "name": "Part 5 Damage"
                },
                {
                    "scaling": [
                        "11.20%*5",
                        "12.12%*5",
                        "13.04%*5",
                        "14.33%*5",
                        "15.25%*5",
                        "16.30%*5",
                        "17.77%*5",
                        "19.24%*5",
                        "20.71%*5",
                        "22.27%*5",
                        "24.11%*5",
                        "25.95%*5",
                        "27.78%*5",
                        "29.62%*5",
                        "31.46%*5",
                        "33.29%*5",
                        "35.13%*5",
                        "36.97%*5",
                        "38.80%*5",
                        "40.64%*5"
                    ],
                    "name": "Heavy Attack Damage"
                },
                {
                    "scaling": [
                        "43.40%",
                        "46.96%",
                        "50.52%",
                        "55.50%",
                        "59.06%",
                        "63.16%",
                        "68.85%",
                        "74.54%",
                        "80.24%",
                        "86.29%",
                        "93.41%",
                        "100.52%",
                        "107.64%",
                        "114.76%",
                        "121.88%",
                        "128.99%",
                        "136.11%",
                        "143.23%",
                        "150.35%",
                        "157.46%"
                    ],
                    "name": "Mid-air Attack Damage"
                },
                {
                    "scaling": [
                        "84.00%",
                        "90.89%",
                        "97.78%",
                        "107.42%",
                        "114.31%",
                        "122.23%",
                        "133.25%",
                        "144.27%",
                        "155.30%",
                        "167.01%",
                        "180.78%",
                        "194.56%",
                        "208.33%",
                        "222.11%",
                        "235.89%",
                        "249.66%",
                        "263.44%",
                        "277.21%",
                        "290.99%",
                        "304.77%"
                    ],
                    "name": "Dodge Counter Damage"
                },
                {
                    "scaling": [
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25"
                    ],
                    "name": "Heavy Attack Stamina Cost"
                },
                {
                    "scaling": [
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30"
                    ],
                    "name": "Mid-air Attack Stamina Cost"
                }
            ],
            "name": "Frigid Light",
            "desc": "<size=40><color=Title>Basic Attack<\/color><\/size>rnSanhua performs up to 5 consecutive attacks, dealing <color=Ice>Glacio DMG<\/color>.rn<size=10> <\/size>rn<size=40><color=Title>Heavy Attack<\/color><\/size>rnSanhua consumes Stamina to launch attacks, dealing <color=Ice>Glacio DMG<\/color>.rn<size=10> <\/size>rn<size=40><color=Title>Mid-air Attack<\/color><\/size>rnSanhua consumes Stamina to perform a Mid-Air Plunging Attack, dealing <color=Ice>Glacio DMG<\/color>.rn<size=10> <\/size>rn<size=40><color=Title>Dodge Counter<\/color><\/size>rnUse <color=Highlight>Basic Attack<\/color> after a successful <color=Highlight>Dodge<\/color> to attack the target, dealing <color=Ice>Glacio DMG<\/color>."
        },
        "Resonance Skill": {
            "motionValues": [
                {
                    "scaling": [
                        "181.00%",
                        "195.85%",
                        "210.69%",
                        "231.47%",
                        "246.31%",
                        "263.38%",
                        "287.13%",
                        "310.87%",
                        "334.62%",
                        "359.85%",
                        "389.54%",
                        "419.22%",
                        "448.90%",
                        "478.59%",
                        "508.27%",
                        "537.96%",
                        "567.64%",
                        "597.32%",
                        "627.01%",
                        "656.69%"
                    ],
                    "name": "Skill Damage"
                },
                {
                    "scaling": [
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10"
                    ],
                    "name": "Cooldown"
                },
                {
                    "scaling": [
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15"
                    ],
                    "name": "Con. Energy Regen"
                }
            ],
            "name": "Eternal Frost",
            "desc": "Sanhua sends an air blade to create 1 \"Ice Prism\" cross the ground, dealing <color=Ice>Glacio DMG<\/color>."
        },
        "Resonance Liberation": {
            "motionValues": [
                {
                    "scaling": [
                        "407.16%",
                        "440.55%",
                        "473.94%",
                        "520.68%",
                        "554.07%",
                        "592.46%",
                        "645.88%",
                        "699.30%",
                        "752.72%",
                        "809.48%",
                        "876.25%",
                        "943.03%",
                        "1009.80%",
                        "1076.58%",
                        "1143.35%",
                        "1210.13%",
                        "1276.90%",
                        "1343.67%",
                        "1410.45%",
                        "1477.22%"
                    ],
                    "name": "Skill Damage"
                },
                {
                    "scaling": [
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16"
                    ],
                    "name": "Cooldown"
                },
                {
                    "scaling": [
                        "100",
                        "100",
                        "100",
                        "100",
                        "100",
                        "100",
                        "100",
                        "100",
                        "100",
                        "100",
                        "100",
                        "100",
                        "100",
                        "100",
                        "100",
                        "100",
                        "100",
                        "100"
                    ],
                    "name": "Res. Energy Cost"
                },
                {
                    "scaling": [
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20"
                    ],
                    "name": "Con. Energy Regen"
                }
            ],
            "name": "Glacial Gaze",
            "desc": "Sanhua deals <color=Ice>Glacio DMG<\/color> and creates 1 \"Glacier\"."
        },
        "Inherent Skill": {
            "name": "Skillful Cooking",
            "desc": "Has a chance to produce special dishes when cooking"
        },
        "Intro Skill": {
            "motionValues": [
                {
                    "scaling": [
                        "70.00%",
                        "75.74%",
                        "81.48%",
                        "89.52%",
                        "95.26%",
                        "101.86%",
                        "111.05%",
                        "120.23%",
                        "129.41%",
                        "139.17%",
                        "150.65%",
                        "162.13%",
                        "173.61%",
                        "185.09%",
                        "196.57%",
                        "208.05%",
                        "219.53%",
                        "231.01%",
                        "242.49%",
                        "253.97%"
                    ],
                    "name": "Skill Damage"
                },
                {
                    "scaling": [
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10"
                    ],
                    "name": "Con. Energy Regen"
                }
            ],
            "name": "Freezing Thorns",
            "desc": "Sanhua swings her blade downward and creates 1 \"Ice Thorn\", dealing <color=Ice>Glacio DMG<\/color>."
        },
        "Forte Circuit": {
            "motionValues": [
                {
                    "scaling": [
                        "93.70%*2",
                        "101.39%*2",
                        "109.07%*2",
                        "119.83%*2",
                        "127.51%*2",
                        "136.35%*2",
                        "148.64%*2",
                        "160.93%*2",
                        "173.23%*2",
                        "186.29%*2",
                        "201.66%*2",
                        "217.02%*2",
                        "232.39%*2",
                        "247.76%*2",
                        "263.12%*2",
                        "278.49%*2",
                        "293.86%*2",
                        "309.22%*2",
                        "324.59%*2",
                        "339.96%*2"
                    ],
                    "name": "Burst Damage"
                },
                {
                    "scaling": [
                        "70.00%",
                        "75.74%",
                        "81.48%",
                        "89.52%",
                        "95.26%",
                        "101.86%",
                        "111.05%",
                        "120.23%",
                        "129.41%",
                        "139.17%",
                        "150.65%",
                        "162.13%",
                        "173.61%",
                        "185.09%",
                        "196.57%",
                        "208.05%",
                        "219.53%",
                        "231.01%",
                        "242.49%",
                        "253.97%"
                    ],
                    "name": "Glacier Burst Damage"
                },
                {
                    "scaling": [
                        "40.00%",
                        "43.28%",
                        "46.56%",
                        "51.16%",
                        "54.44%",
                        "58.21%",
                        "63.46%",
                        "68.70%",
                        "73.95%",
                        "79.53%",
                        "86.09%",
                        "92.65%",
                        "99.21%",
                        "105.77%",
                        "112.33%",
                        "118.89%",
                        "125.45%",
                        "132.01%",
                        "138.57%",
                        "145.13%"
                    ],
                    "name": "Ice Prism Burst Damage"
                },
                {
                    "scaling": [
                        "30.00%",
                        "32.46%",
                        "34.92%",
                        "38.37%",
                        "40.83%",
                        "43.66%",
                        "47.59%",
                        "51.53%",
                        "55.47%",
                        "59.65%",
                        "64.57%",
                        "69.49%",
                        "74.41%",
                        "79.33%",
                        "84.25%",
                        "89.17%",
                        "94.09%",
                        "99.01%",
                        "103.93%",
                        "108.85%"
                    ],
                    "name": "Ice Thorn Burst Damage"
                },
                {
                    "scaling": [
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5"
                    ],
                    "name": "Clarity Duration"
                },
                {
                    "scaling": [
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5"
                    ],
                    "name": "Glacier Duration"
                },
                {
                    "scaling": [
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5"
                    ],
                    "name": "Ice Prism Duration"
                },
                {
                    "scaling": [
                        "8",
                        "8",
                        "8",
                        "8",
                        "8",
                        "8",
                        "8",
                        "8",
                        "8",
                        "8",
                        "8",
                        "8",
                        "8",
                        "8",
                        "8",
                        "8",
                        "8",
                        "8"
                    ],
                    "name": "Ice Thorn Duration"
                },
                {
                    "scaling": [
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15"
                    ],
                    "name": "Burst Con. Energy Regen"
                },
                {
                    "scaling": [
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15"
                    ],
                    "name": "Glacier Burst Con. Damage Regen"
                },
                {
                    "scaling": [
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15"
                    ],
                    "name": "Ice Prism Burst Con. Damage Regen"
                }
            ],
            "name": "Clarity of Mind",
            "desc": "<size=40><color=Title>Heavy Attack: Detonate<\/color><\/size>nWhen holding <color=Highlight>Basic Attack<\/color>, a cursor moves back and forth on the Forte Gauge. Release <color=Highlight>Basic Attack<\/color> while cursor falls in the \"Frostbite\" area, to perform Heavy Attack <color=Highlight>Detonate<\/color>, dealing <color=Ice>Glacio DMG<\/color> considered as Heavy Attack damage.n<size=10> <\/size>n<size=40><color=Title>Ice Burst<\/color><\/size>nSanhua\u2019s Heavy Attack <color=Highlight>Detonate<\/color> detonates all \"Ice Thorns\", \"Ice Prisms\" and \"Glaciers\" within her attack range, dealing <color=Ice>Glacio DMG<\/color>. DMG done by Ice Burst is considered as Resonance Skill damage.n<size=10> <\/size>n<size=40><color=Title>Frostbite Area<\/color><\/size>nThe \"Frostbite\" area expands with every 1 stack of \"Clarity\". \"Clarity\" stacks up to 2 times.nSanhua obtains 1 stack of \"Clarity\" upon performing <color=Highlight>Basic Attack 5<\/color>.nSanhua obtains 1 stack of \"Clarity\" upon casting Intro Skill <color=Highlight>Freezing Thorns<\/color>.nSanhua obtains 1 stack of \"Clarity\" upon casting Resonance Skill <color=Highlight>Eternal Frost<\/color>.nSanhua obtains 2 stack(s) of \"Clarity\" upon casting Resonance Liberation <color=Highlight>Glacial Gaze<\/color>.nUpon casting Heavy Attack <color=Highlight>Detonate<\/color>, all \"Clarity\" is removed."
        },
        "Outro Skill": {
            "name": "Silversnow",
            "desc": "The next character (or other characters on a nearby team that activates an Outro Skill) gains 38% Basic Attack DMG Deepen for 14s or until they are switched off field."
        }
    }
};