export default {
    "forte": {
        "Basic Attack": {
            "motionValues": [
                {
                    "scaling": [
                        "14.49%",
                        "15.68%",
                        "16.87%",
                        "18.53%",
                        "19.72%",
                        "21.09%",
                        "22.99%",
                        "24.89%",
                        "26.79%",
                        "28.81%",
                        "31.19%",
                        "33.57%",
                        "35.94%",
                        "38.32%",
                        "40.69%",
                        "43.07%",
                        "45.45%",
                        "47.82%",
                        "50.2%",
                        "52.58%"
                    ],
                    "name": "Part 1 Damage"
                },
                {
                    "scaling": [
                        "17.01%*2",
                        "18.41%*2",
                        "19.8%*2",
                        "21.76%*2",
                        "23.15%*2",
                        "24.76%*2",
                        "26.99%*2",
                        "29.22%*2",
                        "31.45%*2",
                        "33.82%*2",
                        "36.61%*2",
                        "39.4%*2",
                        "42.19%*2",
                        "44.98%*2",
                        "47.77%*2",
                        "50.56%*2",
                        "53.35%*2",
                        "56.14%*2",
                        "58.93%*2",
                        "61.72%*2"
                    ],
                    "name": "Part 2 Damage"
                },
                {
                    "scaling": [
                        "7.04%*7",
                        "7.62%*7",
                        "8.19%*7",
                        "9%*7",
                        "9.58%*7",
                        "10.24%*7",
                        "11.16%*7",
                        "12.09%*7",
                        "13.01%*7",
                        "13.99%*7",
                        "15.15%*7",
                        "16.3%*7",
                        "17.45%*7",
                        "18.61%*7",
                        "19.76%*7",
                        "20.91%*7",
                        "22.07%*7",
                        "23.22%*7",
                        "24.37%*7",
                        "25.53%*7"
                    ],
                    "name": "Part 3 Damage"
                },
                {
                    "scaling": [
                        "37.8%",
                        "40.9%",
                        "44%",
                        "48.34%",
                        "51.44%",
                        "55.01%",
                        "59.97%",
                        "64.93%",
                        "69.89%",
                        "75.16%",
                        "81.35%",
                        "87.55%",
                        "93.75%",
                        "99.95%",
                        "106.15%",
                        "112.35%",
                        "118.55%",
                        "124.75%",
                        "130.95%",
                        "137.15%"
                    ],
                    "name": "Part 4 Damage"
                },
                {
                    "scaling": [
                        "15%*2",
                        "16.23%*2",
                        "17.46%*2",
                        "19.19%*2",
                        "20.42%*2",
                        "21.83%*2",
                        "23.8%*2",
                        "25.77%*2",
                        "27.74%*2",
                        "29.83%*2",
                        "32.29%*2",
                        "34.75%*2",
                        "37.21%*2",
                        "39.67%*2",
                        "42.13%*2",
                        "44.59%*2",
                        "47.05%*2",
                        "49.51%*2",
                        "51.97%*2",
                        "54.43%*2"
                    ],
                    "name": "Heavy Attack Damage"
                },
                {
                    "scaling": [
                        "62%",
                        "67.09%",
                        "72.17%",
                        "79.29%",
                        "84.37%",
                        "90.22%",
                        "98.36%",
                        "106.49%",
                        "114.62%",
                        "123.27%",
                        "133.44%",
                        "143.6%",
                        "153.77%",
                        "163.94%",
                        "174.11%",
                        "184.28%",
                        "194.44%",
                        "204.61%",
                        "214.78%",
                        "224.95%"
                    ],
                    "name": "Mid-Air Attack Damage"
                },
                {
                    "scaling": [
                        "12.18%*7",
                        "13.18%*7",
                        "14.18%*7",
                        "15.58%*7",
                        "16.58%*7",
                        "17.72%*7",
                        "19.32%*7",
                        "20.92%*7",
                        "22.52%*7",
                        "24.22%*7",
                        "26.21%*7",
                        "28.21%*7",
                        "30.21%*7",
                        "32.2%*7",
                        "34.2%*7",
                        "36.2%*7",
                        "38.2%*7",
                        "40.19%*7",
                        "42.19%*7",
                        "44.19%*7"
                    ],
                    "name": "Dodge Counter Damage"
                },
                {
                    "scaling": [
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25"
                    ],
                    "name": "Heavy Attack Stamina Consumption"
                },
                {
                    "scaling": [
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30",
                        "30"
                    ],
                    "name": "Mid-Air Attack Stamina Consumption"
                }
            ],
            "name": "Zapstring's Dance",
            "desc": "<size=40><color=Title>Basic Attack<\/color><\/size>rnYinlin controls the puppet \"Zapstring\" to perform up to 4 attacks, dealing <color=Thunder>Electro DMG<\/color>.rn<size=10> <\/size>rn<size=40><color=Title>Heavy Attack<\/color><\/size>rnYinlin consumes Stamina to control \"Zapstring\", dealing <color=Thunder>Electro DMG<\/color>.rn<size=10> <\/size>rn<size=40><color=Title>Mid-air Attack<\/color><\/size>rnYinlin consumes Stamina to control \"Zapstring\" and perform a Mid-air Plunging Attack, dealing <color=Thunder>Electro DMG<\/color>.rn<size=10> <\/size>rn<size=40><color=Title>Dodge Counter<\/color><\/size>rnUse <color=Highlight>Basic Attack<\/color> after a successful <color=Highlight>Dodge<\/color> to attack the target, dealing <color=Thunder>Electro DMG<\/color>."
        },
        "Resonance Skill": {
            "motionValues": [
                {
                    "scaling": [
                        "30%*3",
                        "32.46%*3",
                        "34.92%*3",
                        "38.37%*3",
                        "40.83%*3",
                        "43.66%*3",
                        "47.59%*3",
                        "51.53%*3",
                        "55.47%*3",
                        "59.65%*3",
                        "64.57%*3",
                        "69.49%*3",
                        "74.41%*3",
                        "79.33%*3",
                        "84.25%*3",
                        "89.17%*3",
                        "94.09%*3",
                        "99.01%*3",
                        "103.93%*3",
                        "108.85%*3"
                    ],
                    "name": "Magnetic Roar Damage"
                },
                {
                    "scaling": [
                        "45%*4",
                        "48.69%*4",
                        "52.38%*4",
                        "57.55%*4",
                        "61.24%*4",
                        "65.48%*4",
                        "71.39%*4",
                        "77.29%*4",
                        "83.2%*4",
                        "89.47%*4",
                        "96.85%*4",
                        "104.23%*4",
                        "111.61%*4",
                        "118.99%*4",
                        "126.37%*4",
                        "133.75%*4",
                        "141.13%*4",
                        "148.51%*4",
                        "155.89%*4",
                        "163.27%*4"
                    ],
                    "name": "Lightning Execution Damage"
                },
                {
                    "scaling": [
                        "10%",
                        "10.82%",
                        "11.64%",
                        "12.79%",
                        "13.61%",
                        "14.56%",
                        "15.87%",
                        "17.18%",
                        "18.49%",
                        "19.89%",
                        "21.53%",
                        "23.17%",
                        "24.81%",
                        "26.45%",
                        "28.09%",
                        "29.73%",
                        "31.37%",
                        "33.01%",
                        "34.65%",
                        "36.29%"
                    ],
                    "name": "Electromagnetic Blast Damage"
                },
                {
                    "scaling": [
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10"
                    ],
                    "name": "Execution Mode Duration"
                },
                {
                    "scaling": [
                        "12",
                        "12",
                        "12",
                        "12",
                        "12",
                        "12",
                        "12",
                        "12",
                        "12",
                        "12",
                        "12",
                        "12",
                        "12",
                        "12",
                        "12",
                        "12",
                        "12",
                        "12",
                        "12",
                        "12"
                    ],
                    "name": "Cooldown"
                },
                {
                    "scaling": [
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10"
                    ],
                    "name": "Magnetic Roar Con. Energy Regen"
                },
                {
                    "scaling": [
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15",
                        "15"
                    ],
                    "name": "Lightning Execution Con. Energy Regen"
                },
                {
                    "scaling": [
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5",
                        "5"
                    ],
                    "name": "Electromagnetic Blast Con. Energy Regen"
                }
            ],
            "name": "Magnetic Roar",
            "desc": "<size=40><color=Title>Magnetic Roar<\/color><\/size>rnThe puppet \"Zapstring\" deals <color=Thunder>Electro DMG<\/color> to the target, and puts Yinlin into the <color=Highlight>Execution Mode<\/color>.rn<size=10> <\/size>rn<size=40><color=Title>Execution Mode<\/color><\/size>rn<color=Highlight>Basic Attack<\/color> and <color=Highlight>Dodge Counter<\/color> will trigger 1 <color=Highlight>Electromagnetic Blast<\/color> when hitting a target.rnEach stage of <color=Highlight>Basic Attack<\/color> or <color=Highlight>Dodge Counter<\/color> can only trigger 1 <color=Highlight>Electromagnetic Blast<\/color>, up to 4 times.rn<size=10> <\/size>rn<size=40><color=Title>Electromagnetic Blast<\/color><\/size>rnAttack all targets marked with Resonance Circuit <color=Highlight>Sinner's Mark<\/color>, dealing <color=Thunder>Electro DMG<\/color>.rn<size=10> <\/size>rn<size=40><color=Title>Lightning Execution<\/color><\/size>rnUse Resonance Skill after casting Resonance Skill <color=Highlight>Magnetic Roar<\/color> to cast <color=Highlight>Lightning Execution<\/color> to attack the target, dealing <color=Thunder>Electro DMG<\/color>.rnIf Resonance Skill <color=Highlight>Lightning Execution<\/color> is not activated in a while or this Character is switched, this Skill will be put on Cooldown."
        },
        "Resonance Liberation": {
            "motionValues": [
                {
                    "scaling": [
                        "58.63%*7",
                        "63.44%*7",
                        "68.25%*7",
                        "74.98%*7",
                        "79.79%*7",
                        "85.32%*7",
                        "93.01%*7",
                        "100.7%*7",
                        "108.39%*7",
                        "116.56%*7",
                        "126.18%*7",
                        "135.79%*7",
                        "145.41%*7",
                        "155.02%*7",
                        "164.64%*7",
                        "174.25%*7",
                        "183.87%*7",
                        "193.49%*7",
                        "203.1%*7",
                        "212.72%*7"
                    ],
                    "name": "Skill Damage"
                },
                {
                    "scaling": [
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16",
                        "16"
                    ],
                    "name": "Cooldown"
                },
                {
                    "scaling": [
                        "125",
                        "125",
                        "125",
                        "125",
                        "125",
                        "125",
                        "125",
                        "125",
                        "125",
                        "125",
                        "125",
                        "125",
                        "125",
                        "125",
                        "125",
                        "125",
                        "125",
                        "125"
                    ],
                    "name": "Res. Energy Cost"
                },
                {
                    "scaling": [
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20",
                        "20"
                    ],
                    "name": "Con. Energy Regen"
                }
            ],
            "name": "Thundering Wrath",
            "desc": "Command \"Zapstring\" to call for thunder to fall upon a large range, dealing <color=Thunder>Electro DMG<\/color>."
        },
        "Inherent Skill": {
            "name": "Skillful Cooking",
            "desc": "Has a chance to produce special dishes when cooking"
        },
        "Intro Skill": {
            "motionValues": [
                {
                    "scaling": [
                        "7.2%*10",
                        "7.8%*10",
                        "8.39%*10",
                        "9.21%*10",
                        "9.8%*10",
                        "10.48%*10",
                        "11.43%*10",
                        "12.37%*10",
                        "13.32%*10",
                        "14.32%*10",
                        "15.5%*10",
                        "16.68%*10",
                        "17.86%*10",
                        "19.04%*10",
                        "20.22%*10",
                        "21.4%*10",
                        "22.58%*10",
                        "23.77%*10",
                        "24.95%*10",
                        "26.13%*10"
                    ],
                    "name": "Skill Damage"
                },
                {
                    "scaling": [
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10",
                        "10"
                    ],
                    "name": "Con. Energy Regen"
                }
            ],
            "name": "Raging Storm",
            "desc": "Command puppet \"Zapstring\" to attack, dealing <color=Thunder>Electro DMG<\/color> in a large range."
        },
        "Forte Circuit": {
            "motionValues": [
                {
                    "scaling": [
                        "90%*2",
                        "97.38%*2",
                        "104.76%*2",
                        "115.1%*2",
                        "122.48%*2",
                        "130.96%*2",
                        "142.77%*2",
                        "154.58%*2",
                        "166.39%*2",
                        "178.93%*2",
                        "193.69%*2",
                        "208.45%*2",
                        "223.21%*2",
                        "237.97%*2",
                        "252.73%*2",
                        "267.49%*2",
                        "282.25%*2",
                        "297.01%*2",
                        "311.77%*2",
                        "326.53%*2"
                    ],
                    "name": "Chameleon Cipher Damage"
                },
                {
                    "scaling": [
                        "39.56%",
                        "42.8%",
                        "46.05%",
                        "50.59%",
                        "53.83%",
                        "57.56%",
                        "62.75%",
                        "67.94%",
                        "73.13%",
                        "78.64%",
                        "85.13%",
                        "91.62%",
                        "98.1%",
                        "104.59%",
                        "111.08%",
                        "117.56%",
                        "124.05%",
                        "130.54%",
                        "137.02%",
                        "143.51%"
                    ],
                    "name": "Judgment Strike Damage"
                }
            ],
            "name": "Chameleon Cipher",
            "desc": "<size=40><color=Title>Chameleon Cipher<\/color><\/size>nWhen Yinlin's \"Judgment Points\" is full, her <color=Highlight>Heavy Attack<\/color> is replaced with <color=Highlight>Chameleon Cipher<\/color>, which consumes all \"Judgment Points\" to attack the target, dealing <color=Thunder>Electro DMG<\/color>. When it hits a target marked with <color=Highlight>Sinner's Mark<\/color>, the <color=Highlight>Sinner's Mark<\/color> is replaced with <color=Highlight>Punishment Mark<\/color>, lasting for 18s.n<size=10> <\/size>n<size=40><color=Title>Sinner's Mark<\/color><\/size>nNormal Attack <color=Highlight>Zapstring's Dance<\/color>, Resonance Liberation <color=Highlight>Thundering Wrath<\/color>, and Intro Skill <color=Highlight>Roaring Storm<\/color> will apply <color=Highlight>Sinner's Mark<\/color> on hit.n<color=Highlight>Sinner's Mark<\/color> is removed when Yinlin exits.n<size=10> <\/size>n<size=40><color=Title>\"Punishment Mark\"<\/color><\/size>nWhen a target marked with <color=Highlight>Punishment Mark<\/color> is damaged, <color=Highlight>Judgement Strike<\/color> will fall, dealing <color=Thunder>Electro DMG<\/color> to all targets marked with <color=Highlight>Punishment Mark<\/color>. This can be triggered up to once per second.n<size=10> <\/size>n<size=40><color=Title>Judgment Points<\/color><\/size>nYinlin can hold up to 100 Judgement Points.nWhen Normal Attack <color=Highlight>Zapstring's Dance<\/color> hits a target, it restores \"Judgment Points\".nWhen Resonance Skill <color=Highlight>Magnetic Roar<\/color> hits a target, it restores \"Judgment Points\".nWhen Resonance Skill <color=Highlight>Electromagnetic Blast<\/color> hits a target, it restores \"Judgment Points\".nWhen Resonance Skill <color=Highlight>Lightning Execution<\/color> hits a target, it restores \"Judgment Points\"."
        },
        "Outro Skill": {
            "name": "Strategist",
            "desc": "The next character (or other characters on a nearby team that activates an Outro Skill) gains 20% Electro DMG Deepen and 25% Resonance Liberation DMG Deepen for 14s or until they are switched off field."
        }
    }
};