export default {
  "Ferocious":{"name":"Ferocious","type":"Attack Stat","amount":"20%","effect":"Attack +20%","tier":3},
  "Brave":{"name":"Brave","type":"Attack Stat","amount":"10%","effect":"Attack +10%","tier":1},
  "Coward":{"name":"Coward","type":"Attack Stat","amount":"-10%","effect":"Attack -10%","tier":-1},
  "Pacifist":{"name":"Pacifist","type":"Attack Stat","amount":"-20%","effect":"Attack -20%","tier":-3},
  "Sadist":{"name":"Sadist","type":"Attack Up + Defense Down","amount":"15%","effect":"Attack +15%, Defense -15%","tier":1},
  "Aggressive":{"name":"Aggressive","type":"Attack Up + Defense Down","amount":"10%","effect":"Attack +10%, Defense -10%","tier":1},
  "Musclehead":{"name":"Musclehead","type":"Attack Up + Work Down","amount":"30%","effect":"Attack +30%, Work Speed -50%","tier":2},
  "Hooligan":{"name":"Hooligan","type":"Attack Up + Work Down","amount":"15%","effect":"Attack +15%, Work Speed -10%","tier":1},
  "Legend":{"name":"Legend","type":"Attack, Defense and Speed","amount":"15%","effect":"Attack +20%, Defense +20%, Movement Speed increases 15%","tier":3},
  "Lord of the Underworld":{"name":"Lord of the Underworld","type":"Dark Damage","amount":"20%","effect":"20% increase to Dark attack damage.","tier":3},
  "Veil of Darkness":{"name":"Veil of Darkness","type":"Dark Damage","amount":"10%","effect":"10% increase to Dark attack damage.","tier":1},
  "Cheery":{"name":"Cheery","type":"Dark Defense","amount":"10%","effect":"10% decrease to incoming Dark damage.","tier":1},
  "Burly Body":{"name":"Burly Body","type":"Defense Stat","amount":"20%","effect":"Defense +20%","tier":3},
  "Hard Skin":{"name":"Hard Skin","type":"Defense Stat","amount":"10%","effect":"Defense +10%","tier":1},
  "Downtrodden":{"name":"Downtrodden","type":"Defense Stat","amount":"-10%","effect":"Defense -10%","tier":-1},
  "Brittle":{"name":"Brittle","type":"Defense Stat","amount":"-20%","effect":"Defense -20%","tier":-3},
  "Masochist":{"name":"Masochist","type":"Defense Up + Attack Down","amount":"15%","effect":"Defense +15%, Attack -15%","tier":1},
  "Divine Dragon":{"name":"Divine Dragon","type":"Dragon Damage","amount":"20%","effect":"20% increase to Dragon attack damage.","tier":3},
  "Blood of the Dragon":{"name":"Blood of the Dragon","type":"Dragon Damage","amount":"10%","effect":"10% increase to Dragon attack damage.","tier":1},
  "Dragonkiller":{"name":"Dragonkiller","type":"Dragon Defense","amount":"10%","effect":"10% decrease to incoming Dragon damage.","tier":1},
  "Lord of Lightning":{"name":"Lord of Lightning","type":"Electric Damage","amount":"20%","effect":"20% increase to Lightning attack damage.","tier":3},
  "Capacitor":{"name":"Capacitor","type":"Electric Damage","amount":"10%","effect":"10% increase to Lightning attack damage.","tier":1},
  "Insulated Body":{"name":"Insulated Body","type":"Electric Defense","amount":"10%","effect":"10% decrease to incoming Lightning damage.","tier":1},
  "Flame Emperor":{"name":"Flame Emperor","type":"Fire Damage","amount":"20%","effect":"20% increase to Fire attack damage.","tier":3},
  "Pyromaniac":{"name":"Pyromaniac","type":"Fire Damage","amount":"10%","effect":"10% increase to Fire attack damage.","tier":1},
  "Suntan Lover":{"name":"Suntan Lover","type":"Fire Defense","amount":"10%","effect":"10% decrease to incoming Fire damage.","tier":1},
  "Spirit Emperor":{"name":"Spirit Emperor","type":"Grass Damage","amount":"20%","effect":"20% increase to Grass attack damage.","tier":3},
  "Fragrant Foliage":{"name":"Fragrant Foliage","type":"Grass Damage","amount":"10%","effect":"10% increase to Grass attack damage.","tier":1},
  "Botanical Barrier":{"name":"Botanical Barrier","type":"Grass Defense","amount":"10%","effect":"10% decrease to incoming Grass damage.","tier":1},
  "Earth Emperor":{"name":"Earth Emperor","type":"Ground Damage","amount":"20%","effect":"20% increase to Earth attack damage.","tier":3},
  "Power of Gaia":{"name":"Power of Gaia","type":"Ground Damage","amount":"10%","effect":"10% increase to Earth attack damage.","tier":1},
  "Earthquake Resistant":{"name":"Earthquake Resistant","type":"Ground Defense","amount":"10%","effect":"10% decrease to incoming Ground damage.","tier":1},
  "Ice Emperor":{"name":"Ice Emperor","type":"Ice Damage","amount":"20%","effect":"20% increase to Ice attack damage.","tier":3},
  "Coldblooded":{"name":"Coldblooded","type":"Ice Damage","amount":"10%","effect":"10% increase to Ice attack damage.","tier":1},
  "Heated Body":{"name":"Heated Body","type":"Ice Defense","amount":"10%","effect":"10% decrease to incoming Ice damage.","tier":1},
  "Swift":{"name":"Swift","type":"Movement Speed","amount":"30%","effect":"30% increase to movement speed.","tier":3},
  "Runner":{"name":"Runner","type":"Movement Speed","amount":"20%","effect":"20% increase to Movement Speed.","tier":2},
  "Nimble":{"name":"Nimble","type":"Movement Speed","amount":"10%","effect":"10% increase to Movement Speed.","tier":1},
  "Celestial Emperor":{"name":"Celestial Emperor","type":"Neutral Damage","amount":"20%","effect":"20% increase to Normal attack damage.","tier":3},
  "Zen Mind":{"name":"Zen Mind","type":"Neutral Damage","amount":"10%","effect":"10% increase to Neutral attack damage.","tier":1},
  "Abnormal":{"name":"Abnormal","type":"Neutral Defense","amount":"10%","effect":"10% decreased to incoming Neutral damage.","tier":1},
  "Motivational Leader":{"name":"Motivational Leader","type":"Player Buff","amount":"25%","effect":"25% increase to Player Work Speed.","tier":3},
  "Stronghold Strategist":{"name":"Stronghold Strategist","type":"Player Buff","amount":"10%","effect":"10% increase to Player Defense.","tier":3},
  "Vanguard":{"name":"Vanguard","type":"Player Buff","amount":"10%","effect":"10% increase to Player Attack.","tier":3},
  "Logging Foreman":{"name":"Logging Foreman","type":"Player Buff","amount":"25%","effect":"25% increase to Player Logging Efficiency.","tier":3},
  "Mine Foreman":{"name":"Mine Foreman","type":"Player Buff","amount":"25%","effect":"25% increase to Player Mining Efficiency.","tier":3},
  "Workaholic":{"name":"Workaholic","type":"SAN Depletion","amount":"15%","effect":"SAN drops +15% slower.","tier":3},
  "Positive Thinker":{"name":"Positive Thinker","type":"SAN Depletion","amount":"10%","effect":"SAN drops +10% slower.","tier":1},
  "Unstable":{"name":"Unstable","type":"SAN Depletion","amount":"10%","effect":"SAN drops +10% faster.","tier":-1},
  "Destructive":{"name":"Destructive","type":"SAN Depletion","amount":"15%","effect":"SAN drops +15% faster.","tier":-3},
  "Diet Lover":{"name":"Diet Lover","type":"Satiety","amount":"15%","effect":"Decrease in Hunger is less likely by +15%","tier":3},
  "Dainty Eater":{"name":"Dainty Eater","type":"Satiety","amount":"10%","effect":"Satiety drops +10% slower.","tier":1},
  "Glutton":{"name":"Glutton","type":"Satiety","amount":"10%","effect":"Satiety drops +10% faster.","tier":-1},
  "Bottomless Stomach":{"name":"Bottomless Stomach","type":"Satiety","amount":"15%","effect":"Satiety drops +15% faster.","tier":-2},
  "Lord of the Sea":{"name":"Lord of the Sea","type":"Water Damage","amount":"20%","effect":"20% increase to Water attack damage.","tier":3},
  "Hydromaniac":{"name":"Hydromaniac","type":"Water Damage","amount":"10%","effect":"10% increase to Water attack damage.","tier":1},
  "Waterproof":{"name":"Waterproof","type":"Water Defense","amount":"10%","effect":"10% decrease to incoming Water damage.","tier":1},
  "Lucky":{"name":"Lucky","type":"Work and Attack","amount":"15%","effect":"Work Speed +15%, Attack +15%","tier":3},
  "Artisan":{"name":"Artisan","type":"Work Speed","amount":"50%","effect":"Work Speed +50%","tier":3},
  "Serious":{"name":"Serious","type":"Work Speed","amount":"20%","effect":"Work Speed +20%","tier":2},
  "Clumsy":{"name":"Clumsy","type":"Work Speed","amount":"-10%","effect":"Work Speed -10%","tier":-1},
  "Slacker":{"name":"Slacker","type":"Work Speed","amount":"-30%","effect":"Work Speed -30%","tier":-3},
  "Work Slave":{"name":"Work Slave","type":"Work Speed Up + Attack Down","amount":"30%","effect":"Work Speed +30%, Attack -30%","tier":1},
  "Conceited":{"name":"Conceited","type":"Work Speed Up + Defense Down","amount":"10%","effect":"Work Speed +10%, Defense -10%","tier":1}
};