export default {
    "Aalto": {
        "id": 1403,
        "rarity": 4,
        "weapon": "Pistols",
        "element": "Aero",
        "name": "Aalto",
        "alias": "Mistcloak Strike",
        "weeklyMat": "Monument Bell",
        "bossMat": "Roaring Rock Fist",
        "floraMat": "Wintry Bell",
        "enemyMat": "Howler Core",
        "forgeryMat": "Phlogiston",
        "icon": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRoleHead256\/T_IconRoleHead256_12_UI.T_IconRoleHead256_12_UI",
        "portrait": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRolePile\/T_IconRole_Pile_qiushui_UI.T_IconRole_Pile_qiushui_UI"
    },
    "Baizhi": {
        "id": 1103,
        "rarity": 4,
        "weapon": "Rectifier",
        "element": "Glacio",
        "name": "Baizhi",
        "alias": "Healing You'tan",
        "weeklyMat": "Monument Bell",
        "bossMat": "Sound-Keeping Tacet Core",
        "floraMat": "Lanternberry",
        "enemyMat": "Howler Core",
        "forgeryMat": "Helix",
        "icon": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRoleHead256\/T_IconRoleHead256_6_UI.T_IconRoleHead256_6_UI",
        "portrait": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRolePile\/T_IconRole_Pile_bailian_UI.T_IconRole_Pile_bailian_UI"
    },
    "Calcharo": {
        "id": 1301,
        "rarity": 5,
        "weapon": "Broadblade",
        "element": "Electro",
        "name": "Calcharo",
        "weeklyMat": "Monument Bell",
        "bossMat": "Thundering Tacet Core",
        "floraMat": "Iris",
        "enemyMat": "Ring",
        "forgeryMat": "Waveworn Residue",
        "icon": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRoleHead256\/T_IconRoleHead256_18_UI.T_IconRoleHead256_18_UI",
        "portrait": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRolePile\/T_IconRole_Pile_kakaluo_UI.T_IconRole_Pile_kakaluo_UI",
        "alias": "Calcharo"
    },
    "Camellya": {
        "id": 1603,
        "rarity": 5,
        "weapon": "Sword",
        "element": "Havoc",
        "icon": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRoleHead256\/T_IconRoleHead256_29_UI.T_IconRoleHead256_29_UI",
        "portrait": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRolePile\/T_IconRole_Pile_chun_UI.T_IconRole_Pile_chun_UI",
        "name": "Camellya",
        "alias": "Camellya",
        "weeklyMat": "Dreamless Feather",
        "bossMat": "Topological Confinement",
        "floraMat": "Nova",
        "enemyMat": "Whisperin Core",
        "forgeryMat": "Metallic Drip"
    },
    "Carlotta": {
        "id": 1107,
        "rarity": 5,
        "weapon": "Pistols",
        "element": "Glacio",
        "icon": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRoleHead256\/T_IconRoleHead256_32_UI.T_IconRoleHead256_32_UI",
        "portrait": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRolePile\/T_IconRole_Pile_kelaita_UI.T_IconRole_Pile_kelaita_UI",
        "enemyMat": "Polygon Core",
        "forgeryMat": "Phlogiston",
        "name": "Carlotta",
        "alias": "Carlotta",
        "weeklyMat": "The Netherworld's Stare",
        "bossMat": "Platinum Core",
        "floraMat": "Sword Acorus"
    },
    "Changli": {
        "id": 1205,
        "rarity": 5,
        "weapon": "Sword",
        "element": "Fusion",
        "icon": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRoleHead256\/T_IconRoleHead256_26_UI.T_IconRoleHead256_26_UI",
        "portrait": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRolePile\/T_IconRole_Pile_changli_UI.T_IconRole_Pile_changli_UI",
        "name": "Changli",
        "alias": "",
        "weeklyMat": "Sentinel's Dagger",
        "bossMat": "Rage Tacet Core",
        "floraMat": "Pavo Plum",
        "enemyMat": "Ring",
        "forgeryMat": "Metallic Drip"
    },
    "Chixia": {
        "id": 1202,
        "rarity": 4,
        "weapon": "Pistols",
        "element": "Fusion",
        "name": "Chixia",
        "alias": "Gallant Blaze",
        "weeklyMat": "Monument Bell",
        "bossMat": "Rage Tacet Core",
        "floraMat": "Belle Poppy",
        "enemyMat": "Whisperin Core",
        "forgeryMat": "Phlogiston",
        "icon": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRoleHead256\/T_IconRoleHead256_2_UI.T_IconRoleHead256_2_UI",
        "portrait": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRolePile\/T_IconRole_Pile_maxiaofang_UI.T_IconRole_Pile_maxiaofang_UI"
    },
    "Danjin": {
        "id": 1602,
        "rarity": 4,
        "weapon": "Sword",
        "element": "Havoc",
        "name": "Danjin",
        "alias": "Scarlet Shade",
        "weeklyMat": "Dreamless Feather",
        "bossMat": "Strife Tacet Core",
        "floraMat": "Belle Poppy",
        "enemyMat": "Ring",
        "forgeryMat": "Metallic Drip",
        "icon": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRoleHead256\/T_IconRoleHead256_10_UI.T_IconRoleHead256_10_UI",
        "portrait": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRolePile\/T_IconRole_Pile_micai_UI.T_IconRole_Pile_micai_UI"
    },
    "Encore": {
        "id": 1203,
        "rarity": 5,
        "weapon": "Rectifier",
        "element": "Fusion",
        "name": "Encore",
        "alias": "Wooly-Counting Game",
        "weeklyMat": "Unending Destruction",
        "bossMat": "Rage Tacet Core",
        "floraMat": "Pecok Flower",
        "enemyMat": "Whisperin Core",
        "forgeryMat": "Helix",
        "icon": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRoleHead256\/T_IconRoleHead256_8_UI.T_IconRoleHead256_8_UI",
        "portrait": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRolePile\/T_IconRole_Pile_anke_UI.T_IconRole_Pile_anke_UI"
    },
    "Jianxin": {
        "id": 1405,
        "rarity": 5,
        "weapon": "Gauntlets",
        "element": "Aero",
        "name": "Jianxin",
        "weeklyMat": "Unending Destruction",
        "bossMat": "Roaring Rock Fist",
        "floraMat": "Lanternberry",
        "enemyMat": "Whisperin Core",
        "forgeryMat": "Cadence",
        "icon": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRoleHead256\/T_IconRoleHead256_23_UI.T_IconRoleHead256_23_UI",
        "portrait": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRolePile\/T_IconRole_Pile_jiexin_UI.T_IconRole_Pile_jiexin_UI",
        "alias": "Jianxin's Nickname"
    },
    "Jinhsi": {
        "id": 1304,
        "rarity": 5,
        "weapon": "Broadblade",
        "element": "Spectro",
        "icon": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRoleHead256\/T_IconRoleHead256_24_UI.T_IconRoleHead256_24_UI",
        "portrait": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRolePile\/T_IconRole_Pile_jinxi_UI.T_IconRole_Pile_jinxi_UI",
        "name": "Jinhsi",
        "alias": "Jinhsi's Title",
        "weeklyMat": "Sentinel's Dagger",
        "bossMat": "Elegy Tacet Core",
        "floraMat": "Loong's Pearl",
        "enemyMat": "Howler Core",
        "forgeryMat": "Waveworn Residue"
    },
    "Jiyan": {
        "id": 1404,
        "rarity": 5,
        "weapon": "Broadblade",
        "element": "Aero",
        "name": "Jiyan",
        "alias": "Windborne Rider",
        "weeklyMat": "Monument Bell",
        "bossMat": "Roaring Rock Fist",
        "floraMat": "Pecok Flower",
        "enemyMat": "Howler Core",
        "forgeryMat": "Waveworn Residue",
        "icon": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRoleHead256\/T_IconRoleHead256_11_UI.T_IconRoleHead256_11_UI",
        "portrait": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRolePile\/T_IconRole_Pile_jiyan_UI.T_IconRole_Pile_jiyan_UI"
    },
    "Lingyang": {
        "id": 1104,
        "rarity": 5,
        "weapon": "Gauntlets",
        "element": "Glacio",
        "name": "Lingyang",
        "weeklyMat": "Unending Destruction",
        "bossMat": "Sound-Keeping Tacet Core",
        "floraMat": "Coriolus",
        "enemyMat": "Whisperin Core",
        "forgeryMat": "Cadence",
        "icon": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRoleHead256\/T_IconRoleHead256_14_UI.T_IconRoleHead256_14_UI",
        "portrait": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRolePile\/T_IconRole_Pile_lingyang_UI.T_IconRole_Pile_lingyang_UI",
        "alias": "White Tiger"
    },
    "Lumi": {
        "id": 1504,
        "rarity": 4,
        "weapon": "Broadblade",
        "element": "Electro",
        "icon": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRoleHead256\/T_IconRoleHead256_30_UI.T_IconRoleHead256_30_UI",
        "portrait": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRolePile\/T_IconRole_Pile_dengdeng_UI.T_IconRole_Pile_dengdeng_UI",
        "name": "Lumi",
        "alias": "Lumi",
        "weeklyMat": "Sentinel's Dagger",
        "bossMat": "Thundering Tacet Core",
        "floraMat": "Terraspawn Fungus",
        "enemyMat": "Howler Core",
        "forgeryMat": "Waveworn Residue"
    },
    "Mortefi": {
        "id": 1204,
        "rarity": 4,
        "weapon": "Pistols",
        "element": "Fusion",
        "name": "Mortefi",
        "alias": "Dragon's Breath",
        "weeklyMat": "Monument Bell",
        "bossMat": "Rage Tacet Core",
        "floraMat": "Coriolus",
        "enemyMat": "Whisperin Core",
        "forgeryMat": "Phlogiston",
        "icon": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRoleHead256\/T_IconRoleHead256_13_UI.T_IconRoleHead256_13_UI",
        "portrait": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRolePile\/T_IconRole_Pile_baer_UI.T_IconRole_Pile_baer_UI"
    },
    "Roccia": {
        "id": 1606,
        "rarity": 5,
        "weapon": "Gauntlets",
        "element": "Havoc",
        "icon": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRoleHead256\/T_IconRoleHead256_33_UI.T_IconRoleHead256_33_UI",
        "portrait": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRolePile\/T_IconRole_Pile_luokeke_UI.T_IconRole_Pile_luokeke_UI",
        "enemyMat": "Tidal Residuum",
        "name": "Roccia",
        "alias": "Roccia",
        "weeklyMat": "The Netherworld's Stare",
        "bossMat": "Cleansing Conch",
        "floraMat": "Firecracker Jewelweed",
        "forgeryMat": "Cadence"
    },
    "RoverHavoc": {
        "id": 1605,
        "rarity": 5,
        "weapon": "Sword",
        "element": "Havoc",
        "name": "Rover-Havoc",
        "weeklyMat": "Dreamless Feather",
        "bossMat": "Mysterious Code",
        "floraMat": "Pecok Flower",
        "enemyMat": "Whisperin Core",
        "forgeryMat": "Metallic Drip",
        "icon": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRoleHead256\/T_IconRoleHead256_4_UI.T_IconRoleHead256_4_UI",
        "portrait": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRolePile\/T_IconRole_Pile_zhujuenan_UI.T_IconRole_Pile_zhujuenan_UI",
        "alias": "Vessel of Sounds"
    },
    "RoverSpectro": {
        "id": 1502,
        "rarity": 5,
        "weapon": "Sword",
        "element": "Spectro",
        "name": "Rover-Spectro",
        "alias": "Vessel of Sounds",
        "weeklyMat": "Unending Destruction",
        "bossMat": "Mysterious Code",
        "floraMat": "Pecok Flower",
        "enemyMat": "Whisperin Core",
        "forgeryMat": "Metallic Drip",
        "icon": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRoleHead256\/T_IconRoleHead256_5_UI.T_IconRoleHead256_5_UI",
        "portrait": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRolePile\/T_IconRole_Pile_zhujue_UI.T_IconRole_Pile_zhujue_UI"
    },
    "Sanhua": {
        "id": 1102,
        "rarity": 4,
        "weapon": "Sword",
        "element": "Glacio",
        "name": "Sanhua",
        "alias": "Snow Waltz",
        "weeklyMat": "Unending Destruction",
        "bossMat": "Sound-Keeping Tacet Core",
        "floraMat": "Wintry Bell",
        "enemyMat": "Whisperin Core",
        "forgeryMat": "Metallic Drip",
        "icon": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRoleHead256\/T_IconRoleHead256_7_UI.T_IconRoleHead256_7_UI",
        "portrait": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRolePile\/T_IconRole_Pile_shanhua_UI.T_IconRole_Pile_shanhua_UI"
    },
    "Shorekeeper": {
        "id": 1505,
        "rarity": 5,
        "weapon": "Rectifier",
        "element": "Spectro",
        "icon": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRoleHead256\/T_IconRoleHead256_28_UI.T_IconRoleHead256_28_UI",
        "portrait": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRolePile\/T_IconRole_Pile_shouanren_UI.T_IconRole_Pile_shouanren_UI",
        "name": "Shorekeeper",
        "alias": "Shorekeeper",
        "weeklyMat": "Sentinel's Dagger",
        "bossMat": "Topological Confinement",
        "floraMat": "Nova",
        "enemyMat": "Whisperin Core",
        "forgeryMat": "Helix"
    },
    "Taoqi": {
        "id": 1601,
        "rarity": 4,
        "weapon": "Broadblade",
        "element": "Havoc",
        "name": "Taoqi",
        "alias": "Power of Xuanwu",
        "weeklyMat": "Dreamless Feather",
        "bossMat": "Gold-Dissolving Feather",
        "floraMat": "Iris",
        "enemyMat": "Howler Core",
        "forgeryMat": "Waveworn Residue",
        "icon": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRoleHead256\/T_IconRoleHead256_9_UI.T_IconRoleHead256_9_UI",
        "portrait": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRolePile\/T_IconRole_Pile_taohua_UI.T_IconRole_Pile_taohua_UI"
    },
    "Verina": {
        "id": 1503,
        "rarity": 5,
        "weapon": "Rectifier",
        "element": "Spectro",
        "name": "Verina",
        "alias": "Nature Calling",
        "weeklyMat": "Monument Bell",
        "bossMat": "Elegy Tacet Core",
        "floraMat": "Belle Poppy",
        "enemyMat": "Howler Core",
        "forgeryMat": "Helix",
        "icon": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRoleHead256\/T_IconRoleHead256_3_UI.T_IconRoleHead256_3_UI",
        "portrait": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRolePile\/T_IconRole_Pile_jueyuan_UI.T_IconRole_Pile_jueyuan_UI"
    },
    "XiangliYao": {
        "id": 1305,
        "rarity": 5,
        "weapon": "Gauntlets",
        "element": "Electro",
        "icon": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRoleHead256\/T_IconRoleHead256_25_UI.T_IconRoleHead256_25_UI",
        "portrait": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRolePile\/T_IconRole_Pile_xiangliyao_UI.T_IconRole_Pile_xiangliyao_UI",
        "name": "Xiangli Yao",
        "alias": "Error detected. If you have any questions, please contact Customer Service.",
        "weeklyMat": "Unending Destruction",
        "bossMat": "Hidden Thunder Tacet Core",
        "floraMat": "Violet Coral",
        "enemyMat": "Whisperin Core",
        "forgeryMat": "Cadence"
    },
    "Yangyang": {
        "id": 1402,
        "rarity": 4,
        "weapon": "Sword",
        "element": "Aero",
        "name": "Yangyang",
        "alias": "Breath of Winds",
        "weeklyMat": "Unending Destruction",
        "bossMat": "Roaring Rock Fist",
        "floraMat": "Wintry Bell",
        "enemyMat": "Ring",
        "forgeryMat": "Metallic Drip",
        "icon": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRoleHead256\/T_IconRoleHead256_1_UI.T_IconRoleHead256_1_UI",
        "portrait": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRolePile\/T_IconRole_Pile_yangyang_UI.T_IconRole_Pile_yangyang_UI"
    },
    "Yinlin": {
        "id": 1302,
        "rarity": 5,
        "weapon": "Rectifier",
        "element": "Electro",
        "name": "Yinlin",
        "alias": "Lightning of Execution",
        "weeklyMat": "Dreamless Feather",
        "bossMat": "Group Abomination Tacet Core",
        "floraMat": "Coriolus",
        "enemyMat": "Whisperin Core",
        "forgeryMat": "Helix",
        "icon": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRoleHead256\/T_IconRoleHead256_17_UI.T_IconRoleHead256_17_UI",
        "portrait": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRolePile\/T_IconRole_Pile_yinlin_UI.T_IconRole_Pile_yinlin_UI"
    },
    "Youhu": {
        "id": 1106,
        "rarity": 4,
        "weapon": "Gauntlets",
        "element": "Glacio",
        "icon": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRoleHead256\/T_IconRoleHead256_31_UI.T_IconRoleHead256_31_UI",
        "portrait": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRolePile\/T_IconRole_Pile_youhu_UI.T_IconRole_Pile_youhu_UI",
        "name": "Youhu",
        "alias": "Youhu",
        "weeklyMat": "Monument Bell",
        "bossMat": "Topological Confinement",
        "floraMat": "Violet Coral",
        "enemyMat": "Ring",
        "forgeryMat": "Cadence"
    },
    "Yuanwu": {
        "id": 1303,
        "rarity": 4,
        "weapon": "Gauntlets",
        "element": "Electro",
        "name": "Yuanwu",
        "alias": "Fist of Thunder",
        "weeklyMat": "Unending Destruction",
        "bossMat": "Hidden Thunder Tacet Core",
        "floraMat": "Terraspawn Fungus",
        "enemyMat": "Ring",
        "forgeryMat": "Cadence",
        "icon": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRoleHead256\/T_IconRoleHead256_15_UI.T_IconRoleHead256_15_UI",
        "portrait": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRolePile\/T_IconRole_Pile_yuanwu_UI.T_IconRole_Pile_yuanwu_UI"
    },
    "Zhezhi": {
        "id": 1105,
        "rarity": 5,
        "weapon": "Rectifier",
        "element": "Glacio",
        "icon": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRoleHead256\/T_IconRoleHead256_27_UI.T_IconRoleHead256_27_UI",
        "portrait": "\/Game\/Aki\/UI\/UIResources\/Common\/Image\/IconRolePile\/T_IconRole_Pile_zhezhi_UI.T_IconRole_Pile_zhezhi_UI",
        "name": "Zhezhi",
        "alias": "Zhezhi",
        "weeklyMat": "Monument Bell",
        "bossMat": "Sound-Keeping Tacet Core",
        "floraMat": "Lanternberry",
        "enemyMat": "Howler Core",
        "forgeryMat": "Helix"
    }
};