export default {
    "Aalto": {
        "name": "Aalto",
        "element": "Aero",
        "weapon": "Pistols",
        "rarity": 4,
        "enemyMat": "Howler Core",
        "bossMat": "Roaring Rock Fist",
        "floraMat": "Wintry Bell",
        "forgeryMat": "Phlogiston",
        "weeklyMat": "Monument Bell",
        "id": 1403,
        "SkillTreeGroupId": 1403,
        "ResonanceId": 1403,
        "ResonantChainGroupId": 1403,
        "alias": "Mistcloak Strike"
    },
    "Baizhi": {
        "name": "Baizhi",
        "element": "Glacio",
        "weapon": "Rectifier",
        "rarity": 4,
        "enemyMat": "Howler Core",
        "bossMat": "Sound-Keeping Tacet Core",
        "floraMat": "Lanternberry",
        "forgeryMat": "Helix",
        "weeklyMat": "Monument Bell",
        "id": 1103,
        "SkillTreeGroupId": 1103,
        "ResonanceId": 1103,
        "ResonantChainGroupId": 1103,
        "alias": "Healing You'tan"
    },
    "Calcharo": {
        "name": "Calcharo",
        "element": "Electro",
        "weapon": "Broadblade",
        "rarity": 5,
        "enemyMat": "Ring",
        "bossMat": "Thundering Tacet Core",
        "floraMat": "Iris",
        "forgeryMat": "Waveworn Residue",
        "weeklyMat": "Monument Bell",
        "id": 1301,
        "SkillTreeGroupId": 1301,
        "ResonanceId": 1301,
        "ResonantChainGroupId": 1301
    },
    "Chixia": {
        "name": "Chixia",
        "element": "Fusion",
        "weapon": "Pistols",
        "rarity": 4,
        "enemyMat": "Whisperin Core",
        "bossMat": "Rage Tacet Core",
        "floraMat": "Belle Poppy",
        "forgeryMat": "Phlogiston",
        "weeklyMat": "Monument Bell",
        "id": 1202,
        "SkillTreeGroupId": 1202,
        "ResonanceId": 1202,
        "ResonantChainGroupId": 1202,
        "alias": "Gallant Blaze"
    },
    "Danjin": {
        "name": "Danjin",
        "element": "Havoc",
        "weapon": "Sword",
        "rarity": 4,
        "enemyMat": "Ring",
        "bossMat": "Strife Tacet Core",
        "floraMat": "Belle Poppy",
        "forgeryMat": "Metallic Drip",
        "weeklyMat": "Dreamless Feather",
        "id": 1602,
        "SkillTreeGroupId": 1602,
        "ResonanceId": 1602,
        "ResonantChainGroupId": 1602,
        "alias": "Scarlet Shade"
    },
    "Encore": {
        "name": "Encore",
        "element": "Fusion",
        "weapon": "Rectifier",
        "rarity": 5,
        "enemyMat": "Whisperin Core",
        "bossMat": "Rage Tacet Core",
        "floraMat": "Pecok Flower",
        "forgeryMat": "Helix",
        "weeklyMat": "Unending Destruction",
        "id": 1203,
        "SkillTreeGroupId": 1203,
        "ResonanceId": 1203,
        "ResonantChainGroupId": 1203,
        "alias": "Wooly-counting Game"
    },
    "Jianxin": {
        "name": "Jianxin",
        "element": "Aero",
        "weapon": "Gauntlets",
        "rarity": 5,
        "enemyMat": "Whisperin Core",
        "bossMat": "Roaring Rock Fist",
        "floraMat": "Lanternberry",
        "forgeryMat": "Cadence",
        "weeklyMat": "Unending Destruction",
        "id": 1405,
        "SkillTreeGroupId": 1405,
        "ResonanceId": 1402,
        "ResonantChainGroupId": 1405
    },
    "Jiyan": {
        "name": "Jiyan",
        "element": "Aero",
        "weapon": "Broadblade",
        "rarity": 5,
        "enemyMat": "Howler Core",
        "bossMat": "Roaring Rock Fist",
        "floraMat": "Pecok Flower",
        "forgeryMat": "Waveworn Residue",
        "weeklyMat": "Monument Bell",
        "id": 1404,
        "SkillTreeGroupId": 1404,
        "ResonanceId": 1404,
        "ResonantChainGroupId": 1404,
        "alias": "Windborne Rider"
    },
    "Lingyang": {
        "name": "Lingyang",
        "element": "Glacio",
        "weapon": "Gauntlets",
        "rarity": 5,
        "enemyMat": "Whisperin Core",
        "bossMat": "Sound-Keeping Tacet Core",
        "floraMat": "Coriolus",
        "forgeryMat": "Cadence",
        "weeklyMat": "Unending Destruction",
        "id": 1104,
        "SkillTreeGroupId": 1104,
        "ResonanceId": 1104,
        "ResonantChainGroupId": 1104
    },
    "Mortefi": {
        "name": "Mortefi",
        "element": "Fusion",
        "weapon": "Pistols",
        "rarity": 4,
        "enemyMat": "Whisperin Core",
        "bossMat": "Rage Tacet Core",
        "floraMat": "Coriolus",
        "forgeryMat": "Phlogiston",
        "weeklyMat": "Monument Bell",
        "id": 1204,
        "SkillTreeGroupId": 1204,
        "ResonanceId": 1204,
        "ResonantChainGroupId": 1204,
        "alias": "Dragon's Breath"
    },
    "RoverHavoc": {
        "id": 1605,
        "rarity": 5,
        "weapon": "Sword",
        "element": "Havoc",
        "SkillTreeGroupId": 1604,
        "ResonanceId": 1604,
        "ResonantChainGroupId": 1604,
        "name": "Rover-Havoc",
        "weeklyMat": "Dreamless Feather",
        "bossMat": "Mysterious Code",
        "floraMat": "Pecok Flower",
        "enemyMat": "Whisperin Core",
        "forgeryMat": "Metallic Drip"
    },
    "RoverSpectro": {
        "id": 1502,
        "rarity": 5,
        "weapon": "Sword",
        "element": "Spectro",
        "SkillTreeGroupId": 1501,
        "ResonanceId": 1,
        "ResonantChainGroupId": 1,
        "name": "Rover-Spectro",
        "alias": "Vessel of Sounds",
        "weeklyMat": "Unending Destruction",
        "bossMat": "Mysterious Code",
        "floraMat": "Pecok Flower",
        "enemyMat": "Whisperin Core",
        "forgeryMat": "Metallic Drip"
    },
    "Sanhua": {
        "name": "Sanhua",
        "element": "Glacio",
        "weapon": "Sword",
        "rarity": 4,
        "enemyMat": "Whisperin Core",
        "bossMat": "Sound-Keeping Tacet Core",
        "floraMat": "Wintry Bell",
        "forgeryMat": "Metallic Drip",
        "weeklyMat": "Unending Destruction",
        "id": 1102,
        "SkillTreeGroupId": 1102,
        "ResonanceId": 1102,
        "ResonantChainGroupId": 1102,
        "alias": "Snow Waltz"
    },
    "Taoqi": {
        "name": "Taoqi",
        "element": "Havoc",
        "weapon": "Broadblade",
        "rarity": 4,
        "enemyMat": "Howler Core",
        "bossMat": "Gold-Dissolving Feather",
        "floraMat": "Iris",
        "forgeryMat": "Waveworn Residue",
        "weeklyMat": "Dreamless Feather",
        "id": 1601,
        "SkillTreeGroupId": 1601,
        "ResonanceId": 1601,
        "ResonantChainGroupId": 1601,
        "alias": "Power of Xuanwu"
    },
    "Verina": {
        "name": "Verina",
        "element": "Spectro",
        "weapon": "Rectifier",
        "rarity": 5,
        "enemyMat": "Howler Core",
        "bossMat": "Elegy Tacet Core",
        "floraMat": "Belle Poppy",
        "forgeryMat": "Helix",
        "weeklyMat": "Monument Bell",
        "id": 1503,
        "SkillTreeGroupId": 1503,
        "ResonanceId": 1503,
        "ResonantChainGroupId": 1503,
        "alias": "Nature Calling"
    },
    "Yangyang": {
        "name": "Yangyang",
        "element": "Aero",
        "weapon": "Sword",
        "rarity": 4,
        "enemyMat": "Ring",
        "bossMat": "Roaring Rock Fist",
        "floraMat": "Wintry Bell",
        "forgeryMat": "Metallic Drip",
        "weeklyMat": "Unending Destruction",
        "id": 1402,
        "SkillTreeGroupId": 1402,
        "ResonanceId": 1402,
        "ResonantChainGroupId": 1402,
        "alias": "Breath of Winds"
    },
    "Yinlin": {
        "name": "Yinlin",
        "element": "Electro",
        "weapon": "Rectifier",
        "rarity": 5,
        "enemyMat": "Whisperin Core",
        "bossMat": "Group Abomination Tacet Core",
        "floraMat": "Coriolus",
        "forgeryMat": "Helix",
        "weeklyMat": "Dreamless Feather",
        "id": 1302,
        "SkillTreeGroupId": 1302,
        "ResonanceId": 1302,
        "ResonantChainGroupId": 1302,
        "alias": "Lightning of Execution"
    },
    "Yuanwu": {
        "name": "Yuanwu",
        "element": "Electro",
        "weapon": "Gauntlets",
        "rarity": 4,
        "enemyMat": "Ring",
        "bossMat": "Hidden Thunder Tacet Core",
        "floraMat": "Terraspawn Fungus",
        "forgeryMat": "Cadence",
        "weeklyMat": "Unending Destruction",
        "id": 1303,
        "SkillTreeGroupId": 1303,
        "ResonanceId": 1303,
        "ResonantChainGroupId": 1303,
        "alias": "Fist of Thunder"
    }
};