export default {
    "Aalto": {
        "id": 1403,
        "rarity": 4,
        "weapon": "Pistols",
        "element": "Aero",
        "name": "Aalto",
        "alias": "Mistcloak Strike",
        "weeklyMat": "Monument Bell",
        "bossMat": "Roaring Rock Fist",
        "floraMat": "Wintry Bell",
        "enemyMat": "Howler Core",
        "forgeryMat": "Phlogiston"
    },
    "Baizhi": {
        "id": 1103,
        "rarity": 4,
        "weapon": "Rectifier",
        "element": "Glacio",
        "name": "Baizhi",
        "alias": "Healing You'tan",
        "weeklyMat": "Monument Bell",
        "bossMat": "Sound-Keeping Tacet Core",
        "floraMat": "Lanternberry",
        "enemyMat": "Howler Core",
        "forgeryMat": "Helix"
    },
    "Calcharo": {
        "id": 1301,
        "rarity": 5,
        "weapon": "Broadblade",
        "element": "Electro",
        "name": "Calcharo",
        "weeklyMat": "Monument Bell",
        "bossMat": "Thundering Tacet Core",
        "floraMat": "Iris",
        "enemyMat": "Ring",
        "forgeryMat": "Waveworn Residue"
    },
    "Chixia": {
        "id": 1202,
        "rarity": 4,
        "weapon": "Pistols",
        "element": "Fusion",
        "name": "Chixia",
        "alias": "Gallant Blaze",
        "weeklyMat": "Monument Bell",
        "bossMat": "Rage Tacet Core",
        "floraMat": "Belle Poppy",
        "enemyMat": "Whisperin Core",
        "forgeryMat": "Phlogiston"
    },
    "Danjin": {
        "id": 1602,
        "rarity": 4,
        "weapon": "Sword",
        "element": "Havoc",
        "name": "Danjin",
        "alias": "Scarlet Shade",
        "weeklyMat": "Dreamless Feather",
        "bossMat": "Strife Tacet Core",
        "floraMat": "Belle Poppy",
        "enemyMat": "Ring",
        "forgeryMat": "Metallic Drip"
    },
    "Encore": {
        "id": 1203,
        "rarity": 5,
        "weapon": "Rectifier",
        "element": "Fusion",
        "name": "Encore",
        "alias": "Wooly-counting Game",
        "weeklyMat": "Unending Destruction",
        "bossMat": "Rage Tacet Core",
        "floraMat": "Pecok Flower",
        "enemyMat": "Whisperin Core",
        "forgeryMat": "Helix"
    },
    "Jianxin": {
        "id": 1405,
        "rarity": 5,
        "weapon": "Gauntlets",
        "element": "Aero",
        "name": "Jianxin",
        "weeklyMat": "Unending Destruction",
        "bossMat": "Roaring Rock Fist",
        "floraMat": "Lanternberry",
        "enemyMat": "Whisperin Core",
        "forgeryMat": "Cadence"
    },
    "Jiyan": {
        "id": 1404,
        "rarity": 5,
        "weapon": "Broadblade",
        "element": "Aero",
        "name": "Jiyan",
        "alias": "Windborne Rider",
        "weeklyMat": "Monument Bell",
        "bossMat": "Roaring Rock Fist",
        "floraMat": "Pecok Flower",
        "enemyMat": "Howler Core",
        "forgeryMat": "Waveworn Residue"
    },
    "Lingyang": {
        "id": 1104,
        "rarity": 5,
        "weapon": "Gauntlets",
        "element": "Glacio",
        "name": "Lingyang",
        "weeklyMat": "Unending Destruction",
        "bossMat": "Sound-Keeping Tacet Core",
        "floraMat": "Coriolus",
        "enemyMat": "Whisperin Core",
        "forgeryMat": "Cadence"
    },
    "Mortefi": {
        "id": 1204,
        "rarity": 4,
        "weapon": "Pistols",
        "element": "Fusion",
        "name": "Mortefi",
        "alias": "Dragon's Breath",
        "weeklyMat": "Monument Bell",
        "bossMat": "Rage Tacet Core",
        "floraMat": "Coriolus",
        "enemyMat": "Whisperin Core",
        "forgeryMat": "Phlogiston"
    },
    "RoverHavoc": {
        "id": 1605,
        "rarity": 5,
        "weapon": "Sword",
        "element": "Havoc",
        "name": "Rover-Havoc",
        "weeklyMat": "Dreamless Feather",
        "bossMat": "Mysterious Code",
        "floraMat": "Pecok Flower",
        "enemyMat": "Whisperin Core",
        "forgeryMat": "Metallic Drip"
    },
    "RoverSpectro": {
        "id": 1502,
        "rarity": 5,
        "weapon": "Sword",
        "element": "Spectro",
        "name": "Rover-Spectro",
        "alias": "Vessel of Sounds",
        "weeklyMat": "Unending Destruction",
        "bossMat": "Mysterious Code",
        "floraMat": "Pecok Flower",
        "enemyMat": "Whisperin Core",
        "forgeryMat": "Metallic Drip"
    },
    "Sanhua": {
        "id": 1102,
        "rarity": 4,
        "weapon": "Sword",
        "element": "Glacio",
        "name": "Sanhua",
        "alias": "Snow Waltz",
        "weeklyMat": "Unending Destruction",
        "bossMat": "Sound-Keeping Tacet Core",
        "floraMat": "Wintry Bell",
        "enemyMat": "Whisperin Core",
        "forgeryMat": "Metallic Drip"
    },
    "Taoqi": {
        "id": 1601,
        "rarity": 4,
        "weapon": "Broadblade",
        "element": "Havoc",
        "name": "Taoqi",
        "alias": "Power of Xuanwu",
        "weeklyMat": "Dreamless Feather",
        "bossMat": "Gold-Dissolving Feather",
        "floraMat": "Iris",
        "enemyMat": "Howler Core",
        "forgeryMat": "Waveworn Residue"
    },
    "Verina": {
        "id": 1503,
        "rarity": 5,
        "weapon": "Rectifier",
        "element": "Spectro",
        "name": "Verina",
        "alias": "Nature Calling",
        "weeklyMat": "Monument Bell",
        "bossMat": "Elegy Tacet Core",
        "floraMat": "Belle Poppy",
        "enemyMat": "Howler Core",
        "forgeryMat": "Helix"
    },
    "Yangyang": {
        "id": 1402,
        "rarity": 4,
        "weapon": "Sword",
        "element": "Aero",
        "name": "Yangyang",
        "alias": "Breath of Winds",
        "weeklyMat": "Unending Destruction",
        "bossMat": "Roaring Rock Fist",
        "floraMat": "Wintry Bell",
        "enemyMat": "Ring",
        "forgeryMat": "Metallic Drip"
    },
    "Yinlin": {
        "id": 1302,
        "rarity": 5,
        "weapon": "Rectifier",
        "element": "Electro",
        "name": "Yinlin",
        "alias": "Lightning of Execution",
        "weeklyMat": "Dreamless Feather",
        "bossMat": "Group Abomination Tacet Core",
        "floraMat": "Coriolus",
        "enemyMat": "Whisperin Core",
        "forgeryMat": "Helix"
    },
    "Yuanwu": {
        "id": 1303,
        "rarity": 4,
        "weapon": "Gauntlets",
        "element": "Electro",
        "name": "Yuanwu",
        "alias": "Fist of Thunder",
        "weeklyMat": "Unending Destruction",
        "bossMat": "Hidden Thunder Tacet Core",
        "floraMat": "Terraspawn Fungus",
        "enemyMat": "Ring",
        "forgeryMat": "Cadence"
    }
};