export default {
  '0': {
    levelCap: 20,
    maxTalent: 1,
    ascendMoraCost: 20000,
    ascendMatGemCount: 1,
    ascendMatGemQuality: 2,
    ascendMatBossCount: 0,
    ascendMatFlowerCount: 3,
    ascendMatEnemyCount: 3,
    ascendMatEnemyQuality: 1,
    ascendWpnMoraCost: {
      '5': 10000,
      '4': 5000,
      '3': 5000,
      '2': 5000,
      '1': 0,
    },
    ascendMatForgeQuality: 2,
    ascendMatForgeCount: {
      '5': 5,
      '4': 3,
      '3': 2,
      '2': 1,
      '1': 1,
    },
    ascendMatStrongQuality: 2,
    ascendMatStrongCount: {
      '5': 5,
      '4': 3,
      '3': 2,
      '2': 1,
      '1': 1,
    },
    ascendMatWeakQuality: 1,
    ascendMatWeakCount: {
      '5': 3,
      '4': 2,
      '3': 1,
      '2': 1,
      '1': 1,
    },
  },
  '1': {
    levelCap: 40,
    maxTalent: 1,
    ascendMoraCost: 40000,
    ascendMatGemCount: 3,
    ascendMatGemQuality: 3,
    ascendMatBossCount: 2,
    ascendMatFlowerCount: 10,
    ascendMatEnemyCount: 15,
    ascendMatEnemyQuality: 1,
    ascendWpnMoraCost: {
      '5': 20000,
      '4': 15000,
      '3': 10000,
      '2': 5000,
      '1': 5000,
    },
    ascendMatForgeQuality: 3,
    ascendMatForgeCount: {
      '5': 5,
      '4': 3,
      '3': 2,
      '2': 1,
      '1': 1,
    },
    ascendMatStrongQuality: 2,
    ascendMatStrongCount: {
      '5': 18,
      '4': 12,
      '3': 8,
      '2': 5,
      '1': 4,
    },
    ascendMatWeakQuality: 1,
    ascendMatWeakCount: {
      '5': 12,
      '4': 8,
      '3': 5,
      '2': 4,
      '1': 2,
    },
  },
  '2': {
    levelCap: 50,
    maxTalent: 2,
    ascendMoraCost: 60000,
    ascendMatGemCount: 6,
    ascendMatGemQuality: 3,
    ascendMatBossCount: 4,
    ascendMatFlowerCount: 20,
    ascendMatEnemyCount: 12,
    ascendMatEnemyQuality: 2,
    ascendWpnMoraCost: {
      '5': 30000,
      '4': 20000,
      '3': 15000,
      '2': 10000,
      '1': 5000,
    },
    ascendMatForgeQuality: 3,
    ascendMatForgeCount: {
      '5': 9,
      '4': 6,
      '3': 4,
      '2': 3,
      '1': 2,
    },
    ascendMatStrongQuality: 3,
    ascendMatStrongCount: {
      '5': 9,
      '4': 6,
      '3': 4,
      '2': 3,
      '1': 2,
    },
    ascendMatWeakQuality: 2,
    ascendMatWeakCount: {
      '5': 9,
      '4': 6,
      '3': 4,
      '2': 3,
      '1': 2,
    },
  },
  '3': {
    levelCap: 60,
    maxTalent: 4,
    ascendMoraCost: 80000,
    ascendMatGemCount: 3,
    ascendMatGemQuality: 4,
    ascendMatBossCount: 8,
    ascendMatFlowerCount: 30,
    ascendMatEnemyCount: 18,
    ascendMatEnemyQuality: 2,
    ascendWpnMoraCost: {
      '5': 45000,
      '4': 30000,
      '3': 20000,
      '2': 15000,
      '1': 10000,
    },
    ascendMatForgeQuality: 4,
    ascendMatForgeCount: {
      '5': 5,
      '4': 3,
      '3': 2,
      '2': 1,
      '1': 1,
    },
    ascendMatStrongQuality: 3,
    ascendMatStrongCount: {
      '5': 18,
      '4': 12,
      '3': 8,
      '2': 5,
      '1': 4,
    },
    ascendMatWeakQuality: 2,
    ascendMatWeakCount: {
      '5': 14,
      '4': 9,
      '3': 6,
      '2': 4,
      '1': 3,
    },
  },
  '4': {
    levelCap: 70,
    maxTalent: 6,
    ascendMoraCost: 100000,
    ascendMatGemCount: 6,
    ascendMatGemQuality: 4,
    ascendMatBossCount: 12,
    ascendMatFlowerCount: 45,
    ascendMatEnemyCount: 12,
    ascendMatEnemyQuality: 3,
    ascendWpnMoraCost: {
      '5': 55000,
      '4': 35000,
      '3': 25000,
      '2': 0,
      '1': 0,
    },
    ascendMatForgeQuality: 4,
    ascendMatForgeCount: {
      '5': 9,
      '4': 6,
      '3': 4,
      '2': 0,
      '1': 0,
    },
    ascendMatStrongQuality: 4,
    ascendMatStrongCount: {
      '5': 14,
      '4': 9,
      '3': 6,
      '2': 0,
      '1': 0,
    },
    ascendMatWeakQuality: 3,
    ascendMatWeakCount: {
      '5': 9,
      '4': 6,
      '3': 4,
      '2': 0,
      '1': 0,
    },
  },
  '5': {
    levelCap: 80,
    maxTalent: 8,
    ascendMoraCost: 120000,
    ascendMatGemCount: 6,
    ascendMatGemQuality: 5,
    ascendMatBossCount: 20,
    ascendMatFlowerCount: 60,
    ascendMatEnemyCount: 24,
    ascendMatEnemyQuality: 3,
    ascendWpnMoraCost: {
      '5': 65000,
      '4': 45000,
      '3': 30000,
      '2': 0,
      '1': 0,
    },
    ascendMatForgeQuality: 5,
    ascendMatForgeCount: {
      '5': 6,
      '4': 4,
      '3': 3,
      '2': 0,
      '1': 0,
    },
    ascendMatStrongQuality: 4,
    ascendMatStrongCount: {
      '5': 27,
      '4': 18,
      '3': 12,
      '2': 0,
      '1': 0,
    },
    ascendMatWeakQuality: 3,
    ascendMatWeakCount: {
      '5': 18,
      '4': 12,
      '3': 8,
      '2': 0,
      '1': 0,
    },
  },
  '6': {
    levelCap: 90,
    maxTalent: 10,
    ascendMoraCost: 0,
    ascendMatGemCount: 0,
    ascendMatGemQuality: 5,
    ascendMatBossCount: 0,
    ascendMatFlowerCount: 0,
    ascendMatEnemyCount: 0,
    ascendMatEnemyQuality: 3,
    ascendWpnMoraCost: {
      '5': 0,
      '4': 0,
      '3': 0,
      '2': 0,
      '1': 0,
    },
    ascendMatForgeQuality: 5,
    ascendMatForgeCount: {
      '5': 0,
      '4': 0,
      '3': 0,
      '2': 0,
      '1': 0,
    },
    ascendMatStrongQuality: 4,
    ascendMatStrongCount: {
      '5': 0,
      '4': 0,
      '3': 0,
      '2': 0,
      '1': 0,
    },
    ascendMatWeakQuality: 3,
    ascendMatWeakCount: {
      '5': 0,
      '4': 0,
      '3': 0,
      '2': 0,
      '1': 0,
    },
  },
};
