export default {
    "Albedo": {
        "name": "Albedo",
        "weapon": "Sword",
        "element": "Geo",
        "rarity": 5,
        "ascendStat": "geo_dmg_",
        "matBoss": "Geo Cube",
        "matFlower": "Cecilia",
        "matEnemy": "Samachurls",
        "matMastery": "Ballad",
        "matTrounce": "Tusk of Monoceros Caeli",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/3\/30\/Albedo_Icon.png",
        "region": "Mondstadt",
        "release": "December 23, 2020",
        "patch": "1.2",
        "hpBase": 1029.5856,
        "atkBase": 19.551,
        "defBase": 68.2062,
        "hpMaxAsc": 4228.035,
        "atkMaxAsc": 80.28111,
        "defMaxAsc": 280.098
    },
    "Alhaitham": {
        "name": "Alhaitham",
        "weapon": "Sword",
        "element": "Dendro",
        "rarity": 5,
        "ascendStat": "dendro_dmg_",
        "matBoss": "Wenut",
        "matFlower": "Sand Grease Pupa",
        "matEnemy": "Eremites",
        "matMastery": "Ingenuity",
        "matTrounce": "Mirror of Mushin",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/2\/2c\/Alhaitham_Icon.png",
        "region": "Sumeru",
        "release": "January 18, 2023",
        "patch": "3.4",
        "hpBase": 1039.1188,
        "atkBase": 24.3922,
        "defBase": 60.84711,
        "hpMaxAsc": 4267.1836,
        "atkMaxAsc": 100.16024,
        "defMaxAsc": 249.8769
    },
    "Aloy": {
        "name": "Aloy",
        "weapon": "Bow",
        "element": "Cryo",
        "rarity": 5,
        "ascendStat": "cryo_dmg_",
        "matBoss": "Cryo Cube",
        "matFlower": "Crystal Marrow",
        "matEnemy": "Specters",
        "matMastery": "Freedom",
        "matTrounce": "Molten Moment",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/e\/e5\/Aloy_Icon.png",
        "region": "",
        "release": "September 01, 2021",
        "patch": "2.1",
        "hpBase": 848.4548,
        "atkBase": 18.21036,
        "defBase": 52.6504,
        "hpMaxAsc": 3484.214,
        "atkMaxAsc": 74.77612,
        "defMaxAsc": 216.216
    },
    "Amber": {
        "name": "Amber",
        "weapon": "Bow",
        "element": "Pyro",
        "rarity": 4,
        "ascendStat": "atk_",
        "matBoss": "Pyro Plant",
        "matFlower": "Small Lamp Grass",
        "matEnemy": "Hilichurl Archers",
        "matMastery": "Freedom",
        "matTrounce": "Dvalin's Sigh",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/7\/75\/Amber_Icon.png",
        "region": "Mondstadt",
        "release": "September 28, 2020",
        "patch": "1.0",
        "hpBase": 793.2582,
        "atkBase": 18.6984,
        "defBase": 50.358,
        "hpMaxAsc": 2838.2634,
        "atkMaxAsc": 66.90411,
        "defMaxAsc": 180.18
    },
    "AratakiItto": {
        "name": "Arataki Itto",
        "weapon": "Claymore",
        "element": "Geo",
        "rarity": 5,
        "ascendStat": "critRate_",
        "matBoss": "Wolflord",
        "matFlower": "Onikabuto",
        "matEnemy": "Slimes",
        "matMastery": "Elegance",
        "matTrounce": "Ashen Heart",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/7\/7b\/Arataki_Itto_Icon.png",
        "region": "Inazuma",
        "release": "December 14, 2021",
        "patch": "2.3",
        "hpBase": 1000.986,
        "atkBase": 17.689,
        "defBase": 74.66784,
        "hpMaxAsc": 4110.59,
        "atkMaxAsc": 72.63529,
        "defMaxAsc": 306.6336
    },
    "Baizhu": {
        "name": "Baizhu",
        "weapon": "Catalyst",
        "element": "Dendro",
        "rarity": 5,
        "ascendStat": "hp_",
        "matBoss": "Baptist",
        "matFlower": "Violetgrass",
        "matEnemy": "Fungi",
        "matMastery": "Gold",
        "matTrounce": "Worldspan Fern",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/c\/cb\/Baizhu_Icon.png",
        "region": "Liyue",
        "release": "May 02, 2023",
        "patch": "3.6",
        "hpBase": 1039.1188,
        "atkBase": 14.9891,
        "defBase": 38.8895,
        "hpMaxAsc": 4267.1836,
        "atkMaxAsc": 61.54885,
        "defMaxAsc": 159.705
    },
    "Barbara": {
        "name": "Barbara",
        "weapon": "Catalyst",
        "element": "Hydro",
        "rarity": 4,
        "ascendStat": "hp_",
        "matBoss": "Oceanid",
        "matFlower": "Philanemo Mushroom",
        "matEnemy": "Samachurls",
        "matMastery": "Freedom",
        "matTrounce": "Ring of Boreas",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/6\/6a\/Barbara_Icon.png",
        "region": "Mondstadt",
        "release": "September 28, 2020",
        "patch": "1.0",
        "hpBase": 820.6119,
        "atkBase": 13.356,
        "defBase": 56.0805,
        "hpMaxAsc": 2936.1348,
        "atkMaxAsc": 47.78865,
        "defMaxAsc": 200.655
    },
    "Beidou": {
        "name": "Beidou",
        "weapon": "Claymore",
        "element": "Electro",
        "rarity": 4,
        "ascendStat": "electro_dmg_",
        "matBoss": "Electro Cube",
        "matFlower": "Noctilucous Jade",
        "matEnemy": "Treasure Hoarders",
        "matMastery": "Gold",
        "matTrounce": "Dvalin's Sigh",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/e\/e1\/Beidou_Icon.png",
        "region": "Liyue",
        "release": "September 28, 2020",
        "patch": "1.0",
        "hpBase": 1094.1492,
        "atkBase": 18.87648,
        "defBase": 54.36375,
        "hpMaxAsc": 3914.8462,
        "atkMaxAsc": 67.54129,
        "defMaxAsc": 194.5125
    },
    "Bennett": {
        "name": "Bennett",
        "weapon": "Sword",
        "element": "Pyro",
        "rarity": 4,
        "ascendStat": "enerRech_",
        "matBoss": "Pyro Plant",
        "matFlower": "Windwheel Aster",
        "matEnemy": "Treasure Hoarders",
        "matMastery": "Resistance",
        "matTrounce": "Dvalin's Plume",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/7\/79\/Bennett_Icon.png",
        "region": "Mondstadt",
        "release": "September 28, 2020",
        "patch": "1.0",
        "hpBase": 1039.4418,
        "atkBase": 16.0272,
        "defBase": 64.66425,
        "hpMaxAsc": 3719.104,
        "atkMaxAsc": 57.34638,
        "defMaxAsc": 231.3675
    },
    "Candace": {
        "name": "Candace",
        "weapon": "Polearm",
        "element": "Hydro",
        "rarity": 4,
        "ascendStat": "hp_",
        "matBoss": "Matrix Boss",
        "matFlower": "Henna Berry",
        "matEnemy": "Eremites",
        "matMastery": "Admonition",
        "matTrounce": "Tears of the Calamitous God",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/d\/dd\/Candace_Icon.png",
        "region": "Sumeru",
        "release": "September 28, 2022",
        "patch": "3.1",
        "hpBase": 911.791,
        "atkBase": 17.808,
        "defBase": 57.225,
        "hpMaxAsc": 3262.3718,
        "atkMaxAsc": 63.7182,
        "defMaxAsc": 204.75
    },
    "Chongyun": {
        "name": "Chongyun",
        "weapon": "Claymore",
        "element": "Cryo",
        "rarity": 4,
        "ascendStat": "atk_",
        "matBoss": "Cryo Plant",
        "matFlower": "Cor Lapis",
        "matEnemy": "Hilichurls",
        "matMastery": "Diligence",
        "matTrounce": "Dvalin's Sigh",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/3\/35\/Chongyun_Icon.png",
        "region": "Liyue",
        "release": "September 28, 2020",
        "patch": "1.0",
        "hpBase": 920.90894,
        "atkBase": 18.6984,
        "defBase": 54.36375,
        "hpMaxAsc": 3294.9956,
        "atkMaxAsc": 66.90411,
        "defMaxAsc": 194.5125
    },
    "Collei": {
        "name": "Collei",
        "weapon": "Bow",
        "element": "Dendro",
        "rarity": 4,
        "ascendStat": "atk_",
        "matBoss": "Dendro Bird",
        "matFlower": "Rukkhashava Mushrooms",
        "matEnemy": "Hilichurl Archers",
        "matMastery": "Praxis",
        "matTrounce": "Tears of the Calamitous God",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/a\/a2\/Collei_Icon.png",
        "region": "Sumeru",
        "release": "August 24, 2022",
        "patch": "3.0",
        "hpBase": 820.6119,
        "atkBase": 16.73952,
        "defBase": 50.358,
        "hpMaxAsc": 2936.1348,
        "atkMaxAsc": 59.895107,
        "defMaxAsc": 180.18
    },
    "Cyno": {
        "name": "Cyno",
        "weapon": "Polearm",
        "element": "Electro",
        "rarity": 5,
        "ascendStat": "critDMG_",
        "matBoss": "Electro Plant",
        "matFlower": "Scarab",
        "matEnemy": "Samachurls",
        "matMastery": "Admonition",
        "matTrounce": "Mudra of the Malefic General",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/3\/31\/Cyno_Icon.png",
        "region": "Sumeru",
        "release": "September 28, 2022",
        "patch": "3.1",
        "hpBase": 972.3864,
        "atkBase": 24.7646,
        "defBase": 66.88994,
        "hpMaxAsc": 3993.1443,
        "atkMaxAsc": 101.68941,
        "defMaxAsc": 274.6926
    },
    "Dehya": {
        "name": "Dehya",
        "weapon": "Claymore",
        "element": "Pyro",
        "rarity": 5,
        "ascendStat": "hp_",
        "matBoss": "Matrix Boss",
        "matFlower": "Sand Grease Pupa",
        "matEnemy": "Eremites",
        "matMastery": "Praxis",
        "matTrounce": "Puppet Strings",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/3\/3f\/Dehya_Icon.png",
        "region": "Sumeru",
        "release": "March 01, 2023",
        "patch": "3.5",
        "hpBase": 1220.2496,
        "atkBase": 20.6682,
        "defBase": 48.88111,
        "hpMaxAsc": 5011.0044,
        "atkMaxAsc": 84.8686,
        "defMaxAsc": 200.7369
    },
    "Diluc": {
        "name": "Diluc",
        "weapon": "Claymore",
        "element": "Pyro",
        "rarity": 5,
        "ascendStat": "critRate_",
        "matBoss": "Pyro Plant",
        "matFlower": "Small Lamp Grass",
        "matEnemy": "Fatui",
        "matMastery": "Resistance",
        "matTrounce": "Dvalin's Plume",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/3\/3d\/Diluc_Icon.png",
        "region": "Mondstadt",
        "release": "September 28, 2020",
        "patch": "1.0",
        "hpBase": 1010.5192,
        "atkBase": 26.068,
        "defBase": 61.0266,
        "hpMaxAsc": 4149.7383,
        "atkMaxAsc": 107.04148,
        "defMaxAsc": 250.614
    },
    "Diona": {
        "name": "Diona",
        "weapon": "Bow",
        "element": "Cryo",
        "rarity": 4,
        "ascendStat": "cryo_dmg_",
        "matBoss": "Cryo Plant",
        "matFlower": "Calla Lily",
        "matEnemy": "Hilichurl Archers",
        "matMastery": "Freedom",
        "matTrounce": "Shard of a Foul Legacy",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/4\/40\/Diona_Icon.png",
        "region": "Mondstadt",
        "release": "November 11, 2020",
        "patch": "1.1",
        "hpBase": 802.3761,
        "atkBase": 17.808,
        "defBase": 50.358,
        "hpMaxAsc": 2870.8872,
        "atkMaxAsc": 63.7182,
        "defMaxAsc": 180.18
    },
    "Dori": {
        "name": "Dori",
        "weapon": "Claymore",
        "element": "Electro",
        "rarity": 4,
        "ascendStat": "hp_",
        "matBoss": "Electro Plant",
        "matFlower": "Kalpalata Lotus",
        "matEnemy": "Eremites",
        "matMastery": "Ingenuity",
        "matTrounce": "Bloodjade Branch",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/5\/54\/Dori_Icon.png",
        "region": "Sumeru",
        "release": "September 09, 2022",
        "patch": "3.0",
        "hpBase": 1039.4418,
        "atkBase": 18.6984,
        "defBase": 60.6585,
        "hpMaxAsc": 3719.104,
        "atkMaxAsc": 66.90411,
        "defMaxAsc": 217.035
    },
    "Eula": {
        "name": "Eula",
        "weapon": "Claymore",
        "element": "Cryo",
        "rarity": 5,
        "ascendStat": "critDMG_",
        "matBoss": "Cryo Cube",
        "matFlower": "Dandelion Seed",
        "matEnemy": "Hilichurls",
        "matMastery": "Resistance",
        "matTrounce": "Dragon Lord's Crown",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/a\/af\/Eula_Icon.png",
        "region": "Mondstadt",
        "release": "May 18, 2021",
        "patch": "1.5",
        "hpBase": 1029.5856,
        "atkBase": 26.6266,
        "defBase": 58.45391,
        "hpMaxAsc": 4228.035,
        "atkMaxAsc": 109.33523,
        "defMaxAsc": 240.0489
    },
    "Faruzan": {
        "name": "Faruzan",
        "weapon": "Bow",
        "element": "Anemo",
        "rarity": 4,
        "ascendStat": "atk_",
        "matBoss": "Matrix Boss",
        "matFlower": "Henna Berry",
        "matEnemy": "Eremites",
        "matMastery": "Admonition",
        "matTrounce": "Puppet Strings",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/b\/b2\/Faruzan_Icon.png",
        "region": "Sumeru",
        "release": "December 07, 2022",
        "patch": "3.3",
        "hpBase": 802.3761,
        "atkBase": 16.4724,
        "defBase": 52.647,
        "hpMaxAsc": 2870.8872,
        "atkMaxAsc": 58.939335,
        "defMaxAsc": 188.37
    },
    "Fischl": {
        "name": "Fischl",
        "weapon": "Bow",
        "element": "Electro",
        "rarity": 4,
        "ascendStat": "atk_",
        "matBoss": "Electro Cube",
        "matFlower": "Small Lamp Grass",
        "matEnemy": "Hilichurl Archers",
        "matMastery": "Ballad",
        "matTrounce": "Spirit Locket of Boreas",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/9\/9a\/Fischl_Icon.png",
        "region": "Mondstadt",
        "release": "September 28, 2020",
        "patch": "1.0",
        "hpBase": 770.4634,
        "atkBase": 20.4792,
        "defBase": 49.78575,
        "hpMaxAsc": 2756.704,
        "atkMaxAsc": 73.27593,
        "defMaxAsc": 178.1325
    },
    "Ganyu": {
        "name": "Ganyu",
        "weapon": "Bow",
        "element": "Cryo",
        "rarity": 5,
        "ascendStat": "critDMG_",
        "matBoss": "Cryo Plant",
        "matFlower": "Qingxin",
        "matEnemy": "Whopperflowers",
        "matMastery": "Diligence",
        "matTrounce": "Shadow of the Warrior",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/7\/79\/Ganyu_Icon.png",
        "region": "Liyue",
        "release": "January 12, 2021",
        "patch": "1.2",
        "hpBase": 762.656,
        "atkBase": 26.068,
        "defBase": 49.0606,
        "hpMaxAsc": 3131.878,
        "atkMaxAsc": 107.04148,
        "defMaxAsc": 201.474
    },
    "Gorou": {
        "name": "Gorou",
        "weapon": "Bow",
        "element": "Geo",
        "rarity": 4,
        "ascendStat": "geo_dmg_",
        "matBoss": "Array Boss",
        "matFlower": "Sango Pearl",
        "matEnemy": "Specters",
        "matMastery": "Light",
        "matTrounce": "Molten Moment",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/f\/fe\/Gorou_Icon.png",
        "region": "Inazuma",
        "release": "December 14, 2021",
        "patch": "2.3",
        "hpBase": 802.3761,
        "atkBase": 15.31488,
        "defBase": 54.36375,
        "hpMaxAsc": 2870.8872,
        "atkMaxAsc": 54.797653,
        "defMaxAsc": 194.5125
    },
    "HuTao": {
        "name": "Hu Tao",
        "weapon": "Polearm",
        "element": "Pyro",
        "rarity": 5,
        "ascendStat": "critDMG_",
        "matBoss": "Geovishap",
        "matFlower": "Silk Flower",
        "matEnemy": "Whopperflowers",
        "matMastery": "Diligence",
        "matTrounce": "Shard of a Foul Legacy",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/e\/e9\/Hu_Tao_Icon.png",
        "region": "Liyue",
        "release": "March 02, 2021",
        "patch": "1.3",
        "hpBase": 1210.7164,
        "atkBase": 8.2859,
        "defBase": 68.2062,
        "hpMaxAsc": 4971.856,
        "atkMaxAsc": 34.0239,
        "defMaxAsc": 280.098
    },
    "Jean": {
        "name": "Jean",
        "weapon": "Sword",
        "element": "Anemo",
        "rarity": 5,
        "ascendStat": "heal_",
        "matBoss": "Anemo Cube",
        "matFlower": "Dandelion Seed",
        "matEnemy": "Hilichurls",
        "matMastery": "Resistance",
        "matTrounce": "Dvalin's Plume",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/6\/64\/Jean_Icon.png",
        "region": "Mondstadt",
        "release": "September 28, 2020",
        "patch": "1.0",
        "hpBase": 1143.984,
        "atkBase": 18.62,
        "defBase": 59.83,
        "hpMaxAsc": 4697.817,
        "atkMaxAsc": 76.4582,
        "defMaxAsc": 245.7
    },
    "KaedeharaKazuha": {
        "name": "Kaedehara Kazuha",
        "weapon": "Sword",
        "element": "Anemo",
        "rarity": 5,
        "ascendStat": "eleMas",
        "matBoss": "Maguu Kenki",
        "matFlower": "Sea Ganoderma",
        "matEnemy": "Treasure Hoarders",
        "matMastery": "Diligence",
        "matTrounce": "Gilded Scale",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/e\/e3\/Kaedehara_Kazuha_Icon.png",
        "region": "Inazuma",
        "release": "June 29, 2021",
        "patch": "1.6",
        "hpBase": 1039.1188,
        "atkBase": 23.0888,
        "defBase": 62.8215,
        "hpMaxAsc": 4267.1836,
        "atkMaxAsc": 94.80817,
        "defMaxAsc": 257.985
    },
    "Kaeya": {
        "name": "Kaeya",
        "weapon": "Sword",
        "element": "Cryo",
        "rarity": 4,
        "ascendStat": "enerRech_",
        "matBoss": "Cryo Plant",
        "matFlower": "Calla Lily",
        "matEnemy": "Treasure Hoarders",
        "matMastery": "Ballad",
        "matTrounce": "Spirit Locket of Boreas",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/b\/b6\/Kaeya_Icon.png",
        "region": "Mondstadt",
        "release": "September 28, 2020",
        "patch": "1.0",
        "hpBase": 975.6164,
        "atkBase": 18.6984,
        "defBase": 66.381,
        "hpMaxAsc": 3490.7378,
        "atkMaxAsc": 66.90411,
        "defMaxAsc": 237.51
    },
    "KamisatoAyaka": {
        "name": "Kamisato Ayaka",
        "weapon": "Sword",
        "element": "Cryo",
        "rarity": 5,
        "ascendStat": "critDMG_",
        "matBoss": "Array Boss",
        "matFlower": "Sakura Bloom",
        "matEnemy": "Nobushi",
        "matMastery": "Elegance",
        "matTrounce": "Bloodjade Branch",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/5\/51\/Kamisato_Ayaka_Icon.png",
        "region": "Inazuma",
        "release": "July 21, 2021",
        "patch": "2.0",
        "hpBase": 1000.986,
        "atkBase": 26.6266,
        "defBase": 61.0266,
        "hpMaxAsc": 4110.59,
        "atkMaxAsc": 109.33523,
        "defMaxAsc": 250.614
    },
    "KamisatoAyato": {
        "name": "Kamisato Ayato",
        "weapon": "Sword",
        "element": "Hydro",
        "rarity": 5,
        "ascendStat": "critDMG_",
        "matBoss": "Hydro Cube",
        "matFlower": "Sakura Bloom",
        "matEnemy": "Nobushi",
        "matMastery": "Elegance",
        "matTrounce": "Mudra of the Malefic General",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/2\/27\/Kamisato_Ayato_Icon.png",
        "region": "Inazuma",
        "release": "March 30, 2022",
        "patch": "2.6",
        "hpBase": 1067.7184,
        "atkBase": 23.275,
        "defBase": 59.83,
        "hpMaxAsc": 4384.629,
        "atkMaxAsc": 95.57275,
        "defMaxAsc": 245.7
    },
    "Kaveh": {
        "name": "Kaveh",
        "weapon": "Claymore",
        "element": "Dendro",
        "rarity": 4,
        "ascendStat": "eleMas",
        "matBoss": "Dendro Cube",
        "matFlower": "Mourning Flower",
        "matEnemy": "Fungi",
        "matMastery": "Ingenuity",
        "matTrounce": "Primordial Greenbloom",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/1\/1f\/Kaveh_Icon.png",
        "region": "Sumeru",
        "release": "May 02, 2023",
        "patch": "3.6",
        "hpBase": 1002.9701,
        "atkBase": 19.5888,
        "defBase": 62.9475,
        "hpMaxAsc": 3588.6091,
        "atkMaxAsc": 70.09002,
        "defMaxAsc": 225.225
    },
    "Keqing": {
        "name": "Keqing",
        "weapon": "Sword",
        "element": "Electro",
        "rarity": 5,
        "ascendStat": "critDMG_",
        "matBoss": "Electro Cube",
        "matFlower": "Cor Lapis",
        "matEnemy": "Whopperflowers",
        "matMastery": "Prosperity",
        "matTrounce": "Ring of Boreas",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/5\/52\/Keqing_Icon.png",
        "region": "Liyue",
        "release": "September 28, 2020",
        "patch": "1.0",
        "hpBase": 1020.0524,
        "atkBase": 25.137,
        "defBase": 62.2232,
        "hpMaxAsc": 4188.8867,
        "atkMaxAsc": 103.21857,
        "defMaxAsc": 255.528
    },
    "Kirara": {
        "name": "Kirara",
        "weapon": "Sword",
        "element": "Dendro",
        "rarity": 4,
        "ascendStat": "hp_",
        "matBoss": "Baptist",
        "matFlower": "Amakumo Fruit",
        "matEnemy": "Specters",
        "matMastery": "Transience",
        "matTrounce": "Everamber",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/b\/b6\/Kirara_Icon.png",
        "region": "Inazuma",
        "release": "May 24, 2023",
        "patch": "3.7",
        "hpBase": 1021.2059,
        "atkBase": 18.6984,
        "defBase": 45.78,
        "hpMaxAsc": 3653.8564453125,
        "atkMaxAsc": 66.904113769531,
        "defMaxAsc": 163.8
    },
    "Klee": {
        "name": "Klee",
        "weapon": "Catalyst",
        "element": "Pyro",
        "rarity": 5,
        "ascendStat": "pyro_dmg_",
        "matBoss": "Pyro Plant",
        "matFlower": "Philanemo Mushroom",
        "matEnemy": "Samachurls",
        "matMastery": "Freedom",
        "matTrounce": "Ring of Boreas",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/9\/9c\/Klee_Icon.png",
        "region": "Mondstadt",
        "release": "October 20, 2020",
        "patch": "1.0",
        "hpBase": 800.7888,
        "atkBase": 24.206,
        "defBase": 47.864,
        "hpMaxAsc": 3288.4717,
        "atkMaxAsc": 99.39566,
        "defMaxAsc": 196.56
    },
    "KujouSara": {
        "name": "Kujou Sara",
        "weapon": "Bow",
        "element": "Electro",
        "rarity": 4,
        "ascendStat": "atk_",
        "matBoss": "Thunder Bird",
        "matFlower": "Dendrobium",
        "matEnemy": "Hilichurls",
        "matMastery": "Elegance",
        "matTrounce": "Ashen Heart",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/d\/df\/Kujou_Sara_Icon.png",
        "region": "Inazuma",
        "release": "September 01, 2021",
        "patch": "2.1",
        "hpBase": 802.3761,
        "atkBase": 16.38336,
        "defBase": 52.647,
        "hpMaxAsc": 2870.8872,
        "atkMaxAsc": 58.620743,
        "defMaxAsc": 188.37
    },
    "KukiShinobu": {
        "name": "Kuki Shinobu",
        "weapon": "Sword",
        "element": "Electro",
        "rarity": 4,
        "ascendStat": "hp_",
        "matBoss": "Ruin Serpent",
        "matFlower": "Naku Weed",
        "matEnemy": "Specters",
        "matMastery": "Elegance",
        "matTrounce": "Tears of the Calamitous God",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/b\/b3\/Kuki_Shinobu_Icon.png",
        "region": "Inazuma",
        "release": "June 21, 2022",
        "patch": "2.7",
        "hpBase": 1030.3239,
        "atkBase": 17.808,
        "defBase": 62.9475,
        "hpMaxAsc": 3686.4802,
        "atkMaxAsc": 63.7182,
        "defMaxAsc": 225.225
    },
    "Layla": {
        "name": "Layla",
        "weapon": "Sword",
        "element": "Cryo",
        "rarity": 4,
        "ascendStat": "hp_",
        "matBoss": "Aeonblight",
        "matFlower": "Nilotpala Lotus",
        "matEnemy": "Samachurls",
        "matMastery": "Ingenuity",
        "matTrounce": "Mirror of Mushin",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/1\/1a\/Layla_Icon.png",
        "region": "Sumeru",
        "release": "November 18, 2022",
        "patch": "3.2",
        "hpBase": 930.0268,
        "atkBase": 18.16416,
        "defBase": 54.936,
        "hpMaxAsc": 3327.6194,
        "atkMaxAsc": 64.99256,
        "defMaxAsc": 196.56
    },
    "Lisa": {
        "name": "Lisa",
        "weapon": "Catalyst",
        "element": "Electro",
        "rarity": 4,
        "ascendStat": "eleMas",
        "matBoss": "Electro Cube",
        "matFlower": "Valberry",
        "matEnemy": "Slimes",
        "matMastery": "Ballad",
        "matTrounce": "Dvalin's Claw",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/6\/65\/Lisa_Icon.png",
        "region": "Mondstadt",
        "release": "September 28, 2020",
        "patch": "1.0",
        "hpBase": 802.3761,
        "atkBase": 19.41072,
        "defBase": 48.069,
        "hpMaxAsc": 2870.8872,
        "atkMaxAsc": 69.452835,
        "defMaxAsc": 171.99
    },
    "Mika": {
        "name": "Mika",
        "weapon": "Polearm",
        "element": "Cryo",
        "rarity": 4,
        "ascendStat": "hp_",
        "matBoss": "Wenut",
        "matFlower": "Wolfhook",
        "matEnemy": "Fatui",
        "matMastery": "Ballad",
        "matTrounce": "Mirror of Mushin",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/d\/dd\/Mika_Icon.png",
        "region": "Mondstadt",
        "release": "March 21, 2023",
        "patch": "3.5",
        "hpBase": 1048.5597,
        "atkBase": 18.6984,
        "defBase": 59.800125,
        "hpMaxAsc": 3751.7275,
        "atkMaxAsc": 66.90411,
        "defMaxAsc": 213.96375
    },
    "Mona": {
        "name": "Mona",
        "weapon": "Catalyst",
        "element": "Hydro",
        "rarity": 5,
        "ascendStat": "enerRech_",
        "matBoss": "Oceanid",
        "matFlower": "Philanemo Mushroom",
        "matEnemy": "Whopperflowers",
        "matMastery": "Resistance",
        "matTrounce": "Ring of Boreas",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/4\/41\/Mona_Icon.png",
        "region": "Mondstadt",
        "release": "September 28, 2020",
        "patch": "1.0",
        "hpBase": 810.322,
        "atkBase": 22.344,
        "defBase": 50.8555,
        "hpMaxAsc": 3327.62,
        "atkMaxAsc": 91.74984,
        "defMaxAsc": 208.845
    },
    "Nahida": {
        "name": "Nahida",
        "weapon": "Catalyst",
        "element": "Dendro",
        "rarity": 5,
        "ascendStat": "eleMas",
        "matBoss": "Dendro Cube",
        "matFlower": "Kalpalata Lotus",
        "matEnemy": "Fungi",
        "matMastery": "Ingenuity",
        "matTrounce": "Puppet Strings",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/f\/f9\/Nahida_Icon.png",
        "region": "Sumeru",
        "release": "November 02, 2022",
        "patch": "3.2",
        "hpBase": 806.5087,
        "atkBase": 23.275,
        "defBase": 49.0606,
        "hpMaxAsc": 3311.961,
        "atkMaxAsc": 95.57275,
        "defMaxAsc": 201.474
    },
    "Nilou": {
        "name": "Nilou",
        "weapon": "Sword",
        "element": "Hydro",
        "rarity": 5,
        "ascendStat": "hp_",
        "matBoss": "Aeonblight",
        "matFlower": "Padisarah",
        "matEnemy": "Fungi",
        "matMastery": "Praxis",
        "matTrounce": "Tears of the Calamitous God",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/5\/58\/Nilou_Icon.png",
        "region": "Sumeru",
        "release": "October 14, 2022",
        "patch": "3.1",
        "hpBase": 1182.1168,
        "atkBase": 17.8752,
        "defBase": 56.71884,
        "hpMaxAsc": 4854.4106,
        "atkMaxAsc": 73.39987,
        "defMaxAsc": 232.9236
    },
    "Ningguang": {
        "name": "Ningguang",
        "weapon": "Catalyst",
        "element": "Geo",
        "rarity": 4,
        "ascendStat": "geo_dmg_",
        "matBoss": "Geo Cube",
        "matFlower": "Glaze Lily",
        "matEnemy": "Fatui",
        "matMastery": "Prosperity",
        "matTrounce": "Spirit Locket of Boreas",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/e\/e0\/Ningguang_Icon.png",
        "region": "Liyue",
        "release": "September 28, 2020",
        "patch": "1.0",
        "hpBase": 820.6119,
        "atkBase": 17.808,
        "defBase": 48.069,
        "hpMaxAsc": 2936.1348,
        "atkMaxAsc": 63.7182,
        "defMaxAsc": 171.99
    },
    "Noelle": {
        "name": "Noelle",
        "weapon": "Claymore",
        "element": "Geo",
        "rarity": 4,
        "ascendStat": "def_",
        "matBoss": "Geo Cube",
        "matFlower": "Valberry",
        "matEnemy": "Hilichurls",
        "matMastery": "Resistance",
        "matTrounce": "Dvalin's Claw",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/8\/8e\/Noelle_Icon.png",
        "region": "Mondstadt",
        "release": "September 28, 2020",
        "patch": "1.0",
        "hpBase": 1012.088,
        "atkBase": 16.0272,
        "defBase": 66.95325,
        "hpMaxAsc": 3621.2327,
        "atkMaxAsc": 57.34638,
        "defMaxAsc": 239.5575
    },
    "Qiqi": {
        "name": "Qiqi",
        "weapon": "Sword",
        "element": "Cryo",
        "rarity": 5,
        "ascendStat": "heal_",
        "matBoss": "Cryo Plant",
        "matFlower": "Violetgrass",
        "matEnemy": "Samachurls",
        "matMastery": "Prosperity",
        "matTrounce": "Tail of Boreas",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/b\/b3\/Qiqi_Icon.png",
        "region": "Liyue",
        "release": "September 28, 2020",
        "patch": "1.0",
        "hpBase": 962.8532,
        "atkBase": 22.344,
        "defBase": 71.796,
        "hpMaxAsc": 3953.9958,
        "atkMaxAsc": 91.74984,
        "defMaxAsc": 294.84
    },
    "RaidenShogun": {
        "name": "Raiden Shogun",
        "weapon": "Polearm",
        "element": "Electro",
        "rarity": 5,
        "ascendStat": "enerRech_",
        "matBoss": "Thunder Bird",
        "matFlower": "Amakumo Fruit",
        "matEnemy": "Nobushi",
        "matMastery": "Light",
        "matTrounce": "Molten Moment",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/2\/24\/Raiden_Shogun_Icon.png",
        "region": "Inazuma",
        "release": "September 01, 2021",
        "patch": "2.1",
        "hpBase": 1004.79926,
        "atkBase": 26.2542,
        "defBase": 61.44541,
        "hpMaxAsc": 4126.249,
        "atkMaxAsc": 107.80606,
        "defMaxAsc": 252.3339
    },
    "Razor": {
        "name": "Razor",
        "weapon": "Claymore",
        "element": "Electro",
        "rarity": 4,
        "ascendStat": "physical_dmg_",
        "matBoss": "Electro Cube",
        "matFlower": "Wolfhook",
        "matEnemy": "Hilichurls",
        "matMastery": "Resistance",
        "matTrounce": "Dvalin's Claw",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/b\/b8\/Razor_Icon.png",
        "region": "Mondstadt",
        "release": "September 28, 2020",
        "patch": "1.0",
        "hpBase": 1002.9701,
        "atkBase": 19.5888,
        "defBase": 62.9475,
        "hpMaxAsc": 3588.6091,
        "atkMaxAsc": 70.09002,
        "defMaxAsc": 225.225
    },
    "Rosaria": {
        "name": "Rosaria",
        "weapon": "Polearm",
        "element": "Cryo",
        "rarity": 4,
        "ascendStat": "atk_",
        "matBoss": "Cryo Plant",
        "matFlower": "Valberry",
        "matEnemy": "Fatui",
        "matMastery": "Ballad",
        "matTrounce": "Shadow of the Warrior",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/3\/35\/Rosaria_Icon.png",
        "region": "Mondstadt",
        "release": "April 06, 2021",
        "patch": "1.4",
        "hpBase": 1030.3239,
        "atkBase": 20.12304,
        "defBase": 59.514,
        "hpMaxAsc": 3686.4802,
        "atkMaxAsc": 72.001564,
        "defMaxAsc": 212.94
    },
    "SangonomiyaKokomi": {
        "name": "Sangonomiya Kokomi",
        "weapon": "Catalyst",
        "element": "Hydro",
        "rarity": 5,
        "ascendStat": "hydro_dmg_",
        "matBoss": "Hydro Cube",
        "matFlower": "Sango Pearl",
        "matEnemy": "Specters",
        "matMastery": "Transience",
        "matTrounce": "Hellfire Butterfly",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/f\/ff\/Sangonomiya_Kokomi_Icon.png",
        "region": "Inazuma",
        "release": "September 21, 2021",
        "patch": "2.1",
        "hpBase": 1048.652,
        "atkBase": 18.2476,
        "defBase": 51.15465,
        "hpMaxAsc": 4306.332,
        "atkMaxAsc": 74.92904,
        "defMaxAsc": 210.0735
    },
    "Sayu": {
        "name": "Sayu",
        "weapon": "Claymore",
        "element": "Anemo",
        "rarity": 4,
        "ascendStat": "eleMas",
        "matBoss": "Maguu Kenki",
        "matFlower": "Crystal Marrow",
        "matEnemy": "Whopperflowers",
        "matMastery": "Light",
        "matTrounce": "Gilded Scale",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/2\/22\/Sayu_Icon.png",
        "region": "Inazuma",
        "release": "August 10, 2021",
        "patch": "2.0",
        "hpBase": 993.8522,
        "atkBase": 20.4792,
        "defBase": 62.432476,
        "hpMaxAsc": 3555.9854,
        "atkMaxAsc": 73.27593,
        "defMaxAsc": 223.38225
    },
    "Shenhe": {
        "name": "Shenhe",
        "weapon": "Polearm",
        "element": "Cryo",
        "rarity": 5,
        "ascendStat": "atk_",
        "matBoss": "Vishap Duo",
        "matFlower": "Qingxin",
        "matEnemy": "Whopperflowers",
        "matMastery": "Prosperity",
        "matTrounce": "Hellfire Butterfly",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/a\/af\/Shenhe_Icon.png",
        "region": "Liyue",
        "release": "January 05, 2022",
        "patch": "2.4",
        "hpBase": 1011.47253,
        "atkBase": 23.6474,
        "defBase": 64.6164,
        "hpMaxAsc": 4153.653,
        "atkMaxAsc": 97.10191,
        "defMaxAsc": 265.356
    },
    "ShikanoinHeizou": {
        "name": "Shikanoin Heizou",
        "weapon": "Catalyst",
        "element": "Anemo",
        "rarity": 4,
        "ascendStat": "anemo_dmg_",
        "matBoss": "Ruin Serpent",
        "matFlower": "Onikabuto",
        "matEnemy": "Treasure Hoarders",
        "matMastery": "Transience",
        "matTrounce": "The Meaning of Aeons",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/2\/20\/Shikanoin_Heizou_Icon.png",
        "region": "Inazuma",
        "release": "July 13, 2022",
        "patch": "2.8",
        "hpBase": 893.5552,
        "atkBase": 18.87648,
        "defBase": 57.33945,
        "hpMaxAsc": 3197.1245,
        "atkMaxAsc": 67.54129,
        "defMaxAsc": 205.1595
    },
    "Sucrose": {
        "name": "Sucrose",
        "weapon": "Catalyst",
        "element": "Anemo",
        "rarity": 4,
        "ascendStat": "anemo_dmg_",
        "matBoss": "Anemo Cube",
        "matFlower": "Windwheel Aster",
        "matEnemy": "Whopperflowers",
        "matMastery": "Freedom",
        "matTrounce": "Spirit Locket of Boreas",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/0\/0e\/Sucrose_Icon.png",
        "region": "Mondstadt",
        "release": "September 28, 2020",
        "patch": "1.0",
        "hpBase": 775.02234,
        "atkBase": 14.2464,
        "defBase": 58.94175,
        "hpMaxAsc": 2773.016,
        "atkMaxAsc": 50.97456,
        "defMaxAsc": 210.8925
    },
    "Tartaglia": {
        "name": "Tartaglia",
        "weapon": "Bow",
        "element": "Hydro",
        "rarity": 5,
        "ascendStat": "hydro_dmg_",
        "matBoss": "Oceanid",
        "matFlower": "Starconch",
        "matEnemy": "Fatui",
        "matMastery": "Freedom",
        "matTrounce": "Shard of a Foul Legacy",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/8\/85\/Tartaglia_Icon.png",
        "region": "Snezhnaya",
        "release": "November 11, 2020",
        "patch": "1.1",
        "hpBase": 1020.0524,
        "atkBase": 23.4612,
        "defBase": 63.4198,
        "hpMaxAsc": 4188.8867,
        "atkMaxAsc": 96.33733,
        "defMaxAsc": 260.442
    },
    "Thoma": {
        "name": "Thoma",
        "weapon": "Polearm",
        "element": "Pyro",
        "rarity": 4,
        "ascendStat": "atk_",
        "matBoss": "Pyro Cube",
        "matFlower": "Fluorescent Fungus",
        "matEnemy": "Treasure Hoarders",
        "matMastery": "Transience",
        "matTrounce": "Hellfire Butterfly",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/5\/5b\/Thoma_Icon.png",
        "region": "Inazuma",
        "release": "November 02, 2021",
        "patch": "2.2",
        "hpBase": 866.2015,
        "atkBase": 16.9176,
        "defBase": 62.9475,
        "hpMaxAsc": 3099.2532,
        "atkMaxAsc": 60.53229,
        "defMaxAsc": 225.225
    },
    "Tighnari": {
        "name": "Tighnari",
        "weapon": "Bow",
        "element": "Dendro",
        "rarity": 5,
        "ascendStat": "dendro_dmg_",
        "matBoss": "Dendro Bird",
        "matFlower": "Nilotpala Lotus",
        "matEnemy": "Fungi",
        "matMastery": "Admonition",
        "matTrounce": "The Meaning of Aeons",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/8\/87\/Tighnari_Icon.png",
        "region": "Sumeru",
        "release": "August 24, 2022",
        "patch": "3.0",
        "hpBase": 844.64154,
        "atkBase": 20.8544,
        "defBase": 49.0606,
        "hpMaxAsc": 3468.5547,
        "atkMaxAsc": 85.63319,
        "defMaxAsc": 201.474
    },
    "TravelerAnemo": {
        "name": "Traveler: Anemo",
        "weapon": "Sword",
        "element": "Anemo",
        "rarity": 4,
        "ascendStat": "atk_",
        "matFlower": "Windwheel Aster",
        "matEnemy": "Hilichurls",
        "matTalentEnemy": "Samachurls",
        "matMastery": "Resistance",
        "matTrounce": "Dvalin's Sigh",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/5\/59\/Traveler_Icon.png",
        "region": "",
        "release": "September 28, 2020",
        "patch": "1.0",
        "hpBase": 911.791,
        "atkBase": 17.808,
        "defBase": 57.225,
        "hpMaxAsc": 3262.3718,
        "atkMaxAsc": 63.7182,
        "defMaxAsc": 204.75
    },
    "TravelerGeo": {
        "name": "Traveler: Geo",
        "weapon": "Sword",
        "element": "Geo",
        "rarity": 4,
        "ascendStat": "atk_",
        "matFlower": "Windwheel Aster",
        "matEnemy": "Hilichurls",
        "matTalentEnemy": "Hilichurl Archers",
        "matMastery": "Diligence",
        "matTrounce": "Tail of Boreas",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/5\/59\/Traveler_Icon.png",
        "region": "",
        "release": "September 28, 2020",
        "patch": "1.0",
        "hpBase": 911.791,
        "atkBase": 17.808,
        "defBase": 57.225,
        "hpMaxAsc": 3262.3718,
        "atkMaxAsc": 63.7182,
        "defMaxAsc": 204.75
    },
    "TravelerElectro": {
        "name": "Traveler: Electro",
        "weapon": "Sword",
        "element": "Electro",
        "rarity": 4,
        "ascendStat": "atk_",
        "matFlower": "Windwheel Aster",
        "matEnemy": "Hilichurls",
        "matTalentEnemy": "Nobushi",
        "matMastery": "Light",
        "matTrounce": "Dragon Lord's Crown",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/5\/59\/Traveler_Icon.png",
        "region": "",
        "release": "September 28, 2020",
        "patch": "1.0",
        "hpBase": 911.791,
        "atkBase": 17.808,
        "defBase": 57.225,
        "hpMaxAsc": 3262.3718,
        "atkMaxAsc": 63.7182,
        "defMaxAsc": 204.75
    },
    "TravelerDendro": {
        "name": "Traveler: Dendro",
        "weapon": "Sword",
        "element": "Dendro",
        "rarity": 4,
        "ascendStat": "atk_",
        "matFlower": "Windwheel Aster",
        "matEnemy": "Hilichurls",
        "matTalentEnemy": "Fungi",
        "matMastery": "Praxis",
        "matTrounce": "Mudra of the Malefic General",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/5\/59\/Traveler_Icon.png",
        "region": "",
        "release": "September 28, 2020",
        "patch": "1.0",
        "hpBase": 911.791,
        "atkBase": 17.808,
        "defBase": 57.225,
        "hpMaxAsc": 3262.3718,
        "atkMaxAsc": 63.7182,
        "defMaxAsc": 204.75
    },
    "Venti": {
        "name": "Venti",
        "weapon": "Bow",
        "element": "Anemo",
        "rarity": 5,
        "ascendStat": "enerRech_",
        "matBoss": "Anemo Cube",
        "matFlower": "Cecilia",
        "matEnemy": "Slimes",
        "matMastery": "Ballad",
        "matTrounce": "Tail of Boreas",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/f\/f1\/Venti_Icon.png",
        "region": "Mondstadt",
        "release": "September 28, 2020",
        "patch": "1.0",
        "hpBase": 819.8552,
        "atkBase": 20.482,
        "defBase": 52.0521,
        "hpMaxAsc": 3366.7688,
        "atkMaxAsc": 84.10402,
        "defMaxAsc": 213.759
    },
    "Wanderer": {
        "name": "Wanderer",
        "weapon": "Catalyst",
        "element": "Anemo",
        "rarity": 5,
        "ascendStat": "critRate_",
        "matBoss": "Aeonblight",
        "matFlower": "Rukkhashava Mushrooms",
        "matEnemy": "Nobushi",
        "matMastery": "Praxis",
        "matTrounce": "Daka's Bell",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/f\/f8\/Wanderer_Icon.png",
        "region": "Sumeru",
        "release": "December 07, 2022",
        "patch": "3.3",
        "hpBase": 791.2556,
        "atkBase": 25.5094,
        "defBase": 47.2657,
        "hpMaxAsc": 3249.3232,
        "atkMaxAsc": 104.747734,
        "defMaxAsc": 194.103
    },
    "Xiangling": {
        "name": "Xiangling",
        "weapon": "Polearm",
        "element": "Pyro",
        "rarity": 4,
        "ascendStat": "eleMas",
        "matBoss": "Pyro Plant",
        "matFlower": "Jueyun Chili",
        "matEnemy": "Slimes",
        "matMastery": "Diligence",
        "matTrounce": "Dvalin's Claw",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/3\/39\/Xiangling_Icon.png",
        "region": "Liyue",
        "release": "September 28, 2020",
        "patch": "1.0",
        "hpBase": 911.791,
        "atkBase": 18.87648,
        "defBase": 56.0805,
        "hpMaxAsc": 3262.3718,
        "atkMaxAsc": 67.54129,
        "defMaxAsc": 200.655
    },
    "Xiao": {
        "name": "Xiao",
        "weapon": "Polearm",
        "element": "Anemo",
        "rarity": 5,
        "ascendStat": "critRate_",
        "matBoss": "Geovishap",
        "matFlower": "Qingxin",
        "matEnemy": "Slimes",
        "matMastery": "Prosperity",
        "matTrounce": "Shadow of the Warrior",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/f\/fd\/Xiao_Icon.png",
        "region": "Liyue",
        "release": "February 03, 2021",
        "patch": "1.3",
        "hpBase": 991.4528,
        "atkBase": 27.1852,
        "defBase": 62.2232,
        "hpMaxAsc": 4071.4412,
        "atkMaxAsc": 111.628975,
        "defMaxAsc": 255.528
    },
    "Xingqiu": {
        "name": "Xingqiu",
        "weapon": "Sword",
        "element": "Hydro",
        "rarity": 4,
        "ascendStat": "atk_",
        "matBoss": "Oceanid",
        "matFlower": "Silk Flower",
        "matEnemy": "Hilichurls",
        "matMastery": "Gold",
        "matTrounce": "Tail of Boreas",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/d\/d4\/Xingqiu_Icon.png",
        "region": "Liyue",
        "release": "September 28, 2020",
        "patch": "1.0",
        "hpBase": 857.08356,
        "atkBase": 16.9176,
        "defBase": 63.51975,
        "hpMaxAsc": 3066.6296,
        "atkMaxAsc": 60.53229,
        "defMaxAsc": 227.2725
    },
    "Xinyan": {
        "name": "Xinyan",
        "weapon": "Claymore",
        "element": "Pyro",
        "rarity": 4,
        "ascendStat": "atk_",
        "matBoss": "Pyro Plant",
        "matFlower": "Violetgrass",
        "matEnemy": "Treasure Hoarders",
        "matMastery": "Gold",
        "matTrounce": "Tusk of Monoceros Caeli",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/2\/24\/Xinyan_Icon.png",
        "region": "Liyue",
        "release": "December 01, 2020",
        "patch": "1.1",
        "hpBase": 939.1447,
        "atkBase": 20.83536,
        "defBase": 66.95325,
        "hpMaxAsc": 3360.243,
        "atkMaxAsc": 74.55029,
        "defMaxAsc": 239.5575
    },
    "YaeMiko": {
        "name": "Yae Miko",
        "weapon": "Catalyst",
        "element": "Electro",
        "rarity": 5,
        "ascendStat": "critRate_",
        "matBoss": "Vishap Duo",
        "matFlower": "Sea Ganoderma",
        "matEnemy": "Nobushi",
        "matMastery": "Light",
        "matTrounce": "The Meaning of Aeons",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/b\/ba\/Yae_Miko_Icon.png",
        "region": "Inazuma",
        "release": "February 16, 2022",
        "patch": "2.5",
        "hpBase": 807.46204,
        "atkBase": 26.4404,
        "defBase": 44.2742,
        "hpMaxAsc": 3315.8757,
        "atkMaxAsc": 108.57064,
        "defMaxAsc": 181.818
    },
    "Yanfei": {
        "name": "Yanfei",
        "weapon": "Catalyst",
        "element": "Pyro",
        "rarity": 4,
        "ascendStat": "pyro_dmg_",
        "matBoss": "Geovishap",
        "matFlower": "Noctilucous Jade",
        "matEnemy": "Treasure Hoarders",
        "matMastery": "Gold",
        "matTrounce": "Bloodjade Branch",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/5\/54\/Yanfei_Icon.png",
        "region": "Liyue",
        "release": "April 28, 2021",
        "patch": "1.5",
        "hpBase": 784.14026,
        "atkBase": 20.12304,
        "defBase": 49.2135,
        "hpMaxAsc": 2805.64,
        "atkMaxAsc": 72.001564,
        "defMaxAsc": 176.085
    },
    "Yaoyao": {
        "name": "Yaoyao",
        "weapon": "Polearm",
        "element": "Dendro",
        "rarity": 4,
        "ascendStat": "hp_",
        "matBoss": "Dendro Cube",
        "matFlower": "Jueyun Chili",
        "matEnemy": "Slimes",
        "matMastery": "Diligence",
        "matTrounce": "Daka's Bell",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/8\/83\/Yaoyao_Icon.png",
        "region": "Liyue",
        "release": "January 18, 2023",
        "patch": "3.4",
        "hpBase": 1030.3239,
        "atkBase": 17.808,
        "defBase": 62.9475,
        "hpMaxAsc": 3686.4802,
        "atkMaxAsc": 63.7182,
        "defMaxAsc": 225.225
    },
    "Yelan": {
        "name": "Yelan",
        "weapon": "Bow",
        "element": "Hydro",
        "rarity": 5,
        "ascendStat": "critRate_",
        "matBoss": "Ruin Serpent",
        "matFlower": "Starconch",
        "matEnemy": "Fatui",
        "matMastery": "Prosperity",
        "matTrounce": "Gilded Scale",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/d\/d3\/Yelan_Icon.png",
        "region": "Liyue",
        "release": "May 31, 2022",
        "patch": "2.7",
        "hpBase": 1124.9176,
        "atkBase": 18.9924,
        "defBase": 42.65879,
        "hpMaxAsc": 4619.52,
        "atkMaxAsc": 77.987366,
        "defMaxAsc": 175.1841
    },
    "Yoimiya": {
        "name": "Yoimiya",
        "weapon": "Bow",
        "element": "Pyro",
        "rarity": 5,
        "ascendStat": "critRate_",
        "matBoss": "Pyro Cube",
        "matFlower": "Naku Weed",
        "matEnemy": "Samachurls",
        "matMastery": "Transience",
        "matTrounce": "Dragon Lord's Crown",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/8\/88\/Yoimiya_Icon.png",
        "region": "Inazuma",
        "release": "August 10, 2021",
        "patch": "2.0",
        "hpBase": 791.2556,
        "atkBase": 25.137,
        "defBase": 47.864,
        "hpMaxAsc": 3249.3232,
        "atkMaxAsc": 103.21857,
        "defMaxAsc": 196.56
    },
    "YunJin": {
        "name": "Yun Jin",
        "weapon": "Polearm",
        "element": "Geo",
        "rarity": 4,
        "ascendStat": "enerRech_",
        "matBoss": "Wolflord",
        "matFlower": "Glaze Lily",
        "matEnemy": "Hilichurls",
        "matMastery": "Diligence",
        "matTrounce": "Ashen Heart",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/9\/9c\/Yun_Jin_Icon.png",
        "region": "Liyue",
        "release": "January 05, 2022",
        "patch": "2.4",
        "hpBase": 893.5552,
        "atkBase": 16.0272,
        "defBase": 61.5741,
        "hpMaxAsc": 3197.1245,
        "atkMaxAsc": 57.34638,
        "defMaxAsc": 220.311
    },
    "Zhongli": {
        "name": "Zhongli",
        "weapon": "Polearm",
        "element": "Geo",
        "rarity": 5,
        "ascendStat": "geo_dmg_",
        "matBoss": "Geo Cube",
        "matFlower": "Cor Lapis",
        "matEnemy": "Slimes",
        "matMastery": "Gold",
        "matTrounce": "Tusk of Monoceros Caeli",
        "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/a\/a6\/Zhongli_Icon.png",
        "region": "Liyue",
        "release": "December 01, 2020",
        "patch": "1.1",
        "hpBase": 1143.984,
        "atkBase": 19.551,
        "defBase": 57.4368,
        "hpMaxAsc": 4697.817,
        "atkMaxAsc": 80.2811,
        "defMaxAsc": 235.872
    }
};
