export default {
  '1': {
    matEnemyCount: 6,
    matEnemyQuality: 1,
    matDomainCount: 3,
    matDomainQuality: 2,
    matTrounceCount: 0,
    matCrownCount: 0,
  },
  '2': {
    matEnemyCount: 3,
    matEnemyQuality: 2,
    matDomainCount: 2,
    matDomainQuality: 3,
    matTrounceCount: 0,
    matCrownCount: 0,
  },
  '3': {
    matEnemyCount: 4,
    matEnemyQuality: 2,
    matDomainCount: 4,
    matDomainQuality: 3,
    matTrounceCount: 0,
    matCrownCount: 0,
  },
  '4': {
    matEnemyCount: 6,
    matEnemyQuality: 2,
    matDomainCount: 6,
    matDomainQuality: 3,
    matTrounceCount: 0,
    matCrownCount: 0,
  },
  '5': {
    matEnemyCount: 9,
    matEnemyQuality: 2,
    matDomainCount: 9,
    matDomainQuality: 3,
    matTrounceCount: 0,
    matCrownCount: 0,
  },
  '6': {
    matEnemyCount: 4,
    matEnemyQuality: 3,
    matDomainCount: 4,
    matDomainQuality: 4,
    matTrounceCount: 1,
    matCrownCount: 0,
  },
  '7': {
    matEnemyCount: 6,
    matEnemyQuality: 3,
    matDomainCount: 6,
    matDomainQuality: 4,
    matTrounceCount: 1,
    matCrownCount: 0,
  },
  '8': {
    matEnemyCount: 9,
    matEnemyQuality: 3,
    matDomainCount: 12,
    matDomainQuality: 4,
    matTrounceCount: 2,
    matCrownCount: 0,
  },
  '9': {
    matEnemyCount: 12,
    matEnemyQuality: 3,
    matDomainCount: 16,
    matDomainQuality: 4,
    matTrounceCount: 2,
    matCrownCount: 1,
  },
  '10': {
    matEnemyCount: 0,
    matEnemyQuality: 3,
    matDomainCount: 0,
    matDomainQuality: 4,
    matTrounceCount: 0,
    matCrownCount: 0,
  },
};
