export default {
    "AThousandFloatingDreams": {
        "name": "A Thousand Floating Dreams",
        "quality": 5,
        "type": "Catalyst",
        "matForgery": "Plate",
        "matStrongEnemy": "Primal Constructs",
        "matWeakEnemy": "Fungi",
        "baseATK": 44,
        "stat": "eleMas",
        "baseStat": 58
    },
    "AmosBow": {
        "name": "Amos' Bow",
        "quality": 5,
        "type": "Bow",
        "matForgery": "Cuffs",
        "matStrongEnemy": "Ruin Guards",
        "matWeakEnemy": "Slimes",
        "baseATK": 46,
        "stat": "atk_",
        "baseStat": 10.8
    },
    "AquaSimulacra": {
        "name": "Aqua Simulacra",
        "quality": 5,
        "type": "Bow",
        "matForgery": "Pillar",
        "matStrongEnemy": "Black Serpents",
        "matWeakEnemy": "Specters",
        "baseATK": 44,
        "stat": "critDMG_",
        "baseStat": 19.2
    },
    "AquilaFavonia": {
        "name": "Aquila Favonia",
        "quality": 5,
        "type": "Sword",
        "matForgery": "Tile",
        "matStrongEnemy": "Big Hilichurls",
        "matWeakEnemy": "Hilichurl Archers",
        "baseATK": 48,
        "stat": "physical_dmg_",
        "baseStat": 9
    },
    "BeaconOfTheReedSea": {
        "name": "Beacon of the Reed Sea",
        "quality": 5,
        "type": "Claymore",
        "matForgery": "Scarab",
        "matStrongEnemy": "Consecrated Beasts",
        "matWeakEnemy": "Eremites",
        "baseATK": 46,
        "stat": "critRate_",
        "baseStat": 7.2
    },
    "CalamityQueller": {
        "name": "Calamity Queller",
        "quality": 5,
        "type": "Polearm",
        "matForgery": "Balls",
        "matStrongEnemy": "Fatui Cicin Mages",
        "matWeakEnemy": "Whopperflowers",
        "baseATK": 49,
        "stat": "atk_",
        "baseStat": 3.6
    },
    "ElegyForTheEnd": {
        "name": "Elegy for the End",
        "quality": 5,
        "type": "Bow",
        "matForgery": "Tooth",
        "matStrongEnemy": "Big Hilichurls",
        "matWeakEnemy": "Fatui",
        "baseATK": 46,
        "stat": "enerRech_",
        "baseStat": 12
    },
    "EngulfingLightning": {
        "name": "Engulfing Lightning",
        "quality": 5,
        "type": "Polearm",
        "matForgery": "Mask",
        "matStrongEnemy": "Ruin Sentinels",
        "matWeakEnemy": "Nobushi",
        "baseATK": 46,
        "stat": "enerRech_",
        "baseStat": 12
    },
    "EverlastingMoonglow": {
        "name": "Everlasting Moonglow",
        "quality": 5,
        "type": "Catalyst",
        "matForgery": "Branch",
        "matStrongEnemy": "Mirror Maidens",
        "matWeakEnemy": "Specters",
        "baseATK": 46,
        "stat": "hp_",
        "baseStat": 10.8
    },
    "FreedomSworn": {
        "name": "Freedom-Sworn",
        "quality": 5,
        "type": "Sword",
        "matForgery": "Cuffs",
        "matStrongEnemy": "Ruin Guards",
        "matWeakEnemy": "Samachurls",
        "baseATK": 46,
        "stat": "eleMas",
        "baseStat": 43
    },
    "HaranGeppakuFutsu": {
        "name": "Haran Geppaku Futsu",
        "quality": 5,
        "type": "Sword",
        "matForgery": "Claw",
        "matStrongEnemy": "Black Serpents",
        "matWeakEnemy": "Nobushi",
        "baseATK": 46,
        "stat": "critRate_",
        "baseStat": 7.2
    },
    "HuntersPath": {
        "name": "Hunter's Path",
        "quality": 5,
        "type": "Bow",
        "matForgery": "Scarab",
        "matStrongEnemy": "Activated Fungi",
        "matWeakEnemy": "Eremites",
        "baseATK": 44,
        "stat": "critRate_",
        "baseStat": 9.6
    },
    "JadefallsSplendor": {
        "name": "Jadefall's Splendor",
        "quality": 5,
        "type": "Catalyst",
        "matForgery": "Pillar",
        "matStrongEnemy": "Hilichurl Rogues",
        "matWeakEnemy": "Fungi",
        "baseATK": 46,
        "stat": "hp_",
        "baseStat": 10.8
    },
    "KagurasVerity": {
        "name": "Kagura's Verity",
        "quality": 5,
        "type": "Catalyst",
        "matForgery": "Mask",
        "matStrongEnemy": "Riftwolves",
        "matWeakEnemy": "Specters",
        "baseATK": 46,
        "stat": "critDMG_",
        "baseStat": 14.4
    },
    "KeyOfKhajNisut": {
        "name": "Key of Khaj-Nisut",
        "quality": 5,
        "type": "Sword",
        "matForgery": "Talisman",
        "matStrongEnemy": "Primal Constructs",
        "matWeakEnemy": "Eremites",
        "baseATK": 44,
        "stat": "hp_",
        "baseStat": 14.4
    },
    "LightOfFoliarIncision": {
        "name": "Light of Foliar Incision",
        "quality": 5,
        "type": "Sword",
        "matForgery": "Talisman",
        "matStrongEnemy": "Consecrated Beasts",
        "matWeakEnemy": "Eremites",
        "baseATK": 44,
        "stat": "critDMG_",
        "baseStat": 19.2
    },
    "LostPrayerToTheSacredWinds": {
        "name": "Lost Prayer to the Sacred Winds",
        "quality": 5,
        "type": "Catalyst",
        "matForgery": "Cuffs",
        "matStrongEnemy": "Ruin Guards",
        "matWeakEnemy": "Slimes",
        "baseATK": 46,
        "stat": "critRate_",
        "baseStat": 7.2
    },
    "MemoryOfDust": {
        "name": "Memory of Dust",
        "quality": 5,
        "type": "Catalyst",
        "matForgery": "Piece",
        "matStrongEnemy": "Geovishaps",
        "matWeakEnemy": "Hilichurls",
        "baseATK": 46,
        "stat": "atk_",
        "baseStat": 10.8
    },
    "MistsplitterReforged": {
        "name": "Mistsplitter Reforged",
        "quality": 5,
        "type": "Sword",
        "matForgery": "Branch",
        "matStrongEnemy": "Ruin Sentinels",
        "matWeakEnemy": "Nobushi",
        "baseATK": 48,
        "stat": "critDMG_",
        "baseStat": 9.6
    },
    "PolarStar": {
        "name": "Polar Star",
        "quality": 5,
        "type": "Bow",
        "matForgery": "Mask",
        "matStrongEnemy": "Riftwolves",
        "matWeakEnemy": "Specters",
        "baseATK": 46,
        "stat": "critRate_",
        "baseStat": 7.2
    },
    "PrimordialJadeCutter": {
        "name": "Primordial Jade Cutter",
        "quality": 5,
        "type": "Sword",
        "matForgery": "Balls",
        "matStrongEnemy": "Fatui Cicin Mages",
        "matWeakEnemy": "Treasure Hoarders",
        "baseATK": 44,
        "stat": "critRate_",
        "baseStat": 9.6
    },
    "PrimordialJadeWingedSpear": {
        "name": "Primordial Jade Winged-Spear",
        "quality": 5,
        "type": "Polearm",
        "matForgery": "Pillar",
        "matStrongEnemy": "Fatui Agents",
        "matWeakEnemy": "Fatui",
        "baseATK": 48,
        "stat": "critRate_",
        "baseStat": 4.8
    },
    "RedhornStonethresher": {
        "name": "Redhorn Stone\u00adthresher",
        "quality": 5,
        "type": "Claymore",
        "matForgery": "Claw",
        "matStrongEnemy": "Riftwolves",
        "matWeakEnemy": "Nobushi",
        "baseATK": 44,
        "stat": "critDMG_",
        "baseStat": 19.2
    },
    "SkywardAtlas": {
        "name": "Skyward Atlas",
        "quality": 5,
        "type": "Catalyst",
        "matForgery": "Tooth",
        "matStrongEnemy": "Abyss Mages",
        "matWeakEnemy": "Hilichurl Archers",
        "baseATK": 48,
        "stat": "atk_",
        "baseStat": 7.2
    },
    "SkywardBlade": {
        "name": "Skyward Blade",
        "quality": 5,
        "type": "Sword",
        "matForgery": "Tooth",
        "matStrongEnemy": "Abyss Mages",
        "matWeakEnemy": "Slimes",
        "baseATK": 46,
        "stat": "enerRech_",
        "baseStat": 12
    },
    "SkywardHarp": {
        "name": "Skyward Harp",
        "quality": 5,
        "type": "Bow",
        "matForgery": "Tooth",
        "matStrongEnemy": "Abyss Mages",
        "matWeakEnemy": "Hilichurl Archers",
        "baseATK": 48,
        "stat": "critRate_",
        "baseStat": 4.8
    },
    "SkywardPride": {
        "name": "Skyward Pride",
        "quality": 5,
        "type": "Claymore",
        "matForgery": "Tooth",
        "matStrongEnemy": "Abyss Mages",
        "matWeakEnemy": "Slimes",
        "baseATK": 48,
        "stat": "enerRech_",
        "baseStat": 8
    },
    "SkywardSpine": {
        "name": "Skyward Spine",
        "quality": 5,
        "type": "Polearm",
        "matForgery": "Cuffs",
        "matStrongEnemy": "Ruin Guards",
        "matWeakEnemy": "Samachurls",
        "baseATK": 48,
        "stat": "enerRech_",
        "baseStat": 8
    },
    "SongOfBrokenPines": {
        "name": "Song of Broken Pines",
        "quality": 5,
        "type": "Claymore",
        "matForgery": "Tile",
        "matStrongEnemy": "Big Hilichurls",
        "matWeakEnemy": "Hilichurls",
        "baseATK": 49,
        "stat": "physical_dmg_",
        "baseStat": 4.5
    },
    "StaffOfHoma": {
        "name": "Staff of Homa",
        "quality": 5,
        "type": "Polearm",
        "matForgery": "Piece",
        "matStrongEnemy": "Abyss Mages",
        "matWeakEnemy": "Slimes",
        "baseATK": 46,
        "stat": "critDMG_",
        "baseStat": 14.4
    },
    "StaffOfTheScarletSands": {
        "name": "Staff of the Scarlet Sands",
        "quality": 5,
        "type": "Polearm",
        "matForgery": "Plate",
        "matStrongEnemy": "Ruin Drakes",
        "matWeakEnemy": "Fungi",
        "baseATK": 44,
        "stat": "critRate_",
        "baseStat": 9.6
    },
    "SummitShaper": {
        "name": "Summit Shaper",
        "quality": 5,
        "type": "Sword",
        "matForgery": "Pillar",
        "matStrongEnemy": "Fatui Agents",
        "matWeakEnemy": "Hilichurls",
        "baseATK": 46,
        "stat": "atk_",
        "baseStat": 10.8
    },
    "TheUnforged": {
        "name": "The Unforged",
        "quality": 5,
        "type": "Claymore",
        "matForgery": "Balls",
        "matStrongEnemy": "Fatui Cicin Mages",
        "matWeakEnemy": "Treasure Hoarders",
        "baseATK": 46,
        "stat": "atk_",
        "baseStat": 10.8
    },
    "ThunderingPulse": {
        "name": "Thundering Pulse",
        "quality": 5,
        "type": "Bow",
        "matForgery": "Claw",
        "matStrongEnemy": "Mirror Maidens",
        "matWeakEnemy": "Hilichurl Archers",
        "baseATK": 46,
        "stat": "critDMG_",
        "baseStat": 14.4
    },
    "TulaytullahsRemembrance": {
        "name": "Tulay\u00adtullah's Remem\u00adbrance",
        "quality": 5,
        "type": "Catalyst",
        "matForgery": "Scarab",
        "matStrongEnemy": "Activated Fungi",
        "matWeakEnemy": "Fungi",
        "baseATK": 48,
        "stat": "critDMG_",
        "baseStat": 9.6
    },
    "VortexVanquisher": {
        "name": "Vortex Vanquisher",
        "quality": 5,
        "type": "Polearm",
        "matForgery": "Piece",
        "matStrongEnemy": "Geovishaps",
        "matWeakEnemy": "Treasure Hoarders",
        "baseATK": 46,
        "stat": "atk_",
        "baseStat": 10.8
    },
    "WolfsGravestone": {
        "name": "Wolf's Gravestone",
        "quality": 5,
        "type": "Claymore",
        "matForgery": "Cuffs",
        "matStrongEnemy": "Ruin Guards",
        "matWeakEnemy": "Samachurls",
        "baseATK": 46,
        "stat": "atk_",
        "baseStat": 10.8
    },
    "TheCatch": {
        "name": "\"The Catch\"",
        "quality": 4,
        "type": "Polearm",
        "matForgery": "Mask",
        "matStrongEnemy": "Ruin Sentinels",
        "matWeakEnemy": "Specters",
        "baseATK": 42,
        "stat": "enerRech_",
        "baseStat": 10
    },
    "Akuoumaru": {
        "name": "Akuoumaru",
        "quality": 4,
        "type": "Claymore",
        "matForgery": "Branch",
        "matStrongEnemy": "Riftwolves",
        "matWeakEnemy": "Nobushi",
        "baseATK": 42,
        "stat": "atk_",
        "baseStat": 9
    },
    "AlleyHunter": {
        "name": "Alley Hunter",
        "quality": 4,
        "type": "Bow",
        "matForgery": "Cuffs",
        "matStrongEnemy": "Ruin Guards",
        "matWeakEnemy": "Slimes",
        "baseATK": 44,
        "stat": "atk_",
        "baseStat": 6
    },
    "AmenomaKageuchi": {
        "name": "Amenoma Kageuchi",
        "quality": 4,
        "type": "Sword",
        "matForgery": "Branch",
        "matStrongEnemy": "Ruin Sentinels",
        "matWeakEnemy": "Nobushi",
        "baseATK": 41,
        "stat": "atk_",
        "baseStat": 12
    },
    "BlackcliffAgate": {
        "name": "Blackcliff Agate",
        "quality": 4,
        "type": "Catalyst",
        "matForgery": "Pillar",
        "matStrongEnemy": "Fatui Agents",
        "matWeakEnemy": "Samachurls",
        "baseATK": 42,
        "stat": "critDMG_",
        "baseStat": 12
    },
    "BlackcliffLongsword": {
        "name": "Blackcliff Longsword",
        "quality": 4,
        "type": "Sword",
        "matForgery": "Pillar",
        "matStrongEnemy": "Fatui Agents",
        "matWeakEnemy": "Hilichurl Archers",
        "baseATK": 44,
        "stat": "critDMG_",
        "baseStat": 8
    },
    "BlackcliffPole": {
        "name": "Blackcliff Pole",
        "quality": 4,
        "type": "Polearm",
        "matForgery": "Balls",
        "matStrongEnemy": "Fatui Cicin Mages",
        "matWeakEnemy": "Fatui",
        "baseATK": 42,
        "stat": "critDMG_",
        "baseStat": 12
    },
    "BlackcliffSlasher": {
        "name": "Blackcliff Slasher",
        "quality": 4,
        "type": "Claymore",
        "matForgery": "Balls",
        "matStrongEnemy": "Fatui Cicin Mages",
        "matWeakEnemy": "Fatui",
        "baseATK": 42,
        "stat": "critDMG_",
        "baseStat": 12
    },
    "BlackcliffWarbow": {
        "name": "Blackcliff Warbow",
        "quality": 4,
        "type": "Bow",
        "matForgery": "Pillar",
        "matStrongEnemy": "Fatui Agents",
        "matWeakEnemy": "Whopperflowers",
        "baseATK": 44,
        "stat": "critDMG_",
        "baseStat": 8
    },
    "CinnabarSpindle": {
        "name": "Cinnabar Spindle",
        "quality": 4,
        "type": "Sword",
        "matForgery": "Tile",
        "matStrongEnemy": "Ruin Guards",
        "matWeakEnemy": "Hilichurls",
        "baseATK": 41,
        "stat": "def_",
        "baseStat": 15
    },
    "CompoundBow": {
        "name": "Compound Bow",
        "quality": 4,
        "type": "Bow",
        "matForgery": "Piece",
        "matStrongEnemy": "Geovishaps",
        "matWeakEnemy": "Fatui",
        "baseATK": 41,
        "stat": "physical_dmg_",
        "baseStat": 15
    },
    "CrescentPike": {
        "name": "Crescent Pike",
        "quality": 4,
        "type": "Polearm",
        "matForgery": "Pillar",
        "matStrongEnemy": "Fatui Agents",
        "matWeakEnemy": "Treasure Hoarders",
        "baseATK": 44,
        "stat": "physical_dmg_",
        "baseStat": 7.5
    },
    "Deathmatch": {
        "name": "Deathmatch",
        "quality": 4,
        "type": "Polearm",
        "matForgery": "Tooth",
        "matStrongEnemy": "Abyss Mages",
        "matWeakEnemy": "Whopperflowers",
        "baseATK": 41,
        "stat": "critRate_",
        "baseStat": 8
    },
    "DodocoTales": {
        "name": "Dodoco Tales",
        "quality": 4,
        "type": "Catalyst",
        "matForgery": "Tooth",
        "matStrongEnemy": "Abyss Mages",
        "matWeakEnemy": "Hilichurls",
        "baseATK": 41,
        "stat": "atk_",
        "baseStat": 12
    },
    "DragonsBane": {
        "name": "Dragon's Bane",
        "quality": 4,
        "type": "Polearm",
        "matForgery": "Balls",
        "matStrongEnemy": "Fatui Cicin Mages",
        "matWeakEnemy": "Samachurls",
        "baseATK": 41,
        "stat": "eleMas",
        "baseStat": 48
    },
    "DragonspineSpear": {
        "name": "Dragonspine Spear",
        "quality": 4,
        "type": "Polearm",
        "matForgery": "Tooth",
        "matStrongEnemy": "Fatui Cicin Mages",
        "matWeakEnemy": "Fatui",
        "baseATK": 41,
        "stat": "physical_dmg_",
        "baseStat": 15
    },
    "EndOfTheLine": {
        "name": "End of the Line",
        "quality": 4,
        "type": "Bow",
        "matForgery": "Scarab",
        "matStrongEnemy": "Activated Fungi",
        "matWeakEnemy": "Fungi",
        "baseATK": 42,
        "stat": "enerRech_",
        "baseStat": 10
    },
    "EyeOfPerception": {
        "name": "Eye of Perception",
        "quality": 4,
        "type": "Catalyst",
        "matForgery": "Balls",
        "matStrongEnemy": "Fatui Cicin Mages",
        "matWeakEnemy": "Hilichurls",
        "baseATK": 41,
        "stat": "atk_",
        "baseStat": 12
    },
    "FadingTwilight": {
        "name": "Fading Twilight",
        "quality": 4,
        "type": "Bow",
        "matForgery": "Piece",
        "matStrongEnemy": "Fatui Agents",
        "matWeakEnemy": "Samachurls",
        "baseATK": 44,
        "stat": "enerRech_",
        "baseStat": 6.7
    },
    "FavoniusCodex": {
        "name": "Favonius Codex",
        "quality": 4,
        "type": "Catalyst",
        "matForgery": "Tile",
        "matStrongEnemy": "Big Hilichurls",
        "matWeakEnemy": "Samachurls",
        "baseATK": 42,
        "stat": "enerRech_",
        "baseStat": 10
    },
    "FavoniusGreatsword": {
        "name": "Favonius Greatsword",
        "quality": 4,
        "type": "Claymore",
        "matForgery": "Cuffs",
        "matStrongEnemy": "Ruin Guards",
        "matWeakEnemy": "Fatui",
        "baseATK": 41,
        "stat": "enerRech_",
        "baseStat": 13.3
    },
    "FavoniusLance": {
        "name": "Favonius Lance",
        "quality": 4,
        "type": "Polearm",
        "matForgery": "Cuffs",
        "matStrongEnemy": "Ruin Guards",
        "matWeakEnemy": "Slimes",
        "baseATK": 44,
        "stat": "enerRech_",
        "baseStat": 6.7
    },
    "FavoniusSword": {
        "name": "Favonius Sword",
        "quality": 4,
        "type": "Sword",
        "matForgery": "Tile",
        "matStrongEnemy": "Big Hilichurls",
        "matWeakEnemy": "Hilichurl Archers",
        "baseATK": 41,
        "stat": "enerRech_",
        "baseStat": 13.3
    },
    "FavoniusWarbow": {
        "name": "Favonius Warbow",
        "quality": 4,
        "type": "Bow",
        "matForgery": "Cuffs",
        "matStrongEnemy": "Ruin Guards",
        "matWeakEnemy": "Whopperflowers",
        "baseATK": 41,
        "stat": "enerRech_",
        "baseStat": 13.3
    },
    "FesteringDesire": {
        "name": "Festering Desire",
        "quality": 4,
        "type": "Sword",
        "matForgery": "Cuffs",
        "matStrongEnemy": "Big Hilichurls",
        "matWeakEnemy": "Fatui",
        "baseATK": 42,
        "stat": "enerRech_",
        "baseStat": 10
    },
    "ForestRegalia": {
        "name": "Forest Regalia",
        "quality": 4,
        "type": "Claymore",
        "matForgery": "Talisman",
        "matStrongEnemy": "Ruin Drakes",
        "matWeakEnemy": "Eremites",
        "baseATK": 44,
        "stat": "enerRech_",
        "baseStat": 6.7
    },
    "Frostbearer": {
        "name": "Frostbearer",
        "quality": 4,
        "type": "Catalyst",
        "matForgery": "Cuffs",
        "matStrongEnemy": "Ruin Guards",
        "matWeakEnemy": "Whopperflowers",
        "baseATK": 42,
        "stat": "atk_",
        "baseStat": 9
    },
    "FruitOfFulfillment": {
        "name": "Fruit of Fulfillment",
        "quality": 4,
        "type": "Catalyst",
        "matForgery": "Plate",
        "matStrongEnemy": "Black Serpents",
        "matWeakEnemy": "Fungi",
        "baseATK": 42,
        "stat": "enerRech_",
        "baseStat": 10
    },
    "HakushinRing": {
        "name": "Hakushin Ring",
        "quality": 4,
        "type": "Catalyst",
        "matForgery": "Branch",
        "matStrongEnemy": "Mirror Maidens",
        "matWeakEnemy": "Samachurls",
        "baseATK": 44,
        "stat": "enerRech_",
        "baseStat": 6.7
    },
    "Hamayumi": {
        "name": "Hamayumi",
        "quality": 4,
        "type": "Bow",
        "matForgery": "Claw",
        "matStrongEnemy": "Mirror Maidens",
        "matWeakEnemy": "Hilichurl Archers",
        "baseATK": 41,
        "stat": "atk_",
        "baseStat": 12
    },
    "IbisPiercer": {
        "name": "Ibis Piercer",
        "quality": 4,
        "type": "Bow",
        "matForgery": "Talisman",
        "matStrongEnemy": "Hilichurl Rogues",
        "matWeakEnemy": "Eremites",
        "baseATK": 44,
        "stat": "atk_",
        "baseStat": 6
    },
    "IronSting": {
        "name": "Iron Sting",
        "quality": 4,
        "type": "Sword",
        "matForgery": "Piece",
        "matStrongEnemy": "Geovishaps",
        "matWeakEnemy": "Whopperflowers",
        "baseATK": 42,
        "stat": "eleMas",
        "baseStat": 36
    },
    "KagotsurubeIsshin": {
        "name": "Kagotsurube Isshin",
        "quality": 4,
        "type": "Sword",
        "matForgery": "Mask",
        "matStrongEnemy": "Black Serpents",
        "matWeakEnemy": "Specters",
        "baseATK": 42,
        "stat": "atk_",
        "baseStat": 9
    },
    "KatsuragikiriNagamasa": {
        "name": "Katsuragi\u00adkiri Nagamasa",
        "quality": 4,
        "type": "Claymore",
        "matForgery": "Claw",
        "matStrongEnemy": "Ruin Sentinels",
        "matWeakEnemy": "Nobushi",
        "baseATK": 42,
        "stat": "enerRech_",
        "baseStat": 10
    },
    "KingsSquire": {
        "name": "King's Squire",
        "quality": 4,
        "type": "Bow",
        "matForgery": "Scarab",
        "matStrongEnemy": "Activated Fungi",
        "matWeakEnemy": "Hilichurl Archers",
        "baseATK": 41,
        "stat": "atk_",
        "baseStat": 12
    },
    "KitainCrossSpear": {
        "name": "Kitain Cross Spear",
        "quality": 4,
        "type": "Polearm",
        "matForgery": "Mask",
        "matStrongEnemy": "Ruin Sentinels",
        "matWeakEnemy": "Treasure Hoarders",
        "baseATK": 44,
        "stat": "eleMas",
        "baseStat": 24
    },
    "LionsRoar": {
        "name": "Lion's Roar",
        "quality": 4,
        "type": "Sword",
        "matForgery": "Pillar",
        "matStrongEnemy": "Fatui Agents",
        "matWeakEnemy": "Treasure Hoarders",
        "baseATK": 42,
        "stat": "atk_",
        "baseStat": 9
    },
    "LithicBlade": {
        "name": "Lithic Blade",
        "quality": 4,
        "type": "Claymore",
        "matForgery": "Pillar",
        "matStrongEnemy": "Fatui Agents",
        "matWeakEnemy": "Hilichurl Archers",
        "baseATK": 42,
        "stat": "atk_",
        "baseStat": 9
    },
    "LithicSpear": {
        "name": "Lithic Spear",
        "quality": 4,
        "type": "Polearm",
        "matForgery": "Piece",
        "matStrongEnemy": "Geovishaps",
        "matWeakEnemy": "Hilichurl Archers",
        "baseATK": 44,
        "stat": "atk_",
        "baseStat": 6
    },
    "LuxuriousSeaLord": {
        "name": "Luxurious Sea-Lord",
        "quality": 4,
        "type": "Claymore",
        "matForgery": "Piece",
        "matStrongEnemy": "Geovishaps",
        "matWeakEnemy": "Slimes",
        "baseATK": 41,
        "stat": "atk_",
        "baseStat": 12
    },
    "MailedFlower": {
        "name": "Mailed Flower",
        "quality": 4,
        "type": "Claymore",
        "matForgery": "Cuffs",
        "matStrongEnemy": "Consecrated Beasts",
        "matWeakEnemy": "Specters",
        "baseATK": 44,
        "stat": "eleMas",
        "baseStat": 24
    },
    "MakhairaAquamarine": {
        "name": "Makhaira Aquamarine",
        "quality": 4,
        "type": "Claymore",
        "matForgery": "Scarab",
        "matStrongEnemy": "Ruin Drakes",
        "matWeakEnemy": "Treasure Hoarders",
        "baseATK": 42,
        "stat": "eleMas",
        "baseStat": 36
    },
    "MappaMare": {
        "name": "Mappa Mare",
        "quality": 4,
        "type": "Catalyst",
        "matForgery": "Piece",
        "matStrongEnemy": "Geovishaps",
        "matWeakEnemy": "Slimes",
        "baseATK": 44,
        "stat": "eleMas",
        "baseStat": 24
    },
    "MissiveWindspear": {
        "name": "Missive Windspear",
        "quality": 4,
        "type": "Polearm",
        "matForgery": "Tooth",
        "matStrongEnemy": "Black Serpents",
        "matWeakEnemy": "Slimes",
        "baseATK": 42,
        "stat": "atk_",
        "baseStat": 9
    },
    "MitternachtsWaltz": {
        "name": "Mitternachts Waltz",
        "quality": 4,
        "type": "Bow",
        "matForgery": "Tile",
        "matStrongEnemy": "Big Hilichurls",
        "matWeakEnemy": "Treasure Hoarders",
        "baseATK": 42,
        "stat": "physical_dmg_",
        "baseStat": 11.3
    },
    "Moonpiercer": {
        "name": "Moonpiercer",
        "quality": 4,
        "type": "Polearm",
        "matForgery": "Plate",
        "matStrongEnemy": "Ruin Drakes",
        "matWeakEnemy": "Fatui",
        "baseATK": 44,
        "stat": "eleMas",
        "baseStat": 24
    },
    "MouunsMoon": {
        "name": "Mouun's Moon",
        "quality": 4,
        "type": "Bow",
        "matForgery": "Claw",
        "matStrongEnemy": "Mirror Maidens",
        "matWeakEnemy": "Specters",
        "baseATK": 44,
        "stat": "atk_",
        "baseStat": 6
    },
    "OathswornEye": {
        "name": "Oathsworn Eye",
        "quality": 4,
        "type": "Catalyst",
        "matForgery": "Branch",
        "matStrongEnemy": "Riftwolves",
        "matWeakEnemy": "Specters",
        "baseATK": 44,
        "stat": "atk_",
        "baseStat": 6
    },
    "Predator": {
        "name": "Predator",
        "quality": 4,
        "type": "Bow",
        "matForgery": "Claw",
        "matStrongEnemy": "Mirror Maidens",
        "matWeakEnemy": "Hilichurl Archers",
        "baseATK": 42,
        "stat": "atk_",
        "baseStat": 9
    },
    "PrototypeAmber": {
        "name": "Prototype Amber",
        "quality": 4,
        "type": "Catalyst",
        "matForgery": "Balls",
        "matStrongEnemy": "Fatui Cicin Mages",
        "matWeakEnemy": "Hilichurl Archers",
        "baseATK": 42,
        "stat": "hp_",
        "baseStat": 9
    },
    "PrototypeArchaic": {
        "name": "Prototype Archaic",
        "quality": 4,
        "type": "Claymore",
        "matForgery": "Piece",
        "matStrongEnemy": "Geovishaps",
        "matWeakEnemy": "Hilichurls",
        "baseATK": 44,
        "stat": "atk_",
        "baseStat": 6
    },
    "PrototypeCrescent": {
        "name": "Prototype Crescent",
        "quality": 4,
        "type": "Bow",
        "matForgery": "Balls",
        "matStrongEnemy": "Fatui Cicin Mages",
        "matWeakEnemy": "Treasure Hoarders",
        "baseATK": 42,
        "stat": "atk_",
        "baseStat": 9
    },
    "PrototypeRancour": {
        "name": "Prototype Rancour",
        "quality": 4,
        "type": "Sword",
        "matForgery": "Balls",
        "matStrongEnemy": "Fatui Cicin Mages",
        "matWeakEnemy": "Fatui",
        "baseATK": 44,
        "stat": "physical_dmg_",
        "baseStat": 7.5
    },
    "PrototypeStarglitter": {
        "name": "Prototype Starglitter",
        "quality": 4,
        "type": "Polearm",
        "matForgery": "Piece",
        "matStrongEnemy": "Geovishaps",
        "matWeakEnemy": "Hilichurls",
        "baseATK": 42,
        "stat": "enerRech_",
        "baseStat": 10
    },
    "Rainslasher": {
        "name": "Rainslasher",
        "quality": 4,
        "type": "Claymore",
        "matForgery": "Balls",
        "matStrongEnemy": "Fatui Cicin Mages",
        "matWeakEnemy": "Samachurls",
        "baseATK": 42,
        "stat": "eleMas",
        "baseStat": 36
    },
    "RoyalBow": {
        "name": "Royal Bow",
        "quality": 4,
        "type": "Bow",
        "matForgery": "Cuffs",
        "matStrongEnemy": "Ruin Guards",
        "matWeakEnemy": "Samachurls",
        "baseATK": 42,
        "stat": "atk_",
        "baseStat": 9
    },
    "RoyalGreatsword": {
        "name": "Royal Greatsword",
        "quality": 4,
        "type": "Claymore",
        "matForgery": "Cuffs",
        "matStrongEnemy": "Ruin Guards",
        "matWeakEnemy": "Slimes",
        "baseATK": 44,
        "stat": "atk_",
        "baseStat": 6
    },
    "RoyalGrimoire": {
        "name": "Royal Grimoire",
        "quality": 4,
        "type": "Catalyst",
        "matForgery": "Tile",
        "matStrongEnemy": "Big Hilichurls",
        "matWeakEnemy": "Fatui",
        "baseATK": 44,
        "stat": "atk_",
        "baseStat": 6
    },
    "RoyalLongsword": {
        "name": "Royal Longsword",
        "quality": 4,
        "type": "Sword",
        "matForgery": "Tile",
        "matStrongEnemy": "Big Hilichurls",
        "matWeakEnemy": "Hilichurl Archers",
        "baseATK": 42,
        "stat": "atk_",
        "baseStat": 9
    },
    "RoyalSpear": {
        "name": "Royal Spear",
        "quality": 4,
        "type": "Polearm",
        "matForgery": "Balls",
        "matStrongEnemy": "Fatui Cicin Mages",
        "matWeakEnemy": "Fatui",
        "baseATK": 44,
        "stat": "atk_",
        "baseStat": 6
    },
    "Rust": {
        "name": "Rust",
        "quality": 4,
        "type": "Bow",
        "matForgery": "Pillar",
        "matStrongEnemy": "Fatui Agents",
        "matWeakEnemy": "Hilichurls",
        "baseATK": 42,
        "stat": "atk_",
        "baseStat": 9
    },
    "SacrificialBow": {
        "name": "Sacrificial Bow",
        "quality": 4,
        "type": "Bow",
        "matForgery": "Tooth",
        "matStrongEnemy": "Abyss Mages",
        "matWeakEnemy": "Slimes",
        "baseATK": 44,
        "stat": "enerRech_",
        "baseStat": 6.7
    },
    "SacrificialFragments": {
        "name": "Sacrificial Fragments",
        "quality": 4,
        "type": "Catalyst",
        "matForgery": "Cuffs",
        "matStrongEnemy": "Ruin Guards",
        "matWeakEnemy": "Treasure Hoarders",
        "baseATK": 41,
        "stat": "eleMas",
        "baseStat": 48
    },
    "SacrificialGreatsword": {
        "name": "Sacrificial Greatsword",
        "quality": 4,
        "type": "Claymore",
        "matForgery": "Tooth",
        "matStrongEnemy": "Abyss Mages",
        "matWeakEnemy": "Hilichurl Archers",
        "baseATK": 44,
        "stat": "enerRech_",
        "baseStat": 6.7
    },
    "SacrificialSword": {
        "name": "Sacrificial Sword",
        "quality": 4,
        "type": "Sword",
        "matForgery": "Cuffs",
        "matStrongEnemy": "Ruin Guards",
        "matWeakEnemy": "Samachurls",
        "baseATK": 41,
        "stat": "enerRech_",
        "baseStat": 13.3
    },
    "SapwoodBlade": {
        "name": "Sapwood Blade",
        "quality": 4,
        "type": "Sword",
        "matForgery": "Talisman",
        "matStrongEnemy": "Ruin Drakes",
        "matWeakEnemy": "Eremites",
        "baseATK": 44,
        "stat": "enerRech_",
        "baseStat": 6.7
    },
    "SerpentSpine": {
        "name": "Serpent Spine",
        "quality": 4,
        "type": "Claymore",
        "matForgery": "Piece",
        "matStrongEnemy": "Geovishaps",
        "matWeakEnemy": "Whopperflowers",
        "baseATK": 42,
        "stat": "critRate_",
        "baseStat": 6
    },
    "SnowTombedStarsilver": {
        "name": "Snow-Tombed Starsilver",
        "quality": 4,
        "type": "Claymore",
        "matForgery": "Tile",
        "matStrongEnemy": "Big Hilichurls",
        "matWeakEnemy": "Slimes",
        "baseATK": 44,
        "stat": "physical_dmg_",
        "baseStat": 7.5
    },
    "SolarPearl": {
        "name": "Solar Pearl",
        "quality": 4,
        "type": "Catalyst",
        "matForgery": "Pillar",
        "matStrongEnemy": "Fatui Agents",
        "matWeakEnemy": "Whopperflowers",
        "baseATK": 42,
        "stat": "critRate_",
        "baseStat": 6
    },
    "SwordOfDescension": {
        "name": "Sword of Descension",
        "quality": 4,
        "type": "Sword",
        "matForgery": "Tooth",
        "matStrongEnemy": "Abyss Mages",
        "matWeakEnemy": "Treasure Hoarders",
        "baseATK": 39,
        "stat": "atk_",
        "baseStat": 7.7
    },
    "TheAlleyFlash": {
        "name": "The Alley Flash",
        "quality": 4,
        "type": "Sword",
        "matForgery": "Tile",
        "matStrongEnemy": "Big Hilichurls",
        "matWeakEnemy": "Samachurls",
        "baseATK": 45,
        "stat": "eleMas",
        "baseStat": 12
    },
    "TheBell": {
        "name": "The Bell",
        "quality": 4,
        "type": "Claymore",
        "matForgery": "Tile",
        "matStrongEnemy": "Big Hilichurls",
        "matWeakEnemy": "Whopperflowers",
        "baseATK": 42,
        "stat": "hp_",
        "baseStat": 9
    },
    "TheBlackSword": {
        "name": "The Black Sword",
        "quality": 4,
        "type": "Sword",
        "matForgery": "Tooth",
        "matStrongEnemy": "Abyss Mages",
        "matWeakEnemy": "Slimes",
        "baseATK": 42,
        "stat": "critRate_",
        "baseStat": 6
    },
    "TheFlute": {
        "name": "The Flute",
        "quality": 4,
        "type": "Sword",
        "matForgery": "Tooth",
        "matStrongEnemy": "Abyss Mages",
        "matWeakEnemy": "Slimes",
        "baseATK": 42,
        "stat": "atk_",
        "baseStat": 9
    },
    "TheStringless": {
        "name": "The Stringless",
        "quality": 4,
        "type": "Bow",
        "matForgery": "Tile",
        "matStrongEnemy": "Big Hilichurls",
        "matWeakEnemy": "Hilichurl Archers",
        "baseATK": 42,
        "stat": "eleMas",
        "baseStat": 36
    },
    "TheViridescentHunt": {
        "name": "The Viridescent Hunt",
        "quality": 4,
        "type": "Bow",
        "matForgery": "Tile",
        "matStrongEnemy": "Big Hilichurls",
        "matWeakEnemy": "Hilichurl Archers",
        "baseATK": 42,
        "stat": "critRate_",
        "baseStat": 6
    },
    "TheWidsith": {
        "name": "The Widsith",
        "quality": 4,
        "type": "Catalyst",
        "matForgery": "Tooth",
        "matStrongEnemy": "Abyss Mages",
        "matWeakEnemy": "Hilichurls",
        "baseATK": 42,
        "stat": "critDMG_",
        "baseStat": 12
    },
    "ToukabouShigure": {
        "name": "Toukabou Shigure",
        "quality": 4,
        "type": "Sword",
        "matForgery": "Claw",
        "matStrongEnemy": "Primal Constructs",
        "matWeakEnemy": "Nobushi",
        "baseATK": 42,
        "stat": "eleMas",
        "baseStat": 36
    },
    "WanderingEvenstar": {
        "name": "Wandering Evenstar",
        "quality": 4,
        "type": "Catalyst",
        "matForgery": "Plate",
        "matStrongEnemy": "Activated Fungi",
        "matWeakEnemy": "Fungi",
        "baseATK": 42,
        "stat": "eleMas",
        "baseStat": 36
    },
    "WavebreakersFin": {
        "name": "Wave\u00adbreaker's Fin",
        "quality": 4,
        "type": "Polearm",
        "matForgery": "Mask",
        "matStrongEnemy": "Riftwolves",
        "matWeakEnemy": "Nobushi",
        "baseATK": 45,
        "stat": "atk_",
        "baseStat": 3
    },
    "Whiteblind": {
        "name": "Whiteblind",
        "quality": 4,
        "type": "Claymore",
        "matForgery": "Pillar",
        "matStrongEnemy": "Fatui Agents",
        "matWeakEnemy": "Treasure Hoarders",
        "baseATK": 42,
        "stat": "def_",
        "baseStat": 11.3
    },
    "WindblumeOde": {
        "name": "Windblume Ode",
        "quality": 4,
        "type": "Bow",
        "matForgery": "Cuffs",
        "matStrongEnemy": "Abyss Mages",
        "matWeakEnemy": "Whopperflowers",
        "baseATK": 42,
        "stat": "eleMas",
        "baseStat": 36
    },
    "WineAndSong": {
        "name": "Wine and Song",
        "quality": 4,
        "type": "Catalyst",
        "matForgery": "Tooth",
        "matStrongEnemy": "Abyss Mages",
        "matWeakEnemy": "Treasure Hoarders",
        "baseATK": 44,
        "stat": "enerRech_",
        "baseStat": 6.7
    },
    "XiphosMoonlight": {
        "name": "Xiphos' Moonlight",
        "quality": 4,
        "type": "Sword",
        "matForgery": "Talisman",
        "matStrongEnemy": "Primal Constructs",
        "matWeakEnemy": "Eremites",
        "baseATK": 42,
        "stat": "eleMas",
        "baseStat": 36
    },
    "BlackTassel": {
        "name": "Black Tassel",
        "quality": 3,
        "type": "Polearm",
        "matForgery": "Piece",
        "matStrongEnemy": "Geovishaps",
        "matWeakEnemy": "Hilichurl Archers",
        "baseATK": 38,
        "stat": "hp_",
        "baseStat": 10.2
    },
    "BloodtaintedGreatsword": {
        "name": "Bloodtainted Greatsword",
        "quality": 3,
        "type": "Claymore",
        "matForgery": "Tooth",
        "matStrongEnemy": "Abyss Mages",
        "matWeakEnemy": "Hilichurl Archers",
        "baseATK": 38,
        "stat": "eleMas",
        "baseStat": 41
    },
    "CoolSteel": {
        "name": "Cool Steel",
        "quality": 3,
        "type": "Sword",
        "matForgery": "Tile",
        "matStrongEnemy": "Big Hilichurls",
        "matWeakEnemy": "Hilichurl Archers",
        "baseATK": 39,
        "stat": "atk_",
        "baseStat": 7.7
    },
    "DarkIronSword": {
        "name": "Dark Iron Sword",
        "quality": 3,
        "type": "Sword",
        "matForgery": "Pillar",
        "matStrongEnemy": "Fatui Agents",
        "matWeakEnemy": "Hilichurls",
        "baseATK": 39,
        "stat": "eleMas",
        "baseStat": 31
    },
    "DebateClub": {
        "name": "Debate Club",
        "quality": 3,
        "type": "Claymore",
        "matForgery": "Balls",
        "matStrongEnemy": "Fatui Cicin Mages",
        "matWeakEnemy": "Hilichurls",
        "baseATK": 39,
        "stat": "atk_",
        "baseStat": 7.7
    },
    "EmeraldOrb": {
        "name": "Emerald Orb",
        "quality": 3,
        "type": "Catalyst",
        "matForgery": "Pillar",
        "matStrongEnemy": "Fatui Agents",
        "matWeakEnemy": "Treasure Hoarders",
        "baseATK": 40,
        "stat": "eleMas",
        "baseStat": 20
    },
    "FerrousShadow": {
        "name": "Ferrous Shadow",
        "quality": 3,
        "type": "Claymore",
        "matForgery": "Tile",
        "matStrongEnemy": "Big Hilichurls",
        "matWeakEnemy": "Whopperflowers",
        "baseATK": 39,
        "stat": "hp_",
        "baseStat": 7.7
    },
    "FilletBlade": {
        "name": "Fillet Blade",
        "quality": 3,
        "type": "Sword",
        "matForgery": "Balls",
        "matStrongEnemy": "Fatui Cicin Mages",
        "matWeakEnemy": "Treasure Hoarders",
        "baseATK": 39,
        "stat": "atk_",
        "baseStat": 7.7
    },
    "Halberd": {
        "name": "Halberd",
        "quality": 3,
        "type": "Polearm",
        "matForgery": "Balls",
        "matStrongEnemy": "Fatui Cicin Mages",
        "matWeakEnemy": "Whopperflowers",
        "baseATK": 40,
        "stat": "atk_",
        "baseStat": 5.1
    },
    "HarbingerOfDawn": {
        "name": "Harbinger of Dawn",
        "quality": 3,
        "type": "Sword",
        "matForgery": "Tooth",
        "matStrongEnemy": "Abyss Mages",
        "matWeakEnemy": "Slimes",
        "baseATK": 39,
        "stat": "critDMG_",
        "baseStat": 10.2
    },
    "MagicGuide": {
        "name": "Magic Guide",
        "quality": 3,
        "type": "Catalyst",
        "matForgery": "Tile",
        "matStrongEnemy": "Big Hilichurls",
        "matWeakEnemy": "Slimes",
        "baseATK": 38,
        "stat": "eleMas",
        "baseStat": 41
    },
    "Messenger": {
        "name": "Messenger",
        "quality": 3,
        "type": "Bow",
        "matForgery": "Balls",
        "matStrongEnemy": "Fatui Cicin Mages",
        "matWeakEnemy": "Treasure Hoarders",
        "baseATK": 40,
        "stat": "critDMG_",
        "baseStat": 6.8
    },
    "OtherworldlyStory": {
        "name": "Otherworldly Story",
        "quality": 3,
        "type": "Catalyst",
        "matForgery": "Cuffs",
        "matStrongEnemy": "Ruin Guards",
        "matWeakEnemy": "Hilichurls",
        "baseATK": 39,
        "stat": "enerRech_",
        "baseStat": 8.5
    },
    "RavenBow": {
        "name": "Raven Bow",
        "quality": 3,
        "type": "Bow",
        "matForgery": "Tile",
        "matStrongEnemy": "Big Hilichurls",
        "matWeakEnemy": "Hilichurl Archers",
        "baseATK": 40,
        "stat": "eleMas",
        "baseStat": 20
    },
    "RecurveBow": {
        "name": "Recurve Bow",
        "quality": 3,
        "type": "Bow",
        "matForgery": "Cuffs",
        "matStrongEnemy": "Ruin Guards",
        "matWeakEnemy": "Samachurls",
        "baseATK": 38,
        "stat": "hp_",
        "baseStat": 10.2
    },
    "SharpshootersOath": {
        "name": "Sharp\u00adshooter's Oath",
        "quality": 3,
        "type": "Bow",
        "matForgery": "Tooth",
        "matStrongEnemy": "Abyss Mages",
        "matWeakEnemy": "Slimes",
        "baseATK": 39,
        "stat": "critDMG_",
        "baseStat": 10.2
    },
    "SkyriderGreatsword": {
        "name": "Skyrider Greatsword",
        "quality": 3,
        "type": "Claymore",
        "matForgery": "Piece",
        "matStrongEnemy": "Geovishaps",
        "matWeakEnemy": "Treasure Hoarders",
        "baseATK": 39,
        "stat": "physical_dmg_",
        "baseStat": 9.6
    },
    "SkyriderSword": {
        "name": "Skyrider Sword",
        "quality": 3,
        "type": "Sword",
        "matForgery": "Piece",
        "matStrongEnemy": "Geovishaps",
        "matWeakEnemy": "Fatui",
        "baseATK": 38,
        "stat": "enerRech_",
        "baseStat": 11.3
    },
    "Slingshot": {
        "name": "Slingshot",
        "quality": 3,
        "type": "Bow",
        "matForgery": "Pillar",
        "matStrongEnemy": "Fatui Agents",
        "matWeakEnemy": "Hilichurls",
        "baseATK": 38,
        "stat": "critRate_",
        "baseStat": 6.8
    },
    "ThrillingTalesOfDragonSlayers": {
        "name": "Thrilling Tales of Dragon Slayers",
        "quality": 3,
        "type": "Catalyst",
        "matForgery": "Tooth",
        "matStrongEnemy": "Abyss Mages",
        "matWeakEnemy": "Samachurls",
        "baseATK": 39,
        "stat": "hp_",
        "baseStat": 7.7
    },
    "TravelersHandySword": {
        "name": "Traveler's Handy Sword",
        "quality": 3,
        "type": "Sword",
        "matForgery": "Cuffs",
        "matStrongEnemy": "Ruin Guards",
        "matWeakEnemy": "Samachurls",
        "baseATK": 40,
        "stat": "def_",
        "baseStat": 6.4
    },
    "TwinNephrite": {
        "name": "Twin Nephrite",
        "quality": 3,
        "type": "Catalyst",
        "matForgery": "Balls",
        "matStrongEnemy": "Fatui Cicin Mages",
        "matWeakEnemy": "Fatui",
        "baseATK": 40,
        "stat": "critRate_",
        "baseStat": 3.4
    },
    "WhiteIronGreatsword": {
        "name": "White Iron Greatsword",
        "quality": 3,
        "type": "Claymore",
        "matForgery": "Cuffs",
        "matStrongEnemy": "Ruin Guards",
        "matWeakEnemy": "Slimes",
        "baseATK": 39,
        "stat": "def_",
        "baseStat": 9.6
    },
    "WhiteTassel": {
        "name": "White Tassel",
        "quality": 3,
        "type": "Polearm",
        "matForgery": "Pillar",
        "matStrongEnemy": "Fatui Agents",
        "matWeakEnemy": "Fatui",
        "baseATK": 39,
        "stat": "critRate_",
        "baseStat": 5.1
    },
    "IronPoint": {
        "name": "Iron Point",
        "quality": 2,
        "type": "Polearm",
        "matForgery": "Cuffs",
        "matStrongEnemy": "Ruin Guards",
        "matWeakEnemy": "Samachurls",
        "baseATK": 33,
        "stat": "",
        "baseStat": 0
    },
    "OldMercsPal": {
        "name": "Old Merc's Pal",
        "quality": 2,
        "type": "Claymore",
        "matForgery": "Tooth",
        "matStrongEnemy": "Abyss Mages",
        "matWeakEnemy": "Slimes",
        "baseATK": 33,
        "stat": "",
        "baseStat": 0
    },
    "PocketGrimoire": {
        "name": "Pocket Grimoire",
        "quality": 2,
        "type": "Catalyst",
        "matForgery": "Tile",
        "matStrongEnemy": "Big Hilichurls",
        "matWeakEnemy": "Hilichurls",
        "baseATK": 33,
        "stat": "",
        "baseStat": 0
    },
    "SeasonedHuntersBow": {
        "name": "Seasoned Hunter's Bow",
        "quality": 2,
        "type": "Bow",
        "matForgery": "Tooth",
        "matStrongEnemy": "Abyss Mages",
        "matWeakEnemy": "Treasure Hoarders",
        "baseATK": 33,
        "stat": "",
        "baseStat": 0
    },
    "SilverSword": {
        "name": "Silver Sword",
        "quality": 2,
        "type": "Sword",
        "matForgery": "Tile",
        "matStrongEnemy": "Big Hilichurls",
        "matWeakEnemy": "Hilichurl Archers",
        "baseATK": 33,
        "stat": "",
        "baseStat": 0
    },
    "ApprenticesNotes": {
        "name": "Apprentice's Notes",
        "quality": 1,
        "type": "Catalyst",
        "matForgery": "Tile",
        "matStrongEnemy": "Big Hilichurls",
        "matWeakEnemy": "Hilichurls",
        "baseATK": 23,
        "stat": "",
        "baseStat": 0
    },
    "BeginnersProtector": {
        "name": "Beginner's Protector",
        "quality": 1,
        "type": "Polearm",
        "matForgery": "Cuffs",
        "matStrongEnemy": "Ruin Guards",
        "matWeakEnemy": "Samachurls",
        "baseATK": 23,
        "stat": "",
        "baseStat": 0
    },
    "DullBlade": {
        "name": "Dull Blade",
        "quality": 1,
        "type": "Sword",
        "matForgery": "Tile",
        "matStrongEnemy": "Big Hilichurls",
        "matWeakEnemy": "Hilichurl Archers",
        "baseATK": 23,
        "stat": "",
        "baseStat": 0
    },
    "HuntersBow": {
        "name": "Hunter's Bow",
        "quality": 1,
        "type": "Bow",
        "matForgery": "Tooth",
        "matStrongEnemy": "Abyss Mages",
        "matWeakEnemy": "Treasure Hoarders",
        "baseATK": 23,
        "stat": "",
        "baseStat": 0
    },
    "WasterGreatsword": {
        "name": "Waster Greatsword",
        "quality": 1,
        "type": "Claymore",
        "matForgery": "Tooth",
        "matStrongEnemy": "Abyss Mages",
        "matWeakEnemy": "Slimes",
        "baseATK": 23,
        "stat": "",
        "baseStat": 0
    }
};
