export default {
  'Albedo': {
    name: "Albedo",
    weapon: "Sword",
    element: "Geo",
    rarity: 5,
    ascendStat: "geo_dmg_",
    matBoss: "Geo Cube",
    matFlower: "Cecilia",
    matEnemy: "Samachurls",
    matMastery: "Ballad",
    matTrounce: "Tusk Of Monoceros Caeli",
  },
  'Alhaitham': {
    name: "Alhaitham",
    weapon: "Sword",
    element: "Dendro",
    rarity: 5,
    ascendStat: "dendro_dmg_",
    matBoss: "Setekh Wenut",
    matFlower: "Sand Grease Pupa",
    matEnemy: "Eremites",
    matMastery: "Ingenuity",
    matTrounce: "Mirror Of Mushin",
  },
  'Aloy': {
    name: "Aloy",
    weapon: "Bow",
    element: "Cryo",
    rarity: 5,
    ascendStat: "cryo_dmg_",
    matBoss: "Cryo Cube",
    matFlower: "Crystal Marrow",
    matEnemy: "Specters",
    matMastery: "Freedom",
    matTrounce: "Molten Moment",
  },
  'Amber': {
    name: "Amber",
    weapon: "Bow",
    element: "Pyro",
    rarity: 4,
    ascendStat: "atk_",
    matBoss: "Pyro Plant",
    matFlower: "Small Lamp Grass",
    matEnemy: "Hilichurl Archers",
    matMastery: "Freedom",
    matTrounce: "Dvalin's Sigh",
  },
  'AratakiItto': {
    name: "Arataki Itto",
    weapon: "Claymore",
    element: "Geo",
    rarity: 5,
    ascendStat: "critRate_",
    matBoss: "Golden Wolflord",
    matFlower: "Onikabuto",
    matEnemy: "Slimes",
    matMastery: "Elegance",
    matTrounce: "Ashen Heart",
  },
  'Baizhu': {
    name: "Baizhu",
    weapon: "Catalyst",
    element: "Dendro",
    rarity: 5,
    ascendStat: "hp_",
    matBoss: "Baptist",
    matFlower: "Violetgrass",
    matEnemy: "Fungi",
    matMastery: "Gold",
    matTrounce: "Worldspan Fern",
  },
  'Barbara': {
    name: "Barbara",
    weapon: "Catalyst",
    element: "Hydro",
    rarity: 4,
    ascendStat: "hp_",
    matBoss: "Oceanid",
    matFlower: "Philanemo Mushroom",
    matEnemy: "Samachurls",
    matMastery: "Freedom",
    matTrounce: "Ring Of Boreas",
  },
  'Beidou': {
    name: "Beidou",
    weapon: "Claymore",
    element: "Electro",
    rarity: 4,
    ascendStat: "electro_dmg_",
    matBoss: "Electro Cube",
    matFlower: "Noctilucous Jade",
    matEnemy: "Treasure Hoarders",
    matMastery: "Gold",
    matTrounce: "Dvalin's Sigh",
  },
  'Bennett': {
    name: "Bennett",
    weapon: "Sword",
    element: "Pyro",
    rarity: 4,
    ascendStat: "enerRech_",
    matBoss: "Pyro Plant",
    matFlower: "Windwheel Aster",
    matEnemy: "Treasure Hoarders",
    matMastery: "Resistance",
    matTrounce: "Dvalin's Plume",
  },
  'Candace': {
    name: "Candace",
    weapon: "Polearm",
    element: "Hydro",
    rarity: 4,
    ascendStat: "hp_",
    matBoss: "Matrix Boss",
    matFlower: "Henna Berry",
    matEnemy: "Eremites",
    matMastery: "Admonition",
    matTrounce: "Tears Of The Calamitous God",
  },
  'Chongyun': {
    name: "Chongyun",
    weapon: "Claymore",
    element: "Cryo",
    rarity: 4,
    ascendStat: "atk_",
    matBoss: "Cryo Plant",
    matFlower: "Cor Lapis",
    matEnemy: "Hilichurls",
    matMastery: "Diligence",
    matTrounce: "Dvalin's Sigh",
  },
  'Collei': {
    name: "Collei",
    weapon: "Bow",
    element: "Dendro",
    rarity: 4,
    ascendStat: "atk_",
    matBoss: "Dendro Bird",
    matFlower: "Rukkhashava Mushrooms",
    matEnemy: "Hilichurl Archers",
    matMastery: "Praxis",
    matTrounce: "Tears Of The Calamitous God",
  },
  'Cyno': {
    name: "Cyno",
    weapon: "Polearm",
    element: "Electro",
    rarity: 5,
    ascendStat: "critDMG_",
    matBoss: "Electro Plant",
    matFlower: "Scarab",
    matEnemy: "Samachurls",
    matMastery: "Admonition",
    matTrounce: "Mudra Of The Malefic General",
  },
  'Dehya': {
    name: "Dehya",
    weapon: "Claymore",
    element: "Pyro",
    rarity: 5,
    ascendStat: "hp_",
    matBoss: "Matrix Boss",
    matFlower: "Sand Grease Pupa",
    matEnemy: "Eremites",
    matMastery: "Praxis",
    matTrounce: "Puppet Strings",
  },
  'Diluc': {
    name: "Diluc",
    weapon: "Claymore",
    element: "Pyro",
    rarity: 5,
    ascendStat: "critRate_",
    matBoss: "Pyro Plant",
    matFlower: "Small Lamp Grass",
    matEnemy: "Fatui",
    matMastery: "Resistance",
    matTrounce: "Dvalin's Plume",
  },
  'Diona': {
    name: "Diona",
    weapon: "Bow",
    element: "Cryo",
    rarity: 4,
    ascendStat: "cryo_dmg_",
    matBoss: "Cryo Plant",
    matFlower: "Calla Lily",
    matEnemy: "Hilichurl Archers",
    matMastery: "Freedom",
    matTrounce: "Shard Of A Foul Legacy",
  },
  'Dori': {
    name: "Dori",
    weapon: "Claymore",
    element: "Electro",
    rarity: 4,
    ascendStat: "hp_",
    matBoss: "Electro Plant",
    matFlower: "Kalpalata Lotus",
    matEnemy: "Eremites",
    matMastery: "Ingenuity",
    matTrounce: "Bloodjade Branch",
  },
  'Eula': {
    name: "Eula",
    weapon: "Claymore",
    element: "Cryo",
    rarity: 5,
    ascendStat: "critDMG_",
    matBoss: "Cryo Cube",
    matFlower: "Dandelion Seed",
    matEnemy: "Hilichurls",
    matMastery: "Resistance",
    matTrounce: "Dragon Lord's Crown",
  },
  'Faruzan': {
    name: "Faruzan",
    weapon: "Bow",
    element: "Anemo",
    rarity: 4,
    ascendStat: "atk_",
    matBoss: "Matrix Boss",
    matFlower: "Henna Berry",
    matEnemy: "Eremites",
    matMastery: "Admonition",
    matTrounce: "Puppet Strings",
  },
  'Fischl': {
    name: "Fischl",
    weapon: "Bow",
    element: "Electro",
    rarity: 4,
    ascendStat: "atk_",
    matBoss: "Electro Cube",
    matFlower: "Small Lamp Grass",
    matEnemy: "Hilichurl Archers",
    matMastery: "Ballad",
    matTrounce: "Spirit Locket Of Boreas",
  },
  'Ganyu': {
    name: "Ganyu",
    weapon: "Bow",
    element: "Cryo",
    rarity: 5,
    ascendStat: "critDMG_",
    matBoss: "Cryo Plant",
    matFlower: "Qingxin",
    matEnemy: "Whopperflowers",
    matMastery: "Diligence",
    matTrounce: "Shadow Of The Warrior",
  },
  'Gorou': {
    name: "Gorou",
    weapon: "Bow",
    element: "Geo",
    rarity: 4,
    ascendStat: "geo_dmg_",
    matBoss: "Array Boss",
    matFlower: "Sango Pearl",
    matEnemy: "Specters",
    matMastery: "Light",
    matTrounce: "Molten Moment",
  },
  'HuTao': {
    name: "Hu Tao",
    weapon: "Polearm",
    element: "Pyro",
    rarity: 5,
    ascendStat: "critDMG_",
    matBoss: "Primo Geovishap",
    matFlower: "Silk Flower",
    matEnemy: "Whopperflowers",
    matMastery: "Diligence",
    matTrounce: "Shard Of A Foul Legacy",
  },
  'Jean': {
    name: "Jean",
    weapon: "Sword",
    element: "Anemo",
    rarity: 5,
    ascendStat: "heal_",
    matBoss: "Anemo Cube",
    matFlower: "Dandelion Seed",
    matEnemy: "Hilichurls",
    matMastery: "Resistance",
    matTrounce: "Dvalin's Plume",
  },
  'KaedeharaKazuha': {
    name: "Kaedehara Kazuha",
    weapon: "Sword",
    element: "Anemo",
    rarity: 5,
    ascendStat: "eleMas",
    matBoss: "Maguu Kenki",
    matFlower: "Sea Ganoderma",
    matEnemy: "Treasure Hoarders",
    matMastery: "Diligence",
    matTrounce: "Gilded Scale",
  },
  'Kaeya': {
    name: "Kaeya",
    weapon: "Sword",
    element: "Cryo",
    rarity: 4,
    ascendStat: "enerRech_",
    matBoss: "Cryo Plant",
    matFlower: "Calla Lily",
    matEnemy: "Treasure Hoarders",
    matMastery: "Ballad",
    matTrounce: "Spirit Locket Of Boreas",
  },
  'KamisatoAyaka': {
    name: "Kamisato Ayaka",
    weapon: "Sword",
    element: "Cryo",
    rarity: 5,
    ascendStat: "critDMG_",
    matBoss: "Array Boss",
    matFlower: "Sakura Bloom",
    matEnemy: "Nobushi",
    matMastery: "Elegance",
    matTrounce: "Bloodjade Branch",
  },
  'KamisatoAyato': {
    name: "Kamisato Ayato",
    weapon: "Sword",
    element: "Hydro",
    rarity: 5,
    ascendStat: "critDMG_",
    matBoss: "Hydro Cube",
    matFlower: "Sakura Bloom",
    matEnemy: "Nobushi",
    matMastery: "Elegance",
    matTrounce: "Mudra Of The Malefic General",
  },
  'Kaveh': {
    name: "Kaveh",
    weapon: "Claymore",
    element: "Dendro",
    rarity: 4,
    ascendStat: "eleMas",
    matBoss: "Dendro Cube",
    matFlower: "Mourning Flower",
    matEnemy: "Fungi",
    matMastery: "Ingenuity",
    matTrounce: "Primordial Greenbloom",
  },
  'Keqing': {
    name: "Keqing",
    weapon: "Sword",
    element: "Electro",
    rarity: 5,
    ascendStat: "critDMG_",
    matBoss: "Electro Cube",
    matFlower: "Cor Lapis",
    matEnemy: "Whopperflowers",
    matMastery: "Prosperity",
    matTrounce: "Ring Of Boreas",
  },
  'Klee': {
    name: "Klee",
    weapon: "Catalyst",
    element: "Pyro",
    rarity: 5,
    ascendStat: "pyro_dmg_",
    matBoss: "Pyro Plant",
    matFlower: "Philanemo Mushroom",
    matEnemy: "Samachurls",
    matMastery: "Freedom",
    matTrounce: "Ring Of Boreas",
  },
  'KujouSara': {
    name: "Kujou Sara",
    weapon: "Bow",
    element: "Electro",
    rarity: 4,
    ascendStat: "atk_",
    matBoss: "Thunder Manifest",
    matFlower: "Dendrobrium",
    matEnemy: "Hilichurls",
    matMastery: "Elegance",
    matTrounce: "Ashen Heart",
  },
  'KukiShinobu': {
    name: "Kuki Shinobu",
    weapon: "Sword",
    element: "Electro",
    rarity: 4,
    ascendStat: "hp_",
    matBoss: "Ruin Serpent",
    matFlower: "Naku Weed",
    matEnemy: "Specters",
    matMastery: "Elegance",
    matTrounce: "Tears Of The Calamitous God",
  },
  'Layla': {
    name: "Layla",
    weapon: "Sword",
    element: "Cryo",
    rarity: 4,
    ascendStat: "hp_",
    matBoss: "Aeonblight Drake",
    matFlower: "Nilotpala Lotus",
    matEnemy: "Samachurls",
    matMastery: "Ingenuity",
    matTrounce: "Mirror Of Mushin",
  },
  'Lisa': {
    name: "Lisa",
    weapon: "Catalyst",
    element: "Electro",
    rarity: 4,
    ascendStat: "eleMas",
    matBoss: "Electro Cube",
    matFlower: "Valberry",
    matEnemy: "Slimes",
    matMastery: "Ballad",
    matTrounce: "Dvalin's Claw",
  },
  'Mika': {
    name: "Mika",
    weapon: "Polearm",
    element: "Cryo",
    rarity: 4,
    ascendStat: "hp_",
    matBoss: "Setekh Wenut",
    matFlower: "Wolfhook",
    matEnemy: "Fatui",
    matMastery: "Ballad",
    matTrounce: "Mirror Of Mushin",
  },
  'Mona': {
    name: "Mona",
    weapon: "Catalyst",
    element: "Hydro",
    rarity: 5,
    ascendStat: "enerRech_",
    matBoss: "Oceanid",
    matFlower: "Philanemo Mushroom",
    matEnemy: "Whopperflowers",
    matMastery: "Resistance",
    matTrounce: "Ring Of Boreas",
  },
  'Nahida': {
    name: "Nahida",
    weapon: "Catalyst",
    element: "Dendro",
    rarity: 5,
    ascendStat: "eleMas",
    matBoss: "Dendro Cube",
    matFlower: "Kalpalata Lotus",
    matEnemy: "Fungi",
    matMastery: "Ingenuity",
    matTrounce: "Puppet Strings",
  },
  'Nilou': {
    name: "Nilou",
    weapon: "Sword",
    element: "Hydro",
    rarity: 5,
    ascendStat: "hp_",
    matBoss: "Aeonblight Drake",
    matFlower: "Padisarah",
    matEnemy: "Fungi",
    matMastery: "Praxis",
    matTrounce: "Tears Of The Calamitous God",
  },
  'Ningguang': {
    name: "Ningguang",
    weapon: "Catalyst",
    element: "Geo",
    rarity: 4,
    ascendStat: "geo_dmg_",
    matBoss: "Geo Cube",
    matFlower: "Glaze Lily",
    matEnemy: "Fatui",
    matMastery: "Prosperity",
    matTrounce: "Spirit Locket Of Boreas",
  },
  'Noelle': {
    name: "Noelle",
    weapon: "Claymore",
    element: "Geo",
    rarity: 4,
    ascendStat: "def_",
    matBoss: "Geo Cube",
    matFlower: "Valberry",
    matEnemy: "Hilichurls",
    matMastery: "Resistance",
    matTrounce: "Dvalin's Claw",
  },
  'Qiqi': {
    name: "Qiqi",
    weapon: "Sword",
    element: "Cryo",
    rarity: 5,
    ascendStat: "heal_",
    matBoss: "Cryo Plant",
    matFlower: "Violetgrass",
    matEnemy: "Samachurls",
    matMastery: "Properity",
    matTrounce: "Tail Of Boreas",
  },
  'RaidenShogun': {
    name: "Raiden Shogun",
    weapon: "Polearm",
    element: "Electro",
    rarity: 5,
    ascendStat: "enerRech_",
    matBoss: "Thunder Manifest",
    matFlower: "Amakumo Fruit",
    matEnemy: "Nobushi",
    matMastery: "Light",
    matTrounce: "Molten Moment",
  },
  'Razor': {
    name: "Razor",
    weapon: "Claymore",
    element: "Electro",
    rarity: 4,
    ascendStat: "physical_dmg_",
    matBoss: "Electro Cube",
    matFlower: "Wolfhook",
    matEnemy: "Hilichurls",
    matMastery: "Resistance",
    matTrounce: "Dvalin's Claw",
  },
  'Rosaria': {
    name: "Rosaria",
    weapon: "Polearm",
    element: "Cryo",
    rarity: 4,
    ascendStat: "atk_",
    matBoss: "Cryo Plant",
    matFlower: "Valberry",
    matEnemy: "Fatui",
    matMastery: "Ballad",
    matTrounce: "Shadow Of The Warrior",
  },
  'SangonomiyaKokomi': {
    name: "Sangonomiya Kokomi",
    weapon: "Catalyst",
    element: "Hydro",
    rarity: 5,
    ascendStat: "hydro_dmg_",
    matBoss: "Hydro Cube",
    matFlower: "Sango Pearl",
    matEnemy: "Specters",
    matMastery: "Transience",
    matTrounce: "Hellfire Butterfly",
  },
  'Sayu': {
    name: "Sayu",
    weapon: "Claymore",
    element: "Anemo",
    rarity: 4,
    ascendStat: "eleMas",
    matBoss: "Maguu Kenki",
    matFlower: "Crystal Marrow",
    matEnemy: "Whopperflowers",
    matMastery: "Light",
    matTrounce: "Gilded Scale",
  },
  'Shenhe': {
    name: "Shenhe",
    weapon: "Polearm",
    element: "Cryo",
    rarity: 5,
    ascendStat: "atk_",
    matBoss: "Coral Defenders",
    matFlower: "Qingxin",
    matEnemy: "Whopperflowers",
    matMastery: "Prosperity",
    matTrounce: "Hellfire Butterfly",
  },
  'ShikanoinHeizou': {
    name: "Shikanoin Heizou",
    weapon: "Catalyst",
    element: "Anemo",
    rarity: 4,
    ascendStat: "anemo_dmg_",
    matBoss: "Ruin Serpent",
    matFlower: "Onikabuto",
    matEnemy: "Treasure Hoarders",
    matMastery: "Transience",
    matTrounce: "The Meaning Of Aeons",
  },
  'Sucrose': {
    name: "Sucrose",
    weapon: "Catalyst",
    element: "Anemo",
    rarity: 4,
    ascendStat: "anemo_dmg_",
    matBoss: "Anemo Cube",
    matFlower: "Windwheel Aster",
    matEnemy: "Whopperflowers",
    matMastery: "Freedom",
    matTrounce: "Spirit Locket Of Boreas",
  },
  'Tartaglia': {
    name: "Tartaglia",
    weapon: "Bow",
    element: "Hydro",
    rarity: 5,
    ascendStat: "hydro_dmg_",
    matBoss: "Oceanid",
    matFlower: "Starconch",
    matEnemy: "Fatui",
    matMastery: "Freedom",
    matTrounce: "Shard Of A Foul Legacy",
  },
  'Thoma': {
    name: "Thoma",
    weapon: "Polearm",
    element: "Pyro",
    rarity: 4,
    ascendStat: "atk_",
    matBoss: "Pyro Cube",
    matFlower: "Fluorescent Fungus",
    matEnemy: "Treasure Hoarders",
    matMastery: "Transience",
    matTrounce: "Hellfire Butterfly",
  },
  'Tighnari': {
    name: "Tighnari",
    weapon: "Bow",
    element: "Dendro",
    rarity: 5,
    ascendStat: "dendro_dmg_",
    matBoss: "Dendro Bird",
    matFlower: "Nilotpala Lotus",
    matEnemy: "Fungi",
    matMastery: "Admonition",
    matTrounce: "The Meaning Of Aeons",
  },
  'TravelerAnemo': {
    name: "Traveler: Anemo",
    weapon: "Sword",
    element: "Anemo",
    rarity: 4, // Stat scaling trumps the yellow background.
    ascendStat: "atk_",
    matFlower: "Windwheel Aster",
    matEnemy: "Hilichurls",
    matTalentEnemy: "Samachurls",
    matMastery: "Resistance",
    matTrounce: "Dvalin's Sigh",
  },
  'TravelerGeo': {
    name: "Traveler: Geo",
    weapon: "Sword",
    element: "Geo",
    rarity: 4,
    ascendStat: "atk_",
    matFlower: "Windwheel Aster",
    matEnemy: "Hilichurls",
    matTalentEnemy: "Hilichurl Archers",
    matMastery: "Diligence",
    matTrounce: "Tail Of Boreas",
  },
  'TravelerElectro': {
    name: "Traveler: Electro",
    weapon: "Sword",
    element: "Electro",
    rarity: 4,
    ascendStat: "atk_",
    matFlower: "Windwheel Aster",
    matEnemy: "Hilichurls",
    matTalentEnemy: "Nobushi",
    matMastery: "Light",
    matTrounce: "Dragon Lord's Crown",
  },
  'TravelerDendro': {
    name: "Traveler: Dendro",
    weapon: "Sword",
    element: "Dendro",
    rarity: 4,
    ascendStat: "atk_",
    matFlower: "Windwheel Aster",
    matEnemy: "Hilichurls",
    matTalentEnemy: "Fungi",
    matMastery: "Praxis",
    matTrounce: "Mudra Of The Malefic General",
  },
  'Venti': {
    name: "Venti",
    weapon: "Bow",
    element: "Anemo",
    rarity: 5,
    ascendStat: "enerRech_",
    matBoss: "Anemo Cube",
    matFlower: "Cecilia",
    matEnemy: "Slimes",
    matMastery: "Ballad",
    matTrounce: "Tail Of Boreas",
  },
  'Wanderer': {
    name: "Wanderer",
    weapon: "Catalyst",
    element: "Anemo",
    rarity: 5,
    ascendStat: "critRate_",
    matBoss: "Aeonblight Drake",
    matFlower: "Rukkhashava Mushrooms",
    matEnemy: "Nobushi",
    matMastery: "Praxis",
    matTrounce: "Daka's Bell",
  },
  'Xiangling': {
    name: "Xiangling",
    weapon: "Polearm",
    element: "Pyro",
    rarity: 4,
    ascendStat: "eleMas",
    matBoss: "Pyro Plant",
    matFlower: "Jueyun Chili",
    matEnemy: "Slimes",
    matMastery: "Diligence",
    matTrounce: "Dvalin's Claw",
  },
  'Xiao': {
    name: "Xiao",
    weapon: "Polearm",
    element: "Anemo",
    rarity: 5,
    ascendStat: "critRate_",
    matBoss: "Primo Geovishap",
    matFlower: "Qingxin",
    matEnemy: "Slimes",
    matMastery: "Prosperity",
    matTrounce: "Shadow Of The Warrior",
  },
  'Xingqiu': {
    name: "Xingqiu",
    weapon: "Sword",
    element: "Hydro",
    rarity: 4,
    ascendStat: "atk_",
    matBoss: "Oceanid",
    matFlower: "Silk Flower",
    matEnemy: "Hilichurls",
    matMastery: "Gold",
    matTrounce: "Tail Of Boreas",
  },
  'Xinyan': {
    name: "Xinyan",
    weapon: "Claymore",
    element: "Pyro",
    rarity: 4,
    ascendStat: "atk_",
    matBoss: "Pyro Plant",
    matFlower: "Violetgrass",
    matEnemy: "Treasure Hoarders",
    matMastery: "Gold",
    matTrounce: "Tusk Of Monoceros Caeli",
  },
  'YaeMiko': {
    name: "Yae Miko",
    weapon: "Catalyst",
    element: "Electro",
    rarity: 5,
    ascendStat: "critRate_",
    matBoss: "Coral Defenders",
    matFlower: "Sea Ganoderma",
    matEnemy: "Nobushi",
    matMastery: "Light",
    matTrounce: "The Meaning Of Aeons",
  },
  'Yanfei': {
    name: "Yanfei",
    weapon: "Catalyst",
    element: "Pyro",
    rarity: 4,
    ascendStat: "pyro_dmg_",
    matBoss: "Primo Geovishap",
    matFlower: "Noctilucous Jade",
    matEnemy: "Treasure Hoarders",
    matMastery: "Gold",
    matTrounce: "Bloodjade Branch",
  },
  'Yaoyao': {
    name: "Yaoyao",
    weapon: "Polearm",
    element: "Dendro",
    rarity: 4,
    ascendStat: "hp_",
    matBoss: "Dendro Cube",
    matFlower: "Jueyun Chili",
    matEnemy: "Slimes",
    matMastery: "Diligence",
    matTrounce: "Daka's Bell",
  },
  'Yelan': {
    name: "Yelan",
    weapon: "Bow",
    element: "Hydro",
    rarity: 5,
    ascendStat: "critRate_",
    matBoss: "Ruin Serpent",
    matFlower: "Starconch",
    matEnemy: "Fatui",
    matMastery: "Prosperity",
    matTrounce: "Gilded Scale",
  },
  'Yoimiya': {
    name: "Yoimiya",
    weapon: "Bow",
    element: "Pyro",
    rarity: 5,
    ascendStat: "critRate_",
    matBoss: "Pyro Cube",
    matFlower: "Naku Weed",
    matEnemy: "Samachurls",
    matMastery: "Transience",
    matTrounce: "Dragon Lord's Crown",
  },
  'YunJin': {
    name: "Yun Jin",
    weapon: "Polearm",
    element: "Geo",
    rarity: 4,
    ascendStat: "enerRech_",
    matBoss: "Golden Wolflord",
    matFlower: "Glaze Lily",
    matEnemy: "Hilichurls",
    matMastery: "Diligence",
    matTrounce: "Ashen Heart",
  },
  'Zhongli': {
    name: "Zhongli",
    weapon: "Polearm",
    element: "Geo",
    rarity: 5,
    ascendStat: "geo_dmg_",
    matBoss: "Geo Cube",
    matFlower: "Cor Lapis",
    matEnemy: "Slimes",
    matMastery: "Gold",
    matTrounce: "Tusk Of Monoceros Caeli",
  },
};
