export default {
    "talents": {
        "Normal Attack": {
            "name": "Skirmishing Spear",
            "icon": "Skill_A_03",
            "text": "<color=#FFD780FF>Normal Attack<\/color>\\nPerforms up to 4 consecutive spear strikes and applies the {LINK#N11480001}<color=#FFD780FF>Hunter's Mark<\/color>{\/LINK} to the opponent hit by the final strike.\\n\\n<color=#FFD780FF>Charged Attack<\/color>\\nConsumes a certain amount of Stamina to lunge forward, dealing damage to opponents in his path.\\n\\n<color=#FFD780FF>Plunging Attack<\/color>\\nPlunges from mid-air to strike the ground below, damaging opponents along the path and dealing AoE DMG upon impact.",
            "scaling": {
                "1-Hit DMG": [
                    "47.82%",
                    "51.71%",
                    "55.6%",
                    "61.16%",
                    "65.05%",
                    "69.5%",
                    "75.62%",
                    "81.73%",
                    "87.85%",
                    "94.52%",
                    "101.19%",
                    "107.86%",
                    "114.54%",
                    "121.21%",
                    "127.88%"
                ],
                "2-Hit DMG": [
                    "48.16%",
                    "52.08%",
                    "56%",
                    "61.6%",
                    "65.52%",
                    "70%",
                    "76.16%",
                    "82.32%",
                    "88.48%",
                    "95.2%",
                    "101.92%",
                    "108.64%",
                    "115.36%",
                    "122.08%",
                    "128.8%"
                ],
                "3-Hit DMG": [
                    "34.23%+31.82%",
                    "37.01%+34.41%",
                    "39.8%+37%",
                    "43.78%+40.7%",
                    "46.57%+43.29%",
                    "49.75%+46.25%",
                    "54.13%+50.32%",
                    "58.51%+54.39%",
                    "62.88%+58.46%",
                    "67.66%+62.9%",
                    "72.44%+67.34%",
                    "77.21%+71.78%",
                    "81.99%+76.22%",
                    "86.76%+80.66%",
                    "91.54%+85.1%"
                ],
                "4-Hit DMG": [
                    "75.85%",
                    "82.03%",
                    "88.2%",
                    "97.02%",
                    "103.19%",
                    "110.25%",
                    "119.95%",
                    "129.65%",
                    "139.36%",
                    "149.94%",
                    "160.52%",
                    "171.11%",
                    "181.69%",
                    "192.28%",
                    "202.86%"
                ],
                "Charged Attack DMG": [
                    "111.03%",
                    "120.06%",
                    "129.1%",
                    "142.01%",
                    "151.05%",
                    "161.37%",
                    "175.58%",
                    "189.78%",
                    "203.98%",
                    "219.47%",
                    "234.96%",
                    "250.45%",
                    "265.95%",
                    "281.44%",
                    "296.93%"
                ],
                "Charged Attack Stamina Cost": [
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25"
                ],
                "Plunge DMG": [
                    "63.93%",
                    "69.14%",
                    "74.34%",
                    "81.77%",
                    "86.98%",
                    "92.93%",
                    "101.1%",
                    "109.28%",
                    "117.46%",
                    "126.38%",
                    "135.3%",
                    "144.22%",
                    "153.14%",
                    "162.06%",
                    "170.98%"
                ],
                "Low\/High Plunge DMG": [
                    "127.84%\/159.68%",
                    "138.24%\/172.67%",
                    "148.65%\/185.67%",
                    "163.51%\/204.24%",
                    "173.92%\/217.23%",
                    "185.81%\/232.09%",
                    "202.16%\/252.51%",
                    "218.51%\/272.93%",
                    "234.86%\/293.36%",
                    "252.7%\/315.64%",
                    "270.54%\/337.92%",
                    "288.38%\/360.2%",
                    "306.22%\/382.48%",
                    "324.05%\/404.76%",
                    "341.89%\/427.04%"
                ]
            }
        },
        "Elemental Skill": {
            "name": "Thunderbolt Strike",
            "icon": "Skill_S_Alyosha_01",
            "text": "Follows his hunter's instincts. Tap or hold to produce different effects as well as apply the {LINK#N11480001}<color=#FFD780FF>Hunter's Mark<\/color>{\/LINK} effect to the hit opponents.\\n\\n<color=#FFD780FF>Tapping<\/color>\\nFires at opponents in front of him, dealing <color=#FFACFFFF>AoE Electro DMG<\/color>.\\n\\n<color=#FFD780FF>Holding<\/color>\\nEnters aiming mode, then targets opponents within a certain area in front of him. Alyosha's Interruption RES is enhanced when in this mode.\\nAt the end of the button hold, he deals <color=#FFACFFFF>Electro DMG<\/color> to the targeted opponents.\\n\\n<i>The reckless hunter once reached for the spear's edge, and it was only after they survived a lesson paid in blood that they came to understand the harsh truths of survival on the frozen plains.<\/i>",
            "scaling": {
                "Press DMG": [
                    "286.72%",
                    "308.22%",
                    "329.73%",
                    "358.4%",
                    "379.9%",
                    "401.41%",
                    "430.08%",
                    "458.75%",
                    "487.42%",
                    "516.1%",
                    "544.77%",
                    "573.44%",
                    "609.28%",
                    "645.12%",
                    "680.96%"
                ],
                "Hold DMG": [
                    "358.4%",
                    "385.28%",
                    "412.16%",
                    "448%",
                    "474.88%",
                    "501.76%",
                    "537.6%",
                    "573.44%",
                    "609.28%",
                    "645.12%",
                    "680.96%",
                    "716.8%",
                    "761.6%",
                    "806.4%",
                    "851.2%"
                ],
                "CD": [
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s"
                ],
                "Hunter's Mark Duration": [
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s"
                ],
                "Hunter's Precision ATK Bonus": [
                    "11.66%",
                    "12.72%",
                    "13.78%",
                    "14.84%",
                    "15.9%",
                    "16.96%",
                    "18.02%",
                    "19.08%",
                    "20.14%",
                    "21.2%",
                    "22.47%",
                    "23.74%",
                    "25.02%",
                    "26.29%",
                    "27.56%"
                ],
                "Hunter's Precision Duration": [
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s"
                ]
            }
        },
        "Elemental Burst": {
            "name": "Hunter's Advance",
            "icon": "Skill_E_Alyosha_01",
            "text": "Summons his trusted companion <color=#FFD780FF>Tugarin<\/color> to fight alongside him on the field. This also turns an area in front of him into a <color=#FFD780FF>Fulgurite Hunting Field<\/color> for a short time.\\n\\n<color=#FFD780FF>Fulgurite Hunting Field<\/color>\\n\u00b7 Continuously taunts nearby opponents to incite them to attack.\\n\u00b7 Every 2s, deals an instance of <color=#FFACFFFF>AoE Electro DMG<\/color> to any opponent that enters the field.\\n\\n<color=#FFD780FF>Tugarin<\/color>\\n\u00b7 If there are any opponents nearby, Tugarin will quickly move close to an opponent and maul them every 2s, dealing <color=#FFD780FF>Electro DMG<\/color>.\\n\u00b7 If an opponent affected by the <color=#FFD780FF>Hunter's Mark<\/color> effect is hit, the <color=#FFD780FF>Hunter's Mark<\/color> will also be activated.\\n\u00b7 Where there are multiple opponents, Tugarin will attack those affected by the <color=#FFD780FF>Hunter's Mark<\/color> effect first.\\n\\n<i>Wait. Keep waiting until the impatience fades. That's when the red-bellied plover shall sweep across the birch grove and present itself before one's arrow.<\/i>",
            "scaling": {
                "Fulgurite Hunting Field DMG": [
                    "74.96%",
                    "80.58%",
                    "86.2%",
                    "93.7%",
                    "99.32%",
                    "104.94%",
                    "112.44%",
                    "119.94%",
                    "127.43%",
                    "134.93%",
                    "142.42%",
                    "149.92%",
                    "159.29%",
                    "168.66%",
                    "178.03%"
                ],
                "Tugarin DMG": [
                    "50.22%",
                    "53.99%",
                    "57.76%",
                    "62.78%",
                    "66.55%",
                    "70.31%",
                    "75.33%",
                    "80.36%",
                    "85.38%",
                    "90.4%",
                    "95.42%",
                    "100.45%",
                    "106.72%",
                    "113%",
                    "119.28%"
                ],
                "Duration": [
                    "14s",
                    "14s",
                    "14s",
                    "14s",
                    "14s",
                    "14s",
                    "14s",
                    "14s",
                    "14s",
                    "14s",
                    "14s",
                    "14s",
                    "14s",
                    "14s",
                    "14s"
                ],
                "CD": [
                    "18s",
                    "18s",
                    "18s",
                    "18s",
                    "18s",
                    "18s",
                    "18s",
                    "18s",
                    "18s",
                    "18s",
                    "18s",
                    "18s",
                    "18s",
                    "18s",
                    "18s"
                ],
                "Energy Cost": [
                    "70",
                    "70",
                    "70",
                    "70",
                    "70",
                    "70",
                    "70",
                    "70",
                    "70",
                    "70",
                    "70",
                    "70",
                    "70",
                    "70",
                    "70"
                ]
            }
        },
        "1st Ascension Passive": {
            "name": "Awakened by the Baying Hounds",
            "icon": "UI_Talent_S_Alyosha_05",
            "text": "When {LINK#N11480002}<color=#FFD780FF>Tugarin<\/color>{\/LINK} attacks, it will also restore HP to nearby active characters at 120% of Alyosha's ATK."
        },
        "4th Ascension Passive": {
            "name": "Suffer the Winter Wheat Will",
            "icon": "UI_Talent_S_Alyosha_06",
            "text": "Increases the DMG Alyosha deals with his Elemental Skill and Elemental Burst by 0.35% for every 1% of his Energy Recharge. Up to a 70% increase can be obtained in this way."
        },
        "Utility Passive": {
            "name": "Into the Fray",
            "icon": "UI_Talent_S_Alyosha_07",
            "text": "Alyosha will enter the <color=#FFD780FF>Radiance: Stellar-Conduct<\/color> state when inside a {LINK#N11330003}<color=#FFD780FF>Polestar Field<\/color>{\/LINK}.\\n<color=#FFD780FF>Radiance: Stellar-Conduct<\/color>: The <color=#FFD780FF>Hunter's Precision<\/color> effect obtained when the {LINK#N11480001}<color=#FFD780FF>Hunter's Mark<\/color>{\/LINK} is activated will also increase Stellar-Conduct reaction DMG dealt by the character when on the field by 20%."
        },
        "Passive": {
            "name": "Treetop Watch",
            "icon": "UI_Talent_S_Alyosha_08",
            "text": "Displays the location of nearby <color=#FFD780FF>resources unique to Snezhnaya<\/color> on the mini-map."
        }
    },
    "constellations": {
        "1": {
            "name": "Frostvale Thunderclap",
            "icon": "UI_Talent_S_Alyosha_01",
            "text": "Alyosha regenerates 15 Elemental Energy when nearby party members trigger an <color=#FFACFFFF>Electro-related reaction<\/color> on an opponent. This effect can trigger once every 18s."
        },
        "2": {
            "name": "Howl From Afar",
            "icon": "UI_Talent_S_Alyosha_02",
            "text": "The duration of the Elemental Burst <color=#FFD780FF>Hunter's Advance<\/color> is extended by 6s.\\nAdditionally, each time {LINK#N11480002}<color=#FFD780FF>Tugarin<\/color>{\/LINK} attacks the opponent, he will also apply the {LINK#N11480001}<color=#FFD780FF>Hunter's Mark<\/color>{\/LINK} to a target. This effect does not activate existing <color=#FFD780FF>Hunter's Marks<\/color>."
        },
        "3": {
            "name": "Friendly Call",
            "icon": "UI_Talent_U_Alyosha_01",
            "text": "Increases the Level of the Elemental Skill <color=#FFD780FF>Thunderbolt Strike<\/color> by 3.\\nMaximum upgrade level is 15."
        },
        "4": {
            "name": "Harvest the Spoils",
            "icon": "UI_Talent_S_Alyosha_03",
            "text": "When {LINK#N11480002}<color=#FFD780FF>Tugarin<\/color>{\/LINK} attacks, he will also restore 60% of Alyosha's ATK as HP to the nearby party member with the lowest HP by percentage."
        },
        "5": {
            "name": "When the Nightbird Falls Silent",
            "icon": "UI_Talent_U_Alyosha_02",
            "text": "Increases the Level of the Elemental Burst <color=#FFD780FF>Hunter's Advance<\/color> by 3.\\nMaximum upgrade level is 15."
        },
        "6": {
            "name": "Standard Reclaimed",
            "icon": "UI_Talent_S_Alyosha_04",
            "text": "The <color=#FFD780FF>Hunter's Precision<\/color> effect obtained from activating a {LINK#N11480001}<color=#FFD780FF>Hunter's Mark<\/color>{\/LINK} can now stack, max 2 stacks. When the stack count reaches 2, characters affected by <color=#FFD780FF>Hunter's Precision<\/color> will also have their Elemental Mastery increased by 100 if they are on the field."
        }
    }
};