export default {
    "talents": {
        "Normal Attack": {
            "name": "Oceanborne",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/0\/0f\/Claymore_Electro.png",
            "text": "<color=#FFD780FF>Normal Attack<\/color>\\nPerforms up to 5 consecutive strikes.\\n\\n<color=#FFD780FF>Charged Attack<\/color>\\nDrains Stamina over time to perform continuous slashes.\\nAt the end of the sequence, performs a more powerful slash.\\n\\n<color=#FFD780FF>Plunging Attack<\/color>\\nPlunges from mid-air to strike the ground, damaging opponents along the path and dealing AoE DMG upon impact.",
            "scaling": {
                "1-Hit DMG": [
                    "71.12%",
                    "76.91%",
                    "82.7%",
                    "90.97%",
                    "96.76%",
                    "103.38%",
                    "112.47%",
                    "121.57%",
                    "130.67%",
                    "140.59%",
                    "151.96%",
                    "165.33%",
                    "178.71%",
                    "192.08%",
                    "206.67%"
                ],
                "2-Hit DMG": [
                    "70.86%",
                    "76.63%",
                    "82.4%",
                    "90.64%",
                    "96.41%",
                    "103%",
                    "112.06%",
                    "121.13%",
                    "130.19%",
                    "140.08%",
                    "151.41%",
                    "164.73%",
                    "178.06%",
                    "191.38%",
                    "205.92%"
                ],
                "3-Hit DMG": [
                    "88.32%",
                    "95.51%",
                    "102.7%",
                    "112.97%",
                    "120.16%",
                    "128.38%",
                    "139.67%",
                    "150.97%",
                    "162.27%",
                    "174.59%",
                    "188.71%",
                    "205.32%",
                    "221.92%",
                    "238.53%",
                    "256.65%"
                ],
                "4-Hit DMG": [
                    "86.52%",
                    "93.56%",
                    "100.6%",
                    "110.66%",
                    "117.7%",
                    "125.75%",
                    "136.82%",
                    "147.88%",
                    "158.95%",
                    "171.02%",
                    "184.85%",
                    "201.12%",
                    "217.39%",
                    "233.65%",
                    "251.4%"
                ],
                "5-Hit DMG": [
                    "112.14%",
                    "121.27%",
                    "130.4%",
                    "143.44%",
                    "152.57%",
                    "163%",
                    "177.34%",
                    "191.69%",
                    "206.03%",
                    "221.68%",
                    "239.61%",
                    "260.7%",
                    "281.78%",
                    "302.87%",
                    "325.87%"
                ],
                "Charged Attack Cyclic DMG": [
                    "56.24%",
                    "60.82%",
                    "65.4%",
                    "71.94%",
                    "76.52%",
                    "81.75%",
                    "88.94%",
                    "96.14%",
                    "103.33%",
                    "111.18%",
                    "120.17%",
                    "130.75%",
                    "141.32%",
                    "151.9%",
                    "163.43%"
                ],
                "Charged Attack Final DMG": [
                    "101.82%",
                    "110.11%",
                    "118.4%",
                    "130.24%",
                    "138.53%",
                    "148%",
                    "161.02%",
                    "174.05%",
                    "187.07%",
                    "201.28%",
                    "217.56%",
                    "236.71%",
                    "255.85%",
                    "275%",
                    "295.88%"
                ],
                "Charged Attack Stamina Cost": [
                    "40\/s",
                    "40\/s",
                    "40\/s",
                    "40\/s",
                    "40\/s",
                    "40\/s",
                    "40\/s",
                    "40\/s",
                    "40\/s",
                    "40\/s",
                    "40\/s",
                    "40\/s",
                    "40\/s",
                    "40\/s",
                    "40\/s"
                ],
                "Max Duration": [
                    "5s",
                    "5s",
                    "5s",
                    "5s",
                    "5s",
                    "5s",
                    "5s",
                    "5s",
                    "5s",
                    "5s",
                    "5s",
                    "5s",
                    "5s",
                    "5s",
                    "5s"
                ],
                "Plunge DMG": [
                    "74.59%",
                    "80.66%",
                    "86.73%",
                    "95.4%",
                    "101.47%",
                    "108.41%",
                    "117.95%",
                    "127.49%",
                    "137.03%",
                    "147.44%",
                    "157.85%",
                    "168.26%",
                    "178.66%",
                    "189.07%",
                    "199.48%"
                ],
                "Low\/High Plunge DMG": [
                    "149.14%\/186.29%",
                    "161.28%\/201.45%",
                    "173.42%\/216.62%",
                    "190.77%\/238.28%",
                    "202.91%\/253.44%",
                    "216.78%\/270.77%",
                    "235.86%\/294.6%",
                    "254.93%\/318.42%",
                    "274.01%\/342.25%",
                    "294.82%\/368.25%",
                    "315.63%\/394.24%",
                    "336.44%\/420.23%",
                    "357.25%\/446.23%",
                    "378.06%\/472.22%",
                    "398.87%\/498.21%"
                ]
            },
            "icon": "Skill_A_04"
        },
        "Elemental Skill": {
            "name": "Tidecaller",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/9\/92\/Talent_Tidecaller.png",
            "text": "#Nothing to worry about. Should anyone raise a hand against her or her men, she will avenge it ten-fold with sword and thunder.\\n\\n<color=#FFD780FF>Press<\/color>\\nAccumulating the power of lightning, Beidou swings her blade forward fiercely, dealing <color=#FFACFFFF>Electro DMG<\/color>.\\n\\n<color=#FFD780FF>Hold<\/color>\\nLifts her weapon up as a shield. Max DMG absorbed scales off Beidou's Max HP.\\nAttacks using the energy stored within the greatsword upon release or once this ability's duration expires, dealing <color=#FFACFFFF>Electro DMG<\/color>. DMG dealt scales with the number of times Beidou is attacked in the skill's duration. The greatest DMG Bonus will be attained once this effect is triggered twice.\\nThe shield possesses the following properties:\\n\u00b7Has 250% <color=#FFACFFFF>Electro DMG<\/color> Absorption Efficiency.\\n\u00b7Applies the <color=#FFACFFFF>Electro element<\/color> to Beidou upon activation.\\n\\n<i>Conquer the high seas! Pursue the waves and chase the storm!<\/i>",
            "scaling": {
                "Shield DMG Absorption": [
                    "14.4% Max HP+1386",
                    "15.48% Max HP+1525",
                    "16.56% Max HP+1675",
                    "18% Max HP+1837",
                    "19.08% Max HP+2010",
                    "20.16% Max HP+2195",
                    "21.6% Max HP+2392",
                    "23.04% Max HP+2600",
                    "24.48% Max HP+2819",
                    "25.92% Max HP+3050",
                    "27.36% Max HP+3293",
                    "28.8% Max HP+3547",
                    "30.6% Max HP+3813",
                    "32.4% Max HP+4090",
                    "34.2% Max HP+4379"
                ],
                "Base DMG": [
                    "121.6%",
                    "130.72%",
                    "139.84%",
                    "152%",
                    "161.12%",
                    "170.24%",
                    "182.4%",
                    "194.56%",
                    "206.72%",
                    "218.88%",
                    "231.04%",
                    "243.2%",
                    "258.4%",
                    "273.6%",
                    "288.8%"
                ],
                "DMG Bonus on Hit Taken": [
                    "160%",
                    "172%",
                    "184%",
                    "200%",
                    "212%",
                    "224%",
                    "240%",
                    "256%",
                    "272%",
                    "288%",
                    "304%",
                    "320%",
                    "340%",
                    "360%",
                    "380%"
                ],
                "CD": [
                    "7.5s",
                    "7.5s",
                    "7.5s",
                    "7.5s",
                    "7.5s",
                    "7.5s",
                    "7.5s",
                    "7.5s",
                    "7.5s",
                    "7.5s",
                    "7.5s",
                    "7.5s",
                    "7.5s",
                    "7.5s",
                    "7.5s"
                ]
            },
            "icon": "Skill_S_Beidou_01"
        },
        "Elemental Burst": {
            "name": "Stormbreaker",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/3\/33\/Talent_Stormbreaker.png",
            "text": "Recalling her slaying of the great beast Haishan, Beidou calls upon that monstrous strength and the lightning to create a Thunderbeast's Targe around herself, dealing <color=#FFACFFFF>Electro DMG<\/color> to nearby opponents.\\n\\n<color=#FFD780FF>Thunderbeast's Targe<\/color>\\n\u00b7When Normal and Charged Attacks hit, they create a lightning discharge that can jump between opponents, dealing <color=#FFACFFFF>Electro DMG<\/color>.\\n\u00b7Increases the character's resistance to interruption, and decreases DMG taken.\\n\\nA maximum of 1 lightning discharge can be triggered per second.\\n\\n<i>With a peal of thunder, Haishan is slain.<\/i>",
            "scaling": {
                "Skill DMG": [
                    "121.6%",
                    "130.72%",
                    "139.84%",
                    "152%",
                    "161.12%",
                    "170.24%",
                    "182.4%",
                    "194.56%",
                    "206.72%",
                    "218.88%",
                    "231.04%",
                    "243.2%",
                    "258.4%",
                    "273.6%",
                    "288.8%"
                ],
                "Lightning DMG": [
                    "96%",
                    "103.2%",
                    "110.4%",
                    "120%",
                    "127.2%",
                    "134.4%",
                    "144%",
                    "153.6%",
                    "163.2%",
                    "172.8%",
                    "182.4%",
                    "192%",
                    "204%",
                    "216%",
                    "228%"
                ],
                "DMG Reduction": [
                    "20%",
                    "21%",
                    "22%",
                    "24%",
                    "25%",
                    "26%",
                    "28%",
                    "30%",
                    "32%",
                    "34%",
                    "35%",
                    "36%",
                    "37%",
                    "38%",
                    "39%"
                ],
                "Duration": [
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s"
                ],
                "CD": [
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s"
                ],
                "Energy Cost": [
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80"
                ]
            },
            "icon": "Skill_E_Beidou_01"
        },
        "1st Ascension Passive": {
            "name": "Retribution",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/6\/69\/Talent_Retribution.png",
            "text": "Counterattacking with <color=#FFD780FF>Tidecaller<\/color> at the precise moment when the character is hit grants the maximum DMG Bonus.",
            "icon": "UI_Talent_S_Beidou_05"
        },
        "4th Ascension Passive": {
            "name": "Lightning Storm",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/8\/8a\/Talent_Lightning_Storm.png",
            "text": "Gain the following effects for 10s after unleashing <color=#FFD780FF>Tidecaller<\/color> with its maximum DMG Bonus: \\n\u00b7DMG dealt by Normal and Charged Attacks is increased by 15%. ATK SPD of Normal and Charged Attacks is increased by 15%.\\n\u00b7Greatly reduced delay before unleashing Charged Attacks.",
            "code": [
                "proc",
                [
                    "stat",
                    [
                        [
                            "normal_dmg_",
                            "charged_dmg_",
                            "normal_spd_",
                            "charged_spd_"
                        ],
                        15
                    ]
                ],
                "After Tidecaller Parry (10s)"
            ],
            "icon": "UI_Talent_S_Beidou_06"
        },
        "Utility Passive": {
            "name": "Conqueror of Tides",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/d\/d3\/Talent_Conqueror_of_Tides.png",
            "text": "Decreases swimming Stamina consumption for your own party members by 20%.\\nNot stackable with Passive Talents that provide the exact same effects.",
            "icon": "UI_Talent_Explosion_Swim"
        },
        "Passive": {
            "name": "Polaris",
            "icon": "UI_Talent_S_Beidou_08",
            "text": "When holding down on the Elemental Skill <color=#FFD780FF>Tidecaller<\/color>, 1 stack of power will accumulate every 0.8s, even when not under attack. This increases the DMG dealt at the point of unleashing.\\nAdditionally, holding down to unleash <color=#FFD780FF>Tidecaller<\/color> and hitting the opponent also gives extra boosts based on the power accumulated: every stack active decreases Beidou's Elemental Skill CD by 4s, as well as regenerates 8 Elemental Energy for her. This effect can trigger once every 15s.\\nAdditionally, when inside a {LINK#N11330003}<color=#FFD780FF>Polestar Field<\/color>{\/LINK}, Beidou will enter the <color=#FFD780FF>Radiance: Stellar-Conduct<\/color> state."
        }
    },
    "constellations": {
        "1": {
            "name": "Sea Beast's Scourge",
            "icon": "UI_Talent_S_Beidou_02",
            "text": "When <color=#FFD780FF>Stormbreaker<\/color> is used:\\nCreates a shield that absorbs up to 16% of Beidou's Max HP for 15s.\\nThis shield absorbs <color=#FFACFFFF>Electro DMG<\/color> 250% more effectively."
        },
        "2": {
            "name": "Upon the Turbulent Sea, the Thunder Arises",
            "icon": "UI_Talent_S_Beidou_01",
            "text": "<color=#FFD780FF>Stormbreaker<\/color>'s arc lightning can jump to 2 additional targets."
        },
        "3": {
            "name": "Summoner of Storm",
            "icon": "UI_Talent_U_Beidou_01",
            "text": "Increases the Level of <color=#FFD780FF>Tidecaller<\/color> by 3.\\nMaximum upgrade level is 15."
        },
        "4": {
            "name": "Stunning Revenge",
            "icon": "UI_Talent_S_Beidou_03",
            "text": "Upon being attacked, Beidou's Normal Attacks gain an additional instance of 20% <color=#FFACFFFF>Electro DMG<\/color> for 10s."
        },
        "5": {
            "name": "Crimson Tidewalker",
            "icon": "UI_Talent_U_Beidou_02",
            "text": "Increases the Level of <color=#FFD780FF>Stormbreaker<\/color> by 3.\\nMaximum upgrade level is 15."
        },
        "6": {
            "name": "Bane of Evil",
            "icon": "UI_Talent_S_Beidou_04",
            "text": "While <color=#FFD780FF>Stormbreaker<\/color> is active, nearby opponents' <color=#FFACFFFF>Electro RES<\/color> is reduced by 15%.\\n\\n<color=#FFD780FF>Radiance: Stellar-Conduct<\/color>: The <color=#99FFFFFF>Cryo RES<\/color> of nearby opponents is decreased by 15%, and the Elemental Mastery of the current active character is increased by 200, while Stormbreaker is active."
        }
    }
};