export default {
    "talents": {
        "Normal Attack": {
            "name": "Invoker's Spear",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/0\/06\/Polearm_Electro.png",
            "text": "<color=#FFD780FF>Normal Attack<\/color>\\nPerforms up to 4 consecutive spear strikes.\\n\\n<color=#FFD780FF>Charged Attack<\/color>\\nConsumes a certain amount of Stamina to lunge forward, dealing damage to opponents along the way.\\n\\n<color=#FFD780FF>Plunging Attack<\/color>\\nPlunges from mid-air to strike the ground below, damaging opponents along the path and dealing AoE DMG upon impact.",
            "scaling": {
                "1-Hit DMG": [
                    "49.26%",
                    "53.27%",
                    "57.28%",
                    "63%",
                    "67.01%",
                    "71.6%",
                    "77.9%",
                    "84.2%",
                    "90.5%",
                    "97.37%",
                    "104.24%",
                    "111.12%",
                    "117.99%",
                    "124.86%",
                    "131.73%"
                ],
                "2-Hit DMG": [
                    "47.92%",
                    "51.82%",
                    "55.72%",
                    "61.29%",
                    "65.19%",
                    "69.65%",
                    "75.78%",
                    "81.91%",
                    "88.04%",
                    "94.73%",
                    "101.41%",
                    "108.1%",
                    "114.79%",
                    "121.47%",
                    "128.16%"
                ],
                "3-Hit DMG": [
                    "29.31%+29.31%",
                    "31.69%+31.69%",
                    "34.08%+34.08%",
                    "37.48%+37.48%",
                    "39.87%+39.87%",
                    "42.6%+42.6%",
                    "46.34%+46.34%",
                    "50.09%+50.09%",
                    "53.84%+53.84%",
                    "57.93%+57.93%",
                    "62.02%+62.02%",
                    "66.11%+66.11%",
                    "70.2%+70.2%",
                    "74.29%+74.29%",
                    "78.38%+78.38%"
                ],
                "4-Hit DMG": [
                    "75.89%",
                    "82.07%",
                    "88.24%",
                    "97.07%",
                    "103.25%",
                    "110.31%",
                    "120.01%",
                    "129.72%",
                    "139.43%",
                    "150.02%",
                    "160.61%",
                    "171.2%",
                    "181.78%",
                    "192.37%",
                    "202.96%"
                ],
                "Charged Attack DMG": [
                    "122.38%",
                    "132.34%",
                    "142.3%",
                    "156.53%",
                    "166.49%",
                    "177.87%",
                    "193.53%",
                    "209.18%",
                    "224.83%",
                    "241.91%",
                    "258.99%",
                    "276.06%",
                    "293.14%",
                    "310.21%",
                    "327.29%"
                ],
                "Charged Attack Stamina Cost": [
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25"
                ],
                "Plunge DMG": [
                    "63.93%",
                    "69.14%",
                    "74.34%",
                    "81.77%",
                    "86.98%",
                    "92.93%",
                    "101.1%",
                    "109.28%",
                    "117.46%",
                    "126.38%",
                    "135.3%",
                    "144.22%",
                    "153.14%",
                    "162.06%",
                    "170.98%"
                ],
                "Low\/High Plunge DMG": [
                    "127.84%\/159.68%",
                    "138.24%\/172.67%",
                    "148.65%\/185.67%",
                    "163.51%\/204.24%",
                    "173.92%\/217.23%",
                    "185.81%\/232.09%",
                    "202.16%\/252.51%",
                    "218.51%\/272.93%",
                    "234.86%\/293.36%",
                    "252.7%\/315.64%",
                    "270.54%\/337.92%",
                    "288.38%\/360.2%",
                    "306.22%\/382.48%",
                    "324.05%\/404.76%",
                    "341.89%\/427.04%"
                ]
            },
            "icon": "Skill_A_03"
        },
        "Elemental Skill": {
            "name": "Secret Rite: Chasmic Soulfarer",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/e\/e3\/Talent_Secret_Rite_Chasmic_Soulfarer.png",
            "text": "Performs a swift thrust, dealing <color=#FFACFFFF>Electro DMG<\/color> to opponents along the way.\\n\\nWhen Cyno is in the Pactsworn Pathclearer state, he will instead unleash a <color=#FFD780FF>Mortuary Rite<\/color> that deals thunderous <color=#FFACFFFF>AoE Electro DMG<\/color>. If Cyno enters the Pactsworn Pathclearer through the Elemental Burst <color=#FFD780FF>Sacred Rite: Wolf's Swiftness<\/color>, unleashing <color=#FFD780FF>Mortuary Rite<\/color> will also extend the duration of the current instance of Pactsworn Pathclearer.\\n\\n<i>\"This judgment brooks no choice. There is no rejection or acceptance here... We have both long been bound up in this conviction.\"<\/i>",
            "scaling": {
                "Skill DMG": [
                    "130.4%",
                    "140.18%",
                    "149.96%",
                    "163%",
                    "172.78%",
                    "182.56%",
                    "195.6%",
                    "208.64%",
                    "221.68%",
                    "234.72%",
                    "247.76%",
                    "260.8%",
                    "277.1%",
                    "293.4%",
                    "309.7%"
                ],
                "Mortuary Rite DMG": [
                    "156.8%",
                    "168.56%",
                    "180.32%",
                    "196%",
                    "207.76%",
                    "219.52%",
                    "235.2%",
                    "250.88%",
                    "266.56%",
                    "282.24%",
                    "297.92%",
                    "313.6%",
                    "333.2%",
                    "352.8%",
                    "372.4%"
                ],
                "Pactsworn Pathclearer Duration Bonus": [
                    "4s",
                    "4s",
                    "4s",
                    "4s",
                    "4s",
                    "4s",
                    "4s",
                    "4s",
                    "4s",
                    "4s",
                    "4s",
                    "4s",
                    "4s",
                    "4s",
                    "4s"
                ],
                "CD": [
                    "7.5s",
                    "7.5s",
                    "7.5s",
                    "7.5s",
                    "7.5s",
                    "7.5s",
                    "7.5s",
                    "7.5s",
                    "7.5s",
                    "7.5s",
                    "7.5s",
                    "7.5s",
                    "7.5s",
                    "7.5s",
                    "7.5s"
                ],
                "Mortuary Rite CD": [
                    "3s",
                    "3s",
                    "3s",
                    "3s",
                    "3s",
                    "3s",
                    "3s",
                    "3s",
                    "3s",
                    "3s",
                    "3s",
                    "3s",
                    "3s",
                    "3s",
                    "3s"
                ]
            },
            "icon": "Skill_S_Cyno_01"
        },
        "Elemental Burst": {
            "name": "Sacred Rite: Wolf's Swiftness",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/a\/a0\/Talent_Sacred_Rite_Wolf%27s_Swiftness.png",
            "text": "Calls upon a divine spirit to indwell him, morphing into the Pactsworn Pathclearer.\\n\\n<color=#FFD780FF>Pactsworn Pathclearer<\/color>\\nCyno's Normal, Charged, and Plunging Attacks will be converted to <color=#FFACFFFF>Electro DMG<\/color> that cannot be overridden.\\n\u00b7Cyno's Elemental Mastery and resistance to interruption will increase, and he gains immunity to Electro-Charged DMG.\\n\\nThis effect will be canceled when Cyno leaves the field and lasts a maximum of 18s.\\n\\n<i>The secret rituals passed down within the ancient nation are as a final judgment to the General Mahamatra.<\/i>\\n<i>Whether now or in the past, whether great storm or serpent, none shall shake the majesty of the law.<\/i>",
            "scaling": {
                "1-Hit DMG": [
                    "78.28%",
                    "84.66%",
                    "91.03%",
                    "100.13%",
                    "106.5%",
                    "113.78%",
                    "123.8%",
                    "133.81%",
                    "143.82%",
                    "154.75%",
                    "165.67%",
                    "176.59%",
                    "187.52%",
                    "198.44%",
                    "209.36%"
                ],
                "2-Hit DMG": [
                    "82.47%",
                    "89.18%",
                    "95.89%",
                    "105.48%",
                    "112.2%",
                    "119.87%",
                    "130.42%",
                    "140.96%",
                    "151.51%",
                    "163.02%",
                    "174.53%",
                    "186.03%",
                    "197.54%",
                    "209.05%",
                    "220.56%"
                ],
                "3-Hit DMG": [
                    "104.63%",
                    "113.15%",
                    "121.67%",
                    "133.83%",
                    "142.35%",
                    "152.08%",
                    "165.47%",
                    "178.85%",
                    "192.23%",
                    "206.83%",
                    "221.43%",
                    "236.03%",
                    "250.63%",
                    "265.23%",
                    "279.83%"
                ],
                "4-Hit DMG": [
                    "51.69%+51.69%",
                    "55.9%+55.9%",
                    "60.11%+60.11%",
                    "66.12%+66.12%",
                    "70.33%+70.33%",
                    "75.14%+75.14%",
                    "81.75%+81.75%",
                    "88.36%+88.36%",
                    "94.97%+94.97%",
                    "102.19%+102.19%",
                    "109.4%+109.4%",
                    "116.61%+116.61%",
                    "123.83%+123.83%",
                    "131.04%+131.04%",
                    "138.25%+138.25%"
                ],
                "5-Hit DMG": [
                    "130.84%",
                    "141.49%",
                    "152.15%",
                    "167.36%",
                    "178.01%",
                    "190.18%",
                    "206.92%",
                    "223.65%",
                    "240.39%",
                    "258.65%",
                    "276.9%",
                    "295.16%",
                    "313.42%",
                    "331.68%",
                    "349.93%"
                ],
                "Charged Attack DMG": [
                    "101.05%",
                    "109.27%",
                    "117.5%",
                    "129.25%",
                    "137.48%",
                    "146.88%",
                    "159.8%",
                    "172.72%",
                    "185.65%",
                    "199.75%",
                    "213.85%",
                    "227.95%",
                    "242.05%",
                    "256.15%",
                    "270.25%"
                ],
                "Charged Attack Stamina Cost": [
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25",
                    "25"
                ],
                "Plunge DMG": [
                    "63.93%",
                    "69.14%",
                    "74.34%",
                    "81.77%",
                    "86.98%",
                    "92.93%",
                    "101.1%",
                    "109.28%",
                    "117.46%",
                    "126.38%",
                    "135.3%",
                    "144.22%",
                    "153.14%",
                    "162.06%",
                    "170.98%"
                ],
                "Low\/High Plunge DMG": [
                    "127.84%\/159.68%",
                    "138.24%\/172.67%",
                    "148.65%\/185.67%",
                    "163.51%\/204.24%",
                    "173.92%\/217.23%",
                    "185.81%\/232.09%",
                    "202.16%\/252.51%",
                    "218.51%\/272.93%",
                    "234.86%\/293.36%",
                    "252.7%\/315.64%",
                    "270.54%\/337.92%",
                    "288.38%\/360.2%",
                    "306.22%\/382.48%",
                    "324.05%\/404.76%",
                    "341.89%\/427.04%"
                ],
                "Elemental Mastery Bonus": [
                    "100",
                    "100",
                    "100",
                    "100",
                    "100",
                    "100",
                    "100",
                    "100",
                    "100",
                    "100",
                    "100",
                    "100",
                    "100",
                    "100",
                    "100"
                ],
                "Basic Duration": [
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s"
                ],
                "CD": [
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s"
                ],
                "Energy Cost": [
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80"
                ]
            },
            "icon": "Skill_E_Cyno_01"
        },
        "1st Ascension Passive": {
            "name": "Featherfall Judgment",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/b\/b5\/Talent_Featherfall_Judgment.png",
            "text": "When Cyno is in the Pactsworn Pathclearer state, he will enter the Endseer stance at intervals. If he activates <color=#FFD780FF>Secret Rite: Chasmic Soulfarer<\/color> while affected by this stance, he will activate the Judication effect, increasing the DMG of this Secret Rite: Chasmic Soulfarer by 35%, and firing off 3 Duststalker Bolts that deal 100% of Cyno's ATK as <color=#FFACFFFF>Electro DMG.<\/color> Duststalker Bolt DMG is considered Elemental Skill DMG.\\n\\n<color=#FFD780FF>Radiance: Stellar-Conduct<\/color>: When Judication is triggered, Cyno will instead fire 3 <color=#FFD780FF>Duststalker Bolts - Starsame<\/color> to his front, dealing <color=#FFACFFFF>Electro DMG<\/color> at 200% of his ATK. This DMG is considered Stellar-Conduct DMG.",
            "icon": "UI_Talent_S_Cyno_05"
        },
        "4th Ascension Passive": {
            "name": "Authority Over the Nine Bows",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/e\/ed\/Talent_Authority_Over_the_Nine_Bows.png",
            "text": "Cyno's DMG values will be increased based on his Elemental Mastery as follows:\\n\u00b7 Pactsworn Pathclearer's Normal Attack DMG is increased by 150% of his Elemental Mastery.\\n\u00b7 Duststalker Bolt DMG from his Ascension Talent Featherfall Judgment is increased by 250% of his Elemental Mastery.\\n\u00b7 Duststalker Bolts - Starsame from the Ascension Talent \"Featherfall Judgment\": 600% of Elemental Mastery.",
            "icon": "UI_Talent_S_Cyno_06"
        },
        "Utility Passive": {
            "name": "The Gift of Silence",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/4\/4b\/Talent_The_Gift_of_Silence.png",
            "text": "Gains 25% more rewards when dispatched on a Sumeru Expedition for 20 hours.",
            "icon": "UI_Talent_S_Cyno_07"
        },
        "Passive": {
            "name": "A Star With Which to Start the Journey",
            "icon": "UI_Talent_S_Cyno_08",
            "text": "If Cyno unleashes the Elemental Skill <color=#FFD780FF>Secret Rite: Chasmic Soulfarer<\/color> while not in the Pactsworn Pathclearer state, he will enter Pactsworn Pathclearer for 6s.\\nAdditionally, when in a {LINK#N11330003}<color=#FFD780FF>Polestar Field<\/color>{\/LINK}, Cyno will enter the <color=#FFD780FF>Radiance: Stellar-Conduct<\/color> state."
        }
    },
    "constellations": {
        "1": {
            "name": "Ordinance: Unceasing Vigil",
            "icon": "UI_Talent_S_Cyno_01",
            "text": "After using <color=#FFD780FF>Sacred Rite: Wolf's Swiftness<\/color>, Cyno's Normal Attack SPD will be increased by 20% for 10s. If the Judication effect of his Ascension Talent Featherfall Judgment is triggered during <color=#FFD780FF>Secret Rite: Chasmic Soulfarer<\/color>, the duration of this increase will be refreshed.\\nYou must first unlock the Ascension Talent \"Featherfall Judgment.\"\\n\\n<color=#FFD780FF>Radiance: Stellar-Conduct<\/color>: When Cyno enters the Pactsworn Pathclearer state, he will also gain the <color=#FFD780FF>Together We Rise<\/color> effect: Elemental Mastery is increased by 200. During this time, when switching characters from Cyno on the field, the incoming active character will take on the <color=#FFD780FF>Together We Rise<\/color> effect for the remaining duration."
        },
        "2": {
            "name": "Ceremony: Homecoming of Spirits",
            "icon": "UI_Talent_S_Cyno_02",
            "text": "When Cyno's Normal Attacks hit opponents, his <color=#FFACFFFF>Electro DMG Bonus<\/color> will increase by 10% for 4s. This effect can be triggered once every 0.1s. Max 5 stacks.\\n\\nAdditionally, when characters affected by <color=#FFD780FF>Together We Rise<\/color> hit opponents with their Normal Attacks or Charged Attacks, their Stellar-Conduct DMG dealt is increased by 16%. This effect, which can trigger once every 0.1s, will remain active for the remaining duration of <color=#FFD780FF>Together We Rise<\/color>. Max 5 stacks."
        },
        "3": {
            "name": "Precept: Lawful Enforcer",
            "icon": "UI_Talent_U_Cyno_01",
            "text": "Increases the Level of <color=#FFD780FF>Sacred Rite: Wolf's Swiftness<\/color> by 3.\\nMaximum upgrade level is 15."
        },
        "4": {
            "name": "Austerity: Forbidding Guard",
            "icon": "UI_Talent_S_Cyno_03",
            "text": "When Cyno is in the Pactsworn Pathclearer state triggered by <color=#FFD780FF>Sacred Rite: Wolf's Swiftness<\/color>, after he triggers an Electro-Charged, Lunar-Charged, Superconduct, Stellar-Conduct, Overloaded, Quicken, Aggravate, Hyperbloom, or Electro Swirl reaction, he will restore 3 Elemental Energy to all nearby party members (except himself). This effect can occur 5 times within one use of <color=#FFD780FF>Sacred Rite: Wolf's Swiftness<\/color>.\\n\\nWhen other characters affected by <color=#FFD780FF>Together We Rise<\/color> trigger the aforementioned reaction, they will also regenerate 20 Elemental Energy for Cyno. This effect can trigger once every 18s."
        },
        "5": {
            "name": "Funerary Rite: The Passing of Starlight",
            "icon": "UI_Talent_U_Cyno_02",
            "text": "Increases the Level of <color=#FFD780FF>Secret Rite: Chasmic Soulfarer<\/color> by 3.\\nMaximum upgrade level is 15."
        },
        "6": {
            "name": "Raiment: Just Scales",
            "icon": "UI_Talent_S_Cyno_04",
            "text": "After using <color=#FFD780FF>Sacred Rite: Wolf's Swiftness<\/color> or triggering the Judication effect of the Ascension Talent \"Featherfall Judgment,\" Cyno will gain 4 stacks of the \"Day of the Jackal\" effect. When he hits opponents with Normal Attacks, he will consume 1 stack of \"Day of the Jackal\" to fire off one Duststalker Bolt. If Cyno is affected by <color=#FFD780FF>Together We Rise<\/color>, he will fire one <color=#FFD780FF>Duststalker Bolt\u00b7- Starsame<\/color> instead.\\nDay of the Jackal\" lasts for 8s. Max 8 stacks for each instance of Pactsworn Pathclearer. It will be canceled once Pactsworn Pathclearer from Sacred Rite: Wolf's Swiftness ends.\\nA maximum of 1 Duststalker Bolt or 1 Duststalker Bolt - Starsame can be unleashed this way every 0.4s.\\nYou must first unlock the Ascension Talent \"Featherfall Judgment.\""
        }
    }
};