export default {
    "talents": {
        "Normal Attack": {
            "name": "Peregrination of Linnunrata",
            "text": "<color=#FFD780FF>Normal Attack<\/color>\\nPerforms up to 3 attacks that deal <color=#99FF88FF>Dendro DMG<\/color>\\n\\n<color=#FFD780FF>Charged Attack<\/color>\\nLauma undergoes Spirit Envoy Metamorphosis, transforming into an envoy of the tranquil forest and consuming Stamina to charge forward for up to 10s. While in this state, Lauma's interruption resistance is increased, and she can consume additional Stamina to perform up to two consecutive jumps.\\nWhen exiting the Spirit Envoy state, Spirit Envoy Metamorphosis will enter cooldown, during which time, Lauma's Charged Attack will be transformed into Spiritcall Prayer: Consumes a certain amount of Stamina to deal <color=#99FF88FF>AoE Dendro DMG<\/color> to opponents in front of her after a short casting time.\\n\\n<color=#FFD780FF>Plunging Attack<\/color>\\nCalling upon the might of Dendro, Lauma plunges towards the ground from mid-air, damaging all opponents in her path and dealing <color=#99FF88FF>AoE Dendro DMG<\/color> upon impact with the ground.",
            "scaling": {
                "1-Hit DMG": {
                    "1": "33.7024%",
                    "2": "36.2301%",
                    "3": "38.7578%",
                    "4": "42.128%",
                    "5": "44.6557%",
                    "6": "47.1834%",
                    "7": "50.5536%",
                    "8": "53.9238%",
                    "9": "57.2941%",
                    "10": "60.6643%",
                    "11": "64.0346%",
                    "12": "67.4048%",
                    "13": "71.6176%",
                    "14": "75.8304%",
                    "15": "80.0432%"
                },
                "2-Hit DMG": {
                    "1": "31.8048%",
                    "2": "34.1902%",
                    "3": "36.5755%",
                    "4": "39.756%",
                    "5": "42.1414%",
                    "6": "44.5267%",
                    "7": "47.7072%",
                    "8": "50.8877%",
                    "9": "54.0682%",
                    "10": "57.2486%",
                    "11": "60.4291%",
                    "12": "63.6096%",
                    "13": "67.5852%",
                    "14": "71.5608%",
                    "15": "75.5364%"
                },
                "3-Hit DMG": {
                    "1": "44.4968%",
                    "2": "47.8341%",
                    "3": "51.1713%",
                    "4": "55.621%",
                    "5": "58.9583%",
                    "6": "62.2955%",
                    "7": "66.7452%",
                    "8": "71.1949%",
                    "9": "75.6446%",
                    "10": "80.0942%",
                    "11": "84.5439%",
                    "12": "88.9936%",
                    "13": "94.5557%",
                    "14": "100.1178%",
                    "15": "105.6799%"
                },
                "Spirit Envoy Form Movement Stamina Cost": {
                    "1": "25\/s",
                    "2": "25\/s",
                    "3": "25\/s",
                    "4": "25\/s",
                    "5": "25\/s",
                    "6": "25\/s",
                    "7": "25\/s",
                    "8": "25\/s",
                    "9": "25\/s",
                    "10": "25\/s",
                    "11": "25\/s",
                    "12": "25\/s",
                    "13": "25\/s",
                    "14": "25\/s",
                    "15": "25\/s"
                },
                "Spirit Envoy Form Jumping Stamina Cost": {
                    "1": "10",
                    "2": "10",
                    "3": "10",
                    "4": "10",
                    "5": "10",
                    "6": "10",
                    "7": "10",
                    "8": "10",
                    "9": "10",
                    "10": "10",
                    "11": "10",
                    "12": "10",
                    "13": "10",
                    "14": "10",
                    "15": "10"
                },
                "Spirit Envoy Form Max Duration": {
                    "1": "10s",
                    "2": "10s",
                    "3": "10s",
                    "4": "10s",
                    "5": "10s",
                    "6": "10s",
                    "7": "10s",
                    "8": "10s",
                    "9": "10s",
                    "10": "10s",
                    "11": "10s",
                    "12": "10s",
                    "13": "10s",
                    "14": "10s",
                    "15": "10s"
                },
                "Spirit Envoy Metamorphosis CD": {
                    "1": "4s",
                    "2": "4s",
                    "3": "4s",
                    "4": "4s",
                    "5": "4s",
                    "6": "4s",
                    "7": "4s",
                    "8": "4s",
                    "9": "4s",
                    "10": "4s",
                    "11": "4s",
                    "12": "4s",
                    "13": "4s",
                    "14": "4s",
                    "15": "4s"
                },
                "Spiritcall Prayer Stamina Cost": {
                    "1": "50",
                    "2": "50",
                    "3": "50",
                    "4": "50",
                    "5": "50",
                    "6": "50",
                    "7": "50",
                    "8": "50",
                    "9": "50",
                    "10": "50",
                    "11": "50",
                    "12": "50",
                    "13": "50",
                    "14": "50",
                    "15": "50"
                },
                "Spiritcall Prayer DMG": {
                    "1": "129.04%",
                    "2": "138.718%",
                    "3": "148.396%",
                    "4": "161.3%",
                    "5": "170.978%",
                    "6": "180.656%",
                    "7": "193.56%",
                    "8": "206.464%",
                    "9": "219.368%",
                    "10": "232.272%",
                    "11": "245.176%",
                    "12": "258.08%",
                    "13": "274.21%",
                    "14": "290.34%",
                    "15": "306.47%"
                },
                "Plunge DMG": {
                    "1": "56.8288%",
                    "2": "61.4544%",
                    "3": "66.08%",
                    "4": "72.688%",
                    "5": "77.3136%",
                    "6": "82.6%",
                    "7": "89.8688%",
                    "8": "97.1376%",
                    "9": "104.4064%",
                    "10": "112.336%",
                    "11": "120.2656%",
                    "12": "128.1952%",
                    "13": "136.1248%",
                    "14": "144.0544%",
                    "15": "151.984%"
                },
                "Low\/High Plunge DMG": {
                    "1": "113.6335%\/141.9344%",
                    "2": "122.8828%\/153.4872%",
                    "3": "132.132%\/165.04%",
                    "4": "145.3452%\/181.544%",
                    "5": "154.5944%\/193.0968%",
                    "6": "165.165%\/206.3%",
                    "7": "179.6995%\/224.4544%",
                    "8": "194.234%\/242.6088%",
                    "9": "208.7686%\/260.7632%",
                    "10": "224.6244%\/280.568%",
                    "11": "240.4802%\/300.3728%",
                    "12": "256.3361%\/320.1776%",
                    "13": "272.1919%\/339.9824%",
                    "14": "288.0478%\/359.7872%",
                    "15": "303.9036%\/379.592%"
                }
            }
        },
        "Elemental Skill": {
            "name": "Runo: Dawnless Rest of Karsikko",
            "text": "Silently incants an ancient hymn, summoning a {LINK#N11190001}<color=#FFD780FF>Frostgrove Sanctuary<\/color>{\/LINK} with different effects depending on whether you Tap or Hold.\\n\\n<color=#FFD780FF>Tap<\/color>\\nIntone a Hymn of Hunting, dealing <color=#99FF88FF>AoE Dendro DMG<\/color>.\\n\\n<color=#FFD780FF>Hold<\/color>\\nCan be unleashed when you have at least 1 {LINK#N11190008}<color=#FFD780FF>Verdant Dew<\/color>{\/LINK}. Lauma consumes all Verdant Dew and intones a Hymn of Eternal Rest, dealing one regular instance of <color=#99FF88FF>AoE Dendro DMG<\/color> and another instance of <color=#99FF88FF>AoE Dendro DMG<\/color> that is considered Lunar-Bloom DMG. Each Verdant Dew consumed will give Lauma one stack of {LINK#N11190002}<color=#FFD780FF>Moon Song<\/color>{\/LINK}. Each time you Hold to cast an Elemental Skill, a maximum of 3 Verdant Dew can be consumed in this way.\\n\\nAdditionally, when Lauma's Elemental Skill or attacks from Frostgrove Sanctuary hit an opponent, that opponent's <color=#99FF88FF>Dendro RES<\/color> and <color=#80C0FFFF>Hydro RES<\/color> will be decreased for 10s.",
            "scaling": {
                "Press DMG": {
                    "1": "121.6%",
                    "2": "130.72%",
                    "3": "139.84%",
                    "4": "152%",
                    "5": "161.12%",
                    "6": "170.24%",
                    "7": "182.4%",
                    "8": "194.56%",
                    "9": "206.72%",
                    "10": "218.88%",
                    "11": "231.04%",
                    "12": "243.2%",
                    "13": "258.4%",
                    "14": "273.6%",
                    "15": "288.8%"
                },
                "1-Hit Hold DMG": {
                    "1": "158.08%",
                    "2": "169.936%",
                    "3": "181.792%",
                    "4": "197.6%",
                    "5": "209.456%",
                    "6": "221.312%",
                    "7": "237.12%",
                    "8": "252.928%",
                    "9": "268.736%",
                    "10": "284.544%",
                    "11": "300.352%",
                    "12": "316.16%",
                    "13": "335.92%",
                    "14": "355.68%",
                    "15": "375.44%"
                },
                "2-Hit Hold DMG": {
                    "1": "152% Elemental Mastery Per Verdant Dew",
                    "2": "163.4% Elemental Mastery Per Verdant Dew",
                    "3": "174.8% Elemental Mastery Per Verdant Dew",
                    "4": "190% Elemental Mastery Per Verdant Dew",
                    "5": "201.4% Elemental Mastery Per Verdant Dew",
                    "6": "212.8% Elemental Mastery Per Verdant Dew",
                    "7": "228% Elemental Mastery Per Verdant Dew",
                    "8": "243.2% Elemental Mastery Per Verdant Dew",
                    "9": "258.4% Elemental Mastery Per Verdant Dew",
                    "10": "273.6% Elemental Mastery Per Verdant Dew",
                    "11": "288.8% Elemental Mastery Per Verdant Dew",
                    "12": "304% Elemental Mastery Per Verdant Dew",
                    "13": "323% Elemental Mastery Per Verdant Dew",
                    "14": "342% Elemental Mastery Per Verdant Dew",
                    "15": "361% Elemental Mastery Per Verdant Dew"
                },
                "Frostgrove Sanctuary Attack DMG": {
                    "1": "96% ATK+192% Elemental Mastery",
                    "2": "103.2% ATK+206.4% Elemental Mastery",
                    "3": "110.4% ATK+220.8% Elemental Mastery",
                    "4": "120% ATK+240% Elemental Mastery",
                    "5": "127.2% ATK+254.4% Elemental Mastery",
                    "6": "134.4% ATK+268.8% Elemental Mastery",
                    "7": "144% ATK+288% Elemental Mastery",
                    "8": "153.6% ATK+307.2% Elemental Mastery",
                    "9": "163.2% ATK+326.4% Elemental Mastery",
                    "10": "172.8% ATK+345.6% Elemental Mastery",
                    "11": "182.4% ATK+364.8% Elemental Mastery",
                    "12": "192% ATK+384% Elemental Mastery",
                    "13": "204% ATK+408% Elemental Mastery",
                    "14": "216% ATK+432% Elemental Mastery",
                    "15": "228% ATK+456% Elemental Mastery"
                },
                "Frostgrove Sanctuary Duration": {
                    "1": "15s",
                    "2": "15s",
                    "3": "15s",
                    "4": "15s",
                    "5": "15s",
                    "6": "15s",
                    "7": "15s",
                    "8": "15s",
                    "9": "15s",
                    "10": "15s",
                    "11": "15s",
                    "12": "15s",
                    "13": "15s",
                    "14": "15s",
                    "15": "15s"
                },
                "Moon Song Duration": {
                    "1": "15s",
                    "2": "15s",
                    "3": "15s",
                    "4": "15s",
                    "5": "15s",
                    "6": "15s",
                    "7": "15s",
                    "8": "15s",
                    "9": "15s",
                    "10": "15s",
                    "11": "15s",
                    "12": "15s",
                    "13": "15s",
                    "14": "15s",
                    "15": "15s"
                },
                "Elemental RES Decrease": {
                    "1": "2.5%",
                    "2": "5%",
                    "3": "7.5%",
                    "4": "10%",
                    "5": "12.5%",
                    "6": "15%",
                    "7": "17.5%",
                    "8": "20%",
                    "9": "22.5%",
                    "10": "25%",
                    "11": "28%",
                    "12": "31%",
                    "13": "34%",
                    "14": "37%",
                    "15": "40%"
                },
                "Elemental RES Decrease Duration": {
                    "1": "10s",
                    "2": "10s",
                    "3": "10s",
                    "4": "10s",
                    "5": "10s",
                    "6": "10s",
                    "7": "10s",
                    "8": "10s",
                    "9": "10s",
                    "10": "10s",
                    "11": "10s",
                    "12": "10s",
                    "13": "10s",
                    "14": "10s",
                    "15": "10s"
                },
                "CD": {
                    "1": "12s",
                    "2": "12s",
                    "3": "12s",
                    "4": "12s",
                    "5": "12s",
                    "6": "12s",
                    "7": "12s",
                    "8": "12s",
                    "9": "12s",
                    "10": "12s",
                    "11": "12s",
                    "12": "12s",
                    "13": "12s",
                    "14": "12s",
                    "15": "12s"
                }
            }
        },
        "Elemental Burst": {
            "name": "Runo: All Hearts Become the Beating Moon",
            "text": "Let the wishes of all beings become as moonlight that bathes the earth. Lauma incants a sacred song of the far north, gaining 18 stacks of {LINK#N11190003}<color=#FFD780FF>Pale Hymn<\/color>{\/LINK}.\\nAdditionally, if Lauma uses her Elemental Burst while she has {LINK#N11190002}<color=#FFD780FF>Moon Song<\/color>{\/LINK}, or she gains Moon Song within 15s of using her Elemental Burst, she will consume all Moon Song stacks and gain 6 stacks of Pale Hymn for every Moon Song stack consumed. This effect can only be triggered once for each Elemental Burst used, including the 15 seconds following its use.\\n\\n<color=#FFD780FF>Pale Hymn<\/color>\\nWhen nearby party members deal Bloom, Hyperbloom, Burgeon, or Lunar-Bloom DMG, 1 stack of Pale Hymn will be consumed and the DMG dealt will be increased based on Lauma's Elemental Mastery. If this DMG hits multiple opponents at once, then multiple stacks of Pale Hymn will be consumed, depending on how many opponents are hit.\\nThe duration for each stack of Pale Hymn is counted independently.",
            "scaling": {
                "Pale Hymn Stacks Gained From Elemental Burst": {
                    "1": "18",
                    "2": "18",
                    "3": "18",
                    "4": "18",
                    "5": "18",
                    "6": "18",
                    "7": "18",
                    "8": "18",
                    "9": "18",
                    "10": "18",
                    "11": "18",
                    "12": "18",
                    "13": "18",
                    "14": "18",
                    "15": "18"
                },
                "Moon Song to Pale Hymn Conversion": {
                    "1": "6 Stacks Per Moon Song",
                    "2": "6 Stacks Per Moon Song",
                    "3": "6 Stacks Per Moon Song",
                    "4": "6 Stacks Per Moon Song",
                    "5": "6 Stacks Per Moon Song",
                    "6": "6 Stacks Per Moon Song",
                    "7": "6 Stacks Per Moon Song",
                    "8": "6 Stacks Per Moon Song",
                    "9": "6 Stacks Per Moon Song",
                    "10": "6 Stacks Per Moon Song",
                    "11": "6 Stacks Per Moon Song",
                    "12": "6 Stacks Per Moon Song",
                    "13": "6 Stacks Per Moon Song",
                    "14": "6 Stacks Per Moon Song",
                    "15": "6 Stacks Per Moon Song"
                },
                "Bloom, Hyperbloom, and Burgeon DMG Increase": {
                    "1": "277.76% Elemental Mastery",
                    "2": "298.592% Elemental Mastery",
                    "3": "319.424% Elemental Mastery",
                    "4": "347.2% Elemental Mastery",
                    "5": "368.032% Elemental Mastery",
                    "6": "388.864% Elemental Mastery",
                    "7": "416.64% Elemental Mastery",
                    "8": "444.416% Elemental Mastery",
                    "9": "472.192% Elemental Mastery",
                    "10": "499.968% Elemental Mastery",
                    "11": "527.744% Elemental Mastery",
                    "12": "555.52% Elemental Mastery",
                    "13": "590.24% Elemental Mastery",
                    "14": "624.96% Elemental Mastery",
                    "15": "659.68% Elemental Mastery"
                },
                "Lunar-Bloom DMG Increase": {
                    "1": "222.24% Elemental Mastery",
                    "2": "238.908% Elemental Mastery",
                    "3": "255.576% Elemental Mastery",
                    "4": "277.8% Elemental Mastery",
                    "5": "294.468% Elemental Mastery",
                    "6": "311.136% Elemental Mastery",
                    "7": "333.36% Elemental Mastery",
                    "8": "355.584% Elemental Mastery",
                    "9": "377.808% Elemental Mastery",
                    "10": "400.032% Elemental Mastery",
                    "11": "422.256% Elemental Mastery",
                    "12": "444.48% Elemental Mastery",
                    "13": "472.26% Elemental Mastery",
                    "14": "500.04% Elemental Mastery",
                    "15": "527.82% Elemental Mastery"
                },
                "Pale Hymn Duration": {
                    "1": "15s",
                    "2": "15s",
                    "3": "15s",
                    "4": "15s",
                    "5": "15s",
                    "6": "15s",
                    "7": "15s",
                    "8": "15s",
                    "9": "15s",
                    "10": "15s",
                    "11": "15s",
                    "12": "15s",
                    "13": "15s",
                    "14": "15s",
                    "15": "15s"
                },
                "CD": {
                    "1": "15s",
                    "2": "15s",
                    "3": "15s",
                    "4": "15s",
                    "5": "15s",
                    "6": "15s",
                    "7": "15s",
                    "8": "15s",
                    "9": "15s",
                    "10": "15s",
                    "11": "15s",
                    "12": "15s",
                    "13": "15s",
                    "14": "15s",
                    "15": "15s"
                },
                "Energy Cost": {
                    "1": "60",
                    "2": "60",
                    "3": "60",
                    "4": "60",
                    "5": "60",
                    "6": "60",
                    "7": "60",
                    "8": "60",
                    "9": "60",
                    "10": "60",
                    "11": "60",
                    "12": "60",
                    "13": "60",
                    "14": "60",
                    "15": "60"
                }
            }
        },
        "1st Ascension Passive": {
            "name": "Light for the Frosty Night",
            "text": "For the next 20s after Lauma uses her Elemental Skill <color=#FFD780FF>{LINK#S11192}Runo: Dawnless Rest of Karsikko{\/LINK}<\/color>, corresponding differing buff effects will be granted depending on the party's <color=#FFD780FF>Moonsign<\/color>. The buffs provided by different Moonsign levels cannot stack.\\n\\n<color=#FFD780FF>Moonsign: Nascent Gleam<\/color>\\nBloom, Hyperbloom, and Burgeon DMG dealt by all nearby party members can score CRIT Hits, with CRIT Rate fixed at 15%, and CRIT DMG fixed at 100%. CRIT Rate from this effect stacks with CRIT Rate from similar effects that allow these Elemental Reactions to CRIT.\\n\\n<color=#FFD780FF>Moonsign: Ascendant Gleam<\/color>\\nAll nearby party members' Lunar-Bloom DMG CRIT Rate +10%, CRIT DMG +20%."
        },
        "4th Ascension Passive": {
            "name": "Cleansing for the Spring",
            "text": "Each point of Elemental Mastery Lauma has will give her the following bonuses:\\n\u00b7 DMG dealt by her Elemental Skill is increased by 0.04%. The maximum increase obtainable this way is 32%.\\n\u00b7 The cooldown of her Charged Attack <color=#FFD780FF>Spirit Envoy Metamorphosis<\/color> is reduced by 0.02%. The maximum reduction obtainable this way is 20%."
        },
        "Utility Passive": {
            "name": "Moonsign Benediction: Nature's Chorus",
            "text": "When a Bloom reaction is triggered by a party member, it will be converted into the Lunar-Bloom reaction, with every point of Elemental Mastery that Lauma has increasing Lunar-Bloom's Base DMG by 0.0175%, up to a maximum of 14%.\\n\\nAdditionally, when Lauma is in the party, the party's <color=#FFD780FF>Moonsign<\/color> will increase by 1 level."
        },
        "Passive": {
            "name": "Prayers for the Forest",
            "text": "Displays the location of nearby <color=#FFD780FF>resources unique to Nod-Krai<\/color> on the mini-map.\\nAdditionally, Lauma appears to have a special affinity with some small animals affected by kuuvahki..."
        }
    },
    "constellations": {
        "1": {
            "name": "\"O Lips, Weave Me Songs and Psalms\"",
            "text": "After Lauma uses her Elemental Skill <color=#FFD780FF>{LINK#S11192}Runo: Dawnless Rest of Karsikko{\/LINK}<\/color> or her Elemental Burst <color=#FFD780FF>{LINK#S11195}Runo: All Hearts Become the Beating Moon{\/LINK}<\/color>, she will gain Threads of Life for 20s.\\nDuring this time, when nearby party members trigger Lunar-Bloom reactions, nearby active characters will recover HP equal to 500% of Lauma's Elemental Mastery. This effect can be triggered once every 1.9s.\\nAdditionally, the Stamina cost for Lauma's Spirit Envoy Form will be reduced by 40%, and its Max Duration will be extended by 5s."
        },
        "2": {
            "name": "\"Twine Warnings and Tales From the North\"",
            "text": "The Elemental Burst <color=#FFD780FF>{LINK#S11195}Runo: All Hearts Become the Beating Moon{\/LINK}<\/color> is enhanced:\\n\u00b7 {LINK#N11190003}<color=#FFD780FF>Pale Hymn<\/color>{\/LINK} effects are increased: All nearby party members' Bloom, Hyperbloom, and Burgeon DMG is further increased by 500% of Lauma's Elemental Mastery, and their Lunar-Bloom DMG is further increased by 400% of Lauma's Elemental Mastery.\\n\\n<color=#FFD780FF>Moonsign: Ascendant Gleam<\/color>: All nearby party members' Lunar-Bloom DMG is increased by 40%."
        },
        "3": {
            "name": "\"Seek Not to Tread the Sly Fox's Path\"",
            "text": "Increases the Level of <color=#FFD780FF>{LINK#S11195}Runo: All Hearts Become the Beating Moon{\/LINK}<\/color> by 3.\\nMaximum upgrade level is 15."
        },
        "4": {
            "name": "\"Nor Yearn for the Great Bear's Might\"",
            "text": "When attacks from the {LINK#N11190001}<color=#FFD780FF>Frostgrove Sanctuary<\/color>{\/LINK} summoned by her Elemental Skill <color=#FFD780FF>{LINK#S11192}Runo: Dawnless Rest of Karsikko{\/LINK}<\/color> hit opponents, Lauma will regain 4 Elemental Energy. This effect can be triggered once every 5s."
        },
        "5": {
            "name": "\"If Truth May Be Subject to Witness\"",
            "text": "Increases the Level of <color=#FFD780FF>{LINK#S11192}Runo: Dawnless Rest of Karsikko{\/LINK}<\/color> by 3.\\nMaximum upgrade level is 15."
        },
        "6": {
            "name": "\"I Offer Blood and Tears to the Moonlight\"",
            "text": "When the {LINK#N11190001}<color=#FFD780FF>Frostgrove Sanctuary<\/color>{\/LINK} attacks opponents, it will deal 1 additional instance of <color=#99FF88FF>AoE Dendro DMG<\/color> equal to 185% of Lauma's Elemental Mastery. This DMG is considered Lunar-Bloom DMG. This instance of DMG will not consume any {LINK#N11190003}<color=#FFD780FF>Pale Hymn<\/color>{\/LINK} stacks and will provide Lauma with 2 stacks of Pale Hymn, as well as refreshing the duration of Pale Hymn stacks gained in this manner.\\nThis effect can occur up to 8 times during each Frostgrove Sanctuary. When using the Elemental Skill <color=#FFD780FF>{LINK#S11192}Runo: Dawnless Rest of Karsikko{\/LINK}<\/color>, all Pale Hymn stacks gained in this manner will be removed.\\n\\nAdditionally, when Lauma uses a Normal Attack while she has Pale Hymn stacks, she will consume 1 stack to convert this to deal <color=#99FF88FF>Dendro DMG<\/color> equal to 150% of her Elemental Mastery. This DMG is considered Lunar-Bloom DMG.\\n\\n<color=#FFD780FF>Moonsign: Ascendant Gleam<\/color>: All nearby party members' Lunar-Bloom DMG is {LINK#N11190007}<color=#FFD780FF>elevated<\/color>{\/LINK} by 25%."
        }
    }
};