export default {
    "talents": {
        "Normal Attack": {
            "name": "Allegoria",
            "icon": "Skill_A_Catalyst_MD",
            "text": "<color=#FFD780FF>Normal Attack<\/color>\\nProclaims a decree in the primordial tongue and performs up to 3 attacks that deal <color=#FF9999FF>Pyro DMG<\/color>.\\n\\n<color=#FFD780FF>Charged Attack<\/color>\\nConsumes a certain amount of Stamina to deal <color=#FF9999FF>AoE Pyro DMG<\/color> to opponents in front of her after a short casting time.\\n\\n<color=#FFD780FF>Plunging Attack<\/color>\\nNicole plunges towards the ground from mid-air, damaging all opponents in her path. Also deals <color=#FF9999FF>AoE Pyro DMG<\/color> upon impact with the ground.",
            "scaling": {
                "1-Hit DMG": [
                    "35.18%",
                    "37.82%",
                    "40.46%",
                    "43.97%",
                    "46.61%",
                    "49.25%",
                    "52.77%",
                    "56.29%",
                    "59.8%",
                    "63.32%",
                    "66.84%",
                    "70.36%",
                    "74.76%",
                    "79.15%",
                    "83.55%"
                ],
                "2-Hit DMG": [
                    "29.63%",
                    "31.86%",
                    "34.08%",
                    "37.04%",
                    "39.26%",
                    "41.49%",
                    "44.45%",
                    "47.41%",
                    "50.38%",
                    "53.34%",
                    "56.3%",
                    "59.27%",
                    "62.97%",
                    "66.68%",
                    "70.38%"
                ],
                "3-Hit DMG": [
                    "46.19%",
                    "49.65%",
                    "53.12%",
                    "57.74%",
                    "61.2%",
                    "64.66%",
                    "69.28%",
                    "73.9%",
                    "78.52%",
                    "83.14%",
                    "87.76%",
                    "92.38%",
                    "98.15%",
                    "103.92%",
                    "109.7%"
                ],
                "Charged Attack DMG": [
                    "112.32%",
                    "120.74%",
                    "129.17%",
                    "140.4%",
                    "148.82%",
                    "157.25%",
                    "168.48%",
                    "179.71%",
                    "190.94%",
                    "202.18%",
                    "213.41%",
                    "224.64%",
                    "238.68%",
                    "252.72%",
                    "266.76%"
                ],
                "Charged Attack Stamina Cost": [
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50"
                ],
                "Plunge DMG": [
                    "56.83%",
                    "61.45%",
                    "66.08%",
                    "72.69%",
                    "77.31%",
                    "82.6%",
                    "89.87%",
                    "97.14%",
                    "104.41%",
                    "112.34%",
                    "120.27%",
                    "128.2%",
                    "136.12%",
                    "144.05%",
                    "151.98%"
                ],
                "Low\/High Plunge DMG": [
                    "113.63%\/141.93%",
                    "122.88%\/153.49%",
                    "132.13%\/165.04%",
                    "145.35%\/181.54%",
                    "154.59%\/193.1%",
                    "165.16%\/206.3%",
                    "179.7%\/224.45%",
                    "194.23%\/242.61%",
                    "208.77%\/260.76%",
                    "224.62%\/280.57%",
                    "240.48%\/300.37%",
                    "256.34%\/320.18%",
                    "272.19%\/339.98%",
                    "288.05%\/359.79%",
                    "303.9%\/379.59%"
                ]
            }
        },
        "Elemental Skill": {
            "name": "Revelation: Uncreated Light",
            "icon": "Skill_S_Nicole_01",
            "text": "Recreates a fleeting glimpse of an age long past, when the angels acted on the authority of the heavens, bestowing the {LINK#N11310001}<color=#FFD780FF>Grace of Kenosis<\/color>{\/LINK}{LINK#N11310002}{\/LINK} effect on nearby party members. This increases their ATK and deals <color=#FF9999FF>AoE Pyro DMG<\/color>, as well as creates a Shield of Blazing Light.\\nThe Shield of Blazing Light's DMG Absorption is based on Nicole's ATK, and it will absorb <color=#FF9999FF>Pyro DMG<\/color> at 250% effectiveness.\n\\n\\n<i>\"Light is not a product of creation, and yet it has been favored and shaped into the miracle of human reason. Only the uncreated may caress the visage of eternity. That is why the unwritten word has value beyond anything put to paper.\"\\n\"What do you think? A fine excuse not to pick up the pen myself, wouldn't you say? Doesn't it sound just like one of those bits of 'ancient wisdom' that sound so profound, but no one really understands?\"<\/i>",
            "scaling": {
                "Skill DMG": [
                    "138.4%",
                    "148.78%",
                    "159.16%",
                    "173%",
                    "183.38%",
                    "193.76%",
                    "207.6%",
                    "221.44%",
                    "235.28%",
                    "249.12%",
                    "262.96%",
                    "276.8%",
                    "294.1%",
                    "311.4%",
                    "328.7%"
                ],
                "Shield DMG Absorption": [
                    "221.18% ATK+1387",
                    "237.77% ATK+1525",
                    "254.36% ATK+1676",
                    "276.48% ATK+1837",
                    "293.07% ATK+2011",
                    "309.66% ATK+2196",
                    "331.78% ATK+2392",
                    "353.89% ATK+2600",
                    "376.01% ATK+2820",
                    "398.13% ATK+3051",
                    "420.25% ATK+3294",
                    "442.37% ATK+3548",
                    "470.02% ATK+3814",
                    "497.66% ATK+4091",
                    "525.31% ATK+4380"
                ],
                "Shield Duration": [
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s"
                ],
                "Grace of Kenosis ATK Bonus Ratio": [
                    "8.25% ATK",
                    "9% ATK",
                    "9.75% ATK",
                    "10.5% ATK",
                    "11.25% ATK",
                    "12% ATK",
                    "12.75% ATK",
                    "13.5% ATK",
                    "14.25% ATK",
                    "15% ATK",
                    "15.9% ATK",
                    "16.8% ATK",
                    "17.7% ATK",
                    "18.6% ATK",
                    "19.5% ATK"
                ],
                "Grace of Kenosis Max ATK Bonus": [
                    "330",
                    "360",
                    "390",
                    "420",
                    "450",
                    "480",
                    "510",
                    "540",
                    "570",
                    "600",
                    "636",
                    "672",
                    "708",
                    "744",
                    "780"
                ],
                "Grace of Kenosis Duration": [
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s"
                ],
                "CD": [
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s"
                ]
            }
        },
        "Elemental Burst": {
            "name": "Revelation: Ladder of Divine Ascent",
            "icon": "Skill_E_Nicole_01",
            "text": "As Nicole weaves the path of anchored fate with golden threads of light, she deals <color=#FF9999FF>AoE Pyro DMG<\/color> and switches to Silent Contemplation mode.\\nIn this mode, when nearby active party members hit an opponent, an Arcane Projection is summoned to perform a Coordinated Attack against the opponent, dealing AoE Elemental DMG of the character's corresponding Elemental Type. This DMG scales based on the corresponding character's ATK and will be considered as having been dealt by them.\\nThis effect can occur once every 3s, and can be triggered up to 4 times each time Nicole switches to Silent Contemplation mode.\\n\\nIt is worth noting that Hexerei characters' Arcane Projections appear to differ somehow in appearance from the others...\n\\n\\n<i>\"Hmm? You want to know the principles that underpin the divine plan? Hah, that's an easy one \u2014 ever heard of the saying, 'The gods became human so that humans could become gods; the gods walked as humans so that humans could walk as gods'?\"\\n\"Though the civilization that gave us this saying \u2014 I fear even uttering their name could invite disaster \u2014 is now gone, I don't see any harm in passing on their words to you... Well, even if there is harm in it, the harm's already done. Ahem... In any case, what you should understand is that they who dwell above...\"\\n\"...Hmm, on second thought, I really shouldn't say \u2014 I'm afraid I can't answer your question right now. How about we talk about something else?\"<\/i>",
            "scaling": {
                "Skill DMG": [
                    "316.8%",
                    "340.56%",
                    "364.32%",
                    "396%",
                    "419.76%",
                    "443.52%",
                    "475.2%",
                    "506.88%",
                    "538.56%",
                    "570.24%",
                    "601.92%",
                    "633.6%",
                    "673.2%",
                    "712.8%",
                    "752.4%"
                ],
                "Arcane Projection DMG": [
                    "99% Corresponding Character's ATK",
                    "108% Corresponding Character's ATK",
                    "117% Corresponding Character's ATK",
                    "126% Corresponding Character's ATK",
                    "135% Corresponding Character's ATK",
                    "144% Corresponding Character's ATK",
                    "153% Corresponding Character's ATK",
                    "162% Corresponding Character's ATK",
                    "171% Corresponding Character's ATK",
                    "180% Corresponding Character's ATK",
                    "190.8% Corresponding Character's ATK",
                    "201.6% Corresponding Character's ATK",
                    "212.4% Corresponding Character's ATK",
                    "223.2% Corresponding Character's ATK",
                    "234% Corresponding Character's ATK"
                ],
                "Arcane Projection Attack Count": [
                    "4",
                    "4",
                    "4",
                    "4",
                    "4",
                    "4",
                    "4",
                    "4",
                    "4",
                    "4",
                    "4",
                    "4",
                    "4",
                    "4",
                    "4"
                ],
                "Silent Contemplation Duration": [
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s"
                ],
                "CD": [
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s"
                ],
                "Energy Cost": [
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60"
                ]
            }
        },
        "1st Ascension Passive": {
            "name": "Methexis",
            "icon": "UI_Talent_S_Nicole_05",
            "text": "For 20s after unleashing the Elemental Skill <color=#FFD780FF>{LINK#S11312}Revelation: Uncreated Light{\/LINK}<\/color>, Nicole will continuously \"observe\" the other current active party members. After the observed character has remained on the field for 3s, their {LINK#N11310001}<color=#FFD780FF>Grace of Kenosis<\/color>{\/LINK} is upgraded to {LINK#N11310002}<color=#FFD780FF>Guidance of Theosis<\/color>{\/LINK}, increasing their ATK by an additional 300. If the observed character is a Hexerei character, <color=#FFD780FF>Grace of Kenosis<\/color> is upgraded to <color=#FFD780FF>Guidance of Theosis<\/color> straight away.\\nWhen characters other than Nicole who have <color=#FFD780FF>Guidance of Theosis<\/color> leave the field, their effect reverts to <color=#FFD780FF>Grace of Kenosis<\/color>."
        },
        "4th Ascension Passive": {
            "name": "Philokalia",
            "icon": "UI_Talent_S_Nicole_06",
            "text": "When Elemental DMG from nearby active party members hits an opponent, Nicole's own {LINK#N11310001}<color=#FFD780FF>Grace of Kenosis<\/color>{\/LINK} effect is upgraded to {LINK#N11310002}<color=#FFD780FF>Guidance of Theosis<\/color>{\/LINK} for 8s."
        },
        "Utility Passive": {
            "name": "Nepsis",
            "icon": "UI_Talent_S_Nicole_08",
            "text": "When you are in Teyvat and not in combat, Nicole's Charged Attack becomes \"Emissarial Guidance\" if you have already obtained the current region's Treasure Compass. Emissarial Guidance: Calls upon nearby Seelie to show the way, triggering an effect similar to the region's Treasure Compass.\\nThis effect has a cooldown time of 5 seconds and does not work in Domains, Trounce Domains, and the Spiral Abyss."
        },
        "Passive": {
            "name": "Witch's Eve Rite: Light in the Darkness",
            "icon": "UI_Talent_S_Nicole_07",
            "text": "After completing <color=#FFD780FF>Witch's Homework: The Role of a Guide...?<\/color>, Nicole becomes a <color=#FFD780FF>Hexerei<\/color> character. When the party includes at least 2 Hexerei characters, you gain the <color=#FFD780FF>Hexerei: Secret Rite<\/color> effect, which enhances Hexerei characters.\\n\\n<color=#FFD780FF>Hexerei: Secret Rite<\/color>\\nIncreases the DMG dealt by Hexerei characters' <color=#FFD780FF>{LINK#S11315}Arcane Projections{\/LINK}<\/color> by 300% of Nicole's ATK."
        }
    },
    "constellations": {
        "1": {
            "name": "\"Do Not Be Afraid, Child Who Is Loved\"",
            "icon": "UI_Talent_S_Nicole_01",
            "text": "When the current active character of your own in the party hits an opponent, an additional special \"Arcane Projection: Unity\" will be summoned to perform a Coordinated Attack against the opponent, dealing AoE Elemental DMG of the character's corresponding Elemental Type at 600% of their ATK. This DMG will be considered as having been dealt by the corresponding character.\\nThis effect can trigger once every 6s."
        },
        "2": {
            "name": "\"I Will Guide You and Show You the Path You Should Tread\"",
            "icon": "UI_Talent_S_Nicole_02",
            "text": "Enhances the effects of the Elemental Skill <color=#FFD780FF>{LINK#S11312}Revelation: Uncreated Light{\/LINK}<\/color>: {LINK#N11310001}<color=#FFD780FF>Grace of Kenosis<\/color>{\/LINK} increases ATK by an additional 300 (which does not count toward this effect's ATK Bonus limit), while {LINK#N11310002}<color=#FFD780FF>Guidance of Theosis<\/color>{\/LINK} decreases nearby opponents' Elemental RES based on the corresponding character's Elemental Type by 25%. This effect does not stack for the same Element.\\nAdditionally, when Nicole unleashes her Elemental Skill <color=#FFD780FF>Revelation: Uncreated Light<\/color>, nearby active party members will also gain a Shield of Blazing Light."
        },
        "3": {
            "name": "\"A Lamp by Your Side, A Light to Shine the Way\"",
            "icon": "UI_Talent_U_Nicole_01",
            "text": "Increases the Level of <color=#FFD780FF>{LINK#S11312}Revelation: Uncreated Light{\/LINK}<\/color> by 3.\\nMaximum upgrade level is 15."
        },
        "4": {
            "name": "\"Whether Left or Right, No Matter Which Way You Turn\"",
            "icon": "UI_Talent_S_Nicole_03",
            "text": "When nearby party members have their {LINK#N11310001}<color=#FFD780FF>Grace of Kenosis<\/color>{\/LINK} upgraded to {LINK#N11310002}<color=#FFD780FF>Guidance of Theosis<\/color>{\/LINK}, Nicole also bestows upon them the Pathfinder's Blessing effect for 20s. Each character can gain this effect once every 16s.\\nThe Normal Attack, Charged Attack, Plunging Attack, Elemental Skill, and Elemental Burst DMG of characters with Pathfinder's Blessing is increased by 70% of Nicole's ATK. This effect will be removed once it has taken effect 8 times or when its duration is over.\\nWhen multiple opponents are hit at once, instances of Pathfinder's Blessing are consumed equal to the number of opponents hit. Each character's Pathfinder's Blessing is counted independently."
        },
        "5": {
            "name": "\"You Will Hear My Voice Beside You\"",
            "icon": "UI_Talent_U_Nicole_02",
            "text": "Increases the Level of <color=#FFD780FF>{LINK#S11315}Revelation: Ladder of Divine Ascent{\/LINK}<\/color> by 3.\\nMaximum upgrade level is 15."
        },
        "6": {
            "name": "\"This Is the Path, Walk It Without Delay\"",
            "icon": "UI_Talent_S_Nicole_04",
            "text": "When Nicole's {LINK#N11310001}<color=#FFD780FF>Grace of Kenosis<\/color>{\/LINK} is upgraded to {LINK#N11310002}<color=#FFD780FF>Guidance of Theosis<\/color>{\/LINK}, all nearby party members' <color=#FFD780FF>Grace of Kenosis<\/color> will also be upgraded to <color=#FFD780FF>Guidance of Theosis<\/color>. Once upgraded, <color=#FFD780FF>Guidance of Theosis<\/color> will no longer revert to <color=#FFD780FF>Grace of Kenosis<\/color>.\\nAdditionally, DMG dealt by characters with <color=#FFD780FF>Guidance of Theosis<\/color> will ignore 40% of opponents' DEF."
        }
    }
};