export default {
    "talents": {
        "Normal Attack": {
            "name": "Snow Swan Variation",
            "icon": "Skill_A_01",
            "text": "<color=#FFD780FF>Normal Attack<\/color>\\nUnleashes a sword attack of up to 5 consecutive strikes.\\n\\n<color=#FFD780FF>Charged Attack<\/color>\\nConsumes a certain amount of Stamina to unleash a dazzling slash on opponents in front of her.\\n\\n<color=#FFD780FF>Plunging Attack<\/color>\\nAttacks opponents in her path while plunging from mid-air, then deals AoE DMG upon landing.",
            "scaling": {
                "1-Hit DMG": [
                    "51.86%",
                    "56.08%",
                    "60.3%",
                    "66.33%",
                    "70.55%",
                    "75.37%",
                    "82.01%",
                    "88.64%",
                    "95.27%",
                    "102.51%",
                    "109.74%",
                    "116.98%",
                    "124.22%",
                    "131.45%",
                    "138.69%"
                ],
                "2-Hit DMG": [
                    "51.51%",
                    "55.7%",
                    "59.9%",
                    "65.89%",
                    "70.08%",
                    "74.87%",
                    "81.46%",
                    "88.05%",
                    "94.64%",
                    "101.82%",
                    "109.01%",
                    "116.2%",
                    "123.39%",
                    "130.57%",
                    "137.76%"
                ],
                "3-Hit DMG": [
                    "32.61%+38.28%",
                    "35.27%+41.39%",
                    "37.92%+44.51%",
                    "41.71%+48.96%",
                    "44.37%+52.08%",
                    "47.4%+55.64%",
                    "51.57%+60.53%",
                    "55.74%+65.43%",
                    "59.91%+70.33%",
                    "64.46%+75.67%",
                    "69.01%+81.01%",
                    "73.56%+86.35%",
                    "78.12%+91.69%",
                    "82.67%+97.03%",
                    "87.22%+102.37%"
                ],
                "4-Hit DMG": [
                    "74.57%",
                    "80.64%",
                    "86.71%",
                    "95.38%",
                    "101.45%",
                    "108.39%",
                    "117.93%",
                    "127.47%",
                    "137.01%",
                    "147.41%",
                    "157.82%",
                    "168.22%",
                    "178.63%",
                    "189.03%",
                    "199.44%"
                ],
                "5-Hit DMG": [
                    "90.21%",
                    "97.56%",
                    "104.9%",
                    "115.39%",
                    "122.73%",
                    "131.12%",
                    "142.66%",
                    "154.2%",
                    "165.74%",
                    "178.33%",
                    "190.91%",
                    "203.5%",
                    "216.09%",
                    "228.68%",
                    "241.27%"
                ],
                "Charged Attack DMG": [
                    "107.41%",
                    "116.16%",
                    "124.9%",
                    "137.39%",
                    "146.13%",
                    "156.12%",
                    "169.86%",
                    "183.6%",
                    "197.34%",
                    "212.33%",
                    "227.32%",
                    "242.31%",
                    "257.29%",
                    "272.28%",
                    "287.27%"
                ],
                "Charged Attack Stamina Cost": [
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20"
                ],
                "Plunge DMG": [
                    "63.93%",
                    "69.14%",
                    "74.34%",
                    "81.77%",
                    "86.98%",
                    "92.93%",
                    "101.1%",
                    "109.28%",
                    "117.46%",
                    "126.38%",
                    "135.3%",
                    "144.22%",
                    "153.14%",
                    "162.06%",
                    "170.98%"
                ],
                "Low\/High Plunge DMG": [
                    "127.84%\/159.68%",
                    "138.24%\/172.67%",
                    "148.65%\/185.67%",
                    "163.51%\/204.24%",
                    "173.92%\/217.23%",
                    "185.81%\/232.09%",
                    "202.16%\/252.51%",
                    "218.51%\/272.93%",
                    "234.86%\/293.36%",
                    "252.7%\/315.64%",
                    "270.54%\/337.92%",
                    "288.38%\/360.2%",
                    "306.22%\/382.48%",
                    "324.05%\/404.76%",
                    "341.89%\/427.04%"
                ]
            }
        },
        "Elemental Skill": {
            "name": "Adagio: Phantom Night Dancers",
            "icon": "Skill_S_Odette_01",
            "text": "With slow, graceful dance steps, Odette deals <color=#99FFFFFF>AoE Cryo DMG<\/color> to the opponent, and also summons her {LINK#N11500001}<color=#FFD780FF>Solo Dance Double<\/color>{\/LINK} to the field.\\nIf a <color=#FFD780FF>Dance Double<\/color> summoned by Odette is already on the field, this will re-summon the Dance Double and reset its duration.\\n\\n<color=#FFD780FF>Solo Dance Double<\/color>\\nAlternates between the <color=#FFD780FF>Plume<\/color> and <color=#FFD780FF>Wing<\/color> dance moves, periodically attacking nearby opponents and dealing to them <color=#99FFFFFF>AoE Cryo DMG<\/color>.\\nAdditionally, for 6s after unleashing the Elemental Skill <color=#FFD780FF>Adagio: Phantom Night Dancers<\/color>, Odette's Elemental Skill <color=#FFD780FF>Adagio: Phantom Night Dancers<\/color> will become the special Elemental Skill {LINK#N11500002}<color=#FFD780FF>Adagio: Coda at Dawn's Tolling<\/color>{\/LINK} instead, where a dance duet deals <color=#99FFFFFF>AoE Cryo DMG<\/color> to nearby opponents over time. Then, when the duet ends, she deals another instance of <color=#99FFFFFF>AoE Cryo DMG<\/color> that is considered Stellar-Conduct or Stellar Swirl DMG.\n\\n\\n<i>\"Dance, o candle flame of winter, dance!\"\\n\"Pain and tears, laughter and happiness... Life, o life! Life is but a fleeting solo dance: one is only briefly alive with music and mirth before they fade into silence as the curtain falls...\"<\/i>",
            "scaling": {
                "Skill DMG": [
                    "108.08%",
                    "116.19%",
                    "124.29%",
                    "135.1%",
                    "143.21%",
                    "151.31%",
                    "162.12%",
                    "172.93%",
                    "183.74%",
                    "194.54%",
                    "205.35%",
                    "216.16%",
                    "229.67%",
                    "243.18%",
                    "256.69%"
                ],
                "Coda at Dawn's Tolling DoT": [
                    "95.84%",
                    "103.03%",
                    "110.22%",
                    "119.8%",
                    "126.99%",
                    "134.18%",
                    "143.76%",
                    "153.34%",
                    "162.93%",
                    "172.51%",
                    "182.1%",
                    "191.68%",
                    "203.66%",
                    "215.64%",
                    "227.62%"
                ],
                "Coda at Dawn's Tolling Stellar-Conduct\/Stellar Swirl DMG": [
                    "305.76%\/458.64%",
                    "328.69%\/493.04%",
                    "351.62%\/527.44%",
                    "382.2%\/573.3%",
                    "405.13%\/607.7%",
                    "428.06%\/642.1%",
                    "458.64%\/687.96%",
                    "489.22%\/733.82%",
                    "519.79%\/779.69%",
                    "550.37%\/825.55%",
                    "580.94%\/871.42%",
                    "611.52%\/917.28%",
                    "649.74%\/974.61%",
                    "687.96%\/1031.94%",
                    "726.18%\/1089.27%"
                ],
                "\"Plume\" Dance Move DMG": [
                    "43.04%",
                    "46.27%",
                    "49.5%",
                    "53.8%",
                    "57.03%",
                    "60.26%",
                    "64.56%",
                    "68.86%",
                    "73.17%",
                    "77.47%",
                    "81.78%",
                    "86.08%",
                    "91.46%",
                    "96.84%",
                    "102.22%"
                ],
                "\"Plume\" Dance Move Stellar-Conduct\/Stellar Swirl DMG": [
                    "27.02%\/40.53%",
                    "29.05%\/43.57%",
                    "31.08%\/46.61%",
                    "33.78%\/50.66%",
                    "35.81%\/53.7%",
                    "37.83%\/56.74%",
                    "40.54%\/60.79%",
                    "43.24%\/64.84%",
                    "45.94%\/68.9%",
                    "48.64%\/72.95%",
                    "51.35%\/77%",
                    "54.05%\/81.06%",
                    "57.43%\/86.12%",
                    "60.8%\/91.19%",
                    "64.18%\/96.25%"
                ],
                "\"Wing\" Dance Move DMG": [
                    "51.46%",
                    "55.32%",
                    "59.18%",
                    "64.33%",
                    "68.19%",
                    "72.05%",
                    "77.2%",
                    "82.34%",
                    "87.49%",
                    "92.64%",
                    "97.78%",
                    "102.93%",
                    "109.36%",
                    "115.79%",
                    "122.23%"
                ],
                "\"Wing\" Dance Move Stellar-Conduct\/Stellar Swirl DMG": [
                    "32.31%\/48.46%",
                    "34.74%\/52.1%",
                    "37.16%\/55.73%",
                    "40.39%\/60.58%",
                    "42.81%\/64.21%",
                    "45.24%\/67.85%",
                    "48.47%\/72.7%",
                    "51.7%\/77.54%",
                    "54.93%\/82.39%",
                    "58.16%\/87.24%",
                    "61.39%\/92.08%",
                    "64.62%\/96.93%",
                    "68.66%\/102.99%",
                    "72.7%\/109.04%",
                    "76.74%\/115.1%"
                ],
                "Coda at Dawn's Tolling CD": [
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s"
                ],
                "Solo Dance Double Duration": [
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s"
                ],
                "CD": [
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s"
                ]
            }
        },
        "Elemental Burst": {
            "name": "Presto: Bluebird Finale",
            "icon": "Skill_E_Odette_01",
            "text": "With quick, lively dance steps, Odette deals multiple instances of <color=#99FFFFFF>AoE Cryo DMG<\/color>, and summons her <color=#FFD780FF>{LINK#N11500001}Solo Dance Double<\/color>{\/LINK}. She also gains <color=#FFD780FF>Snow Swan's Dream<\/color>, which increases the Stellar Glimmer reaction DMG Odette deals.\\nAdditionally, for 6s after unleashing the Elemental Burst <color=#FFD780FF>Presto: Bluebird Finale<\/color>, Odette's Elemental Skill <color=#FFD780FF>Adagio: Phantom Night Dancers<\/color> will be replaced with the special Elemental Skill {LINK#N11500002}<color=#FFD780FF>Adagio: Coda at Dawn's Tolling<\/color>{\/LINK} instead.\\n\\nIf there is a Solo Dance Double summoned by Odette on the field, it will be summoned to her side with its duration refreshed.\n\\n\\n<i>The dawn-lit clouds were hanging just within reach. It was as though she needed only spread her wings to touch them.<\/i>",
            "scaling": {
                "Slash DMG": [
                    "110.18% \u00d73",
                    "118.44% \u00d73",
                    "126.7% \u00d73",
                    "137.72% \u00d73",
                    "145.98% \u00d73",
                    "154.25% \u00d73",
                    "165.26% \u00d73",
                    "176.28% \u00d73",
                    "187.3% \u00d73",
                    "198.32% \u00d73",
                    "209.33% \u00d73",
                    "220.35% \u00d73",
                    "234.12% \u00d73",
                    "247.9% \u00d73",
                    "261.67% \u00d73"
                ],
                "Final Slash DMG": [
                    "170.27%",
                    "183.04%",
                    "195.81%",
                    "212.84%",
                    "225.61%",
                    "238.38%",
                    "255.41%",
                    "272.44%",
                    "289.46%",
                    "306.49%",
                    "323.52%",
                    "340.54%",
                    "361.83%",
                    "383.11%",
                    "404.4%"
                ],
                "Snow Swan's Dream Stellar Glimmer Reaction DMG Bonus": [
                    "14%",
                    "18%",
                    "22%",
                    "26%",
                    "30%",
                    "34%",
                    "38%",
                    "42%",
                    "46%",
                    "50%",
                    "54%",
                    "58%",
                    "62%",
                    "66%",
                    "70%"
                ],
                "Snow Swan's Dream Duration": [
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s"
                ],
                "Solo Dance Double Duration": [
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s"
                ],
                "CD": [
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s"
                ],
                "Energy Cost": [
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60"
                ]
            }
        },
        "1st Ascension Passive": {
            "name": "Spring Rite of the Chosen One",
            "icon": "UI_Talent_S_Odette_05",
            "text": "When Odette summons her {LINK#N11500001}<color=#FFD780FF>Solo Dance Double<\/color>{\/LINK}, she also obtains 4 stacks of {LINK#N11500003}<color=#FFD780FF>Marvelous Splendor<\/color>{\/LINK}."
        },
        "4th Ascension Passive": {
            "name": "Pathetique of Pateticheskaya",
            "icon": "UI_Talent_S_Odette_06",
            "text": "For every 100 ATK Odette has over 1,000, her Stellar Glimmer DMG is additionally increased by 1.5% of the original DMG. She can deal up to 30% more additional DMG in this way."
        },
        "Utility Passive": {
            "name": "Stellar Jubilee: Dance of Aurore",
            "icon": "UI_Talent_S_Odette_07",
            "text": "Odette will enter the <color=#FFD780FF>Radiance: Stellar-Conduct<\/color> state when she is inside a {LINK#N11330003}<color=#FFD780FF>Polestar Field<\/color>{\/LINK}, or the <color=#FFD780FF>Radiance: Stellar Swirl<\/color> state for 8s after a nearby party member triggers a Stellar Swirl reaction.\\nWhen a party member triggers a Superconduct or Cryo Swirl reaction, it becomes a Stellar-Conduct or Stellar Swirl reaction instead, and the Base DMG of said reaction is also increased by 0.7% for every 100 points of Odette's ATK. A maximum increase of 14% can be obtained in this way."
        },
        "Passive": {
            "name": "Echo of Winter Daydreams",
            "icon": "UI_Talent_S_Odette_08",
            "text": "Shows the locations of <color=#FFD780FF>Snezhnaya's Local Specialties<\/color> on the mini-map.\\nPracticing dance in one's spare time might even trigger other effects..."
        }
    },
    "constellations": {
        "1": {
            "name": "\"On This Danceless Morn, She Gazes at Her Reflection\"",
            "icon": "UI_Talent_S_Odette_01",
            "text": "After unleashing the special Elemental Skill {LINK#N11500002}<color=#FFD780FF>Adagio: Coda at Dawn's Tolling<\/color>{\/LINK}, at the dance duet's end Odette will deal an additional instance of <color=#99FFFFFF>Cryo AoE DMG<\/color> to nearby opponents that is considered:\\n<color=#FFD780FF>Radiance: Stellar-Conduct<\/color> or when not in a Radiance state: Stellar-Conduct reaction DMG at 300% of Odette's ATK;\\n<color=#FFD780FF>Radiance: Stellar Swirl<\/color>: Stellar Swirl reaction DMG at 450% of Odette's ATK.\\n\\nAdditionally, the Ascension Talent \"Spring Rite of the Chosen One\" is also enhanced: now, when the {LINK#N11500001}<color=#FFD780FF>Solo Dance Double<\/color>{\/LINK} is summoned, Odette also gains 2 stacks of {LINK#N11500003}<color=#FFD780FF>Marvelous Splendor<\/color>{\/LINK}. When Odette is off-field, the rate at which <color=#FFD780FF>Marvelous Splendor<\/color> is removed is sped up to 2 stacks per second."
        },
        "2": {
            "name": "\"I Must See the Snow Swan's Unseen Dream for Myself, She Thought\"",
            "icon": "UI_Talent_S_Odette_02",
            "text": "The Ascension Talent \"Spring Rite of the Chosen One\" is enhanced as follows: every stack of {LINK#N11500003}<color=#FFD780FF>Marvelous Splendor<\/color>{\/LINK} active also increases the character's ATK by 7%.\\nAdditionally, if Odette is in the {LINK#N11500004}<color=#FFD780FF>Radiance: Stellar Glimmer<\/color>{\/LINK} state when there is a {LINK#N11500001}<color=#FFD780FF>Solo Dance Double<\/color>{\/LINK} on the field, opponents near the <color=#FFD780FF>Dance Double<\/color> will also have their corresponding Elemental RES lowered by 20%.\\n\u00b7<color=#FFD780FF>Radiance: Stellar-Conduct<\/color>: <color=#99FFFFFF>Cryo<\/color> and <color=#FFACFFFF>Electro<\/color>.\\n\u00b7<color=#FFD780FF>Radiance: Stellar Swirl<\/color>: <color=#99FFFFFF>Cryo<\/color> and <color=#80FFD7FF>Anemo<\/color>."
        },
        "3": {
            "name": "\"I'll Chase the Shouting Wind Along, Climbing Alone As I Go\"",
            "icon": "UI_Talent_U_Odette_01",
            "text": "Increases the Level of <color=#FFD780FF>{LINK#S11502}Adagio: Phantom Night Dancers{\/LINK}<\/color> by 3.\\nMaximum upgrade level is 15."
        },
        "4": {
            "name": "\"Up, Up the Long, Delirious, Burning Blue\"",
            "icon": "UI_Talent_S_Odette_03",
            "text": "The Elemental Burst <color=#FFD780FF>Presto: Bluebird Finale<\/color> is enhanced as follows: when Odette obtains <color=#FFD780FF>Snow Swan's Dream<\/color>, Stellar Glimmer reaction DMG dealt by other nearby party members is increased by 50% of <color=#FFD780FF>Snow Swan Dream<\/color>'s effects.\\n\\nAdditionally, when a party member deals Stellar Glimmer reaction DMG to an opponent, Odette will also join in with a coordinated attack, dealing an instance of <color=#99FFFFFF>AoE Cryo DMG<\/color>. This effect, which can trigger once every 3.5s, will be considered:\\n\u00b7<color=#FFD780FF>Radiance: Stellar-Conduct<\/color> or when not in a Radiance state: Stellar-Conduct reaction DMG at 66% of Odette's ATK.\\n\u00b7<color=#FFD780FF>Radiance: Stellar Swirl<\/color>: Stellar Swirl reaction DMG at 99% of Odette's ATK."
        },
        "5": {
            "name": "\"Oh! I Have Slipped the Surly Bonds of Earth\"",
            "icon": "UI_Talent_U_Odette_02",
            "text": "Increases the Level of <color=#FFD780FF>{LINK#S11505}Presto: Bluebird Finale{\/LINK} <\/color> by 3.\\nMaximum upgrade level is 15."
        },
        "6": {
            "name": "\"Put Out My Hand, and Touched the Face of the Divine\"",
            "icon": "UI_Talent_S_Odette_04",
            "text": "The Ascension Talent \"Spring Rite of the Chosen One\" is enhanced as follows: When Odette grants {LINK#N11500003}<color=#FFD780FF>Marvelous Splendor<\/color>{\/LINK} to all nearby party members, her own Marvelous Splendor stacks will no longer decrease.\\nAdditionally, characters affected by <color=#FFD780FF>Marvelous Splendor<\/color> have their Stellar Glimmer reaction DMG dealt to opponents {LINK#N11190007}<color=#FFD780FF>elevated<\/color>{\/LINK} by 25%, and Stellar Glimmer reaction DMG dealt by Odette is elevated by an additional 20%."
        }
    }
};