export default {
    "talents": {
        "Normal Attack": {
            "name": "Ancient Sword Art",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/6\/6a\/Sword_Cryo.png",
            "text": "<color=#FFD780FF>Normal Attack<\/color>\\nPerforms up to 5 rapid strikes.\\n\\n<color=#FFD780FF>Charged Attack<\/color>\\nConsumes a certain amount of Stamina to unleash 2 rapid sword strikes.\\n\\n<color=#FFD780FF>Plunging Attack<\/color>\\nPlunges from mid-air to strike the ground below, damaging opponents along the path and dealing AoE DMG upon impact.",
            "scaling": {
                "1-Hit DMG": [
                    "37.75%",
                    "40.83%",
                    "43.9%",
                    "48.29%",
                    "51.36%",
                    "54.87%",
                    "59.7%",
                    "64.53%",
                    "69.36%",
                    "74.63%",
                    "79.9%",
                    "85.17%",
                    "90.43%",
                    "95.7%",
                    "100.97%"
                ],
                "2-Hit DMG": [
                    "38.87%",
                    "42.04%",
                    "45.2%",
                    "49.72%",
                    "52.88%",
                    "56.5%",
                    "61.47%",
                    "66.44%",
                    "71.42%",
                    "76.84%",
                    "82.26%",
                    "87.69%",
                    "93.11%",
                    "98.54%",
                    "103.96%"
                ],
                "3-Hit DMG": [
                    "24.17%+24.17%",
                    "26.13%+26.13%",
                    "28.1%+28.1%",
                    "30.91%+30.91%",
                    "32.88%+32.88%",
                    "35.12%+35.12%",
                    "38.22%+38.22%",
                    "41.31%+41.31%",
                    "44.4%+44.4%",
                    "47.77%+47.77%",
                    "51.14%+51.14%",
                    "54.51%+54.51%",
                    "57.89%+57.89%",
                    "61.26%+61.26%",
                    "64.63%+64.63%"
                ],
                "4-Hit DMG": [
                    "24.68%+24.68%",
                    "26.69%+26.69%",
                    "28.7%+28.7%",
                    "31.57%+31.57%",
                    "33.58%+33.58%",
                    "35.87%+35.87%",
                    "39.03%+39.03%",
                    "42.19%+42.19%",
                    "45.35%+45.35%",
                    "48.79%+48.79%",
                    "52.23%+52.23%",
                    "55.68%+55.68%",
                    "59.12%+59.12%",
                    "62.57%+62.57%",
                    "66.01%+66.01%"
                ],
                "5-Hit DMG": [
                    "63.04%",
                    "68.17%",
                    "73.3%",
                    "80.63%",
                    "85.76%",
                    "91.62%",
                    "99.69%",
                    "107.75%",
                    "115.81%",
                    "124.61%",
                    "133.41%",
                    "142.2%",
                    "151%",
                    "159.79%",
                    "168.59%"
                ],
                "Charged Attack DMG": [
                    "64.33%+64.33%",
                    "69.56%+69.56%",
                    "74.8%+74.8%",
                    "82.28%+82.28%",
                    "87.52%+87.52%",
                    "93.5%+93.5%",
                    "101.73%+101.73%",
                    "109.96%+109.96%",
                    "118.18%+118.18%",
                    "127.16%+127.16%",
                    "136.14%+136.14%",
                    "145.11%+145.11%",
                    "154.09%+154.09%",
                    "163.06%+163.06%",
                    "172.04%+172.04%"
                ],
                "Charged Attack Stamina Cost": [
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20"
                ],
                "Plunge DMG": [
                    "63.93%",
                    "69.14%",
                    "74.34%",
                    "81.77%",
                    "86.98%",
                    "92.93%",
                    "101.1%",
                    "109.28%",
                    "117.46%",
                    "126.38%",
                    "135.3%",
                    "144.22%",
                    "153.14%",
                    "162.06%",
                    "170.98%"
                ],
                "Low\/High Plunge DMG": [
                    "127.84%\/159.68%",
                    "138.24%\/172.67%",
                    "148.65%\/185.67%",
                    "163.51%\/204.24%",
                    "173.92%\/217.23%",
                    "185.81%\/232.09%",
                    "202.16%\/252.51%",
                    "218.51%\/272.93%",
                    "234.86%\/293.36%",
                    "252.7%\/315.64%",
                    "270.54%\/337.92%",
                    "288.38%\/360.2%",
                    "306.22%\/382.48%",
                    "324.05%\/404.76%",
                    "341.89%\/427.04%"
                ]
            },
            "icon": "Skill_A_01"
        },
        "Elemental Skill": {
            "name": "Adeptus Art: Herald of Frost",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/7\/7f\/Talent_Adeptus_Art_Herald_of_Frost.png",
            "text": "Using the Icevein Talisman, Qiqi brings forth the Herald of Frost, dealing <color=#99FFFFFF>Cryo DMG<\/color> to surrounding opponents.\\n\\n<color=#FFD780FF>Herald of Frost<\/color>\\n\u00b7 On hit, Qiqi's Normal and Charged Attacks regenerate HP for party members and nearby teammates, with healing scaled based on Qiqi's ATK.\\n\u00b7 Periodically regenerates your active character's HP.\\n\u00b7 Follows the character around, dealing <color=#99FFFFFF>Cryo DMG<\/color> to opponents in their path.\\nIf your current active character hits an opponent with an attack, the Herald of Frost will perform a coordinated attack on the opponent, dealing <color=#99FFFFFF>Cryo DMG<\/color>.\\n\\n<i>\"I use this to prevent warming and rot... of Dr. Bai's precious ingredients. Yes.\"<\/i>",
            "scaling": {
                "Skill DMG": [
                    "96%",
                    "103.2%",
                    "110.4%",
                    "120%",
                    "127.2%",
                    "134.4%",
                    "144%",
                    "153.6%",
                    "163.2%",
                    "172.8%",
                    "182.4%",
                    "192%",
                    "204%",
                    "216%",
                    "228%"
                ],
                "Regeneration on Hit": [
                    "10.56% ATK+67",
                    "11.35% ATK+74",
                    "12.14% ATK+81",
                    "13.2% ATK+89",
                    "13.99% ATK+98",
                    "14.78% ATK+107",
                    "15.84% ATK+116",
                    "16.9% ATK+126",
                    "17.95% ATK+137",
                    "19.01% ATK+148",
                    "20.06% ATK+160",
                    "21.12% ATK+172",
                    "22.44% ATK+185",
                    "23.76% ATK+199",
                    "25.08% ATK+213"
                ],
                "Continuous Regeneration": [
                    "69.6% ATK+451",
                    "74.82% ATK+496",
                    "80.04% ATK+544",
                    "87% ATK+597",
                    "92.22% ATK+653",
                    "97.44% ATK+713",
                    "104.4% ATK+777",
                    "111.36% ATK+845",
                    "118.32% ATK+916",
                    "125.28% ATK+991",
                    "132.24% ATK+1070",
                    "139.2% ATK+1153",
                    "147.9% ATK+1239",
                    "156.6% ATK+1329",
                    "165.3% ATK+1423"
                ],
                "Herald of Frost DMG": [
                    "36%",
                    "38.7%",
                    "41.4%",
                    "45%",
                    "47.7%",
                    "50.4%",
                    "54%",
                    "57.6%",
                    "61.2%",
                    "64.8%",
                    "68.4%",
                    "72%",
                    "76.5%",
                    "81%",
                    "85.5%"
                ],
                "Duration": [
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s"
                ],
                "CD": [
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s"
                ],
                "Herald of Frost Coordinated Attack DMG": [
                    "24%",
                    "25.8%",
                    "27.6%",
                    "30%",
                    "31.8%",
                    "33.6%",
                    "36%",
                    "38.4%",
                    "40.8%",
                    "43.2%",
                    "45.6%",
                    "48%",
                    "51%",
                    "54%",
                    "57%"
                ],
                "Herald of Frost Coordinated Attack CD": [
                    "2.2s",
                    "2.2s",
                    "2.2s",
                    "2.2s",
                    "2.2s",
                    "2.2s",
                    "2.2s",
                    "2.2s",
                    "2.2s",
                    "2.2s",
                    "2.2s",
                    "2.2s",
                    "2.2s",
                    "2.2s",
                    "2.2s"
                ]
            },
            "icon": "Skill_S_Qiqi_01"
        },
        "Elemental Burst": {
            "name": "Adeptus Art: Preserver of Fortune",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/7\/7c\/Talent_Adeptus_Art_Preserver_of_Fortune.png",
            "text": "Qiqi releases the Adeptal power sealed within her body, marking nearby opponents with a Fortune-Preserving Talisman that deals <color=#99FFFFFF>Cryo DMG<\/color>.\\n<color=#FFD780FF>Radiance: Stellar-Conduct<\/color>: Deals an additional instance of <color=#99FFFFFF>Cryo DMG<\/color> that is also considered Stellar-Conduct DMG.\\n\\n<color=#FFD780FF>Fortune-Preserving Talisman<\/color>\\nWhen opponents affected by this Talisman take DMG, the character that dealt this DMG regenerates HP.\\n\\n<i>\"I am the Fortune Preserver, the Maiden of Resurrection.\"<\/i>\\n<i>\u2014 Qiqi does not remember these words.<\/i>",
            "scaling": {
                "Skill DMG": [
                    "284.8%",
                    "306.16%",
                    "327.52%",
                    "356%",
                    "377.36%",
                    "398.72%",
                    "427.2%",
                    "455.68%",
                    "484.16%",
                    "512.64%",
                    "541.12%",
                    "569.6%",
                    "605.2%",
                    "640.8%",
                    "676.4%"
                ],
                "Healing": [
                    "90% ATK+577",
                    "96.75% ATK+635",
                    "103.5% ATK+698",
                    "112.5% ATK+765",
                    "119.25% ATK+837",
                    "126% ATK+914",
                    "135% ATK+996",
                    "144% ATK+1083",
                    "153% ATK+1174",
                    "162% ATK+1270",
                    "171% ATK+1371",
                    "180% ATK+1477",
                    "191.25% ATK+1588",
                    "202.5% ATK+1703",
                    "213.75% ATK+1824"
                ],
                "Duration": [
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s"
                ],
                "CD": [
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s",
                    "20s"
                ],
                "Energy Cost": [
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80",
                    "80"
                ],
                "Stellar-Conduct DMG": [
                    "297.33%",
                    "319.63%",
                    "341.93%",
                    "371.67%",
                    "393.97%",
                    "416.27%",
                    "446%",
                    "475.73%",
                    "505.47%",
                    "535.2%",
                    "564.93%",
                    "594.67%",
                    "631.83%",
                    "669%",
                    "706.17%"
                ]
            },
            "icon": "Skill_E_Qiqi_01"
        },
        "1st Ascension Passive": {
            "name": "Life-Prolonging Methods",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/b\/b5\/Talent_Life-Prolonging_Methods.png",
            "text": "When a character under the effects of <color=#FFD780FF>Adeptus Art: Herald of Frost<\/color> triggers an Elemental Reaction, their Incoming Healing Bonus is increased by 20% for 8s.",
            "icon": "UI_Talent_S_Qiqi_05"
        },
        "4th Ascension Passive": {
            "name": "A Glimpse Into Arcanum",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/f\/f8\/Talent_A_Glimpse_Into_Arcanum.png",
            "text": "When Qiqi hits opponents with her Normal and Charged Attacks, she has a 50% chance to apply a Fortune-Preserving Talisman to them for 6s. This effect can only occur once every 30s.\\n<color=#FFD780FF>Radiance: Stellar-Conduct<\/color>: The effect now has a 100% chance to trigger, and cooldown time is reduced to 15s.",
            "icon": "UI_Talent_S_Qiqi_06"
        },
        "Utility Passive": {
            "name": "Former Life Memories",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/5\/5e\/Talent_Former_Life_Memories.png",
            "text": "Displays the location of nearby <color=#FFD780FF>resources unique to Liyue<\/color> on the mini-map.",
            "icon": "UI_Talent_Collect_Local_Liyue"
        },
        "Passive": {
            "name": "Seven Sacred Treasures",
            "icon": "UI_Talent_S_Qiqi_08",
            "text": "The cooldown of the Elemental Skill <color=#FFD780FF>Adeptus Art: Herald of Frost<\/color> is reduced to 15s.\\n<color=#FFD780FF>Radiance: Stellar-Conduct<\/color>: While the Herald of Frost is on the field, characters in Qiqi's party have their Superconduct, Stellar-Conduct, and Cryo Swirl Reaction DMG increased by 50%.\\nAdditionally, when inside a {LINK#N11330003}<color=#FFD780FF>Polestar Field<\/color>{\/LINK}, Qiqi will enter the <color=#FFD780FF>Radiance: Stellar-Conduct<\/color> state."
        }
    },
    "constellations": {
        "1": {
            "name": "Ascetics of Frost",
            "icon": "UI_Talent_S_Qiqi_01",
            "text": "Qiqi regenerates 2 Energy when the Herald of Frost hits an opponent marked by a Fortune-Preserving Talisman.\\n<color=#FFD780FF>Radiance: Stellar-Conduct<\/color>: Qiqi also regenerates 6 Elemental Energy when the Herald of Frost's attacks and coordinated attacks hit opponents. This effect can trigger once every 6s."
        },
        "2": {
            "name": "Frozen to the Bone",
            "icon": "UI_Talent_S_Qiqi_02",
            "text": "Qiqi's Normal and Charged Attack DMG against opponents affected by <color=#99FFFFFF>Cryo<\/color> is increased by 15%.\\n<color=#FFD780FF>Radiance: Stellar-Conduct<\/color>: Qiqi's ATK is increased by 50%."
        },
        "3": {
            "name": "Ascendant Praise",
            "icon": "UI_Talent_U_Qiqi_01",
            "text": "Increases the Level of <color=#FFD780FF>Adeptus Art: Preserver of Fortune<\/color> by 3.\\nMaximum upgrade level is 15."
        },
        "4": {
            "name": "Divine Suppression",
            "icon": "UI_Talent_S_Qiqi_03",
            "text": "Targets marked by a Fortune-Preserving Talisman have their ATK reduced by 20%.\\nAdditionally, when the healing effect of Fortune-Preserving Talisman triggers, the nearby party member with the lowest HP percentage remaining will also receive an additional instance of healing for 180% of Qiqi's ATK."
        },
        "5": {
            "name": "Crimson Lotus Bloom",
            "icon": "UI_Talent_U_Qiqi_02",
            "text": "Increases the Level of <color=#FFD780FF>Adeptus Art: Herald of Frost<\/color> by 3.\\nMaximum upgrade level is 15."
        },
        "6": {
            "name": "Rite of Resurrection",
            "icon": "UI_Talent_S_Qiqi_04",
            "text": "Using <color=#FFD780FF>Adeptus Art: Preserver of Fortune<\/color> revives all fallen party members nearby and regenerates 50% of their HP.\\nThis effect can only occur once every 15 mins.\\nAdditionally, after using <color=#FFD780FF>Adeptus Art: Preserver of Fortune<\/color>, Qiqi will also gain 4 stacks of <color=#FFD780FF>Glimpse of Mystery<\/color>, and when your current active character (other than Qiqi) deals Stellar-Conduct DMG, 1 stack of <color=#FFD780FF>Glimpse of Mystery<\/color> is consumed, and DMG dealt is increased by 600% of Qiqi's ATK. The <color=#FFD780FF>Glimpse of Mystery<\/color> effect lasts up to 12s, and unleashing <color=#FFD780FF>Adeptus Art: Preserver of Fortune<\/color> refreshes the stack count."
        }
    }
};