export default {
    "talents": {
        "Normal Attack": {
            "name": "Steel Fang",
            "text": "<color=#FFD780FF>Normal Attack<\/color>\\nPerforms up to 4 consecutive strikes.\\n\\n<color=#FFD780FF>Charged Attack<\/color>\\nDrains Stamina over time to perform continuous spinning attacks against all nearby opponents.\\nAt the end of the sequence, performs a more powerful slash. \\n\\n<color=#FFD780FF>Plunging Attack<\/color>\\nPlunges from mid-air to strike the ground below, damaging opponents along the path and dealing AoE DMG upon impact.",
            "scaling": {
                "1-Hit DMG": {
                    "1": "95.92%",
                    "2": "102.46%",
                    "3": "109%",
                    "4": "117.72%",
                    "5": "124.26%",
                    "6": "131.89%",
                    "7": "141.7%",
                    "8": "151.51%",
                    "9": "161.32%",
                    "10": "171.13%",
                    "11": "180.94%",
                    "12": "190.75%",
                    "13": "200.56%",
                    "14": "210.37%",
                    "15": "220.18%"
                },
                "2-Hit DMG": {
                    "1": "82.632%",
                    "2": "88.266%",
                    "3": "93.9%",
                    "4": "101.412%",
                    "5": "107.046%",
                    "6": "113.619%",
                    "7": "122.07%",
                    "8": "130.521%",
                    "9": "138.972%",
                    "10": "147.423%",
                    "11": "155.874%",
                    "12": "164.325%",
                    "13": "172.776%",
                    "14": "181.227%",
                    "15": "189.678%"
                },
                "3-Hit DMG": {
                    "1": "103.312%",
                    "2": "110.356%",
                    "3": "117.4%",
                    "4": "126.792%",
                    "5": "133.836%",
                    "6": "142.054%",
                    "7": "152.62%",
                    "8": "163.186%",
                    "9": "173.752%",
                    "10": "184.318%",
                    "11": "194.884%",
                    "12": "205.45%",
                    "13": "216.016%",
                    "14": "226.582%",
                    "15": "237.148%"
                },
                "4-Hit DMG": {
                    "1": "136.048%",
                    "2": "145.324%",
                    "3": "154.6%",
                    "4": "166.968%",
                    "5": "176.244%",
                    "6": "187.066%",
                    "7": "200.98%",
                    "8": "214.894%",
                    "9": "228.808%",
                    "10": "242.722%",
                    "11": "256.636%",
                    "12": "270.55%",
                    "13": "284.464%",
                    "14": "298.378%",
                    "15": "312.292%"
                },
                "Charged Attack Cyclic DMG": {
                    "1": "62.5392%",
                    "2": "67.6296%",
                    "3": "72.72%",
                    "4": "79.992%",
                    "5": "85.0824%",
                    "6": "90.9%",
                    "7": "98.8992%",
                    "8": "106.8984%",
                    "9": "114.8976%",
                    "10": "123.624%",
                    "11": "132.3504%",
                    "12": "141.0768%",
                    "13": "149.8032%",
                    "14": "158.5296%",
                    "15": "167.256%"
                },
                "Charged Attack Final DMG": {
                    "1": "113.09%",
                    "2": "122.295%",
                    "3": "131.5%",
                    "4": "144.65%",
                    "5": "153.855%",
                    "6": "164.375%",
                    "7": "178.84%",
                    "8": "193.305%",
                    "9": "207.77%",
                    "10": "223.55%",
                    "11": "239.33%",
                    "12": "255.11%",
                    "13": "270.89%",
                    "14": "286.67%",
                    "15": "302.45%"
                },
                "Charged Attack Stamina Cost": {
                    "1": "40\/s",
                    "2": "40\/s",
                    "3": "40\/s",
                    "4": "40\/s",
                    "5": "40\/s",
                    "6": "40\/s",
                    "7": "40\/s",
                    "8": "40\/s",
                    "9": "40\/s",
                    "10": "40\/s",
                    "11": "40\/s",
                    "12": "40\/s",
                    "13": "40\/s",
                    "14": "40\/s",
                    "15": "40\/s"
                },
                "Max Duration": {
                    "1": "5s",
                    "2": "5s",
                    "3": "5s",
                    "4": "5s",
                    "5": "5s",
                    "6": "5s",
                    "7": "5s",
                    "8": "5s",
                    "9": "5s",
                    "10": "5s",
                    "11": "5s",
                    "12": "5s",
                    "13": "5s",
                    "14": "5s",
                    "15": "5s"
                },
                "Plunge DMG": {
                    "1": "82.0466%",
                    "2": "88.7248%",
                    "3": "95.403%",
                    "4": "104.9433%",
                    "5": "111.6215%",
                    "6": "119.2538%",
                    "7": "129.7481%",
                    "8": "140.2424%",
                    "9": "150.7367%",
                    "10": "162.1851%",
                    "11": "173.6335%",
                    "12": "185.0818%",
                    "13": "196.5302%",
                    "14": "207.9785%",
                    "15": "219.4269%"
                },
                "Low\/High Plunge DMG": {
                    "1": "164.0584%\/204.9178%",
                    "2": "177.412%\/221.5971%",
                    "3": "190.7656%\/238.2765%",
                    "4": "209.8421%\/262.1042%",
                    "5": "223.1957%\/278.7835%",
                    "6": "238.457%\/297.8456%",
                    "7": "259.4412%\/324.056%",
                    "8": "280.4254%\/350.2665%",
                    "9": "301.4096%\/376.4769%",
                    "10": "324.3015%\/405.0701%",
                    "11": "347.1933%\/433.6632%",
                    "12": "370.0852%\/462.2564%",
                    "13": "392.9771%\/490.8496%",
                    "14": "415.869%\/519.4428%",
                    "15": "438.7608%\/548.036%"
                }
            }
        },
        "Elemental Skill": {
            "name": "Claw and Thunder",
            "text": "#Hunts his prey using the techniques taught to him by his master and his lupical.\\n\\n<color=#FFD780FF>{LAYOUT_MOBILE#Tap}{LAYOUT_PC#Press}{LAYOUT_PS#Press}<\/color>\\nSwings the Thunder Wolf Claw, dealing <color=#FFACFFFF>Electro DMG<\/color> to opponents in front of Razor.\\nUpon striking an opponent, Razor will gain an Electro Sigil, which increases his Energy Recharge rate.\\nRazor can have up to 3 Electro Sigils simultaneously, and gaining a new Electro Sigil refreshes their duration.\\n\\n<color=#FFD780FF>Hold<\/color>\\nGathers Electro energy to unleash a lightning storm over a small AoE, causing massive <color=#FFACFFFF>Electro DMG<\/color>, and clears all of Razor's Electro Sigils.\\nEach Electro Sigil cleared in this manner will be converted into Energy for Razor.\\n\\n<i>In the moment when lightning strikes, you can sometimes glimpse the look of a predator sizing up his prey deep within Razor's eyes.<\/i>",
            "scaling": {
                "Press Skill DMG": {
                    "1": "199.2%",
                    "2": "214.14%",
                    "3": "229.08%",
                    "4": "249%",
                    "5": "263.94%",
                    "6": "278.88%",
                    "7": "298.8%",
                    "8": "318.72%",
                    "9": "338.64%",
                    "10": "358.56%",
                    "11": "378.48%",
                    "12": "398.4%",
                    "13": "423.3%",
                    "14": "448.2%",
                    "15": "473.1%"
                },
                "Hold Skill DMG": {
                    "1": "295.2%",
                    "2": "317.34%",
                    "3": "339.48%",
                    "4": "369%",
                    "5": "391.14%",
                    "6": "413.28%",
                    "7": "442.8%",
                    "8": "472.32%",
                    "9": "501.84%",
                    "10": "531.36%",
                    "11": "560.88%",
                    "12": "590.4%",
                    "13": "627.3%",
                    "14": "664.2%",
                    "15": "701.1%"
                },
                "Energy Recharge Bonus": {
                    "1": "20% per Electro Sigil",
                    "2": "20% per Electro Sigil",
                    "3": "20% per Electro Sigil",
                    "4": "20% per Electro Sigil",
                    "5": "20% per Electro Sigil",
                    "6": "20% per Electro Sigil",
                    "7": "20% per Electro Sigil",
                    "8": "20% per Electro Sigil",
                    "9": "20% per Electro Sigil",
                    "10": "20% per Electro Sigil",
                    "11": "20% per Electro Sigil",
                    "12": "20% per Electro Sigil",
                    "13": "20% per Electro Sigil",
                    "14": "20% per Electro Sigil",
                    "15": "20% per Electro Sigil"
                },
                "Energy Regenerated": {
                    "1": "5 per Electro Sigil Absorbed",
                    "2": "5 per Electro Sigil Absorbed",
                    "3": "5 per Electro Sigil Absorbed",
                    "4": "5 per Electro Sigil Absorbed",
                    "5": "5 per Electro Sigil Absorbed",
                    "6": "5 per Electro Sigil Absorbed",
                    "7": "5 per Electro Sigil Absorbed",
                    "8": "5 per Electro Sigil Absorbed",
                    "9": "5 per Electro Sigil Absorbed",
                    "10": "5 per Electro Sigil Absorbed",
                    "11": "5 per Electro Sigil Absorbed",
                    "12": "5 per Electro Sigil Absorbed",
                    "13": "5 per Electro Sigil Absorbed",
                    "14": "5 per Electro Sigil Absorbed",
                    "15": "5 per Electro Sigil Absorbed"
                },
                "Electro Sigil duration": {
                    "1": "18s",
                    "2": "18s",
                    "3": "18s",
                    "4": "18s",
                    "5": "18s",
                    "6": "18s",
                    "7": "18s",
                    "8": "18s",
                    "9": "18s",
                    "10": "18s",
                    "11": "18s",
                    "12": "18s",
                    "13": "18s",
                    "14": "18s",
                    "15": "18s"
                },
                "Press CD": {
                    "1": "6s",
                    "2": "6s",
                    "3": "6s",
                    "4": "6s",
                    "5": "6s",
                    "6": "6s",
                    "7": "6s",
                    "8": "6s",
                    "9": "6s",
                    "10": "6s",
                    "11": "6s",
                    "12": "6s",
                    "13": "6s",
                    "14": "6s",
                    "15": "6s"
                },
                "Hold CD": {
                    "1": "10s",
                    "2": "10s",
                    "3": "10s",
                    "4": "10s",
                    "5": "10s",
                    "6": "10s",
                    "7": "10s",
                    "8": "10s",
                    "9": "10s",
                    "10": "10s",
                    "11": "10s",
                    "12": "10s",
                    "13": "10s",
                    "14": "10s",
                    "15": "10s"
                }
            }
        },
        "Elemental Burst": {
            "name": "Lightning Fang",
            "text": "Summons the Wolf Within, which deals <color=#FFACFFFF>Electro DMG<\/color> to all nearby opponents. This clears all of Razor's Electro Sigils, which will be converted into Elemental Energy for him.\\nThe Wolf Within will fight alongside Razor for the skill's duration.\\n\\n<color=#FFD780FF>The Wolf Within<\/color>\\n\u00b7Strikes alongside Razor's normal attacks, dealing <color=#FFACFFFF>Electro DMG<\/color>.\\n\u00b7Raises Razor's ATK SPD and <color=#FFACFFFF>Electro RES<\/color>.\\n\u00b7Causes Razor to be immune to DMG inflicted by the <color=#FFACFFFF>Electro-Charged<\/color> status.\\n\u00b7Disables Razor's Charged Attacks.\\n\u00b7Increases Razor's resistance to interruption.\\n\\nThese effects end when Razor leaves the battlefield.\\nWhen Razor leaves the field, a maximum of 10 Energy will be returned to him based off the duration remaining on this skill.\\n\\n<i>The wolf has awoken. The hunt is on.<\/i>",
            "scaling": {
                "Burst DMG": {
                    "1": "160%",
                    "2": "172%",
                    "3": "184%",
                    "4": "200%",
                    "5": "212%",
                    "6": "224%",
                    "7": "240%",
                    "8": "256%",
                    "9": "272%",
                    "10": "288%",
                    "11": "304%",
                    "12": "320%",
                    "13": "340%",
                    "14": "360%",
                    "15": "380%"
                },
                "Soul Companion DMG": {
                    "1": "24% Normal Attack DMG",
                    "2": "25.8% Normal Attack DMG",
                    "3": "27.6% Normal Attack DMG",
                    "4": "30% Normal Attack DMG",
                    "5": "31.8% Normal Attack DMG",
                    "6": "33.6% Normal Attack DMG",
                    "7": "36% Normal Attack DMG",
                    "8": "38.4% Normal Attack DMG",
                    "9": "40.8% Normal Attack DMG",
                    "10": "43.2% Normal Attack DMG",
                    "11": "45.6% Normal Attack DMG",
                    "12": "48% Normal Attack DMG",
                    "13": "51% Normal Attack DMG",
                    "14": "54% Normal Attack DMG",
                    "15": "57% Normal Attack DMG"
                },
                "Normal ATK SPD Bonus": {
                    "1": "26%",
                    "2": "28%",
                    "3": "30%",
                    "4": "32%",
                    "5": "34%",
                    "6": "36%",
                    "7": "37%",
                    "8": "38%",
                    "9": "39%",
                    "10": "40%",
                    "11": "40%",
                    "12": "40%",
                    "13": "40%",
                    "14": "40%",
                    "15": "40%"
                },
                "Electro RES Bonus": {
                    "1": "80%",
                    "2": "80%",
                    "3": "80%",
                    "4": "80%",
                    "5": "80%",
                    "6": "80%",
                    "7": "80%",
                    "8": "80%",
                    "9": "80%",
                    "10": "80%",
                    "11": "80%",
                    "12": "80%",
                    "13": "80%",
                    "14": "80%",
                    "15": "80%"
                },
                "Duration": {
                    "1": "15s",
                    "2": "15s",
                    "3": "15s",
                    "4": "15s",
                    "5": "15s",
                    "6": "15s",
                    "7": "15s",
                    "8": "15s",
                    "9": "15s",
                    "10": "15s",
                    "11": "15s",
                    "12": "15s",
                    "13": "15s",
                    "14": "15s",
                    "15": "15s"
                },
                "CD": {
                    "1": "20s",
                    "2": "20s",
                    "3": "20s",
                    "4": "20s",
                    "5": "20s",
                    "6": "20s",
                    "7": "20s",
                    "8": "20s",
                    "9": "20s",
                    "10": "20s",
                    "11": "20s",
                    "12": "20s",
                    "13": "20s",
                    "14": "20s",
                    "15": "20s"
                },
                "Energy Cost": {
                    "1": "80",
                    "2": "80",
                    "3": "80",
                    "4": "80",
                    "5": "80",
                    "6": "80",
                    "7": "80",
                    "8": "80",
                    "9": "80",
                    "10": "80",
                    "11": "80",
                    "12": "80",
                    "13": "80",
                    "14": "80",
                    "15": "80"
                }
            }
        },
        "1st Ascension Passive": {
            "name": "Awakening",
            "text": "Decreases <color=#FFD780FF>Claw and Thunder<\/color>'s CD by 18%.\\nUsing <color=#FFD780FF>Lightning Fang<\/color> resets the CD of <color=#FFD780FF>Claw and Thunder<\/color>."
        },
        "4th Ascension Passive": {
            "name": "Hunger",
            "text": "When Razor's Energy is below 50%, increases Energy Recharge by 30%."
        },
        "Utility Passive": {
            "name": "Wolvensprint",
            "text": "Decreases sprinting Stamina consumption for your own party members by 20%.\\nNot stackable with Passive Talents that provide the exact same effects."
        },
        "Passive": {
            "name": "Witch's Eve Rite: Surge of Lightning",
            "text": "After completing <color=#FFD780FF>Witch's Homework: Of the Little Wolf Pack<\/color>, Razor will become a <color=#FFD780FF>Hexerei<\/color> character. When the party includes at least 2 Hexerei characters, you will gain the <color=#FFD780FF>Hexerei: Secret Rite<\/color> effect, which enhances Hexerei characters.\\nAdditionally, Razor's Elemental Burst <color=#FFD780FF>Lightning Fang<\/color> is enhanced: <color=#FFD780FF>The Wolf Within<\/color>'s DMG dealt is increased by 70% of Razor's ATK.\\n\\n<color=#FFD780FF>Hexerei: Secret Rite<\/color>\\nWhile the Wolf Within summoned by Razor's Elemental Burst <color=#FFD780FF>Lightning Fang<\/color> is active, if the Electro Sigils from Razor's Elemental Skill <color=#FFD780FF>Claw and Thunder<\/color> overflow, the Wolf Within will call down a lightning strike on nearby enemies, dealing AoE Electro DMG equal to 150% of Razor's ATK and restoring 7 Energy to Razor. This effect can be triggered once every 1s."
        }
    },
    "constellations": {
        "1": {
            "name": "Wolf's Instinct",
            "text": "Picking up an Elemental Orb or Particle increases Razor's DMG by 10% for 8s."
        },
        "2": {
            "name": "Suppression",
            "text": "Increases CRIT Rate against opponents with less than 30% HP by 10%."
        },
        "3": {
            "name": "Soul Companion",
            "text": "Increases the Level of <color=#FFD780FF>Lightning Fang<\/color> by 3.\\nMaximum upgrade level is 15."
        },
        "4": {
            "name": "Bite",
            "text": "#When casting <color=#FFD780FF>Claw and Thunder<\/color> ({LAYOUT_MOBILE#Tap}{LAYOUT_PC#Press}{LAYOUT_PS#Press}), opponents hit will have their DEF decreased by 15% for 7s."
        },
        "5": {
            "name": "Sharpened Claws",
            "text": "Increases the Level of <color=#FFD780FF>Claw and Thunder<\/color> by 3.\\nMaximum upgrade level is 15."
        },
        "6": {
            "name": "Lupus Fulguris",
            "text": "Every 10s, Razor's sword charges up, causing the next Normal Attack to release lightning that deals 100% of Razor's ATK as <color=#FFACFFFF>Electro DMG<\/color>.\\nWhen Razor is not using <color=#FFD780FF>Lightning Fang<\/color>, a lightning strike on an opponent will grant Razor an Electro Sigil for <color=#FFD780FF>Claw and Thunder<\/color>."
        }
    }
};