export default {
    "talents": {
        "Normal Attack": {
            "name": "Normal Attack: By the Horns",
            "text": "<color=#FFD780FF>Normal Attack<\/color>\\nGotta try... to do battle like the greatest champion luchadors do! Varesa launches up to 3 strikes, dealing <color=#FFACFFFF>Electro DMG<\/color>.\\n\\n<color=#FFD780FF>Charged Attack<\/color>\\nConsumes a certain amount of Stamina to headbutt opponents in front, dealing Nightsoul-aligned <color=#FFACFFFF>Electro DMG<\/color> and using the momentum to leap into the air.\\n\\n<color=#FFD780FF>Plunging Attack<\/color>\\nPlunges from mid-air to strike the ground below, damaging opponents along the path and dealing Nightsoul-aligned <color=#FFACFFFF>AoE Electro DMG<\/color> upon impact. If Varesa is in a combat state upon landing, or if the shockwave from her plunging attack hits an opponent, she will gain 25 Nightsoul points. She enters the Fiery Passion state upon reaching maximum Nightsoul points through this method.\\n\\n<color=#FFD780FF>Fiery Passion<\/color>\\nIn this state, Varesa's Normal, Charged, and Plunging Attacks will gain corresponding buffs:\\n\\n<color=#FFD780FF>Normal Attack<\/color>\\nFight like a superstar champion luchador! Launches up to 3 fierce strikes, dealing greater <color=#FFACFFFF>Electro DMG<\/color>.\\n\\n<color=#FFD780FF>Charged Attack<\/color>\\nConsumes a certain amount of Stamina to slam into her opponents, dealing greater amounts of Nightsoul-aligned <color=#FFACFFFF>Electro DMG<\/color> and using the momentum to leap into the air.\\n\\n<color=#FFD780FF>Plunging Attack<\/color>\\nConsumes all her Nightsoul points and slams down on the ground from mid-air, dealing DMG to opponents in her path and dealing greater amounts of Nightsoul-aligned <color=#FFACFFFF>AoE Electro DMG<\/color> upon hitting the ground.",
            "scaling": {
                "1-Hit DMG": {
                    "1": "46.7784%",
                    "2": "50.2868%",
                    "3": "53.7952%",
                    "4": "58.473%",
                    "5": "61.9814%",
                    "6": "65.4898%",
                    "7": "70.1676%",
                    "8": "74.8454%",
                    "9": "79.5233%",
                    "10": "84.2011%",
                    "11": "88.879%",
                    "12": "93.5568%",
                    "13": "99.4041%",
                    "14": "105.2514%",
                    "15": "111.0987%"
                },
                "2-Hit DMG": {
                    "1": "40.028%",
                    "2": "43.0301%",
                    "3": "46.0322%",
                    "4": "50.035%",
                    "5": "53.0371%",
                    "6": "56.0392%",
                    "7": "60.042%",
                    "8": "64.0448%",
                    "9": "68.0476%",
                    "10": "72.0504%",
                    "11": "76.0532%",
                    "12": "80.056%",
                    "13": "85.0595%",
                    "14": "90.063%",
                    "15": "95.0665%"
                },
                "3-Hit DMG": {
                    "1": "56.3128%",
                    "2": "60.5363%",
                    "3": "64.7597%",
                    "4": "70.391%",
                    "5": "74.6145%",
                    "6": "78.8379%",
                    "7": "84.4692%",
                    "8": "90.1005%",
                    "9": "95.7318%",
                    "10": "101.363%",
                    "11": "106.9943%",
                    "12": "112.6256%",
                    "13": "119.6647%",
                    "14": "126.7038%",
                    "15": "133.7429%"
                },
                "Charged Attack DMG": {
                    "1": "89.28%",
                    "2": "95.976%",
                    "3": "102.672%",
                    "4": "111.6%",
                    "5": "118.296%",
                    "6": "124.992%",
                    "7": "133.92%",
                    "8": "142.848%",
                    "9": "151.776%",
                    "10": "160.704%",
                    "11": "169.632%",
                    "12": "178.56%",
                    "13": "189.72%",
                    "14": "200.88%",
                    "15": "212.04%"
                },
                "Charged Attack Stamina Cost": {
                    "1": "50",
                    "2": "50",
                    "3": "50",
                    "4": "50",
                    "5": "50",
                    "6": "50",
                    "7": "50",
                    "8": "50",
                    "9": "50",
                    "10": "50",
                    "11": "50",
                    "12": "50",
                    "13": "50",
                    "14": "50",
                    "15": "50"
                },
                "Plunge DMG": {
                    "1": "74.5878%",
                    "2": "80.6589%",
                    "3": "86.73%",
                    "4": "95.403%",
                    "5": "101.4741%",
                    "6": "108.4125%",
                    "7": "117.9528%",
                    "8": "127.4931%",
                    "9": "137.0334%",
                    "10": "147.441%",
                    "11": "157.8486%",
                    "12": "168.2562%",
                    "13": "178.6638%",
                    "14": "189.0714%",
                    "15": "199.479%"
                },
                "Low\/High Plunge DMG": {
                    "1": "149.144%\/186.2889%",
                    "2": "161.2836%\/201.452%",
                    "3": "173.4233%\/216.615%",
                    "4": "190.7656%\/238.2765%",
                    "5": "202.9052%\/253.4396%",
                    "6": "216.7791%\/270.7688%",
                    "7": "235.8556%\/294.5964%",
                    "8": "254.9322%\/318.4241%",
                    "9": "274.0087%\/342.2517%",
                    "10": "294.8195%\/368.2455%",
                    "11": "315.6303%\/394.2393%",
                    "12": "336.4411%\/420.2331%",
                    "13": "357.2519%\/446.2269%",
                    "14": "378.0627%\/472.2207%",
                    "15": "398.8735%\/498.2145%"
                },
                "Fiery Passion 1-Hit DMG": {
                    "1": "54.4072%",
                    "2": "58.4877%",
                    "3": "62.5683%",
                    "4": "68.009%",
                    "5": "72.0895%",
                    "6": "76.1701%",
                    "7": "81.6108%",
                    "8": "87.0515%",
                    "9": "92.4922%",
                    "10": "97.933%",
                    "11": "103.3737%",
                    "12": "108.8144%",
                    "13": "115.6153%",
                    "14": "122.4162%",
                    "15": "129.2171%"
                },
                "Fiery Passion 2-Hit DMG": {
                    "1": "52.0288%",
                    "2": "55.931%",
                    "3": "59.8331%",
                    "4": "65.036%",
                    "5": "68.9382%",
                    "6": "72.8403%",
                    "7": "78.0432%",
                    "8": "83.2461%",
                    "9": "88.449%",
                    "10": "93.6518%",
                    "11": "98.8547%",
                    "12": "104.0576%",
                    "13": "110.5612%",
                    "14": "117.0648%",
                    "15": "123.5684%"
                },
                "Fiery Passion 3-Hit DMG": {
                    "1": "73.5864%",
                    "2": "79.1054%",
                    "3": "84.6244%",
                    "4": "91.983%",
                    "5": "97.502%",
                    "6": "103.021%",
                    "7": "110.3796%",
                    "8": "117.7382%",
                    "9": "125.0969%",
                    "10": "132.4555%",
                    "11": "139.8142%",
                    "12": "147.1728%",
                    "13": "156.3711%",
                    "14": "165.5694%",
                    "15": "174.7677%"
                },
                "Fiery Passion Charged Attack DMG": {
                    "1": "92.64%",
                    "2": "99.588%",
                    "3": "106.536%",
                    "4": "115.8%",
                    "5": "122.748%",
                    "6": "129.696%",
                    "7": "138.96%",
                    "8": "148.224%",
                    "9": "157.488%",
                    "10": "166.752%",
                    "11": "176.016%",
                    "12": "185.28%",
                    "13": "196.86%",
                    "14": "208.44%",
                    "15": "220.02%"
                },
                "Fiery Passion Charged Attack Stamina Cost": {
                    "1": "50",
                    "2": "50",
                    "3": "50",
                    "4": "50",
                    "5": "50",
                    "6": "50",
                    "7": "50",
                    "8": "50",
                    "9": "50",
                    "10": "50",
                    "11": "50",
                    "12": "50",
                    "13": "50",
                    "14": "50",
                    "15": "50"
                },
                "Fiery Passion Plunge DMG": {
                    "1": "74.5878%",
                    "2": "80.6589%",
                    "3": "86.73%",
                    "4": "95.403%",
                    "5": "101.4741%",
                    "6": "108.4125%",
                    "7": "117.9528%",
                    "8": "127.4931%",
                    "9": "137.0334%",
                    "10": "147.441%",
                    "11": "157.8486%",
                    "12": "168.2562%",
                    "13": "178.6638%",
                    "14": "189.0714%",
                    "15": "199.479%"
                },
                "Fiery Passion Low\/High Plunge DMG": {
                    "1": "223.716%\/279.4334%",
                    "2": "241.9254%\/302.1779%",
                    "3": "260.1349%\/324.9225%",
                    "4": "286.1484%\/357.4148%",
                    "5": "304.3578%\/380.1593%",
                    "6": "325.1686%\/406.1531%",
                    "7": "353.7834%\/441.8946%",
                    "8": "382.3983%\/477.6361%",
                    "9": "411.0131%\/513.3776%",
                    "10": "442.2293%\/552.3683%",
                    "11": "473.4455%\/591.359%",
                    "12": "504.6617%\/630.3497%",
                    "13": "535.8778%\/669.3404%",
                    "14": "567.094%\/708.3311%",
                    "15": "598.3102%\/747.3218%"
                }
            }
        },
        "Elemental Skill": {
            "name": "Riding the Night-Rainbow",
            "text": "With footwork swift as lightning and fierce as thunder, Varesa displays the true spirit of lucha libre, rushing forward a certain distance and dealing Nightsoul-aligned <color=#FFACFFFF>Electro DMG<\/color> to opponents in her path.\\nAfter using this Skill, Varesa gains 20 Nightsoul points and gains the \"Follow-Up Strike\" effect: Varesa has increased interruption resistance during this time, and upon pressing her Normal Attack, she will quickly unleash a Charged Attack that does not consume Stamina. \"Follow-Up Strike\" will be canceled after Varesa uses a Charged Attack.\\nShe will use different techniques based on whether the skill is Tapped or Held.\\n\\n<color=#FFD780FF>Tap<\/color>\\nQuickly rush a certain distance forward.\\n\\n<color=#FFD780FF>Hold<\/color>\\nVaresa enters the Nightsoul's Blessing state and switches to Sudden Onrush mode.\\n\\n<color=#FFD780FF>Sudden Onrush<\/color>\\nContinuously consumes Nightsoul points. In this state, Varesa's Movement SPD and interruption resistance are increased. She can use terrain to execute flying leaps or consume additional Nightsoul points to traverse atop water or liquid Phlogiston while remaining immune to DMG from the latter.\\n\\n<color=#FFD780FF>Nightsoul's Blessing: Varesa<\/color>\\nWhen she runs out of Nightsoul points, her Nightsoul's Blessing state will be canceled. When Varesa is in the Sudden Onrush state or Fiery Passion state, she will always be counted as being in the Nightsoul's Blessing state.\\n\\nHas 2 charges. When Varesa enters the Fiery Passion state, she will obtain an additional Tap charge of her Elemental Skill and its DMG will be increased.\\n\\n<color=#FFD780FF>Fiery Passion<\/color>\\n\u00b7 While not in the Fiery Passion state, Varesa can use Plunging Attacks to gain Nightsoul points. She will enter Fiery Passion when she reaches maximum Nightsoul points via this method, or when she uses her Elemental Burst <color=#FFD780FF>Guardian Vent!<\/color>\\n\u00b7 While in the Fiery Passion state, her Normal Attacks, Elemental Skill, and Elemental Burst will gain unique buffs. She can also use a special Elemental Burst shortly after using a Plunging Attack.\\n\u00b7 The Fiery Passion state lasts for up to 15s and will end when she runs out of Nightsoul points or after she leaves combat for a period of time.\\n\\n<i>\"Right now, I'm my own hero.\"<\/i>",
            "scaling": {
                "Rush DMG": {
                    "1": "74.48%",
                    "2": "80.066%",
                    "3": "85.652%",
                    "4": "93.1%",
                    "5": "98.686%",
                    "6": "104.272%",
                    "7": "111.72%",
                    "8": "119.168%",
                    "9": "126.616%",
                    "10": "134.064%",
                    "11": "141.512%",
                    "12": "148.96%",
                    "13": "158.27%",
                    "14": "167.58%",
                    "15": "176.89%"
                },
                "Fiery Passion Rush DMG": {
                    "1": "106.4%",
                    "2": "114.38%",
                    "3": "122.36%",
                    "4": "133%",
                    "5": "140.98%",
                    "6": "148.96%",
                    "7": "159.6%",
                    "8": "170.24%",
                    "9": "180.88%",
                    "10": "191.52%",
                    "11": "202.16%",
                    "12": "212.8%",
                    "13": "226.1%",
                    "14": "239.4%",
                    "15": "252.7%"
                },
                "Follow-Up Strike Duration": {
                    "1": "5s",
                    "2": "5s",
                    "3": "5s",
                    "4": "5s",
                    "5": "5s",
                    "6": "5s",
                    "7": "5s",
                    "8": "5s",
                    "9": "5s",
                    "10": "5s",
                    "11": "5s",
                    "12": "5s",
                    "13": "5s",
                    "14": "5s",
                    "15": "5s"
                },
                "Nightsoul Point Limit": {
                    "1": "40",
                    "2": "40",
                    "3": "40",
                    "4": "40",
                    "5": "40",
                    "6": "40",
                    "7": "40",
                    "8": "40",
                    "9": "40",
                    "10": "40",
                    "11": "40",
                    "12": "40",
                    "13": "40",
                    "14": "40",
                    "15": "40"
                },
                "CD": {
                    "1": "9s",
                    "2": "9s",
                    "3": "9s",
                    "4": "9s",
                    "5": "9s",
                    "6": "9s",
                    "7": "9s",
                    "8": "9s",
                    "9": "9s",
                    "10": "9s",
                    "11": "9s",
                    "12": "9s",
                    "13": "9s",
                    "14": "9s",
                    "15": "9s"
                }
            }
        },
        "Elemental Burst": {
            "name": "Guardian Vent!",
            "text": "Leaps into the air before using the momentum of the drop to unleash a powerful flying kick, dealing Nightsoul-aligned <color=#FFACFFFF>AoE Electro DMG<\/color> to opponents \u2014 just like those heroes of justice in woven scrolls for kids!\\nAfter using this Skill, Varesa's Nightsoul points will be restored to maximum and she will enter the Fiery Passion state.\\n\\nIn the Fiery Passion state, Varesa's Elemental Burst will deal a greater amount of Nightsoul-aligned <color=#FFACFFFF>AoE Electro DMG<\/color>.\\n\\nAdditionally, she will briefly activate Apex Drive after using a Plunging Attack while in her Fiery Passion state.\\n\\n<color=#FFD780FF>Apex Drive<\/color>\\nIncreases Varesa's interruption resistance. While affected by Apex Drive, Varesa can ignore her Elemental Burst CD and consume less Energy to use her special Elemental Burst, \"Guardian Vent: Volcano Kablam\": This causes her to use the especially powerful Plunging Attack, the \"Thunderous Tornado Eruption,\" which deals Nightsoul-aligned <color=#FFACFFFF>AoE Electro DMG<\/color> upon landing before causing her to exit Apex Drive. This DMG is considered Plunging Attack DMG.\\nVaresa will exit Apex Drive after using her Elemental Skill.\\n\\n<i>In truth, the original name Varesa gave this move was the \"Invincible Dynamic Heroic Justice Super Mega Ultimate Thundercrash Sky-Splitting Supersonic Boom Kick.\" Alas, this name proved too long, and she was too embarrassed to shout it in front of everyone, even with her mask on. As such, she changed it to its present title instead.<\/i>",
            "scaling": {
                "Flying Kick DMG": {
                    "1": "345.12%",
                    "2": "371.004%",
                    "3": "396.888%",
                    "4": "431.4%",
                    "5": "457.284%",
                    "6": "483.168%",
                    "7": "517.68%",
                    "8": "552.192%",
                    "9": "586.704%",
                    "10": "621.216%",
                    "11": "655.728%",
                    "12": "690.24%",
                    "13": "733.38%",
                    "14": "776.52%",
                    "15": "819.66%"
                },
                "Fiery Passion Flying Kick DMG": {
                    "1": "575.2%",
                    "2": "618.34%",
                    "3": "661.48%",
                    "4": "719%",
                    "5": "762.14%",
                    "6": "805.28%",
                    "7": "862.8%",
                    "8": "920.32%",
                    "9": "977.84%",
                    "10": "1035.36%",
                    "11": "1092.88%",
                    "12": "1150.4%",
                    "13": "1222.3%",
                    "14": "1294.2%",
                    "15": "1366.1%"
                },
                "CD": {
                    "1": "18s",
                    "2": "18s",
                    "3": "18s",
                    "4": "18s",
                    "5": "18s",
                    "6": "18s",
                    "7": "18s",
                    "8": "18s",
                    "9": "18s",
                    "10": "18s",
                    "11": "18s",
                    "12": "18s",
                    "13": "18s",
                    "14": "18s",
                    "15": "18s"
                },
                "Energy Cost": {
                    "1": "70",
                    "2": "70",
                    "3": "70",
                    "4": "70",
                    "5": "70",
                    "6": "70",
                    "7": "70",
                    "8": "70",
                    "9": "70",
                    "10": "70",
                    "11": "70",
                    "12": "70",
                    "13": "70",
                    "14": "70",
                    "15": "70"
                },
                "Volcano Kablam DMG": {
                    "1": "402.64%",
                    "2": "432.838%",
                    "3": "463.036%",
                    "4": "503.3%",
                    "5": "533.498%",
                    "6": "563.696%",
                    "7": "603.96%",
                    "8": "644.224%",
                    "9": "684.488%",
                    "10": "724.752%",
                    "11": "765.016%",
                    "12": "805.28%",
                    "13": "855.61%",
                    "14": "905.94%",
                    "15": "956.27%"
                },
                "Volcano Kablam Energy Cost": {
                    "1": "30",
                    "2": "30",
                    "3": "30",
                    "4": "30",
                    "5": "30",
                    "6": "30",
                    "7": "30",
                    "8": "30",
                    "9": "30",
                    "10": "30",
                    "11": "30",
                    "12": "30",
                    "13": "30",
                    "14": "30",
                    "15": "30"
                }
            }
        },
        "1st Ascension Passive": {
            "name": "Tag-Team Triple Jump!",
            "text": "After using the Elemental Skill <color=#FFD780FF>Riding the Night-Rainbow<\/color>, Varesa gains \"Rainbow Crash\" for 5s.\\nDuring this time, when Varesa uses a Plunging Attack, the shockwave DMG dealt when she hits the ground is increased by 50% of her ATK. If Varesa is in the Fiery Passion state, this ground impact DMG is increased by 180% of her ATK instead.\\n\\nThe Rainbow Crash effect will be canceled once a ground impact hits an opponent, or when its duration expires."
        },
        "4th Ascension Passive": {
            "name": "The Hero Twice-Returned!",
            "text": "When a nearby party member triggers a Nightsoul Burst, Varesa's ATK increases by 35% for 12s. Max 2 stacks. Each stack's duration is counted independently."
        },
        "Utility Passive": {
            "name": "Night Realm's Gift: A Torch That Incinerates Evil",
            "text": "After Nightsoul points have been fully depleted, Varesa will switch to using Phlogiston to maintain the Sudden Onrush mode from her Nightsoul's Blessing.\\nWhile in an area with Phlogiston Mechanics within Natlan, Nightsoul Transmission: Varesa can be used. When the current active character is sprinting or in movement modes caused by certain Talents, or at a certain height in the air, switching to Varesa will trigger the following: Varesa enters the Nightsoul's Blessing state, switches to Sudden Onrush mode, and obtains 20 Nightsoul points. Nightsoul Transmission can be triggered once every 10s by your own party.\\nWhile in an area with Phlogiston Mechanics within Natlan, Varesa will not take fall DMG when using terrain differences to make leaps."
        },
        "Passive": {
            "name": "Blazing Heart, Singular Advance!",
            "text": "Varesa's Sprint speed is increased. When she is not in combat, her Sprint Stamina consumption will also increase.\\nAdditionally, while in an area with Phlogiston Mechanics within Natlan, your party members will restore 20 Phlogiston when consuming food. This effect can occur once every 10s and does not take effect in Domains, Trounce Domains, or the Spiral Abyss."
        }
    },
    "constellations": {
        "1": {
            "name": "Undying Passion",
            "text": "The effects of the Passive Talent \"Tag-Team Triple Jump!\" are enhanced:\\nWhen performing the Special Plunging Attack \"Thunderous Tornado Eruption,\" Varesa will also gain \"Rainbow Crash\" for 5s.\\nWhen \"Rainbow Crash\" is in effect, Varesa's Plunging Attack ground impact DMG is increased by 180% of her ATK, whether she is in the Fiery Passion state or not. You must first unlock the Passive Talent \"Tag-Team Triple Jump!\" to access the above effect.\\n\\nAdditionally, when Varesa is in the Sudden Onrush mode of her Nightsoul's Blessing, she consumes 30% less Nightsoul points or Phlogiston."
        },
        "2": {
            "name": "Beyond the Edge of Light",
            "text": "Varesa will enter Apex Drive after using a Plunging Attack, regardless of whether she is in the Fiery Passion state or not.\\nWhen Apex Drive is active, Varesa's interruption resistance will also further increase.\\nAdditionally, Varesa will restore 11.5 Energy when her Plunging Attack ground impact hits an opponent."
        },
        "3": {
            "name": "Unbowed Resolve",
            "text": "Increases the Level of <color=#FFD780FF>Guardian Vent!<\/color> by 3.\\nMaximum upgrade level is 15."
        },
        "4": {
            "name": "The Courage to Press On",
            "text": "Varesa will receive various buffs based on her state when using her Elemental Burst <color=#FFD780FF>Guardian Vent!<\/color> If Varesa:\\n\u00b7 Has neither Fiery Passion nor Apex Drive active, she will gain Diligent Refinement for 15s, which will increase her Plunging Attack ground impact DMG by 500% of her ATK, with a maximum increase of 20,000 DMG. This effect will be canceled once the ground impact hits an opponent, or if its duration ends.\\n\u00b7 If she has either Fiery Passion or Apex Drive active, this instance of her Elemental Burst <color=#FFD780FF>Guardian Vent!<\/color> deals 100% increased DMG."
        },
        "5": {
            "name": "Thoughts Floating on the Warm Breeze",
            "text": "Increases the Level of <color=#FFD780FF>Normal Attack: By the Horns<\/color> by 3.\\nMaximum upgrade level is 15."
        },
        "6": {
            "name": "A Hero of Justice's Triumph",
            "text": "Varesa restores 30 Energy when she enters Apex Drive.\\nHer Plunging Attacks and Elemental Burst <color=#FFD780FF>Guardian Vent!<\/color> gain 10% CRIT Rate and 100% CRIT DMG.\\nAdditionally, when Varesa uses the Hold version of her Elemental Skill <color=#FFD780FF>Riding the Night-Rainbow<\/color>, or Taps her Elemental Skill while in the Sudden Onrush mode, she will restore Nightsoul points up to her maximum."
        }
    }
};