export default {
    "talents": {
        "Normal Attack": {
            "name": "Vila Blade Dance",
            "icon": "Skill_A_01",
            "text": "<color=#FFD780FF>Normal Attack<\/color>\\nPerforms up to 6 consecutive strikes.\\n\\n<color=#FFD780FF>Charged Attack<\/color>\\nConsumes a certain amount of Stamina to trample opponents in front of her.\\n\\n<color=#FFD780FF>Plunging Attack<\/color>\\nPlunges from mid-air to strike the ground below, damaging opponents along her path and dealing AoE DMG upon impact.",
            "scaling": {
                "1-Hit DMG": [
                    "40.42%",
                    "43.71%",
                    "47%",
                    "51.7%",
                    "54.99%",
                    "58.75%",
                    "63.92%",
                    "69.09%",
                    "74.26%",
                    "79.9%",
                    "85.54%",
                    "91.18%",
                    "96.82%",
                    "102.46%",
                    "108.1%"
                ],
                "2-Hit DMG": [
                    "48.68%",
                    "52.64%",
                    "56.6%",
                    "62.26%",
                    "66.22%",
                    "70.75%",
                    "76.98%",
                    "83.2%",
                    "89.43%",
                    "96.22%",
                    "103.01%",
                    "109.8%",
                    "116.6%",
                    "123.39%",
                    "130.18%"
                ],
                "3-Hit DMG": [
                    "28.08%\u00d72",
                    "30.36%\u00d72",
                    "32.65%\u00d72",
                    "35.91%\u00d72",
                    "38.2%\u00d72",
                    "40.81%\u00d72",
                    "44.4%\u00d72",
                    "48%\u00d72",
                    "51.59%\u00d72",
                    "55.51%\u00d72",
                    "59.42%\u00d72",
                    "63.34%\u00d72",
                    "67.26%\u00d72",
                    "71.18%\u00d72",
                    "75.09%\u00d72"
                ],
                "4-Hit DMG": [
                    "59.17%",
                    "63.98%",
                    "68.8%",
                    "75.68%",
                    "80.5%",
                    "86%",
                    "93.57%",
                    "101.14%",
                    "108.7%",
                    "116.96%",
                    "125.22%",
                    "133.47%",
                    "141.73%",
                    "149.98%",
                    "158.24%"
                ],
                "5-Hit DMG": [
                    "62.44%",
                    "67.52%",
                    "72.6%",
                    "79.86%",
                    "84.94%",
                    "90.75%",
                    "98.74%",
                    "106.72%",
                    "114.71%",
                    "123.42%",
                    "132.13%",
                    "140.84%",
                    "149.56%",
                    "158.27%",
                    "166.98%"
                ],
                "6-Hit DMG": [
                    "72.24%",
                    "78.12%",
                    "84%",
                    "92.4%",
                    "98.28%",
                    "105%",
                    "114.24%",
                    "123.48%",
                    "132.72%",
                    "142.8%",
                    "152.88%",
                    "162.96%",
                    "173.04%",
                    "183.12%",
                    "193.2%"
                ],
                "Charged Attack DMG": [
                    "133.04%",
                    "143.87%",
                    "154.7%",
                    "170.17%",
                    "181%",
                    "193.38%",
                    "210.39%",
                    "227.41%",
                    "244.43%",
                    "262.99%",
                    "281.55%",
                    "300.12%",
                    "318.68%",
                    "337.25%",
                    "355.81%"
                ],
                "Charged Attack Stamina Cost": [
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20"
                ],
                "Plunge DMG": [
                    "63.93%",
                    "69.14%",
                    "74.34%",
                    "81.77%",
                    "86.98%",
                    "92.93%",
                    "101.1%",
                    "109.28%",
                    "117.46%",
                    "126.38%",
                    "135.3%",
                    "144.22%",
                    "153.14%",
                    "162.06%",
                    "170.98%"
                ],
                "Low\/High Plunge DMG": [
                    "127.84%\/159.68%",
                    "138.24%\/172.67%",
                    "148.65%\/185.67%",
                    "163.51%\/204.24%",
                    "173.92%\/217.23%",
                    "185.81%\/232.09%",
                    "202.16%\/252.51%",
                    "218.51%\/272.93%",
                    "234.86%\/293.36%",
                    "252.7%\/315.64%",
                    "270.54%\/337.92%",
                    "288.38%\/360.2%",
                    "306.22%\/382.48%",
                    "324.05%\/404.76%",
                    "341.89%\/427.04%"
                ]
            }
        },
        "Elemental Skill": {
            "name": "The Art of Victory",
            "icon": "Skill_S_Vesna_01",
            "text": "Calls forth Spirit Blades passed down through generations of the Vila to deal <color=#80FFD7FF>AoE Anemo DMG<\/color>, then switches to the <color=#FFD780FF>{LINK#N11430001}Armed for Action{\/LINK}<\/color> mode and gains 2 stacks of <color=#FFD780FF>{LINK#N11430002}Sword Essence{\/LINK}<\/color>.\\n\\n<color=#FFD780FF>Armed for Action<\/color>\\nDMG dealt by Vesna with her Normal Attacks, Charged Attacks, and Plunging Attacks become <color=#80FFD7FF>Anemo DMG<\/color> that cannot be overridden by another elemental infusion instead. She will also summon a wind pinion that attacks the opponent at the same time, dealing additional <color=#80FFD7FF>Anemo DMG<\/color>. Each time the wind pinion is summoned, Vesna will regenerate a certain amount of <color=#FFD780FF>Sword Essence<\/color>.\\nVesna can consume <color=#FFD780FF>Sword Essence<\/color> to unleash the special Elemental Skill <color=#FFD780FF>{LINK#N11430003}Windborne Sword{\/LINK}<\/color>, which deals to the opponent <color=#80FFD7FF>Anemo DMG<\/color>.\\nEach use of the special Elemental Skill <color=#FFD780FF>Windborne Sword<\/color> in the same instance of <color=#FFD780FF>Armed for Action<\/color> will increase the level of <color=#FFD780FF>Windborne Sword<\/color>, beginning from Lv. 1 to Lv. 3 max, for more <color=#80FFD7FF>Anemo DMG<\/color>. Using <color=#FFD780FF>Windborne Sword<\/color> at Lv. 2 and Lv. 3 will also summon <color=#FFD780FF>{LINK#N11430004}Spirit Blades{\/LINK}<\/color> which deal <color=#80FFD7FF>Anemo DMG<\/color>.\\nVesna will exit the mode when its duration ends or when she has used <color=#FFD780FF>Windborne Sword<\/color> at the highest level 3 times. Exiting will clear all remaining <color=#FFD780FF>Sword Essence<\/color> she has accrued.\\nAdditionally, when in this mode, Vesna's resistance to interruption is increased.\\n<color=#FFD780FF>Radiance: Stellar Swirl<\/color>: DMG dealt with the <color=#FFD780FF>Spirit Blades<\/color> becomes <color=#80FFD7FF>Anemo DMG<\/color> that is also considered Stellar Swirl reaction DMG.\n\\n\\n<i>\"Make way, make way! The Druzhna has command over the battlefield from here on out!\"<\/i>",
            "scaling": {
                "Skill DMG": [
                    "40%",
                    "43%",
                    "46%",
                    "50%",
                    "53%",
                    "56%",
                    "60%",
                    "64%",
                    "68%",
                    "72%",
                    "76%",
                    "80%",
                    "85%",
                    "90%",
                    "95%"
                ],
                "Windborne Sword Lv. 1 DMG": [
                    "40%",
                    "43%",
                    "46%",
                    "50%",
                    "53%",
                    "56%",
                    "60%",
                    "64%",
                    "68%",
                    "72%",
                    "76%",
                    "80%",
                    "85%",
                    "90%",
                    "95%"
                ],
                "Windborne Sword Lv. 2 DMG": [
                    "60%",
                    "64.5%",
                    "69%",
                    "75%",
                    "79.5%",
                    "84%",
                    "90%",
                    "96%",
                    "102%",
                    "108%",
                    "114%",
                    "120%",
                    "127.5%",
                    "135%",
                    "142.5%"
                ],
                "Windborne Sword Lv. 2 Spirit Blade DMG": [
                    "112%",
                    "120.4%",
                    "128.8%",
                    "140%",
                    "148.4%",
                    "156.8%",
                    "168%",
                    "179.2%",
                    "190.4%",
                    "201.6%",
                    "212.8%",
                    "224%",
                    "238%",
                    "252%",
                    "266%"
                ],
                "Windborne Sword Lv. 3 Spirit Blade DMG": [
                    "44.8% \u00d74",
                    "48.16% \u00d74",
                    "51.52% \u00d74",
                    "56% \u00d74",
                    "59.36% \u00d74",
                    "62.72% \u00d74",
                    "67.2% \u00d74",
                    "71.68% \u00d74",
                    "76.16% \u00d74",
                    "80.64% \u00d74",
                    "85.12% \u00d74",
                    "89.6% \u00d74",
                    "95.2% \u00d74",
                    "100.8% \u00d74",
                    "106.4% \u00d74"
                ],
                "Windborne Sword Lv. 3 Spirit Blade Final Hit DMG": [
                    "156.8%",
                    "168.56%",
                    "180.32%",
                    "196%",
                    "207.76%",
                    "219.52%",
                    "235.2%",
                    "250.88%",
                    "266.56%",
                    "282.24%",
                    "297.92%",
                    "313.6%",
                    "333.2%",
                    "352.8%",
                    "372.4%"
                ],
                "Windborne Sword Lv. 2 Spirit Blade Stellar Swirl DMG": [
                    "112%",
                    "120.4%",
                    "128.8%",
                    "140%",
                    "148.4%",
                    "156.8%",
                    "168%",
                    "179.2%",
                    "190.4%",
                    "201.6%",
                    "212.8%",
                    "224%",
                    "238%",
                    "252%",
                    "266%"
                ],
                "Windborne Sword Lv. 3 Spirit Blade Stellar Swirl DMG": [
                    "44.8% \u00d74",
                    "48.16% \u00d74",
                    "51.52% \u00d74",
                    "56% \u00d74",
                    "59.36% \u00d74",
                    "62.72% \u00d74",
                    "67.2% \u00d74",
                    "71.68% \u00d74",
                    "76.16% \u00d74",
                    "80.64% \u00d74",
                    "85.12% \u00d74",
                    "89.6% \u00d74",
                    "95.2% \u00d74",
                    "100.8% \u00d74",
                    "106.4% \u00d74"
                ],
                "Windborne Sword Lv. 3 Spirit Blade Final Hit Stellar Swirl DMG": [
                    "156.8%",
                    "168.56%",
                    "180.32%",
                    "196%",
                    "207.76%",
                    "219.52%",
                    "235.2%",
                    "250.88%",
                    "266.56%",
                    "282.24%",
                    "297.92%",
                    "313.6%",
                    "333.2%",
                    "352.8%",
                    "372.4%"
                ],
                "Wind Pinion DMG": [
                    "10.4%",
                    "11.18%",
                    "11.96%",
                    "13%",
                    "13.78%",
                    "14.56%",
                    "15.6%",
                    "16.64%",
                    "17.68%",
                    "18.72%",
                    "19.76%",
                    "20.8%",
                    "22.1%",
                    "23.4%",
                    "24.7%"
                ],
                "Armed for Action Duration": [
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s"
                ],
                "CD": [
                    "18s",
                    "18s",
                    "18s",
                    "18s",
                    "18s",
                    "18s",
                    "18s",
                    "18s",
                    "18s",
                    "18s",
                    "18s",
                    "18s",
                    "18s",
                    "18s",
                    "18s"
                ]
            }
        },
        "Elemental Burst": {
            "name": "For the Tsaritsa!",
            "icon": "Skill_E_Vesna_01",
            "text": "Summons multiple <color=#FFD780FF>{LINK#N11430004}Spirit Blades{\/LINK}<\/color>, dealing <color=#80FFD7FF>AoE Anemo DMG<\/color>. Also gains a stack of <color=#FFD780FF>{LINK#N11430002}Sword Essence{\/LINK}<\/color>.\n\\n\\n<i>\"First, always hold on tight to the sword in your hand; second, always present a neat and dignified appearance; and most important of all, always remain loyal to Her Majesty the Tsaritsa!\"<\/i>",
            "scaling": {
                "Spirit Blade DMG": [
                    "263.2%",
                    "282.94%",
                    "302.68%",
                    "329%",
                    "348.74%",
                    "368.48%",
                    "394.8%",
                    "421.12%",
                    "447.44%",
                    "473.76%",
                    "500.08%",
                    "526.4%",
                    "559.3%",
                    "592.2%",
                    "625.1%"
                ],
                "Spirit Blade Stellar Swirl DMG": [
                    "263.2%",
                    "282.94%",
                    "302.68%",
                    "329%",
                    "348.74%",
                    "368.48%",
                    "394.8%",
                    "421.12%",
                    "447.44%",
                    "473.76%",
                    "500.08%",
                    "526.4%",
                    "559.3%",
                    "592.2%",
                    "625.1%"
                ],
                "CD": [
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s"
                ],
                "Energy Cost": [
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60"
                ]
            }
        },
        "1st Ascension Passive": {
            "name": "Rite of Spring's Procession",
            "icon": "UI_Talent_S_Vesna_05",
            "text": "After Vesna uses the special Elemental Skill <color=#FFD780FF>{LINK#N11430003}Windborne Sword{\/LINK}<\/color> or the Elemental Burst <color=#FFD780FF>{LINK#S11435}For the Tsaritsa!{\/LINK}<\/color>, she also gains 1 stack of <color=#FFD780FF>Disciplinary Action<\/color> which lasts 20s. Max 6 stacks, and the duration of each stack is independent of the others'.\\nWhen she has <color=#FFD780FF>Disciplinary Action<\/color> stacks active, the <color=#FFD780FF>{LINK#N11430004}Spirit Blades{\/LINK}<\/color> summoned by Vesna will deal DMG equal to (100% + 10% \u00d7 Disciplinary Action stack count) of the original DMG instead. All active stacks of <color=#FFD780FF>Disciplinary Action<\/color> are cleared when Vesna uses the Elemental Skill <color=#FFD780FF>The Art of Victory<\/color> or when she leaves the field."
        },
        "4th Ascension Passive": {
            "name": "Truth Prevails",
            "icon": "UI_Talent_S_Vesna_06",
            "text": "<color=#FFD780FF>Radiance: Stellar Swirl<\/color>: Vesna will gain the corresponding effect based on the Elemental Type of her party members: \\n\u00b7 For every <color=#99FFFFFF>Cryo<\/color> or <color=#80FFD7FF>Anemo<\/color> character in her current party, Vesna's ATK increases by 6%; and\\n\u00b7 For every character of all other Elemental Types in her current party, Vesna's Elemental Mastery increases by 25 instead."
        },
        "Utility Passive": {
            "name": "Stellar Jubilee: Splendid Prelude",
            "icon": "UI_Talent_S_Vesna_08",
            "text": "When party members trigger Cryo Swirl, it will be changed to a Stellar Swirl reaction, and party members' Base DMG for the Stellar Swirl will be increased based on Vesna's ATK. Every 100 ATK she has increases the Base Stellar Swirl DMG by 0.7%. The maximum DMG increase that can be gained this way is 14%.\\nAfter a party member triggers a Stellar Swirl reaction nearby, Vesna enters the <color=#FFD780FF>Radiance: Stellar Swirl<\/color> state for 8s."
        },
        "Passive": {
            "name": "The Grand Circuit",
            "icon": "UI_Talent_S_Vesna_07",
            "text": "Holding on Sprint or Jump when Vesna is not in combat will cause her to enter the <color=#FFD780FF>Coursing<\/color> state.\\n\\n<color=#FFD780FF>Coursing<\/color>\\nContinuously consumes Stamina to hover in mid-air. Sprinting or tapping Jump to go higher expends additional Stamina. Including the hold on Jump that triggers <color=#FFD780FF>Coursing<\/color>, Vesna can go higher up to 3 times in each instance of the <color=#FFD780FF>Coursing<\/color> state.\\n\\nAdditionally, in Snezhnaya (excluding Nod-Krai), when Vesna is switched onto the field while the currently active party member is in mid-air and not in combat, she will immediately enter the <color=#FFD780FF>Coursing<\/color> state and regenerate 50 Stamina. This effect can trigger once every 10s, and does not take effect in Domains, Trounce Domains, or the Spiral Abyss."
        }
    },
    "constellations": {
        "1": {
            "name": "Winter's Farewell Feast",
            "icon": "UI_Talent_S_Vesna_01",
            "text": "When in the <color=#FFD780FF>{LINK#N11430001}Armed for Action{\/LINK}<\/color> mode, Vesna can unleash <color=#FFD780FF>{LINK#N11430003}Windborne Sword{\/LINK}<\/color> at the highest level 4 times instead of 3. Also, each time she enters the <color=#FFD780FF>Armed for Action<\/color> mode, she will not consume <color=#FFD780FF>{LINK#N11430002}Sword Essence{\/LINK}<\/color> the first time she uses <color=#FFD780FF>Windborne Sword<\/color> at the highest level.\\nAdditionally, Vesna deals 20% increased Stellar Swirl reaction DMG when in the <color=#FFD780FF>Armed for Action<\/color> mode."
        },
        "2": {
            "name": "Kolo of Spring's Arrival",
            "icon": "UI_Talent_S_Vesna_02",
            "text": "The Ascension Talent <color=#FFD780FF>{LINK#P1432101}Rite of Spring's Procession{\/LINK}<\/color> is enhanced: Vesna gains the maximum number of <color=#FFD780FF>Disciplinary Action<\/color> stacks when she enters <color=#FFD780FF>{LINK#N11430001}Armed for Action{\/LINK}<\/color> mode. Vesna's ATK is increased by 40% when she has maximum <color=#FFD780FF>Disciplinary Action<\/color> stacks.\\nYou must unlock the Ascension Talent \"Rite of Spring's Procession\" to gain access to the above effects."
        },
        "3": {
            "name": "Winter's Last Offering",
            "icon": "UI_Talent_U_Vesna_01",
            "text": "Increases the Level of the Elemental Skill <color=#FFD780FF>{LINK#S11432}The Art of Victory{\/LINK}<\/color> by 3.\\nMaximum upgrade level is 15."
        },
        "4": {
            "name": "Glory to Our Forebears",
            "icon": "UI_Talent_S_Vesna_03",
            "text": "The Ascension Talent <color=#FFD780FF>{LINK#P1432201}Truth Prevails{\/LINK}<\/color> is enhanced: Its ATK and Elemental Mastery bonuses increase to 3 times their original values."
        },
        "5": {
            "name": "The Nobleborn's Charge",
            "icon": "UI_Talent_U_Vesna_02",
            "text": "Increases the Level of the Elemental Burst <color=#FFD780FF>{LINK#S11435}For the Tsaritsa!{\/LINK}<\/color> by 3.\\nMaximum upgrade level is 15."
        },
        "6": {
            "name": "Unwavering Ardor",
            "icon": "UI_Talent_S_Vesna_04",
            "text": "Tapping on Normal Attack or Elemental Skill in the 5s after Vesna uses <color=#FFD780FF>{LINK#N11430003}Windborne Sword{\/LINK}<\/color> at its highest level will unleash the secret Vila ability <color=#FFD780FF>Windborne Sword: Transpose<\/color>, dealing <color=#80FFD7FF>Anemo DMG<\/color> at 150% of Vesna's ATK as well as summoning <color=#FFD780FF>{LINK#N11430004}Spirit Blades{\/LINK}<\/color> which deal an additional instance of <color=#80FFD7FF>Anemo DMG<\/color> at 200% of Vesna's ATK. If Vesna is in the <color=#FFD780FF>{LINK#N11430001}Armed for Action{\/LINK}<\/color> mode, she will also summon a wind pinion to perform Coordinated Attacks against opponents.\\nAdditionally, Vesna's Stellar Swirl reaction DMG dealt is {LINK#N11190007}<color=#FFD780FF>elevated<\/color>{\/LINK} by 20%."
        }
    }
};