export default {
    "talents": {
        "Normal Attack": {
            "name": "Psyshkhwe Arietta",
            "icon": "Skill_A_Catalyst_MD",
            "text": "<color=#FFD780FF>Normal Attack<\/color>\\nSings an ancient song of the Water Imps, unleashing up to 4 strikes. This deals <color=#80C0FFFF>Hydro DMG<\/color> to the opponent.\\n\\n<color=#FFD780FF>Charged Attack<\/color>\\nConsumes a certain amount of Stamina to hurl a water ball forward, dealing <color=#80C0FFFF>Hydro DMG<\/color>.\\n\\n<color=#FFD780FF>Plunging Attack<\/color>\\nPlunges towards the ground from mid-air, damaging all opponents along the path. Deals <color=#80C0FFFF>AoE Hydro DMG<\/color> upon impact with the ground.",
            "scaling": {
                "1-Hit DMG": [
                    "43.38%",
                    "46.64%",
                    "49.89%",
                    "54.23%",
                    "57.48%",
                    "60.74%",
                    "65.08%",
                    "69.42%",
                    "73.75%",
                    "78.09%",
                    "82.43%",
                    "86.77%",
                    "92.19%",
                    "97.62%",
                    "103.04%"
                ],
                "2-Hit DMG": [
                    "40.23%",
                    "43.25%",
                    "46.27%",
                    "50.29%",
                    "53.31%",
                    "56.32%",
                    "60.35%",
                    "64.37%",
                    "68.39%",
                    "72.42%",
                    "76.44%",
                    "80.46%",
                    "85.49%",
                    "90.52%",
                    "95.55%"
                ],
                "3-Hit DMG": [
                    "49.3%",
                    "53%",
                    "56.7%",
                    "61.63%",
                    "65.32%",
                    "69.02%",
                    "73.95%",
                    "78.88%",
                    "83.81%",
                    "88.74%",
                    "93.67%",
                    "98.6%",
                    "104.77%",
                    "110.93%",
                    "117.09%"
                ],
                "4-Hit DMG": [
                    "65.56%",
                    "70.48%",
                    "75.4%",
                    "81.95%",
                    "86.87%",
                    "91.79%",
                    "98.34%",
                    "104.9%",
                    "111.46%",
                    "118.01%",
                    "124.57%",
                    "131.13%",
                    "139.32%",
                    "147.52%",
                    "155.71%"
                ],
                "Charged Attack DMG": [
                    "123.76%",
                    "133.04%",
                    "142.32%",
                    "154.7%",
                    "163.98%",
                    "173.26%",
                    "185.64%",
                    "198.02%",
                    "210.39%",
                    "222.77%",
                    "235.14%",
                    "247.52%",
                    "262.99%",
                    "278.46%",
                    "293.93%"
                ],
                "Charged Attack Stamina Cost": [
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50"
                ],
                "Plunge DMG": [
                    "56.83%",
                    "61.45%",
                    "66.08%",
                    "72.69%",
                    "77.31%",
                    "82.6%",
                    "89.87%",
                    "97.14%",
                    "104.41%",
                    "112.34%",
                    "120.27%",
                    "128.2%",
                    "136.12%",
                    "144.05%",
                    "151.98%"
                ],
                "Low\/High Plunge DMG": [
                    "113.63%\/141.93%",
                    "122.88%\/153.49%",
                    "132.13%\/165.04%",
                    "145.35%\/181.54%",
                    "154.59%\/193.1%",
                    "165.16%\/206.3%",
                    "179.7%\/224.45%",
                    "194.23%\/242.61%",
                    "208.77%\/260.76%",
                    "224.62%\/280.57%",
                    "240.48%\/300.37%",
                    "256.34%\/320.18%",
                    "272.19%\/339.98%",
                    "288.05%\/359.79%",
                    "303.9%\/379.59%"
                ]
            }
        },
        "Elemental Skill": {
            "name": "Rechitativ: Sonorous Dawn",
            "icon": "Skill_S_Vodyanitsa_01",
            "text": "Reveals her true Water Imp form, dealing <color=#80C0FFFF>AoE Hydro DMG<\/color> and gaining the <color=#FFD780FF>Song of Ages Past<\/color> effect: While this effect is active, Vodyanitsa summons the ancient <color=#FFD780FF>Horn of Spring's Call<\/color>, periodically moving closer to an opponent in a swift movement to attack them, dealing <color=#80C0FFFF>Hydro DMG<\/color>.\\nThe above two types of attacks will also decrease the <color=#80C0FFFF>Hydro RES<\/color> and <color=#99FFFFFF>Cryo RES<\/color> of opponents hit. Additionally, while the <color=#FFD780FF>Song of Ages Past<\/color> effect is active, the party's active character gains increased resistance to interruption and periodically regenerates HP based on Vodyanitsa's Max HP.\n\\n\\n<i>\"I shall not lament, nor shall I call out or weep. All things shall pass, like mist that softly drifts across the boughs of the white apple trees.\"\\n\"And yet, and yet \u2014 for all living things upon the earth, I wish you everlasting beauty and happiness.\"<\/i>",
            "scaling": {
                "Skill DMG": [
                    "3.27% Max HP",
                    "3.52% Max HP",
                    "3.76% Max HP",
                    "4.09% Max HP",
                    "4.34% Max HP",
                    "4.58% Max HP",
                    "4.91% Max HP",
                    "5.24% Max HP",
                    "5.56% Max HP",
                    "5.89% Max HP",
                    "6.22% Max HP",
                    "6.54% Max HP",
                    "6.95% Max HP",
                    "7.36% Max HP",
                    "7.77% Max HP"
                ],
                "Duration": [
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s"
                ],
                "Horn of Spring's Call Attack Interval": [
                    "3s",
                    "3s",
                    "3s",
                    "3s",
                    "3s",
                    "3s",
                    "3s",
                    "3s",
                    "3s",
                    "3s",
                    "3s",
                    "3s",
                    "3s",
                    "3s",
                    "3s"
                ],
                "Horn of Spring's Call DMG": [
                    "3.27% Max HP",
                    "3.52% Max HP",
                    "3.76% Max HP",
                    "4.09% Max HP",
                    "4.34% Max HP",
                    "4.58% Max HP",
                    "4.91% Max HP",
                    "5.24% Max HP",
                    "5.56% Max HP",
                    "5.89% Max HP",
                    "6.22% Max HP",
                    "6.54% Max HP",
                    "6.95% Max HP",
                    "7.36% Max HP",
                    "7.77% Max HP"
                ],
                "Song of Ages Past Healing": [
                    "270 + 2.8% Max HP",
                    "297 + 3.01% Max HP",
                    "326 + 3.22% Max HP",
                    "357 + 3.5% Max HP",
                    "391 + 3.71% Max HP",
                    "427 + 3.92% Max HP",
                    "465 + 4.2% Max HP",
                    "506 + 4.48% Max HP",
                    "548 + 4.76% Max HP",
                    "593 + 5.04% Max HP",
                    "640 + 5.32% Max HP",
                    "690 + 5.6% Max HP",
                    "742 + 5.95% Max HP",
                    "795 + 6.3% Max HP",
                    "852 + 6.65% Max HP"
                ],
                "Song of Ages Past Healing Interval": [
                    "1.5s",
                    "1.5s",
                    "1.5s",
                    "1.5s",
                    "1.5s",
                    "1.5s",
                    "1.5s",
                    "1.5s",
                    "1.5s",
                    "1.5s",
                    "1.5s",
                    "1.5s",
                    "1.5s",
                    "1.5s",
                    "1.5s"
                ],
                "Hydro\/Cryo RES Reduction": [
                    "16.5%",
                    "18%",
                    "19.5%",
                    "21%",
                    "22.5%",
                    "24%",
                    "25.5%",
                    "27%",
                    "28.5%",
                    "30%",
                    "31.8%",
                    "33.6%",
                    "35.4%",
                    "37.2%",
                    "39%"
                ],
                "RES Reduction Duration": [
                    "6s",
                    "6s",
                    "6s",
                    "6s",
                    "6s",
                    "6s",
                    "6s",
                    "6s",
                    "6s",
                    "6s",
                    "6s",
                    "6s",
                    "6s",
                    "6s",
                    "6s"
                ],
                "Skill CD": [
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s"
                ]
            }
        },
        "Elemental Burst": {
            "name": "Koda: Sink With Thee",
            "icon": "Skill_E_Vodyanitsa_01",
            "text": "Leads a song of the Water Imps which lures its listeners to their doom. This deals <color=#80C0FFFF>AoE Hydro DMG<\/color> to the opponent.\\nWhen in the <color=#FFD780FF>{LINK#S11402}Song of Ages Past{\/LINK}<\/color> state, DMG dealt is further increased.\n\\n\\n<i>\"According to legend, the song of the Water Imps can lead sailors to their ruin. But if everyone was lost to the water, where did this story come from?\"\\n\"It's probably from a Domovoy sailor who was too short to go over the ship's railing, heh... Stop giving me that look, Odette! I was just joking!\"<\/i>",
            "scaling": {
                "Skill DMG": [
                    "45.68% Max HP",
                    "49.1% Max HP",
                    "52.53% Max HP",
                    "57.1% Max HP",
                    "60.52% Max HP",
                    "63.95% Max HP",
                    "68.52% Max HP",
                    "73.08% Max HP",
                    "77.65% Max HP",
                    "82.22% Max HP",
                    "86.79% Max HP",
                    "91.35% Max HP",
                    "97.06% Max HP",
                    "102.77% Max HP",
                    "108.48% Max HP"
                ],
                "Song of Ages Past DMG Bonus": [
                    "48%",
                    "51.6%",
                    "55.2%",
                    "60%",
                    "63.6%",
                    "67.2%",
                    "72%",
                    "76.8%",
                    "81.6%",
                    "86.4%",
                    "91.2%",
                    "96%",
                    "102%",
                    "108%",
                    "114%"
                ],
                "CD": [
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s"
                ],
                "Energy Cost": [
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60"
                ]
            }
        },
        "1st Ascension Passive": {
            "name": "The Last Djeguako Songstress",
            "icon": "UI_Talent_S_Vodyanitsa_06",
            "text": "When the Elemental Skill <color=#FFD780FF>Rechitativ: Sonorous Dawn<\/color> is used, any Stellar Vortex on the field will turn into a Wandering Vortex instead. While the <color=#FFD780FF>{LINK#S11402}Song of Ages Past{\/LINK}<\/color> effect is active, nearby party members' Stellar Swirl reactions will generate Wandering Vortex instead.\\nGenerating or detonating a Wandering Vortex will also reduce nearby opponents' <color=#80FFD7FF>Anemo RES<\/color> by 35% for 6s. \\nAdditionally, nearby party members who enter the <color=#FFD780FF>Radiance: Stellar Swirl<\/color> state while <color=#FFD780FF>Song of Ages Past<\/color> is in effect will have the <color=#FFD780FF>Radiance: Stellar Swirl<\/color> state extended by 4s."
        },
        "4th Ascension Passive": {
            "name": "Dirge of the Fandyr",
            "icon": "UI_Talent_S_Vodyanitsa_05",
            "text": "When the Elemental Skill <color=#FFD780FF>Rechitativ: Sonorous Dawn<\/color> is used, Vodyanitsa will also gain 25 stacks of {LINK#N11400001}<color=#FFD780FF>Lead Vocal<\/color>{\/LINK} as well as 10 stacks of {LINK#N11400002}<color=#FFD780FF>Chorus<\/color>{\/LINK}.\\nThe two effects above last 30s each, and the stack count is refreshed when the Elemental Skill is used."
        },
        "Utility Passive": {
            "name": "Echoes Over the Frozen Lake",
            "icon": "UI_Talent_S_Vodyanitsa_07",
            "text": "Holding the Elemental Skill outside of combat will cause Vodyanitsa to embody her true Water Imp form and swim for up to 10s at the cost of Stamina. Naturally, as a Water Imp, she can also move across the water's surface. Vodyanitsa will exit her Water Imp form when the Elemental Skill is used again, when the duration ends, or when all Stamina is depleted.\\nAdditionally, while Vodyanitsa can swim faster, her Stamina consumption rate is also increased."
        },
        "Passive": {
            "name": "Heartless Siren Song",
            "icon": "UI_Talent_S_Vodyanitsa_08",
            "text": "As the Prima Donna of the Korolevskiy Troupe, Vodyanitsa sings in person in place of playing an instrument."
        }
    },
    "constellations": {
        "1": {
            "name": "Waters in Full Splendor",
            "icon": "UI_Talent_S_Vodyanitsa_01",
            "text": "Each time Vodyanitsa triggers the healing effect of <color=#FFD780FF>{LINK#S11402}Song of Ages Past{\/LINK}<\/color>, it also increases the ATK of all nearby party members by 0.8% of her Max HP for 5s."
        },
        "2": {
            "name": "Echoes That Pierce the Snow",
            "icon": "UI_Talent_S_Vodyanitsa_02",
            "text": "When the <color=#FFD780FF>Horn of Spring's Call<\/color> from the Elemental Skill <color=#FFD780FF>Rechitativ: Sonorous Dawn<\/color> attacks the opponent, Vodyanitsa gains the \"Two Voices in Black and White\" effect which increases the CRIT DMG from <color=#80C0FFFF>Hydro DMG<\/color> and <color=#99FFFFFF>Cryo DMG<\/color> dealt by the currently active party member by 50% for 5s.\\nIf there is a Wandering Vortex present on the field or in the 5s after a Wandering Vortex explodes, the effect changes to: increases the CRIT DMG from Stellar Swirl reaction DMG caused by the currently active party member by 60% for 5s.\\nAdditionally, the Elemental Skill <color=#FFD780FF>Rechitativ: Sonorous Dawn<\/color> is enhanced as follows: the duration of the <color=#FFD780FF>{LINK#S11402}Song of Ages Past{\/LINK}<\/color> effect is extended by 9s."
        },
        "3": {
            "name": "Song Lingering on a Spring Morning",
            "icon": "UI_Talent_U_Vodyanitsa_01",
            "text": "Increases the Level of the Elemental Skill <color=#FFD780FF>{LINK#S11402}Rechitativ: Sonorous Dawn{\/LINK}<\/color> by 3.\\nMaximum upgrade level is 15."
        },
        "4": {
            "name": "Melancholic Voice Upon the Gentle Waters",
            "icon": "UI_Talent_S_Vodyanitsa_03",
            "text": "When Vodyanitsa triggers the healing effect of <color=#FFD780FF>{LINK#S11402}Song of Ages Past{\/LINK}<\/color>, an additional effect will be triggered based on the healed character's HP.\\n\u00b7 If the character's HP is below 40%: The healing is increased by 50%; and\\n\u00b7 If the character's HP is 40% or above: Vodyanitsa's Max HP is increased by 20% for 6s. Max 3 stacks, and each stack's duration is counted independently."
        },
        "5": {
            "name": "Together, Down Into the Deep",
            "icon": "UI_Talent_U_Vodyanitsa_02",
            "text": "Increases the Level of the Elemental Burst <color=#FFD780FF>{LINK#S11405}Koda: Sink With Thee{\/LINK}<\/color> by 3.\\nMaximum upgrade level is 15."
        },
        "6": {
            "name": "Neverending Song of Revelry",
            "icon": "UI_Talent_S_Vodyanitsa_04",
            "text": "The Constellation <color=#FFD780FF>Echoes That Pierce the Snow<\/color> is enhanced: \"Two Voices in Black and White\" now applies to all nearby party members.\\nAdditionally, while the <color=#FFD780FF>{LINK#S11402}Song of Ages Past{\/LINK}<\/color> effect is active, Stellar Swirl reaction DMG dealt by nearby party members is {LINK#N11190007}<color=#FFD780FF>elevated<\/color>{\/LINK} by 25% while <color=#80C0FFFF>Hydro DMG<\/color> and <color=#99FFFFFF>Cryo DMG<\/color> dealt are increased by 60%."
        }
    }
};