export default {
    "talents": {
        "Normal Attack": {
            "name": "Forceful Fists of Frost",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/0\/03\/Catalyst_Cryo.png",
            "text": "<color=#FFD780FF>Normal Attack<\/color>\\nCoalescing frost about his fist, Wriothesley will unleash powerful <color=#FFD780FF>Repelling Fists<\/color>, performing up to 5 rapid attacks that deal <color=#99FFFFFF>Cryo DMG<\/color>.\\nApart from this, Normal Attack combo count will not reset for a short time after using Icefang Rush or sprinting.\\n\\n<color=#FFD780FF>Charged Attack<\/color>\\nConsumes a fixed amount of Stamina to leap and unleash a <color=#FFD780FF>Vaulting Fist<\/color>, dealing <color=#99FFFFFF>AoE Cryo DMG<\/color>.\\n\\n<color=#FFD780FF>Plunging Attack<\/color>\\nPlunges from mid-air to strike the ground below, damaging opponents along the path and dealing <color=#99FFFFFF>AoE Cryo DMG<\/color> upon impact.",
            "scaling": {
                "1-Hit DMG": [
                    "53.36%",
                    "57.7%",
                    "62.05%",
                    "68.25%",
                    "72.59%",
                    "77.56%",
                    "84.38%",
                    "91.21%",
                    "98.03%",
                    "105.48%",
                    "112.92%",
                    "120.37%",
                    "127.81%",
                    "135.26%",
                    "142.71%"
                ],
                "2-Hit DMG": [
                    "51.8%",
                    "56.01%",
                    "60.23%",
                    "66.25%",
                    "70.47%",
                    "75.29%",
                    "81.91%",
                    "88.54%",
                    "95.17%",
                    "102.39%",
                    "109.62%",
                    "116.85%",
                    "124.08%",
                    "131.3%",
                    "138.53%"
                ],
                "3-Hit DMG": [
                    "67.22%",
                    "72.69%",
                    "78.17%",
                    "85.98%",
                    "91.45%",
                    "97.71%",
                    "106.31%",
                    "114.9%",
                    "123.5%",
                    "132.88%",
                    "142.26%",
                    "151.64%",
                    "161.02%",
                    "170.4%",
                    "179.78%"
                ],
                "4-Hit DMG": [
                    "37.9%+37.9%",
                    "40.99%+40.99%",
                    "44.07%+44.07%",
                    "48.48%+48.48%",
                    "51.57%+51.57%",
                    "55.09%+55.09%",
                    "59.94%+59.94%",
                    "64.79%+64.79%",
                    "69.64%+69.64%",
                    "74.93%+74.93%",
                    "80.22%+80.22%",
                    "85.5%+85.5%",
                    "90.79%+90.79%",
                    "96.08%+96.08%",
                    "101.37%+101.37%"
                ],
                "5-Hit DMG": [
                    "90.74%",
                    "98.13%",
                    "105.51%",
                    "116.07%",
                    "123.45%",
                    "131.89%",
                    "143.5%",
                    "155.11%",
                    "166.71%",
                    "179.37%",
                    "192.04%",
                    "204.7%",
                    "217.36%",
                    "230.02%",
                    "242.68%"
                ],
                "Charged Attack DMG": [
                    "152.96%",
                    "164.43%",
                    "175.9%",
                    "191.2%",
                    "202.67%",
                    "214.14%",
                    "229.44%",
                    "244.74%",
                    "260.03%",
                    "275.33%",
                    "290.62%",
                    "305.92%",
                    "325.04%",
                    "344.16%",
                    "363.28%"
                ],
                "Charged Attack Stamina Cost": [
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50"
                ],
                "Plunge DMG": [
                    "56.83%",
                    "61.45%",
                    "66.08%",
                    "72.69%",
                    "77.31%",
                    "82.6%",
                    "89.87%",
                    "97.14%",
                    "104.41%",
                    "112.34%",
                    "120.27%",
                    "128.2%",
                    "136.12%",
                    "144.05%",
                    "151.98%"
                ],
                "Low\/High Plunge DMG": [
                    "113.63%\/141.93%",
                    "122.88%\/153.49%",
                    "132.13%\/165.04%",
                    "145.35%\/181.54%",
                    "154.59%\/193.1%",
                    "165.16%\/206.3%",
                    "179.7%\/224.45%",
                    "194.23%\/242.61%",
                    "208.77%\/260.76%",
                    "224.62%\/280.57%",
                    "240.48%\/300.37%",
                    "256.34%\/320.18%",
                    "272.19%\/339.98%",
                    "288.05%\/359.79%",
                    "303.9%\/379.59%"
                ]
            },
            "icon": "Skill_A_Catalyst_MD"
        },
        "Elemental Skill": {
            "name": "Icefang Rush",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/d\/d7\/Talent_Icefang_Rush.png",
            "text": "Adjusting his breathing, rhythm, and pace, Wriothesley sprints forward a short distance, entering the <color=#FFD780FF>Chilling Penalty<\/color> state and unleashing more powerful attacks than before.\\n\\n<color=#FFD780FF>Chilling Penalty<\/color>\\n\u00b7Increases Wriothesley's interruption resistance\\n\u00b7When his HP is above 50%, it will enhance the Repelling Fists of <color=#FFD780FF>Normal Attack: Forceful Fists of Frost<\/color> and increase its DMG. When such an attack hits, it will consume a fixed amount of Wriothesley's HP. HP can be lost this way once every 0.1s.\\nThis effect will be canceled should Wriothesley leave the field.\\n\\n<i>\"Past convictions are past. It is our future choices that we must grasp.\"\\n\"Defy your fate, or else this glutton be, to pay your fate's due, by the crime and thee.\"<\/i>",
            "scaling": {
                "Enhanced Repelling Fist DMG": [
                    "143.17% Normal Attack DMG",
                    "145.75% Normal Attack DMG",
                    "148.34% Normal Attack DMG",
                    "151.7% Normal Attack DMG",
                    "154.29% Normal Attack DMG",
                    "156.87% Normal Attack DMG",
                    "160.23% Normal Attack DMG",
                    "163.59% Normal Attack DMG",
                    "166.95% Normal Attack DMG",
                    "170.31% Normal Attack DMG",
                    "173.67% Normal Attack DMG",
                    "177.03% Normal Attack DMG",
                    "180.39% Normal Attack DMG",
                    "183.75% Normal Attack DMG",
                    "187.11% Normal Attack DMG"
                ],
                "HP Cost": [
                    "4.5% Max HP",
                    "4.5% Max HP",
                    "4.5% Max HP",
                    "4.5% Max HP",
                    "4.5% Max HP",
                    "4.5% Max HP",
                    "4.5% Max HP",
                    "4.5% Max HP",
                    "4.5% Max HP",
                    "4.5% Max HP",
                    "4.5% Max HP",
                    "4.5% Max HP",
                    "4.5% Max HP",
                    "4.5% Max HP",
                    "4.5% Max HP"
                ],
                "Duration": [
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s"
                ],
                "CD": [
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s",
                    "16s"
                ]
            },
            "icon": "Skill_S_Wriothesley_01"
        },
        "Elemental Burst": {
            "name": "Darkgold Wolfbite",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/8\/88\/Talent_Darkgold_Wolfbite.png",
            "text": "Activating his boxing gloves, Wriothesley strikes out with an icy straight, then uses Icicle Impact to cause multiple instances of <color=#99FFFFFF>AoE Cryo DMG<\/color> in a frontal area.\\n\\n<color=#FFD780FF>Arkhe: Ousia<\/color>\\nAfter Icicle Impact ends, a Surging Blade will descend upon the opponent's position, dealing Ousia-aligned <color=#99FFFFFF>Cryo DMG<\/color>.\\n\\n<i>There are some things that even the Duke of the Fortress of Meropide can do little about \u2014 for example, complicated paperwork, the trivialities of a supervisor, or even... little kids pasting a whole host of cute but difficult-to-remove stickers on his boxing gloves.<\/i>",
            "scaling": {
                "Skill DMG": [
                    "127.2%\u00d75",
                    "136.74%\u00d75",
                    "146.28%\u00d75",
                    "159%\u00d75",
                    "168.54%\u00d75",
                    "178.08%\u00d75",
                    "190.8%\u00d75",
                    "203.52%\u00d75",
                    "216.24%\u00d75",
                    "228.96%\u00d75",
                    "241.68%\u00d75",
                    "254.4%\u00d75",
                    "270.3%\u00d75",
                    "286.2%\u00d75",
                    "302.1%\u00d75"
                ],
                "Surging Blade DMG": [
                    "42.4%",
                    "45.58%",
                    "48.76%",
                    "53%",
                    "56.18%",
                    "59.36%",
                    "63.6%",
                    "67.84%",
                    "72.08%",
                    "76.32%",
                    "80.56%",
                    "84.8%",
                    "90.1%",
                    "95.4%",
                    "100.7%"
                ],
                "CD": [
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s"
                ],
                "Surging Blade CD": [
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s",
                    "10s"
                ],
                "Energy Cost": [
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60"
                ]
            },
            "icon": "Skill_E_Wriothesley_01"
        },
        "1st Ascension Passive": {
            "name": "There Shall Be a Plea for Justice",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/1\/10\/Talent_There_Shall_Be_a_Plea_for_Justice.png",
            "text": "When Wriothesley's HP is less than 60%, he will obtain a Gracious Rebuke. The next Charged Attack of his <color=#FFD780FF>Normal Attack: Forceful Fists of Frost<\/color> will be enhanced to become Rebuke: Vaulting Fist. It will not consume Stamina, will deal 50% increased DMG, and after hitting will restore HP for Wriothesley equal to 30% of his Max HP.\\nYou can gain a Gracious Rebuke this way once every 5s.",
            "icon": "UI_Talent_S_Wriothesley_05"
        },
        "4th Ascension Passive": {
            "name": "There Shall Be a Reckoning for Sin",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/0\/02\/Talent_There_Shall_Be_a_Reckoning_for_Sin.png",
            "text": "When Wriothesley's current HP increases or decreases, if he is in the Chilling Penalty state conferred by <color=#FFD780FF>Icefang Rush<\/color>, Chilling Penalty will gain one stack of Prosecution Edict. Max 5 stacks. Each stack will increase Wriothesley's ATK by 6%.",
            "icon": "UI_Talent_S_Wriothesley_06"
        },
        "Utility Passive": {
            "name": "The Duke's Grace",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/5\/53\/Talent_The_Duke%27s_Grace.png",
            "text": "When Wriothesley crafts Weapon Ascension Materials, he has a 10% chance to receive double the product.",
            "icon": "UI_Talent_Combine_Weapon_Double"
        },
        "Passive": {
            "name": "There Shall Be an Unveiling for Injustice",
            "icon": "UI_Talent_S_Wriothesley_08",
            "text": "<color=#FFD780FF>Radiance: Stellar-Conduct<\/color>: The Ascension Talent \"There Shall Be a Plea for Justice\" is changed to the following:\\nWhen Wriothesley's HP is less than 60%, he will obtain a \"Gracious Rebuke: Unveiling.\" This enhances the next Charged Attack of his <color=#FFD780FF>Normal Attack: Forceful Fists of Frost<\/color> into Luster: Vaulting Fist, which will not consume Stamina and restores 30% Max HP to Wriothesley upon hit. Wriothesley can gain HP in this way once every 2s.\\nAdditionally, the third and fifth strikes of Repelling Fist enhanced by <color=#FFD780FF>Chilling Penalty<\/color> will deal 60% and 80% of their original <color=#99FFFFFF>Cryo DMG<\/color> respectively, while Luster: Vaulting Fist will deal 100% of its original <color=#99FFFFFF>AoE Cryo DMG<\/color>. The aforementioned DMG is considered as Stellar-Conduct DMG, and Wriothesley deals 30% increased Stellar-Conduct DMG.\\nAdditionally, when inside a {LINK#N11330003}<color=#FFD780FF>Polestar Field<\/color>{\/LINK}, Wriothesley will enter the <color=#FFD780FF>Radiance: Stellar-Conduct<\/color> state."
        }
    },
    "constellations": {
        "1": {
            "name": "Terror for the Evildoers",
            "icon": "UI_Talent_S_Wriothesley_01",
            "text": "The Gracious Rebuke from the Ascension Talent \"There Shall Be a Plea for Justice\" is changed to this:\\nWhen Wriothesley's HP is less than 60% or while he is in the Chilling Penalty state caused by <color=#FFD780FF>Icefang Rush<\/color>, when the fifth attack of Repelling Fists hits, it will create a Gracious Rebuke. 1 Gracious Rebuke effect can be obtained every 2.5s.\\n\\nAdditionally, Rebuke: Vaulting Fist will obtain the following enhancement:\\n\u00b7 The DMG Bonus gained will be further increased to 200%.\\n\u00b7 When it hits while Wriothesley is in the Chilling Penalty state, that state's duration is extended by 4s.\\n\\n<color=#FFD780FF>Radiance: Stellar-Conduct:<\/color>\\n\u00b7 After a Luster: Vaulting Fist attack hits an opponent, the next fifth attack of Repelling Fist enhanced by <color=#FFD780FF>Chilling Penalty<\/color> that hits within the next 5s deals 50% increased Stellar-Conduct DMG.\\n\u00b7 After the fifth attack of Repelling Fist enhanced by <color=#FFD780FF>Chilling Penalty<\/color> hits an opponent, Luster: Vaulting Fists that hit within the next 5s deal 50% increased DMG.\\n\u00b7 If Luster: Vaulting Fist hits an opponent while Wriothesley is in the <color=#FFD780FF>Chilling Penalty<\/color> state, that state's duration is extended by 4s.\\n\\n1 such extension can occur per 1 <color=#FFD780FF>Chilling Penalty<\/color> duration.\\n\\nYou must first unlock the Ascension Talent \"There Shall Be a Plea for Justice.\""
        },
        "2": {
            "name": "Shackles for the Arrogant",
            "icon": "UI_Talent_S_Wriothesley_02",
            "text": "When <color=#FFD780FF>Darkgold Wolfbite<\/color> is unleashed, each instance of the Prosecution Edict effect from the Ascension Talent \"There Shall Be a Reckoning for Sin\" will increase the DMG dealt by 40%.\\n\\nAdditionally, when the Prosecution Edict stack reaches 5, if Wriothesley:\\n\u00b7 Is in the <color=#FFD780FF>Radiance: Stellar-Conduct<\/color> state: The Talent \"There Shall Be an Unveiling for Injustice\" will be enhanced, so that the third and fifth strikes of Repelling Fist, when enhanced by <color=#FFD780FF>Chilling Penalty<\/color>, deal 90% or 120% of their original <color=#99FFFFFF>Cryo DMG<\/color> respectively, while Luster: Vaulting Fist will deal 150% of its original <color=#99FFFFFF>AoE Cryo DMG<\/color>. The aforementioned DMG is considered Stellar-Conduct DMG.\\n\u00b7 Is not in the <color=#FFD780FF>Radiance: Stellar-Conduct<\/color> state: Normal Attacks and Charged Attacks will deal 125% or 130% of their original DMG respectively.\\n\\nYou must first unlock the Ascension Talent \"There Shall Be a Reckoning for Sin.\""
        },
        "3": {
            "name": "Punishment for the Frauds",
            "icon": "UI_Talent_U_Wriothesley_01",
            "text": "Increases the Level of <color=#FFD780FF>Normal Attack: Forceful Fists of Frost<\/color> by 3.\\nMaximum upgrade level is 15."
        },
        "4": {
            "name": "Redemption for the Suffering",
            "icon": "UI_Talent_S_Wriothesley_03",
            "text": "The HP restored to Wriothesley through Rebuke: Vaulting Fist will be increased to 50% of his Max HP. You must first unlock the Ascension Talent \"There Shall Be a Plea for Justice.\"\\nAdditionally, when Wriothesley is healed, if the amount of healing overflows, the following effects will occur, depending on whether he is on the field. If he is on the field, his ATK SPD will be increased by 20% for 4s. If he is off-field, all of your own party members' ATK SPD will be increased by 10% for 6s. These two ATK SPD boosts cannot stack.\\n\\n<color=#FFD780FF>Radiance: Stellar-Conduct<\/color>: The aforementioned effect is changed to:\\nWriothesley takes 25% less DMG, and his ATK SPD is increased by 20%. Other nearby party members' ATK SPD is increased by 10%."
        },
        "5": {
            "name": "Mercy for the Wronged",
            "icon": "UI_Talent_U_Wriothesley_02",
            "text": "Increases the Level of <color=#FFD780FF>Darkgold Wolfbite<\/color> by 3.\\nMaximum upgrade level is 15."
        },
        "6": {
            "name": "Esteem for the Innocent",
            "icon": "UI_Talent_S_Wriothesley_04",
            "text": "The CRIT Rate of Rebuke: Vaulting Fist will be increased by 10%, and its CRIT DMG by 80%. When unleashed, it will also create an additional icicle that deals 100% of Rebuke: Vaulting Fist's original DMG as <color=#99FFFFFF>Cryo DMG<\/color>. DMG dealt this way is regarded as Charged Attack DMG.\\n\\n<color=#FFD780FF>Radiance: Stellar-Conduct<\/color>: The aforementioned effect is changed to:\\n\u00b7 The Repelling Fist enhanced by <color=#FFD780FF>Chilling Penalty<\/color>, as well as Luster: Vaulting Fist, gain a 10% CRIT Rate and 80% CRIT DMG boost. In addition, the fifth attack of Repelling Fists enhanced by <color=#FFD780FF>Chilling Penalty<\/color>, as well as Luster: Vaulting Fist, will each generate an additional icicle that deals <color=#99FFFFFF>Cryo DMG<\/color> at 20% of its original DMG. This DMG will be considered Stellar-Conduct DMG.\\n\\nYou must first unlock the Ascension Talent \"There Shall Be a Plea for Justice.\""
        }
    }
};