export default {
    "talents": {
        "Normal Attack": {
            "name": "Spiritfox Sin-Eater",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/e\/e7\/Catalyst_Electro.png",
            "text": "<color=#FFD780FF>Normal Attack<\/color>\\nSummons forth kitsune spirits, initiating a maximum of 3 attacks that deal <color=#FFACFFFF>Electro DMG<\/color>.\\n\\n<color=#FFD780FF>Charged Attack<\/color>\\nConsumes a certain amount of Stamina to deal <color=#FFACFFFF>AoE Electro DMG<\/color> after a short casting time.\\n\\n<color=#FFD780FF>Plunging Attack<\/color>\\nPlunges towards the ground from mid-air, damaging all opponents in her path with thunderous might. Deals <color=#FFACFFFF>AoE Electro DMG<\/color> upon impact with the ground.",
            "scaling": {
                "1-Hit DMG": [
                    "39.66%",
                    "42.63%",
                    "45.61%",
                    "49.57%",
                    "52.55%",
                    "55.52%",
                    "59.49%",
                    "63.45%",
                    "67.42%",
                    "71.39%",
                    "75.35%",
                    "79.32%",
                    "84.27%",
                    "89.23%",
                    "94.19%"
                ],
                "2-Hit DMG": [
                    "38.52%",
                    "41.41%",
                    "44.3%",
                    "48.15%",
                    "51.04%",
                    "53.93%",
                    "57.78%",
                    "61.63%",
                    "65.48%",
                    "69.33%",
                    "73.19%",
                    "77.04%",
                    "81.85%",
                    "86.67%",
                    "91.48%"
                ],
                "3-Hit DMG": [
                    "56.89%",
                    "61.16%",
                    "65.42%",
                    "71.11%",
                    "75.38%",
                    "79.64%",
                    "85.33%",
                    "91.02%",
                    "96.71%",
                    "102.4%",
                    "108.09%",
                    "113.78%",
                    "120.89%",
                    "128%",
                    "135.11%"
                ],
                "Charged Attack DMG": [
                    "142.89%",
                    "153.61%",
                    "164.33%",
                    "178.62%",
                    "189.34%",
                    "200.05%",
                    "214.34%",
                    "228.63%",
                    "242.92%",
                    "257.21%",
                    "271.5%",
                    "285.79%",
                    "303.65%",
                    "321.51%",
                    "339.38%"
                ],
                "Charged Attack Stamina Cost": [
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50"
                ],
                "Plunge DMG": [
                    "56.83%",
                    "61.45%",
                    "66.08%",
                    "72.69%",
                    "77.31%",
                    "82.6%",
                    "89.87%",
                    "97.14%",
                    "104.41%",
                    "112.34%",
                    "120.27%",
                    "128.2%",
                    "136.12%",
                    "144.05%",
                    "151.98%"
                ],
                "Low\/High Plunge DMG": [
                    "113.63%\/141.93%",
                    "122.88%\/153.49%",
                    "132.13%\/165.04%",
                    "145.35%\/181.54%",
                    "154.59%\/193.1%",
                    "165.16%\/206.3%",
                    "179.7%\/224.45%",
                    "194.23%\/242.61%",
                    "208.77%\/260.76%",
                    "224.62%\/280.57%",
                    "240.48%\/300.37%",
                    "256.34%\/320.18%",
                    "272.19%\/339.98%",
                    "288.05%\/359.79%",
                    "303.9%\/379.59%"
                ]
            },
            "icon": "Skill_A_Catalyst_MD"
        },
        "Elemental Skill": {
            "name": "Yakan Evocation: Sesshou Sakura",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/9\/93\/Talent_Yakan_Evocation_Sesshou_Sakura.png",
            "text": "To Yae, such dull tasks as can be accomplished by driving spirits out need not be done personally.\\nMoves swiftly, leaving a Sesshou Sakura behind.\\n\\n<color=#FFD780FF>Sesshou Sakura<\/color>\\nHas the following properties:\\n\u00b7 Periodically strikes one nearby opponent with lightning, dealing <color=#FFACFFFF>Electro DMG<\/color>\\n\u00b7 When there are other Sesshou Sakura nearby, their level will increase, boosting the DMG dealt by these lightning strikes.\\n\\nThis skill has three charges.\\nA maximum of 3 Sesshou Sakura can exist simultaneously. The initial level of each Sesshou Sakura is 1, and the initial highest level each sakura can reach is 3. If a new Sesshou Sakura is created too close to an existing one, the existing one will be destroyed.\\n\\n<i>\"The kitsune spirits sealed in the branches are all yakan who stooped to preying upon humans. The yakan are two grades lower than us Sky Kitsune, and so, I hardly see the problem with... asking that they do my bidding. Now, this doesn't mean that you humans should go learning from our grading systems, no indeed \u2014 and as for which of us, kitsune or human, is higher up in the pecking order... Heh, wouldn't you like to know?\"<\/i>",
            "scaling": {
                "Sesshou Sakura DMG: Level 1": [
                    "60.67%",
                    "65.22%",
                    "69.77%",
                    "75.84%",
                    "80.39%",
                    "84.94%",
                    "91.01%",
                    "97.08%",
                    "103.14%",
                    "109.21%",
                    "115.28%",
                    "121.34%",
                    "128.93%",
                    "136.51%",
                    "144.1%"
                ],
                "Sesshou Sakura DMG: Level 2": [
                    "75.84%",
                    "81.53%",
                    "87.22%",
                    "94.8%",
                    "100.49%",
                    "106.18%",
                    "113.76%",
                    "121.34%",
                    "128.93%",
                    "136.51%",
                    "144.1%",
                    "151.68%",
                    "161.16%",
                    "170.64%",
                    "180.12%"
                ],
                "Sesshou Sakura DMG: Level 3": [
                    "94.8%",
                    "101.91%",
                    "109.02%",
                    "118.5%",
                    "125.61%",
                    "132.72%",
                    "142.2%",
                    "151.68%",
                    "161.16%",
                    "170.64%",
                    "180.12%",
                    "189.6%",
                    "201.45%",
                    "213.3%",
                    "225.15%"
                ],
                "Sesshou Sakura DMG: Level 4": [
                    "118.5%",
                    "127.39%",
                    "136.28%",
                    "148.13%",
                    "157.01%",
                    "165.9%",
                    "177.75%",
                    "189.6%",
                    "201.45%",
                    "213.3%",
                    "225.15%",
                    "237%",
                    "251.81%",
                    "266.62%",
                    "281.44%"
                ],
                "Duration": [
                    "14s",
                    "14s",
                    "14s",
                    "14s",
                    "14s",
                    "14s",
                    "14s",
                    "14s",
                    "14s",
                    "14s",
                    "14s",
                    "14s",
                    "14s",
                    "14s",
                    "14s"
                ],
                "CD": [
                    "4s",
                    "4s",
                    "4s",
                    "4s",
                    "4s",
                    "4s",
                    "4s",
                    "4s",
                    "4s",
                    "4s",
                    "4s",
                    "4s",
                    "4s",
                    "4s",
                    "4s"
                ]
            },
            "icon": "Skill_S_Yae_01"
        },
        "Elemental Burst": {
            "name": "Great Secret Art: Tenko Kenshin",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/9\/93\/Talent_Great_Secret_Art_Tenko_Kenshin.png",
            "text": "Legends of \"kitsunetsuki,\" or the manifestation of a kitsune's might, are common in Inazuma's folktales. One that particularly captures the imagination is that of the Sky Kitsune, said to cause lightning to fall down upon the foes of the Grand Narukami Shrine. Summons a lightning strike, dealing <color=#FFACFFFF>AoE Electro DMG<\/color>.\\nWhen this is cast, Yae Miko will transform nearby Sesshou Sakura into Tenko Thunderbolts that descend from the skies, dealing <color=#FFACFFFF>AoE Electro DMG<\/color>. Each Sesshou Sakura within range transforms into one Tenko Thunderbolt.\\n\\n<i>Only at times like these will Yae reveal her Sky Kitsune form and wield lightning itself. None have seen the Lady Guuji's tails and lived to tell the story... so remember, as far as you are concerned, Lady Yae does not have a tail.<\/i>",
            "scaling": {
                "Skill DMG": [
                    "260%",
                    "279.5%",
                    "299%",
                    "325%",
                    "344.5%",
                    "364%",
                    "390%",
                    "416%",
                    "442%",
                    "468%",
                    "494%",
                    "520%",
                    "552.5%",
                    "585%",
                    "617.5%"
                ],
                "Tenko Thunderbolt DMG": [
                    "333.82%",
                    "358.85%",
                    "383.89%",
                    "417.27%",
                    "442.31%",
                    "467.34%",
                    "500.72%",
                    "534.11%",
                    "567.49%",
                    "600.87%",
                    "634.25%",
                    "667.63%",
                    "709.36%",
                    "751.09%",
                    "792.81%"
                ],
                "CD": [
                    "22s",
                    "22s",
                    "22s",
                    "22s",
                    "22s",
                    "22s",
                    "22s",
                    "22s",
                    "22s",
                    "22s",
                    "22s",
                    "22s",
                    "22s",
                    "22s",
                    "22s"
                ],
                "Energy Cost": [
                    "90",
                    "90",
                    "90",
                    "90",
                    "90",
                    "90",
                    "90",
                    "90",
                    "90",
                    "90",
                    "90",
                    "90",
                    "90",
                    "90",
                    "90"
                ]
            },
            "icon": "Skill_E_Yae_01"
        },
        "1st Ascension Passive": {
            "name": "The Shrine's Sacred Shade",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/6\/68\/Talent_The_Shrine%27s_Sacred_Shade.png",
            "text": "When <color=#FFD780FF>Great Secret Art: Tenko Kenshin<\/color> is unleashed, each Sesshou Sakura involved will reset the cooldown for one instance of <color=#FFD780FF>Yakan Evocation: Sesshou Sakura<\/color>.\\nWhen there are at least 3 Sesshou Sakura nearby at the same time, unleashing <color=#FFD780FF>Yakan Evocation: Sesshou Sakura<\/color> will cause Yae Miko to unleash an additional lightning strike which deals <color=#FFACFFFF>Electro DMG<\/color> at 40% of her ATK.\\n<color=#FFD780FF>Radiance: Stellar-Conduct<\/color>: The aforementioned additional lightning strike becomes an instance of <color=#FFACFFFF>Electro DMG<\/color> at 50% of Yae Miko's ATK instead. This DMG will also be considered Stellar-Conduct DMG.",
            "icon": "UI_Talent_S_Yae_05"
        },
        "4th Ascension Passive": {
            "name": "Enlightened Blessing",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/b\/ba\/Talent_Enlightened_Blessing.png",
            "text": "Every point of Elemental Mastery Yae Miko possesses will increase <color=#FFD780FF>Sesshou Sakura<\/color> DMG by 0.15%.",
            "icon": "UI_Talent_S_Yae_06"
        },
        "Utility Passive": {
            "name": "Meditations of a Yako",
            "img": "https:\/\/static.wikia.nocookie.net\/gensin-impact\/images\/e\/e5\/Talent_Meditations_of_a_Yako.png",
            "text": "Has a 25% chance to get 1 regional Character Talent Material (base material excluded) when crafting. The rarity is that of the base material.",
            "icon": "UI_Talent_S_Yae_07"
        },
        "Passive": {
            "name": "Edict of Cleansing",
            "icon": "UI_Talent_S_Yae_08",
            "text": "Extends the duration of the Sesshou Sakura by 10s. When a nearby party member triggers a Superconduct or Stellar-Conduct reaction, the next instance of Sesshou Sakura lightning is enhanced as follows: DMG dealt is increased at 80% of Yae Miko's ATK. This effect can trigger once every 2.5s.\\n<color=#FFD780FF>Radiance: Stellar-Conduct<\/color>: An enhanced Sesshou Sakura lightning bolt hit on an opponent will also cause an additional instance of <color=#FFACFFFF>Electro DMG<\/color> at 200% of Yae Miko's ATK. This DMG is considered Stellar-Conduct DMG.\\nAdditionally, when inside a {LINK#N11330003}<color=#FFD780FF>Polestar Field<\/color>{\/LINK}, Yae Miko will enter the <color=#FFD780FF>Radiance: Stellar-Conduct<\/color> state."
        }
    },
    "constellations": {
        "1": {
            "name": "Yakan Offering",
            "icon": "UI_Talent_S_Yae_01",
            "text": "Each time <color=#FFD780FF>Great Secret Art: Tenko Kenshin<\/color> activates a Tenko Thunderbolt, Yae Miko restores 8 Elemental Energy to herself. After Yae Miko triggers a Superconduct or Stellar-Conduct reaction, or deals Stellar-Conduct DMG, nearby party members will gain a 50% Electro DMG and Stellar-Conduct DMG Bonus for 10s. Triggering these reactions again will refresh the duration of the DMG bonuses."
        },
        "2": {
            "name": "Fox's Mooncall",
            "icon": "UI_Talent_S_Yae_02",
            "text": "<color=#FFD780FF>Sesshou Sakura<\/color> start at Level 2 when created, their max level is increased to 4, and their attack range is increased by 60%. Additionally, when there are Sesshou Sakura in the field, Yae Miko's and your current active character's Elemental Mastery will also be increased by 60\/90\/120\/200 points, depending on the level of the Sesshou Sakura."
        },
        "3": {
            "name": "The Seven Glamours",
            "icon": "UI_Talent_U_Yae_01",
            "text": "Increases the Level of <color=#FFD780FF>Yakan Evocation: Sesshou Sakura<\/color> by 3.\\nMaximum upgrade level is 15."
        },
        "4": {
            "name": "Sakura Channeling",
            "icon": "UI_Talent_S_Yae_03",
            "text": "When <color=#FFD780FF>Sesshou Sakura<\/color> lightning hits opponents, the <color=#FFACFFFF>Electro DMG Bonus<\/color> of all nearby party members is increased by 20% for 5s, and Yae Miko regenerates 8 Elemental Energy. The aforementioned Elemental Energy recovery effect can trigger once every 5s. Additionally, Yae Miko's Elemental Burst DMG is increased by 100%."
        },
        "5": {
            "name": "Mischievous Teasing",
            "icon": "UI_Talent_U_Yae_02",
            "text": "Increases the Level of <color=#FFD780FF>Great Secret Art: Tenko Kenshin<\/color> by 3.\\nMaximum upgrade level is 15."
        },
        "6": {
            "name": "Forbidden Art: Daisesshou",
            "icon": "UI_Talent_S_Yae_04",
            "text": "<color=#FFD780FF>Sesshou Sakura's<\/color> attacks will ignore 60% of the opponents' DEF. The CRIT DMG of Yae Miko's Stellar-Conduct DMG is increased by 200%."
        }
    }
};