export default {
    "talents": {
        "Normal Attack": {
            "name": "Pure Heart, Pure Dreams",
            "text": "<color=#FFD780FF>Normal Attack<\/color>\\nPerforms up to 3 attacks, dealing <color=#80FFD7FF>Anemo DMG<\/color>.\\n\\n<color=#FFD780FF>Charged Attack<\/color>\\nConsumes a certain amount of Stamina and deals <color=#80FFD7FF>AoE Anemo DMG<\/color> after a short casting time.\\n\\n<color=#FFD780FF>Plunging Attack<\/color>\\nCalling upon the power of Anemo, she plunges towards the ground from mid-air, damaging all opponents in her path. Deals <color=#80FFD7FF>AoE Anemo DMG<\/color> upon impact with the ground.",
            "scaling": {
                "1-Hit DMG": [
                    "52.28%",
                    "56.2%",
                    "60.12%",
                    "65.35%",
                    "69.27%",
                    "73.19%",
                    "78.42%",
                    "83.64%",
                    "88.87%",
                    "94.1%",
                    "99.33%",
                    "104.55%",
                    "111.09%",
                    "117.62%",
                    "124.16%"
                ],
                "2-Hit DMG": [
                    "46.91%",
                    "50.43%",
                    "53.95%",
                    "58.64%",
                    "62.16%",
                    "65.68%",
                    "70.37%",
                    "75.06%",
                    "79.75%",
                    "84.45%",
                    "89.14%",
                    "93.83%",
                    "99.69%",
                    "105.56%",
                    "111.42%"
                ],
                "3-Hit DMG": [
                    "71.37%",
                    "76.72%",
                    "82.07%",
                    "89.21%",
                    "94.56%",
                    "99.92%",
                    "107.05%",
                    "114.19%",
                    "121.33%",
                    "128.46%",
                    "135.6%",
                    "142.74%",
                    "151.66%",
                    "160.58%",
                    "169.5%"
                ],
                "Charged Attack DMG": [
                    "130%",
                    "139.75%",
                    "149.5%",
                    "162.5%",
                    "172.25%",
                    "182%",
                    "195%",
                    "208%",
                    "221%",
                    "234%",
                    "247%",
                    "260%",
                    "276.25%",
                    "292.5%",
                    "308.75%"
                ],
                "Charged Attack Stamina Cost": [
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50",
                    "50"
                ],
                "Plunge DMG": [
                    "56.83%",
                    "61.45%",
                    "66.08%",
                    "72.69%",
                    "77.31%",
                    "82.6%",
                    "89.87%",
                    "97.14%",
                    "104.41%",
                    "112.34%",
                    "120.27%",
                    "128.2%",
                    "136.12%",
                    "144.05%",
                    "151.98%"
                ],
                "Low\/High Plunge DMG": [
                    "113.63%\/141.93%",
                    "122.88%\/153.49%",
                    "132.13%\/165.04%",
                    "145.35%\/181.54%",
                    "154.59%\/193.1%",
                    "165.16%\/206.3%",
                    "179.7%\/224.45%",
                    "194.23%\/242.61%",
                    "208.77%\/260.76%",
                    "224.62%\/280.57%",
                    "240.48%\/300.37%",
                    "256.34%\/320.18%",
                    "272.19%\/339.98%",
                    "288.05%\/359.79%",
                    "303.9%\/379.59%"
                ]
            },
            "icon": "Skill_A_Catalyst_MD"
        },
        "Elemental Skill": {
            "name": "Aisa Utamakura Pilgrimage",
            "text": "Weaves memories of lovely dreams, entering a <color=#FFD780FF>Dreamdrifter<\/color> state where Yumemizuki Mizuki floats above the ground, and dealing 1 instance of <color=#80FFD7FF>AoE Anemo DMG<\/color> to nearby opponents.\\n\\n<color=#FFD780FF>Dreamdrifter<\/color>\\n\u00b7While in the Dreamdrifter state, Yumemizuki Mizuki will continuously drift forward, dealing <color=#80FFD7FF>AoE Anemo DMG<\/color> to nearby opponents at regular intervals.\\n\u00b7During this time, Yumemizuki Mizuki can control her direction of drift, and the pick-up distance of <color=#FFD780FF>Yumemi Style Special Snacks<\/color> from the Elemental Burst <color=#FFD780FF>Anraku Secret Spring Therapy<\/color> will be increased.\\n\u00b7Increases the Swirl DMG that nearby party members deal based on Yumemizuki Mizuki's Elemental Mastery.\\n\u00b7Dreamdrifter will end when Mizuki leaves the field or uses her Elemental Skill again.\\n\\n<i>\"Our dreams touch at midnight, their song ringing on in our hearts.\"<\/i>",
            "scaling": {
                "Skill DMG": [
                    "57.74%",
                    "62.07%",
                    "66.41%",
                    "72.18%",
                    "76.51%",
                    "80.84%",
                    "86.62%",
                    "92.39%",
                    "98.16%",
                    "103.94%",
                    "109.71%",
                    "115.49%",
                    "122.71%",
                    "129.92%",
                    "137.14%"
                ],
                "Continuous Attack DMG": [
                    "44.91%",
                    "48.28%",
                    "51.65%",
                    "56.14%",
                    "59.51%",
                    "62.88%",
                    "67.37%",
                    "71.86%",
                    "76.35%",
                    "80.84%",
                    "85.33%",
                    "89.82%",
                    "95.44%",
                    "101.05%",
                    "106.67%"
                ],
                "Dreamdrifter Duration": [
                    "5s",
                    "5s",
                    "5s",
                    "5s",
                    "5s",
                    "5s",
                    "5s",
                    "5s",
                    "5s",
                    "5s",
                    "5s",
                    "5s",
                    "5s",
                    "5s",
                    "5s"
                ],
                "Elemental Mastery-Based Swirl DMG Increase": [
                    "0.18% per Point",
                    "0.21% per Point",
                    "0.24% per Point",
                    "0.27% per Point",
                    "0.3% per Point",
                    "0.33% per Point",
                    "0.36% per Point",
                    "0.39% per Point",
                    "0.42% per Point",
                    "0.45% per Point",
                    "0.48% per Point",
                    "0.51% per Point",
                    "0.54% per Point",
                    "0.57% per Point",
                    "0.6% per Point"
                ],
                "CD": [
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s"
                ]
            },
            "icon": "Skill_S_Mizuki_01"
        },
        "Elemental Burst": {
            "name": "Anraku Secret Spring Therapy",
            "text": "Summons forth countless lovely dreams and nightmares that pull in nearby objects and opponents, dealing <color=#80FFD7FF>AoE Anemo DMG<\/color> and summoning a Mini Baku.\\n\\n<color=#FFD780FF>Mini Baku:<\/color>\\nFollows the current active character. At regular intervals, the Mini Baku will create 1 Yumemi Style Special Snack nearby. After one of your own party members picks up a Special Snack, if their HP is higher than 70%, the Snack will explode and unleash a Munen Shockwave, dealing 1 instance of <color=#80FFD7FF>AoE Anemo DMG<\/color> to nearby opponents. Otherwise, it will heal the character who picked it up based on Yumemizuki Mizuki's Elemental Mastery. When Yumemizuki Mizuki triggers healing by picking up a Yumemi Style Special Snack, the amount of healing is increased by 100%. If a Snack is not picked up after a period of time, it will explode and release a Munen Shockwave, dealing 1 instance of <color=#80FFD7FF>AoE Anemo DMG<\/color> to surrounding opponents.\\n\\n<i>\"If you bury dark emotions for too long, they will become nightmares. With that in mind, why don't we turn them into 'delicious snacks' while we've got the time?\"<\/i>",
            "scaling": {
                "Skill DMG": [
                    "94.08%",
                    "101.14%",
                    "108.19%",
                    "117.6%",
                    "124.66%",
                    "131.71%",
                    "141.12%",
                    "150.53%",
                    "159.94%",
                    "169.34%",
                    "178.75%",
                    "188.16%",
                    "199.92%",
                    "211.68%",
                    "223.44%"
                ],
                "Munen Shockwave DMG": [
                    "70.56%",
                    "75.85%",
                    "81.14%",
                    "88.2%",
                    "93.49%",
                    "98.78%",
                    "105.84%",
                    "112.9%",
                    "119.95%",
                    "127.01%",
                    "134.06%",
                    "141.12%",
                    "149.94%",
                    "158.76%",
                    "167.58%"
                ],
                "Snack Pick-Up HP Regeneration": [
                    "130.56% Elemental Mastery+315",
                    "140.35% Elemental Mastery+346",
                    "150.14% Elemental Mastery+380",
                    "163.2% Elemental Mastery+417",
                    "172.99% Elemental Mastery+456",
                    "182.78% Elemental Mastery+498",
                    "195.84% Elemental Mastery+543",
                    "208.9% Elemental Mastery+590",
                    "221.95% Elemental Mastery+640",
                    "235.01% Elemental Mastery+692",
                    "248.06% Elemental Mastery+747",
                    "261.12% Elemental Mastery+805",
                    "277.44% Elemental Mastery+865",
                    "293.76% Elemental Mastery+928",
                    "310.08% Elemental Mastery+994"
                ],
                "Duration": [
                    "12s",
                    "12s",
                    "12s",
                    "12s",
                    "12s",
                    "12s",
                    "12s",
                    "12s",
                    "12s",
                    "12s",
                    "12s",
                    "12s",
                    "12s",
                    "12s",
                    "12s"
                ],
                "CD": [
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s",
                    "15s"
                ],
                "Energy Cost": [
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60",
                    "60"
                ]
            },
            "icon": "Skill_E_Mizuki_01"
        },
        "1st Ascension Passive": {
            "name": "Bright Moon's Restless Voice",
            "text": "When Yumemizuki Mizuki triggers Swirl while in her Dreamdrifter state, Dreamdrifter's duration increases by 2.5s. This effect can trigger once every 0.3s for a maximum of 2 times per Dreamdrifter state.",
            "icon": "UI_Talent_S_Mizuki_05"
        },
        "4th Ascension Passive": {
            "name": "Thoughts by Day Bring Dreams by Night",
            "text": "While Yumemizuki Mizuki is in the Dreamdrifter state, when other nearby party members hit opponents with <color=#FF9999FF>Pyro<\/color>, <color=#80C0FFFF>Hydro<\/color>, <color=#99FFFFFF>Cryo<\/color>, or <color=#FFACFFFF>Electro<\/color> attacks, her Elemental Mastery will increase by 100 for 4s.",
            "icon": "UI_Talent_S_Mizuki_06"
        },
        "Utility Passive": {
            "name": "All Ailments Banished",
            "text": "When Yumemizuki Mizuki is in the party, party members have a chance to recover 30% additional HP when using healing foods that do not have reviving properties. The trigger chance for this effect increases with the corresponding character's Friendship Level. (This effect will always trigger if the Traveler is the character consuming healing food.)",
            "icon": "UI_Talent_S_Mizuki_07"
        },
        "Passive": {
            "name": "Vast Be the Dream",
            "icon": "UI_Talent_S_Mizuki_08",
            "text": "When Yumemizuki Mizuki triggers a Swirl reaction while in the Dreamdrifter state, the next instance of periodic <color=#80FFD7FF>AoE Anemo DMG<\/color> she deals to nearby enemies during that same state will be increased by 1,000% of her Elemental Mastery. The aforementioned effect can trigger once every 2.5s.\\nAdditionally, while Yumemizuki Mizuki is in the Dreamdrifter state, the Elemental Mastery of nearby party characters is increased by 10% of Yumemizuki Mizuki's Elemental Mastery."
        }
    },
    "constellations": {
        "1": {
            "name": "In Mist-Like Waters",
            "icon": "UI_Talent_S_Mizuki_01",
            "text": "When Yumemizuki Mizuki is in the Dreamdrifter state, she will continuously apply the \"Twenty-Three Nights' Awaiting\" effect to nearby opponents for 3s every 3.5s. When an opponent is affected by Anemo DMG-triggered Swirl reactions while the aforementioned effect is active, the effect will be canceled, and this Swirl instance has its DMG against this opponent increased by 1,100% of Mizuki's Elemental Mastery. She also launches an additional attack on the same opponent, dealing <color=#80FFD7FF>Anemo DMG<\/color> equal to 1,000% of Yumemizuki Mizuki's Elemental Mastery."
        },
        "2": {
            "name": "Your Echo I Meet in Dreams",
            "icon": "UI_Talent_S_Mizuki_02",
            "text": "When Yumemizuki Mizuki enters the Dreamdrifter state, every Elemental Mastery point she has will increase all nearby party members' <color=#FF9999FF>Pyro<\/color>, <color=#80C0FFFF>Hydro<\/color>, <color=#99FFFFFF>Cryo<\/color>, and <color=#FFACFFFF>Electro<\/color> DMG Bonuses by 0.04% until the Dreamdrifter state ends.\\nAdditionally, while Yumemizuki Mizuki is in the Dreamdrifter state, the <color=#FF9999FF>Pyro RES<\/color>, <color=#80C0FFFF>Hydro RES<\/color>, <color=#99FFFFFF>Cryo RES<\/color>, <color=#FFACFFFF>Electro RES<\/color>, and <color=#80FFD7FF>Anemo RES<\/color> of nearby opponents are lowered by 20%."
        },
        "3": {
            "name": "Till Dawn's Moon Ends Night",
            "icon": "UI_Talent_U_Mizuki_01",
            "text": "Increases the Level of <color=#FFD780FF>Aisa Utamakura Pilgrimage<\/color> by 3.\\nMaximum upgrade level is 15."
        },
        "4": {
            "name": "Buds Warm Lucid Springs",
            "icon": "UI_Talent_S_Mizuki_03",
            "text": "Picking up a <color=#FFD780FF>Yumemi Style Special Snack<\/color> from the Elemental Burst <color=#FFD780FF>Anraku Secret Spring Therapy<\/color> will both deal DMG and heal. It will also heal a nearby party member with lower HP for 266% of Yumemizuki Mizuki's Elemental Mastery, as well as regenerate 5 Energy for Yumemizuki Mizuki. Energy can be restored this way 4 times per <color=#FFD780FF>Anraku Secret Spring Therapy<\/color> duration."
        },
        "5": {
            "name": "As Setting Moon Brings Year's End",
            "icon": "UI_Talent_U_Mizuki_02",
            "text": "Increases the Level of <color=#FFD780FF>Anraku Secret Spring Therapy<\/color> by 3.\\nMaximum upgrade level is 15."
        },
        "6": {
            "name": "The Heart Lingers Long",
            "icon": "UI_Talent_S_Mizuki_04",
            "text": "While Yumemizuki Mizuki is in the Dreamdrifter state, Swirl DMG dealt by nearby party members can score CRIT Hits, with CRIT Rate fixed at 30%, and CRIT DMG fixed at 100%.\\nEvery point of Elemental Mastery Yumemizuki Mizuki has in excess of 500 increases her CRIT Rate by 0.04% and her CRIT DMG by 0.16%. Yumemizuki Mizuki's CRIT Rate and CRIT DMG can be increased by up to 20% and 80% in this way, respectively."
        }
    }
};